// Chapitre 12 - Pancreas
// Source: public/chapter-12/Chapitre_12_Pancreas_version_lecteur_reorganise.docx (Guy Boitout)

import type { Chapter } from './types'

export const chapter12Fr: Chapter = {
  slug: 'chapter-12',
  number: '12',
  title: 'Pancreas',
  sections: [
    {
      id: 'presentation',
      title: 'Presentation',
      blocks: [
        { type: 'para', text: 'On distingue le pancreas exocrine, qui produit le suc pancreatique necessaire a la digestion, du pancreas endocrine, qui produit des hormones impliquees dans la regulation de la glycemie, notamment l\'insuline, le glucagon, la somatostatine et le polypeptide pancreatique.' },
        { type: 'para', text: 'De couleur jaune rose, le pancreas est un organe profond de la cavite abdominale, situe en arriere de l\'estomac.' },
        { type: 'para', text: 'Son contact etroit avec le plan vertebral posterieur, ainsi que sa consistance friable et fragile, contribuent a sa vulnerabilite lors de certains traumatismes abdominaux ou dorso-abdominaux, par exemple lors d\'un choc direct, d\'une compression par volant ou guidon, d\'une chute a plat ventre ou d\'un coup violent.' },
        { type: 'para', text: 'Malgre sa taille modeste, de l\'ordre de 16 a 20 cm de long, environ 2,5 cm d\'epaisseur et environ 80 g, il secrete de l\'ordre de 1,5 a 2 litres de suc pancreatique par jour.' },
      ],
    },
    {
      id: 'situation',
      title: 'Situation',
      blocks: [
        { type: 'para', text: 'Le pancreas est sous-diaphragmatique et retro-peritoneal.' },
        { type: 'para', text: 'Son bord inferieur se situe environ quatre travers de doigt au-dessus de l\'ombilic.' },
        { type: 'para', text: 'Son bord superieur se situe environ trois travers de doigt au-dessous du 7eme ou du 8eme cartilage costal gauche.' },
        { type: 'para', text: 'Il s\'etend du cadre duodenal a la rate.' },
        { type: 'para', text: 'Sa direction generale est oblique, cephalique et vers la gauche.' },
        { type: 'para', text: 'Il comprend la tete, le col, le corps et la queue.' },
      ],
    },
    {
      id: 'anatomie',
      title: 'Anatomie',
      blocks: [
        { type: 'sub', text: 'Tete du pancreas' },
        { type: 'para', text: 'Elle est enchassee dans le cadre duodenal.' },
        { type: 'para', text: 'Par analogie, la tete du pancreas peut etre comparee a la jante d\'une roue et le duodenum au pneu.' },
        { type: 'para', text: 'Sa fixation est importante.' },
        { type: 'para', text: 'Sa partie inferieure, situee a droite des vaisseaux mesenteriques superieurs, forme un crochet : le processus uncinatus.' },
        { type: 'sub', text: 'Col du pancreas' },
        { type: 'para', text: 'Il relie la tete au corps.' },
        { type: 'para', text: 'Sa face dorsale presente une echancrure en rapport avec le choledoque.' },
        { type: 'para', text: 'Sa face ventrale est adjacente au pylore.' },
        { type: 'sub', text: 'Corps du pancreas' },
        { type: 'para', text: 'Il s\'etend du col a la queue.' },
        { type: 'para', text: 'Il est situe en avant de l\'aorte et en rapport avec le plan vertebral autour de L2-L3.' },
        { type: 'para', text: 'Sa vulnerabilite dans les traumatismes abdominaux a deja ete signalee.' },
        { type: 'sub', text: 'Queue du pancreas' },
        { type: 'para', text: 'Elle est separee du corps par une zone en rapport avec les vaisseaux spleniques, le rein gauche, le hile de la rate et l\'angle splenique du colon.' },
        { type: 'para', text: 'C\'est la partie la plus mobile du pancreas, en lien avec ses attaches et ses rapports loco-regionaux.' },
        { type: 'sub', text: 'Canal pancreatique principal (ou canal de Wirsung)' },
        { type: 'para', text: 'Il parcourt le pancreas de la queue vers la tete.' },
        { type: 'para', text: 'Il rejoint le choledoque.' },
        { type: 'para', text: 'Les deux debouchent ensemble dans la papille duodenale majeure, ou ampoule hepato-pancreatique de Vater, a la jonction des 2/3 superieurs et du 1/3 inferieur du 2eme duodenum, par la grande caroncule.' },
        { type: 'para', text: 'L\'ouverture de l\'ampoule de Vater est controlee par le sphincter d\'Oddi.' },
        { type: 'sub', text: 'Canal pancreatique accessoire de Santorini' },
        { type: 'para', text: 'Il se separe du canal pancreatique principal au niveau de la tete du pancreas et s\'ouvre dans le 1/3 superieur du 2eme duodenum par la papille duodenale mineure.' },
      ],
    },
    {
      id: 'moyens-de-fixite',
      title: 'Moyens de fixite',
      blocks: [
        { type: 'sub', text: 'Face dorsale du pancreas' },
        { type: 'para', text: 'La majeure partie de la face dorsale du pancreas est accolee a la paroi abdominale posterieure.' },
        { type: 'sub', text: 'Face ventrale du pancreas' },
        { type: 'para', text: 'Elle est en rapport avec la racine du mesocolon transverse, qui relie le colon transverse a la paroi posterieure de l\'abdomen.' },
        { type: 'para', text: 'Le mesocolon transverse est egalement en continuite avec le petit omentum.' },
        { type: 'sub', text: 'Tete du pancreas' },
        { type: 'para', text: 'Elle est tres adherente au duodenum.' },
        { type: 'sub', text: 'Effet turgor et pressions intracavitaires' },
        {
          type: 'xref',
          label: 'Voir la reference dans le chapitre 1',
          text: 'Sereuses : glissement et pressions',
          href: '/lecture/chapitre-1?xrefBack=%2Flecture%2Fchapitre-12%23p-moyens-de-fixite-8&xrefBackLabel=Retour%20au%20chapitre%2012#p-articulations-viscerales-3',
        },
      ],
    },
    {
      id: 'rapports',
      title: 'Rapports',
      blocks: [
        { type: 'sub', text: 'Tete du pancreas' },
        { type: 'para', text: 'Avec le 2eme duodenum dans le quadrilatere de Rogie.' },
        { type: 'sub', text: 'Col du pancreas' },
        { type: 'para', text: 'Dorsalement, avec le choledoque, la veine cave inferieure, l\'aorte abdominale et les vaisseaux renaux droits ; ventralement, avec le pylore.' },
        { type: 'sub', text: 'Corps du pancreas' },
        { type: 'para', text: 'Ventralement, avec l\'estomac, et dorsalement avec la partie initiale des vaisseaux renaux gauches et le rein gauche.' },
        { type: 'sub', text: 'Queue du pancreas' },
        { type: 'para', text: 'Avec la rate.' },
      ],
    },
    {
      id: 'vascularisation',
      title: 'Vascularisation',
      blocks: [
        { type: 'para', text: 'Le pancreas est richement vascularise.' },
        { type: 'para', text: 'Son systeme vasculaire est en continuite avec celui du foie, du duodenum et de la rate.' },
        { type: 'para', text: 'Cette organisation temoigne de liens physiologiques etroits entre ces organes.' },
        { type: 'sub', text: 'Arterielle' },
        { type: 'para', text: 'Elle depend de branches collaterales du tronc cœliaque, lui-meme branche de l\'aorte abdominale.' },
        { type: 'para', text: 'L\'artere gastro-duodenale, branche de l\'artere hepatique commune, et l\'artere mesenterique superieure participent a la vascularisation de la tete du pancreas.' },
        { type: 'sub', text: 'Artere splenique' },
        { type: 'para', text: 'Elle longe le bord superieur du pancreas.' },
        { type: 'para', text: 'Elle vascularise le corps et la queue du pancreas.' },
        { type: 'para', text: 'Son pouls peut etre recherche cliniquement a environ trois travers de doigt au-dessous du 7eme ou du 8eme cartilage costal gauche.' },
        { type: 'sub', text: 'Veineuse' },
        { type: 'para', text: 'Le retour veineux est assure par le systeme porte, constitue notamment par la reunion de la veine mesenterique superieure et de la veine splenique, cette derniere recevant le plus souvent la veine mesenterique inferieure.' },
      ],
    },
    {
      id: 'innervation',
      title: 'Innervation',
      blocks: [
        { type: 'para', text: 'Elle est commune a de nombreux organes de l\'abdomen.' },
        { type: 'sub', text: 'Nerf vague X' },
        { type: 'para', text: 'Le nerf vague participe a la regulation neurovegetative des fonctions digestives et pancreatiques.' },
        { type: 'sub', text: 'Systeme sympathique' },
        { type: 'para', text: 'La commande sympathique impliquee ici est classiquement rapportee aux etages medullaires thoraciques moyens, notamment Th8-Th10 gauches.' },
        { type: 'sub', text: 'Plexus prevertebral' },
        { type: 'para', text: 'Le pancreas est en rapport avec le plexus cœliaque et le plexus mesenterique superieur.' },
      ],
    },
    {
      id: 'interet-en-rop',
      title: 'Interet en ROP',
      blocks: [
        { type: 'para', text: 'Le pancreas partage une vascularisation et une innervation communes avec le duodenum, le foie et la rate.' },
        { type: 'para', text: 'Dans la logique ROP, le travail sur le pancreas s\'accompagne donc de celui des organes partageant avec lui ces rapports vasculo-nerveux.' },
      ],
    },
    {
      id: 'physiologie',
      title: 'Physiologie',
      blocks: [
        { type: 'sub', text: 'Pancreas exocrine' },
        { type: 'para', text: 'Le pancreas exocrine represente environ 95 % du tissu pancreatique.' },
        { type: 'para', text: 'Il produit le suc pancreatique, compose d\'eau, d\'electrolytes, de bicarbonates et d\'enzymes digestives.' },
        { type: 'para', text: 'Il en secrete de l\'ordre de 1,5 a 2 litres par 24 heures.' },
        { type: 'para', text: 'Le bicarbonate pancreatique, dont le pH est alcalin, contribue a neutraliser l\'acidite gastrique dans le duodenum, afin de permettre l\'action optimale des enzymes pancreatiques.' },
        { type: 'sub', text: 'Enzymes principales' },
        { type: 'bullets', items: [
          'Amylase : digestion de l\'amidon.',
          'Chymotrypsine : digestion des proteines.',
          'Lipase : digestion des lipides en glycerol, monoglycerides et acides gras.',
        ]},
        { type: 'para', text: 'Le trypsinogene est active dans le duodenum, ce qui contribue a eviter l\'autodigestion des cellules pancreatiques.' },
        { type: 'para', text: 'La secretion du suc pancreatique est declenchee par :' },
        { type: 'bullets', items: [
          'Le remplissage de l\'estomac ;',
          'L\'activite du nerf vague ;',
          'La neutralisation de l\'acidite gastrique par la secretine dans le duodenum ;',
          'L\'action de la cholecystokinine et d\'autres regulations neuro-hormonales locales.',
        ]},
      ],
    },
    {
      id: 'interet-en-rop-2',
      title: 'Interet en ROP',
      blocks: [
        { type: 'para', text: 'Dans le cadre ROP, on cherche a solliciter le nerf vague, l\'estomac, le foie, la vesicule biliaire et le duodenum, plus particulierement sa 2eme portion, ainsi que le sphincter d\'Oddi, afin d\'accompagner la regulation de la secretion exocrine du pancreas.' },
        { type: 'para', text: 'Cette demarche insiste sur la necessaire synchronisation des differents temps de la digestion.' },
        { type: 'sub', text: 'Pancreas endocrine' },
        { type: 'para', text: 'La fonction endocrine du pancreas participe a la regulation de la glycemie.' },
        { type: 'para', text: 'Le glucose est un substrat energetique indispensable a l\'organisme.' },
        { type: 'para', text: 'Les besoins en glucose du cerveau representent environ 20 % de la consommation totale de l\'organisme.' },
        { type: 'para', text: 'La glycemie fait partie des grandes constantes biologiques de l\'homeostasie.' },
        { type: 'para', text: 'Bien que nos besoins en glucose varient selon l\'activite, la glycemie doit rester dans une fourchette compatible avec le fonctionnement normal, de l\'ordre de 0,80 a 1,20 g/L dans les reperes ici retenus.' },
        { type: 'sub', text: 'Regulation de la glycemie' },
        { type: 'para', text: 'Elle met en jeu le pancreas, le foie, les reins, l\'intestin et son microbiote, ainsi que l\'axe hypothalamo-hypophyso-surrenalien, ou axe HHS, implique dans la reponse au stress.' },
        { type: 'sub', text: 'Pancreas' },
        { type: 'para', text: 'Les ilots de Langerhans ne representent qu\'une faible proportion du tissu pancreatique.' },
        { type: 'para', text: 'Ils produisent notamment l\'insuline et le glucagon.' },
        { type: 'para', text: 'L\'insuline a un effet hypoglycemiant et le glucagon un effet hyperglycemiant.' },
        { type: 'sub', text: 'Foie' },
        { type: 'para', text: 'Il stocke le glucose sous forme de glycogene par la glycogenese et libere du glucose dans le sang selon les besoins par glycogenolyse.' },
        { type: 'para', text: 'Le foie peut aussi synthetiser du glucose a partir d\'elements non glucidiques, notamment des acides amines, du glycerol et du lactate : c\'est la neoglucogenese.' },
        { type: 'sub', text: 'Reins' },
        { type: 'para', text: 'Ils participent a l\'homeostasie glucidique, notamment par la reabsorption tubulaire du glucose filtre et, dans certains contextes, par la neoglucogenese.' },
        { type: 'para', text: 'En cas d\'hyperglycemie depassant les capacites de reabsorption, une glycosurie peut apparaitre.' },
        { type: 'sub', text: 'Glandes surrenales' },
        { type: 'para', text: 'Sous l\'action de l\'axe hypothalamo-hypophyso-surrenalien, l\'adrenaline secretee par la medullo-surrenale contribue a l\'elevation de la glycemie en situation de stress.' },
        { type: 'para', text: 'Le cortisol secrete par la cortico-surrenale participe egalement au maintien de la disponibilite du glucose en periode de stress et d\'activite.' },
        {
          type: 'xref',
          label: 'Voir la reference dans le chapitre 5',
          text: 'Mecanisme de stress',
          href: '/lecture/chapitre-5?xrefBack=%2Flecture%2Fchapitre-12%23p-interet-en-rop-2-23&xrefBackLabel=Retour%20au%20chapitre%2012#p-presentation-0',
        },
        { type: 'sub', text: 'Intestin et microbiote' },
        { type: 'para', text: 'Les bacteries qui peuplent l\'intestin vivent normalement dans une relation de symbiose avec l\'hote.' },
        { type: 'para', text: 'Le stress, l\'inflammation et une alteration de la barriere intestinale peuvent s\'accompagner d\'une dysbiose, c\'est-a-dire d\'une modification de la composition du microbiote au detriment de certains equilibres fonctionnels.' },
        { type: 'para', text: 'Certaines dysbioses sont associees a l\'insulino-resistance et au diabete de type 2.' },
        { type: 'para', text: 'Dans ce contexte, la glycemie peut s\'elever et le pancreas etre davantage sollicite pour maintenir un taux glycemique compatible avec l\'homeostasie.' },
        {
          type: 'xref',
          label: 'Voir la reference dans le chapitre 14',
          text: 'Intestin grele : dysbioses',
          href: '/lecture/chapitre-14?xrefBack=%2Flecture%2Fchapitre-12%23p-interet-en-rop-2-29&xrefBackLabel=Retour%20au%20chapitre%2012#p-pathologies-7',
        },
        { type: 'sub', text: 'Hormones gastro-intestinales' },
        { type: 'para', text: 'En cas de glycemie post-prandiale, des hormones intestinales comme le GLP-1 participent au ralentissement de la vidange gastrique, a l\'inhibition du glucagon et a la stimulation de la secretion d\'insuline.' },
        { type: 'para', text: 'La place exacte du GLP-2 dans cette description doit etre interpretee avec prudence.' },
      ],
    },
    {
      id: 'interet-en-rop-3',
      title: 'Interet en ROP',
      blocks: [
        { type: 'sub', text: 'Segmentation du pancreas' },
        { type: 'para', text: 'Dans notre pratique de ROP, nous pouvons differencier trois segments du pancreas.' },
        { type: 'sub', text: 'Zone 1 : la tete du pancreas' },
        { type: 'para', text: 'Elle correspond surtout au pancreas exocrine.' },
        { type: 'para', text: 'Sa fonction est etroitement liee, dans ce cadre, au foie et a la deuxieme portion du duodenum : l\'ampoule de Vater recoit le choledoque et le canal de Wirsung.' },
        { type: 'para', text: 'Son lien metamerique est presente comme proche de celui du foie : Th7 a Th9 droits.' },
        { type: 'sub', text: 'Zone 2 : le corps du pancreas' },
        { type: 'para', text: 'Il est a la fois exocrine et endocrine.' },
        { type: 'para', text: 'Il constitue la partie la plus exposee a certains traumatismes abdominaux anterieurs ou posterieurs, notamment lors des accidents de la voie publique ou des chutes sur le dos, en raison de ses rapports avec le plan vertebral autour de L2.' },
        { type: 'sub', text: 'Zone 3 : la queue du pancreas' },
        { type: 'para', text: 'Elle est surtout associee, dans ce modele, a la fonction endocrine.' },
        { type: 'para', text: 'Elle est en contact avec le rein gauche.' },
        { type: 'para', text: 'Son lien metamerique est rapporte a T9-Th10 gauches.' },
      ],
    },
    {
      id: 'pathologies-courantes',
      title: 'Pathologies courantes',
      blocks: [
        { type: 'para', text: 'Les patients porteurs d\'une maladie grave ne consultent pas necessairement en premiere intention pour celle-ci.' },
        { type: 'para', text: 'Cependant, comme rappele dans cette approche, certaines pathologies viscerales peuvent initialement se manifester par des douleurs vertebrales d\'apparence banale.' },
        { type: 'para', text: 'C\'est le cas du pancreas, dont les atteintes peuvent parfois s\'accompagner d\'une lombalgie haute aigue, d\'une dorsalgie basse, d\'un lumbago ou d\'une scapulalgie gauche.' },
      ],
    },
    {
      id: 'diagnostics-exclusion',
      title: 'Diagnostics d\'exclusion',
      blocks: [
        { type: 'para', text: 'Les symptomes qui doivent nous alerter sur une possible gravite sont :' },
        { type: 'bullets', items: [
          'Amaigrissement important, involontaire ;',
          'Prurit ;',
          'Polyurie ;',
          'Soif intense ;',
          'Douleur epigastrique vive, transfixiante et surtout nocturne ;',
          'Douleurs dorsales basses, ou lombaires superieures, surtout nocturnes ;',
          'Hepatomegalie ;',
          'Fatigue intense au moindre effort ;',
          'Selles de couleur mastic, flottantes, grasses et luisantes ;',
          'Satiete apres le repas puis, une heure apres, fringale avec envie de viande rouge, d\'aliments gras et sucres.',
        ]},
      ],
    },
    {
      id: 'diabete',
      title: 'Diabete',
      blocks: [
        { type: 'para', text: 'C\'est une elevation anormale de la glycemie.' },
        { type: 'para', text: 'On distingue ici le diabete sucre et le diabete gestationnel.' },
        { type: 'sub', text: 'Diabete sucre : 2 types' },
        { type: 'bullets', items: [
          'Diabete insulino-dependant de type 1 : il s\'agit d\'une maladie auto-immune apparaissant le plus souvent dans l\'enfance ou l\'adolescence, sur un terrain genetique de susceptibilite.',
          'Diabete insulino-resistant de type 2 de l\'adulte : il est associe a l\'obesite, a la sedentarite et a divers facteurs alimentaires et metaboliques.',
        ]},
        { type: 'sub', text: 'Diabete gestationnel' },
        { type: 'para', text: 'Il apparait au cours de la grossesse, le plus souvent au 2eme ou au 3eme trimestre, dans un contexte de diminution de la sensibilite a l\'insuline.' },
        { type: 'para', text: 'Les besoins en insuline augmentent alors, ce qui peut depasser les capacites d\'adaptation.' },
        { type: 'para', text: 'Le glucose traverse la barriere placentaire, contrairement a l\'insuline maternelle.' },
        { type: 'para', text: 'La secretion d\'insuline fœtale peut alors augmenter, avec risque de macrosomie.' },
        { type: 'sub', text: 'Symptomes de la mere' },
        { type: 'para', text: 'Hypertension arterielle gravidique, complications cardio-vasculaires ou metaboliques associees.' },
        { type: 'sub', text: 'Symptomes du bebe' },
        { type: 'para', text: 'Risque accru de macrosomie et de certaines complications neonatales ; certaines malformations peuvent etre associees a des desequilibres glycemiques maternels precoces.' },
      ],
    },
    {
      id: 'complications-du-diabete',
      title: 'Complications du diabete',
      blocks: [
        { type: 'para', text: 'Les consequences de l\'hyperglycemie prolongee incluent des neuropathies, des pathologies cardio-vasculaires et des atteintes osteo-articulaires.' },
        { type: 'sub', text: 'Neuropathies diabetiques' },
        { type: 'para', text: 'L\'hyperglycemie chronique altere en premier lieu la microcirculation et les petites fibres nerveuses.' },
        { type: 'para', text: 'Elle est responsable de neuropathies diabetiques.' },
        { type: 'para', text: 'Nous rencontrons des personnes consultant pour des douleurs pseudo-articulaires des membres inferieurs, qui peuvent en realite correspondre a des neuropathies diabetiques.' },
        { type: 'para', text: 'Dans cette pratique, la prise bilaterale systematique du pouls tibial posterieur, au niveau des malleoles mediales, contribue a orienter vers une participation vasculaire.' },
        { type: 'para', text: 'Les signes associes sont :' },
        { type: 'bullets', items: [
          'Hypoesthesie ;',
          'Peau seche ;',
          'Impatiences des membres inferieurs.',
        ]},
        { type: 'sub', text: 'Pathologies cardio-vasculaires' },
        { type: 'para', text: 'Atherosclerose, atteintes cardiaques, accidents vasculaires cerebraux, arteriopathie des membres inferieurs.' },
        { type: 'para', text: 'Le risque majeur est l\'ischemie tissulaire, pouvant evoluer jusqu\'a la necrose et parfois necessiter une amputation.' },
        { type: 'sub', text: 'Retinopathie' },
        { type: 'para', text: 'Atteinte vasculaire avec risque de baisse visuelle severe, voire de cecite.' },
        { type: 'sub', text: 'Nephropathie' },
        { type: 'para', text: 'Atteinte vasculaire renale, avec risque d\'insuffisance renale et d\'infections urinaires plus frequentes.' },
        { type: 'sub', text: 'Arthralgies' },
        { type: 'para', text: 'Le surpoids, associe aux neuropathies du membre inferieur, peut aggraver les douleurs articulaires touchant les hanches, les genoux et les pieds.' },
        { type: 'para', text: 'Le diabete est une maladie evolutive.' },
        { type: 'para', text: 'S\'il n\'est pas accompagne d\'une prise en charge hygiéno-dietetique adaptee, du controle des facteurs de risque et des traitements appropries, il peut s\'aggraver avec les complications citees ci-dessus.' },
      ],
    },
    {
      id: 'pancreatite',
      title: 'Pancreatite',
      blocks: [
        { type: 'para', text: 'C\'est une inflammation du pancreas.' },
        { type: 'para', text: 'Les causes les plus frequentes sont :' },
        { type: 'bullets', items: [
          'Lithiase biliaire : un calcul se bloque dans l\'ampoule de Vater, ce qui peut obstruer secondairement les voies biliaires et pancreatiques ;',
          'L\'alcool ;',
          'Plus rarement, une complication de la chirurgie biliaire principale ou un traumatisme abdominal.',
        ]},
      ],
    },
    {
      id: 'cancer',
      title: 'Cancer',
      blocks: [
        { type: 'para', text: 'Dans la majorite des cas, il s\'agit d\'un adenocarcinome.' },
        { type: 'para', text: 'Lorsque les symptomes apparaissent, la maladie est souvent deja avancee.' },
        { type: 'para', text: 'Le pronostic reste sombre.' },
        { type: 'para', text: 'Les causes exactes sont incompletement connues.' },
        { type: 'para', text: 'Le tabac est un facteur de risque etabli ; l\'alcool, certains contextes metaboliques et d\'autres facteurs sont discutes selon les situations.' },
        { type: 'para', text: 'Une douleur dorsolombaire inhabituelle peut, parmi d\'autres signes, faire partie du contexte revelateur d\'une atteinte pancreatique.' },
      ],
    },
    {
      id: 'relations-viscero-emotionnelles',
      title: 'Relations viscero-emotionnelles',
      blocks: [
        { type: 'para', text: 'Pancreas et rate sont ici presentes comme difficiles a differencier sur le plan emotionnel.' },
        { type: 'para', text: 'Ils sont mis en relation, dans ce referentiel, avec des stress extremement difficiles a integrer et a compenser par l\'organisme.' },
        { type: 'para', text: 'Ils reagiraient a l\'injustice, aux ruptures familiales ou affectives, aux evenements lourds, aux deuils non acceptes, comme la perte d\'un enfant, a la confrontation a la mortalite, a une enfance meurtrie ou volee, ou encore a la violence.' },
        { type: 'para', text: 'Les personnes « pancreas » ou « rate » sont decrites ici comme tristes, pessimistes et sans energie face aux agressions physiques ou psycho-emotionnelles.' },
      ],
    },
    {
      id: 'indications',
      title: 'Indications : troubles fonctionnels',
      blocks: [
        { type: 'para', text: 'La ROP peut viser ici un accompagnement fonctionnel de la digestion.' },
        { type: 'bullets', items: [
          'Hyperinsulinemie et hypoinsulinemie.',
          'Digestions difficiles, avec mobilisation energetique importante, sueurs froides et fringales anormales une heure apres le repas.',
          'Faciliter le transit des secretions pancreatiques au niveau de l\'ampoule de Vater et du sphincter d\'Oddi.',
          'Stimuler la secretion exocrine (tete du pancreas) et endocrine (corps et queue du pancreas).',
          'Malaise hypoglycemique.',
          'Douleur scapulaire gauche.',
          'Dorsalgie basse ou lombaire haute apres avoir ecarte tout signe de gravite.',
          'Asthme, eczema, psoriasis, en associant le foie.',
          'Apporter un certain confort en agissant sur les organes avec lesquels le pancreas partage une vascularisation et une innervation communes : estomac, foie, vesicule biliaire, duodenum et rate.',
          'N.B. la ROP ne peut eviter la prise d\'insuline chez un patient diabetique.',
        ]},
        {
          type: 'xref',
          label: 'Voir la reference dans le chapitre 5',
          text: 'Mecanisme de stress',
          href: '/lecture/chapitre-5?xrefBack=%2Flecture%2Fchapitre-12%23p-indications-1&xrefBackLabel=Retour%20au%20chapitre%2012#p-presentation-0',
        },
      ],
    },
    {
      id: 'zones-reflexes-podales',
      title: 'Zones reflexes podales',
      blocks: [
        { type: 'sub', text: 'Syndrome general d\'adaptation' },
        { type: 'bullets', items: [
          'Nerfs vagues X.',
          '(figures 4.11 et 4.17)',
          'Colonne vertebrale, articulations costo-transversaires, chaine ganglionnaire latero-vertebrale thoracique (Th8-Th10 gauches).',
          '(figures 4.23 et 4.29)',
          'Plexus prevertebral.',
          '(figures 12.4 et 12.6)',
        ]},
        {
          type: 'xref',
          label: 'Voir la reference dans le chapitre 2',
          text: 'Zones reflexes occipitales et podales',
          href: '/lecture/traitement-rop?xrefBack=%2Flecture%2Fchapitre-12%23p-zones-reflexes-podales-1&xrefBackLabel=Retour%20au%20chapitre%2012#p-hierarchisation-2',
        },
        { type: 'sub', text: 'Syndrome loco-regional' },
        {
          type: 'xref',
          label: 'Voir la reference dans le chapitre 2',
          text: 'Zones reflexes occipitales et podales',
          href: '/lecture/traitement-rop?xrefBack=%2Flecture%2Fchapitre-12%23p-zones-reflexes-podales-4&xrefBackLabel=Retour%20au%20chapitre%2012#p-hierarchisation-2',
        },
        { type: 'sub', text: 'Pancreas' },
        { type: 'bullets', items: [
          'Tete du pancreas : face plantaire du pied droit, dans le cadre duodenal (figure 12.5), avec reperage de la grande caroncule et du sphincter d\'Oddi a la jonction des 2/3 superieurs et du 1/3 inferieur du 2eme duodenum, et de la petite caroncule au 1/3 superieur.',
          'Queue du pancreas : face plantaire du pied gauche (figure 12.7) ; reperer d\'abord la styloide du 5eme metatarse, puis l\'angle splenique du colon situe medialement et legerement au-dessus de la styloide.',
          'La rate est decrite ici comme « posee » sur l\'angle splenique du colon, sous l\'hemi-coupole diaphragmatique.',
          'La queue du pancreas est mediale a la rate.',
          'Corps du pancreas : partant de la rate, un sillon cutane oblique medialement, caudalement et a droite rejoint le bord medial du pied gauche a hauteur des vertebres L2-L3.',
        ]},
        { type: 'sub', text: 'Systeme limbique' },
        { type: 'bullets', items: [
          'Balance cerveau limbique-pancreas : ecoute-induction, un pouce sur le pancreas, l\'autre pouce sur le cerveau limbique.',
          '(figure 1.12)',
        ]},
      ],
    },
    {
      id: 'relations-viscero-somatiques',
      title: 'Relations viscero-somatiques',
      blocks: [
        { type: 'bullets', items: [
          'Th8 et Th9 gauches ;',
          'L1 et L2 ;',
          'Epaule gauche ;',
          'Pieds chez les diabetiques.',
        ]},
      ],
    },
  ],
}
