import type { Chapter } from './types'

export const chapter8Fr: Chapter = {
  slug: 'chapter-8',
  number: '8',
  title: 'Diaphragme',
  sections: [
    {
      id: 'presentation',
      title: 'Présentation',
      blocks: [
        { type: 'para', text: 'Le diaphragme sépare la cavité thoracique de la cavité abdominale, tout en participant à leur solidarité fonctionnelle.' },
        { type: 'bullets', items: [
          'Fonction respiratoire : il est surtout connu comme un muscle inspirateur, mais ses mouvements s’accompagnent aussi d’autres effets mécaniques et fonctionnels.',
          'Fonction viscérale : de nombreux viscères présentent des attaches directes ou des rapports étroits avec le diaphragme.',
          'Les organes sus-diaphragmatiques : cœur et poumons.',
          'Les organes sous-diaphragmatiques : œsophage, estomac, foie, rate, angles coliques, duodénum, reins et surrénales.',
          'La verticalisation de l’Homme a modifié la statique et la dynamique des viscères ; dans ce contexte, les attaches diaphragmatiques participent à leur maintien et à leur mobilité relative.',
          'Fonction de cohésion et de mobilité viscérale : l’alternance inspiration-expiration, à raison d’environ 16/min, soit un ordre de grandeur de plusieurs dizaines de milliers de cycles par 24 heures, participe au glissement relatif des viscères par l’intermédiaire des séreuses mobilisées par le diaphragme.',
          'Fonction veino-lymphatique : l’alternance inspiration-expiration s’accompagne d’une alternance de pressions qui peut contribuer au retour veineux vers le cœur, ainsi qu’au retour de la circulation lymphatique vers le réseau veineux jugulo-subclavier.',
        ]},
        { type: 'sub', text: 'Fonction barométrique' },
        { type: 'para', text: 'Bien qu’il existe un gradient de pression, négative dans la cavité thoracique et positive dans la cavité abdominale, la paroi souple du diaphragme s’appuie sur ces deux cavités et participe à l’équilibre de pression entre elles.' },
        { type: 'para', text: 'Ce gradient de pression contribue au retour du sang vers le cœur.' },
        { type: 'para', text: 'Les mouvements du diaphragme peuvent renforcer ce retour veineux, notamment pour le sang veineux crânien par les veines jugulaires internes, et pour le sang veineux abdominal par la veine cave inférieure et le système porte.' },
        { type: 'para', text: 'Le diaphragme doit sa forme convexe, en partie, au gradient de pression entre cavité thoracique et cavité abdominale.' },
        { type: 'para', text: 'Dans le cadre ROP, la pression positive abdominale permet aux viscères sous-diaphragmatiques de bénéficier d’un effet de soutien diaphragmatique.' },
        { type: 'para', text: 'Dans ce même cadre, ce mécanisme peut contribuer à mieux répartir une partie des contraintes de pression exercées sur les organes pelviens et le plancher périnéal.' },
        { type: 'bullets', items: [
          'Fonction de tension membraneuse : par ses mouvements, le diaphragme mobilise les séreuses : plèvre, péricarde, péritoine.',
          'Fonction sur le système ostéo-musculo-articulaire : par ses connexions vertébrales et costales avec les muscles intervertébraux, abdominaux, grand psoas et carré des lombes, les mouvements du diaphragme s’accompagnent de variations de tension au sein du système musculo-fascial du cou, du thorax et de l’abdomen.',
          'Fonction barométrique articulaire : la pression intra-capsulaire des articulations est infra-atmosphérique.',
          'Elle participe à la coaptation articulaire et à la répartition des contraintes.',
          'L’alternance d’inspiration-expiration du diaphragme favorise le retour des veines iliaques externes, qui drainent le sang veineux des membres inférieurs.',
          'La marche a le double avantage d’activer à la fois le retour veineux et la mobilité diaphragmatique.',
          'Stress : l’alternance inspiration-expiration peut avoir un effet apaisant sur les états de stress.',
        ]},
      ],
    },
    {
      id: 'anatomie',
      title: 'Anatomie',
      blocks: [
        { type: 'para', text: 'Le diaphragme comprend trois parties et des orifices.' },
        { type: 'bullets', items: [
          'Le centre phrénique (tendon central).',
          'La coupole diaphragmatique.',
          'Les piliers.',
          'Trois orifices principaux et des orifices accessoires.',
        ]},
        { type: 'sub', text: 'Centre phrénique du diaphragme' },
        { type: 'para', text: 'Il a la forme d’un trèfle à trois folioles.' },
        { type: 'bullets', items: [
          'Foliole antérieure : elle est attachée en avant au sternum et au processus xyphoïdien par deux faisceaux musculaires.',
          'Folioles droite et gauche : situées plus en arrière, elles donnent naissance aux fibres musculaires qui rejoignent les six dernières côtes pour constituer la coupole diaphragmatique.',
          'Particularité : le centre phrénique sur lequel repose le cœur est oblique en bas, en avant et à gauche.',
        ]},
        { type: 'sub', text: 'Coupole diaphragmatique' },
        { type: 'para', text: 'C’est la partie musculaire en forme de voûte.' },
        { type: 'para', text: 'Dans une lecture fonctionnelle, ses fibres musculaires sont en tensions réciproques et s’équilibrent entre, ventralement, l’attache sternale, latéralement, l’attache sur les cartilages des six dernières côtes et, dorsalement, l’attache lombaire par les piliers du diaphragme.' },
        { type: 'para', text: 'Cet équilibre conditionne l’efficacité mécanique du diaphragme dans les fonctions décrites en présentation.' },
        { type: 'rop', body: [
          'En raison de l’obliquité caudale, ventrale et gauche du centre phrénique, la coupole diaphragmatique gauche est en regard du 6ème espace intercostal antérieur gauche, alors que la coupole diaphragmatique droite est en regard du 5ème espace intercostal droit.',
          'Cette particularité anatomique est importante, dans le cadre ROP, pour bien positionner les zones réflexes du diaphragme et des viscères qui lui sont attachés : foie, estomac, angles coliques, rate.',
        ]},
        { type: 'sub', text: 'Piliers du diaphragme' },
        { type: 'para', text: 'Le diaphragme s’attache dorsalement sur la colonne lombaire par les piliers principaux et accessoires.' },
        { type: 'sub', text: 'Piliers principaux' },
        { type: 'bullets', items: [
          'Pilier médian droit : il s’attache sur les corps vertébraux des quatre premières vertèbres lombaires et les disques qui les séparent.',
          'Les fibres musculaires qui prolongent le pilier médian droit constituent la boucle de l’anneau musculaire du hiatus œsophagien.',
          'Pilier médian gauche : il s’attache sur les corps vertébraux des trois premières vertèbres lombaires et sur les disques qui les séparent.',
          'Les deux piliers médians participent à la formation du hiatus aortique.',
        ]},
        { type: 'sub', text: 'Piliers accessoires ou latéraux' },
        { type: 'bullets', items: [
          'Ligament arqué médian : il va du corps de L1, et parfois L2, à son processus transverse.',
          'Il forme l’arcade du psoas.',
          'Ligament arqué latéral ou ligament lombo-costal de Henlé : il va du processus transverse de L1 à la 12ème côte.',
          'Il forme l’arcade du carré des lombes.',
          'Les fibres musculaires et le ligament de Henlé échangent des fibres avec le muscle transverse de l’abdomen.',
        ]},
        { type: 'rop', body: [
          'Les tensions anormales du diaphragme proviennent rarement de lui-même, à l’exception des traumatismes ou des efforts intenses.',
          'Elles sont, dans le cadre clinique, souvent envisagées en lien avec ses nombreuses connexions viscérales ou ostéo-musculo-articulaires.',
          'Par exemple, le grand psoas échange des fibres musculaires avec les piliers du diaphragme.',
          '« Toute fixation de ce muscle n’est pas seulement problématique pour les membres inférieurs mais l’est aussi pour les piliers et les attaches costales du diaphragme » (Jean-Pierre Barral).',
          'Toute adhérence avec le péritoine, la plèvre ou le péricarde peut perturber le jeu diaphragmatique, avec un retentissement respiratoire, circulatoire ou viscéral variable.',
          'Une baisse de la ventilation respiratoire et de l’oxygénation peut alors être observée dans certains contextes.',
          'Une élévation du gaz carbonique peut s’y associer dans les situations les plus marquées.',
          'Un abaissement du pH sanguin peut également s’observer en cas de retentissement ventilatoire significatif.',
          'Des troubles du retour veineux et lymphatique peuvent accompagner ces limitations mécaniques.',
          'Un brassage viscéral moins efficient peut aussi être discuté dans ce cadre.',
          'Nous retrouvons ici certains effets délétères d’une vie sédentaire.',
        ]},
        { type: 'rop', body: [
          'Il convient d’associer le diaphragme à l’évaluation et, dans le cadre ROP, au traitement des dysfonctions viscérales thoraciques et abdominales.',
        ]},
        { type: 'sub', text: 'Zones réflexes podales du diaphragme : face plantaire des deux pieds' },
        { type: 'bullets', items: [
          'Centre phrénique : à la palpation de la texture de la peau, la partie gauche du centre phrénique est située plus bas que la partie droite, sous la tête du 1er métatarse.',
          'Coupoles diaphragmatiques : il est important de respecter la différence de hauteur des deux coupoles diaphragmatiques pour situer leurs zones réflexes.',
          'Si nous plaçons la coupole diaphragmatique gauche à la même hauteur que la droite, cela revient, en projection réflexe, à perdre la cohérence anatomique avec la position cardiaque.',
          'Chaque coupole suit une ligne courbe allant du centre phrénique à la styloïde du 5ème métatarse.',
          'L’attache antérieure xyphoïdienne est sur le tubercule du naviculaire.',
          'Les attaches latérales sur les six dernières côtes sont sur la face latérale du 5ème métatarse.',
          'Piliers du diaphragme : c’est l’espace entre, d’une part, le bord plantaire des quatre premières vertèbres lombaires à droite et des trois premières vertèbres à gauche, et, d’autre part, le bord médial de la voûte plantaire.',
        ]},
        { type: 'sub', text: 'Orifices du diaphragme' },
        { type: 'para', text: 'Le diaphragme est percé d’orifices qui font communiquer la cavité thoracique avec la cavité abdominale.' },
        { type: 'bullets', items: [
          'Des orifices, ou hiatus, principaux : aortique, œsophagien et de la veine cave inférieure.',
          'Des orifices accessoires : hiatus de Marfran et de Larrey, orifices entre les piliers accessoires, hiatus du ligament lombo-costal de Henlé.',
        ]},
        { type: 'sub', text: 'Hiatus aortique' },
        { type: 'para', text: 'Central, dorsalement entre les deux folioles droite et gauche du centre phrénique, il est issu des deux piliers médians du diaphragme, qui forment un anneau en avant de la vertèbre Th12.' },
        { type: 'para', text: 'Sa structure fibreuse non contractile ne gêne pas directement le flux artériel de l’aorte abdominale ni le flux lymphatique du conduit lymphatique qui le traversent.' },
        { type: 'para', text: 'Le conduit lymphatique, long d’environ 40 cm, dont l’origine est la citerne de Pecquet, se termine au confluent veineux de Pirogoff, constitué par les veines subclavière gauche et jugulaire gauche.' },
        { type: 'para', text: 'Il draine la lymphe de l’ensemble de l’abdomen et des membres inférieurs.' },
        { type: 'para', text: 'N.B. La présence d’un ganglion de Troisier au confluent jugulo-subclavier est un signe clinique d’alerte classiquement associé à une possible atteinte néoplasique abdominale.' },
        { type: 'sub', text: 'Orifice ou hiatus œsophagien' },
        { type: 'para', text: 'Situé à gauche de la vertèbre Th10, entre les deux folioles droite et gauche, il est un orifice formé de fibres musculaires issues essentiellement du pilier médian droit du diaphragme.' },
        { type: 'para', text: 'Il est traversé par l’œsophage, le nerf vague gauche ventralement et le nerf vague droit dorsalement.' },
        { type: 'para', text: 'L’œsophage abdominal va du hiatus œsophagien, à hauteur de la vertèbre Th10, au cardia, à hauteur de la vertèbre Th11.' },
        { type: 'sub', text: 'Dysfonctions du hiatus œsophagien' },
        { type: 'para', text: 'La structure contractile du hiatus œsophagien peut subir des tensions du diaphragme et s’accompagner d’une contrainte sur l’œsophage et les deux nerfs vagues.' },
        { type: 'para', text: 'Les tensions peuvent venir de :' },
        { type: 'bullets', items: [
          'La plèvre, à laquelle le hiatus œsophagien est relié par la gaine de Treitz et Paimer.',
          'Le péritoine, auquel il est relié par les muscles de Juvara et Rouget, issus du diaphragme.',
          'Le lobe gauche du foie, situé en avant du hiatus œsophagien.',
        ]},
        { type: 'sub', text: 'Hiatus de la veine cave inférieure' },
        { type: 'para', text: 'Situé à la jonction des folioles antérieure et droite du centre phrénique, à hauteur de la vertèbre Th9, il est traversé par la veine cave inférieure et le nerf phrénique droit.' },
        { type: 'para', text: 'C’est un orifice fibreux, ce qui limite la gêne mécanique au retour veineux vers l’atrium droit du cœur.' },
        { type: 'sub', text: 'Orifices accessoires' },
        { type: 'sub', text: 'Hiatus de Marfran et de Larrey' },
        { type: 'para', text: 'Les deux faisceaux musculaires qui amarrent le centre phrénique à la face postérieure du sternum et du processus xyphoïdien délimitent un orifice central, le hiatus de Marfran, et deux orifices latéraux, droit et gauche, les hiatus de Larrey.' },
        { type: 'para', text: 'Ils font communiquer la plèvre avec le péritoine.' },
        { type: 'para', text: 'Leur projection postérieure se situe au niveau de la vertèbre Th10 ou Th12, en fonction de la respiration.' },
        { type: 'para', text: 'Les hiatus de Larrey sont traversés par l’artère épigastrique supérieure, branche de l’artère thoracique interne.' },
        { type: 'para', text: 'N.B. Par son anastomose avec l’artère épigastrique inférieure de la région inguinale, l’artère épigastrique supérieure met en continuité vasculaire la région inguinale et la région rétro-claviculaire.' },
        { type: 'para', text: 'Dans le cadre de cette description, le système lymphatique destiné au foie traverse les hiatus de Larrey.' },
        { type: 'sub', text: 'Orifices entre les piliers accessoires' },
        { type: 'para', text: 'Ils servent de passage à la chaîne ganglionnaire sympathique latéro-vertébrale lombaire, d’où partent les nerfs splanchniques destinés aux viscères abdomino-pelviens.' },
        { type: 'para', text: 'Ils laissent également le passage à la veine azygos à droite et à la veine hémi-azygos à gauche.' },
        { type: 'sub', text: 'Hiatus du ligament lombo-costal de Henlé' },
        { type: 'para', text: 'Entre les deux dernières côtes et le ligament de Henlé, ce hiatus fait communiquer la plèvre avec le péritoine.' },
        { type: 'para', text: 'Il existe donc un risque de propagation d’infection entre les deux cavités thoracique et abdominale.' },
        { type: 'para', text: 'Dans le cadre ROP, le ligament de Henlé peut être décrit comme fibrosé à la suite de fixations rénales post-traumatiques, notamment après une chute à plat dos avec le souffle coupé.' },
        { type: 'rop', body: [
          'Les traumatismes de la charnière thoraco-lombaire et costale inférieure ne se résument pas, dans le cadre clinique ROP, à une atteinte ostéo-articulaire ; des fixations rénales peuvent aussi être recherchées en association.',
        ]},
        { type: 'sub', text: 'Zones réflexes podales des orifices' },
        { type: 'bullets', items: [
          'Hiatus œsophagien : face plantaire du pied gauche, il est à gauche du centre phrénique, à l’aplomb d’une ligne partant entre le 1er et le 2ème orteil et coupant la coupole diaphragmatique gauche.',
          'D’où l’importance de bien situer la coupole diaphragmatique gauche.',
          'Hiatus aortique : sa zone réflexe est au niveau de la vertèbre Th12, face plantaire.',
          'Hiatus de la veine cave inférieure : sa zone réflexe est confondue avec le centre phrénique du côté droit.',
          'Hiatus de Marfran et de Larrey : appendice xyphoïde, tubercule du naviculaire.',
          'Hiatus de Henlé : zone réflexe des articulations costo-transversaires des deux dernières côtes sur la face frontale dorsale médiale des pieds, à hauteur de Th11 et Th12.',
        ]},
      ],
    },
    {
      id: 'vascularisation',
      title: 'Vascularisation',
      blocks: [
        { type: 'sub', text: 'Artérielle' },
        { type: 'bullets', items: [
          'Branches des artères thoraciques internes.',
          'Artères phréniques supérieures : elles sont issues de l’aorte thoracique.',
          'Artères phréniques inférieures : elles sont issues du tronc cœliaque, première branche de l’aorte abdominale.',
        ]},
        { type: 'sub', text: 'Veineux' },
        { type: 'bullets', items: [
          'Veines thoraciques internes : elles cheminent avec les artères thoraciques internes.',
          'Veines du système azygos : elles cheminent de chaque côté de la colonne vertébrale.',
          'À gauche, la veine hémi-azygos, réunion de la veine lombale ascendante gauche et de la veine subcostale gauche connectées à la veine rénale gauche, assure la circulation veineuse lombaire.',
          'À droite, la veine azygos naît à hauteur de la vertèbre L1 ou L2 de la réunion de la veine lombale ascendante et de la veine subcostale droites, ou directement de la veine cave inférieure.',
          'La veine azygos et la veine hémi-azygos traversent le diaphragme près des piliers médians et latéraux du diaphragme ; puis la veine hémi-azygos passe du côté droit pour se jeter dans la veine azygos, à hauteur de la vertèbre Th9.',
          'La veine azygos rejoint la veine cave supérieure à hauteur de la vertèbre Th4 et des 2ème et 3ème articulations chondro-costales droites.',
        ]},
        { type: 'rop', body: [
          'Le système azygos présente un intérêt clinique important.',
          'Il participe au système porto-cave.',
          'La jonction azygo-cave — artères et veines pulmonaires droites, nerf phrénique droit, nerf vague droit — proche de la bronche souche droite, constitue, dans le cadre ROP, un carrefour stratégique pouvant être retrouvé en tension chez certains patients présentant asthme, eczéma, psoriasis ou allergies.',
        ]},
        { type: 'sub', text: 'Zones réflexes podales' },
        { type: 'para', text: 'Jonction azygo-cave : 2ème et 3ème articulations chondro-costales droites.' },
      ],
    },
    {
      id: 'innervation',
      title: 'Innervation',
      blocks: [
        { type: 'para', text: 'Le diaphragme reçoit une double innervation somatique : les nerfs phréniques droit et gauche, et les six derniers nerfs intercostaux droit et gauche.' },
        { type: 'sub', text: 'Nerfs phréniques' },
        { type: 'para', text: 'Ils sont les principaux nerfs inspirateurs du diaphragme.' },
        { type: 'para', text: 'Ils interviennent aussi dans la toux, l’éternuement et lors d’efforts de défécation et d’accouchement.' },
        { type: 'para', text: 'Ils sont également sensitifs pour la plèvre, le péricarde, l’œsophage, le péritoine, l’enveloppe fibreuse du foie, ou capsule de Glisson, le méso-côlon transverse, la veine cave inférieure et le thymus.' },
        { type: 'para', text: 'Cette innervation sensitive peut contribuer à expliquer, à droite, certaines douleurs cervicales, scapulaires et scapulo-humérales en lien avec des atteintes hépato-biliaires.' },
        { type: 'para', text: 'À gauche, ces douleurs peuvent être mises en lien avec le cœur, le péricarde et l’estomac.' },
        { type: 'sub', text: 'Anatomie' },
        { type: 'lead', label: 'Origine', text: 'Branche antérieure du 4ème nerf cervical et, accessoirement, des 3ème et 5ème nerfs cervicaux.' },
        { type: 'sub', text: 'Trajet' },
        { type: 'lead', label: 'Niveau cervical', text: 'Le nerf phrénique croise la face antérieure du muscle scalène antérieur puis passe dans le triangle de Sédillot, délimité par les insertions sternale et claviculaire du muscle sterno-cléido-occipito-mastoïdien et la clavicule.' },
        { type: 'lead', label: 'Niveau thoracique', text: 'Dans le médiastin antérieur, les deux nerfs phréniques descendent entre le péricarde et les poumons ; le droit est plus vertical et le gauche s’écarte, dévié par le cœur.' },
        { type: 'para', text: 'Les deux nerfs phréniques s’étalent ensuite sur la face supérieure du diaphragme qu’ils innervent.' },
        { type: 'sub', text: 'Niveau abdominal' },
        { type: 'lead', label: 'Nerf phrénique droit', text: 'Il traverse l’orifice de la veine cave inférieure et innerve le pilier droit du diaphragme, les ligaments coronaire et triangulaire du foie, la capsule de Glisson du foie, le péritoine, la veine cave inférieure et le plexus diaphragmatique, formé par le nerf phrénico-abdominal droit et quelques nerfs intercostaux.' },
        { type: 'lead', label: 'Nerf phrénique gauche', text: 'Il perfore le diaphragme en arrière du cœur et innerve le pilier gauche du diaphragme et le péritoine.' },
        { type: 'lead', label: 'Terminaison', text: 'Les deux nerfs phréniques rejoignent le plexus cœliaque et les surrénales.' },
        { type: 'lead', label: 'Anastomoses', text: 'Les deux nerfs phréniques ont de nombreuses anastomoses. Nerfs crâniens : nerfs hypoglosse XII et accessoire XI. SNA : nerf vague X, ganglion cervical inférieur, plexus cœliaque et anastomoses réciproques.' },
        { type: 'rop', body: [
          'Les deux nerfs phréniques deviennent, dans les états de stress, des acteurs cliniques importants.',
          'L’interaction des émotions sur la respiration peut contribuer à expliquer les dyspnées et l’oppression thoracique observées dans la respiration émotionnelle.',
          'Avoir le souffle coupé, être à bout de souffle, sont des altérations de la respiration retrouvées dans l’anxiété et la dépression.',
          'Nerf du subclavier : il innerve le muscle subclavier entre la clavicule et la 1ère côte.',
          'Il anastomose le nerf phrénique au plexus brachial.',
          'Ce lien peut contribuer à expliquer certains retentissements du territoire innervé par le nerf phrénique droit sur la ceinture scapulaire et l’épaule droite, notamment dans des tableaux de PSH ou de cervico-brachialgie droite.',
        ]},
        { type: 'sub', text: 'Les six derniers nerfs intercostaux' },
        { type: 'para', text: 'Les six derniers nerfs intercostaux participent à l’innervation somatique du diaphragme.' },
        { type: 'sub', text: 'Zones réflexes podales du nerf phrénique' },
        { type: 'bullets', items: [
          '3ème, 4ème et 5ème vertèbres cervicales sur la vue sagittale médiale de la première phalange du gros orteil et sur la vue sagittale latérale.',
          'Triangle de Sédillot : bord supérieur de la malléole tibiale.',
          'Médiastin : face plantaire de la tête des 1ers métatarsiens.',
        ]},
        { type: 'sub', text: 'Zones réflexes des six nerfs intercostaux' },
        { type: 'bullets', items: [
          'Vertèbres Th7 à Th12.',
          'Nerf intercostalbrachial de Hyrtl pour l’asthme, l’eczéma et les allergies : jonction diaphyse-tête latérale du 5ème métatarse.',
        ]},
      ],
    },
    {
      id: 'jonction-oesophago-cardio',
      title: 'Jonction œsophago-cardio-tubérositaire (JOCT)',
      blocks: [
        { type: 'para', text: 'Cette jonction est soumise à de nombreuses tensions.' },
        { type: 'bullets', items: [
          'Verticalisation de l’Homme : elle a conduit la jonction gastro-œsophagienne à une organisation mécanique compatible avec la station debout.',
          'Le sphincter inférieur œsophagien est soumis en permanence à des tensions mécaniques venant du gradient de pression entre la cavité thoracique, où la pression est négative, et la cavité abdominale, où la pression est positive.',
          'Mouvements du diaphragme : dans le cadre ROP, les fascias cervicaux et médiastinaux, tendus entre la base du crâne et le centre phrénique du diaphragme, exercent des tensions sur la JOCT.',
          'Ces fascias prennent le nom de cravate diaphragmatique.',
          'Rotation embryonnaire de l’estomac : l’estomac, en effectuant une rotation d’environ 90° dans le sens horaire selon un axe vertical et dans le plan frontal, a contribué à amener le nerf vague gauche ventralement et le nerf vague droit dorsalement, ainsi qu’à établir une torsion physiologique du SIO.',
          'Système anti-reflux : dès que la pression gastrique augmente par le remplissage alimentaire ou lors de l’inspiration, de la toux et des efforts physiques, les fibres du diaphragme, provenant essentiellement du pilier droit, enserrent le hiatus œsophagien à la manière d’un nœud de cravate.',
          'Les fibres musculaires de Juvara et Rouget viennent, dans cette description, affiner l’adaptation du hiatus œsophagien aux variations de pression pour son ouverture et sa fermeture.',
        ]},
        { type: 'lead', label: 'Cravate d’Helvetius', text: 'Le système anti-reflux, appelé cravate d’Helvetius, est assuré conjointement par la tension des piliers du diaphragme, le SIO, les fascias et les fibres musculaires phrénico-œsophagiennes.' },
        { type: 'lead', label: 'Angle de His', text: 'L’angle de His, ou incisure cardiaque, forme un angle aigu entre la partie distale de l’œsophage et le fundus de l’estomac.' },
        { type: 'para', text: 'Il contribue à la continence du SIO.' },
        { type: 'para', text: 'Dans le cadre de cette présentation, cette continence est également reliée à la valvule de Gubaroff, qui s’oppose au reflux gastro-œsophagien.' },
      ],
    },
    {
      id: 'reflux-hernie-hiatale',
      title: 'Reflux gastro-œsophagien et hernie hiatale',
      blocks: [
        { type: 'sub', text: 'Reflux gastro-œsophagien (RGO)' },
        { type: 'para', text: 'Toute tension anormale pleuro-pulmonaire, du diaphragme, du péritoine, de l’estomac, du foie, de la sphère abdominale et même pelvienne, par les piliers du diaphragme, ainsi que certaines fixations costo-vertébrales des étages Th9, Th10 et Th11, de la 6ème vertèbre thoracique et de la 6ème chondro-costale gauche, sont susceptibles, dans le cadre ROP, de favoriser un reflux gastro-œsophagien et une hernie hiatale.' },
        { type: 'para', text: 'Des varices œsophagiennes par hypertension portale peuvent aussi contribuer à un reflux gastro-œsophagien par dilatation hiatale.' },
        { type: 'para', text: 'Si les fibres musculaires entourant le hiatus œsophagien ne se resserrent pas suffisamment, une partie des aliments et du suc gastrique acide peut remonter dans l’œsophage et contribuer à l’apparition ou à l’aggravation d’une hernie hiatale.' },
        { type: 'sub', text: 'Hernie hiatale' },
        { type: 'para', text: 'Lésion fréquente, elle correspond au déplacement d’une partie de la grosse tubérosité de l’estomac dans le médiastin, à travers le hiatus œsophagien, par affaissement de la partie musculaire du diaphragme, surtout du pilier droit.' },
        { type: 'para', text: 'On distingue deux types de hernies hiatales :' },
        { type: 'bullets', items: [
          'Hernie par roulement : une partie du péritoine, comprenant une partie du fundus, roule ventralement le long de l’œsophage, le cardia restant en place.',
          'Hernie par glissement : l’œsophage abdominal, le cardia et le fundus glissent crânialement à travers le hiatus œsophagien.',
        ]},
        { type: 'para', text: 'L’action occlusive du pilier droit du diaphragme ne peut alors plus assurer pleinement sa fonction.' },
        { type: 'sub', text: 'Étiologie' },
        { type: 'bullets', items: [
          'Gastroparésie.',
          'Dilatation stomacale.',
          'Obésité ou, au contraire, amaigrissement rapide.',
          'Fixations costo-vertébrales, chondro-costales et thoraco-lombaires.',
          'Grossesse, par conséquences mécaniques et hormonales.',
          'Ménopause.',
          'Abus de graisse, d’alcool et de boissons gazeuses.',
          'Prise au long cours de médicaments : anti-inflammatoires, antidépresseurs, aspirine, antidouleurs, cortisone, vasodilatateurs.',
        ]},
        { type: 'sub', text: 'Symptômes' },
        { type: 'bullets', items: [
          'Pyrosis, brûlure acide dans l’œsophage.',
          'Dyspepsie.',
          'Dysphagie.',
          'Fausses cardiopathies, ou précordialgies, source d’angoisse et de diagnostic erroné.',
          'Dyspnée par sensation d’oppression et de difficulté à réaliser des inspirations profondes.',
          'Laryngite, gingivite, sinusite, otite séreuse, crises asthmatiformes, œsophagite par remontée acide.',
          'Sialorrhée, ou excès de salive.',
        ]},
        { type: 'sub', text: 'ROP du RGO et de la hernie hiatale' },
        { type: 'bullets', items: [
          'Colonne cervico-thoraco-abdominale, articulations costo-vertébrales.',
          'Diaphragme, nerf phrénique, six derniers nerfs intercostaux.',
          'Nerf vague.',
          'Hiatus œsophagien.',
          'Estomac.',
          'Lobe gauche du foie.',
        ]},
        { type: 'sub', text: 'RGO du nouveau-né' },
        { type: 'para', text: 'Dans le cadre ROP, le RGO du nouveau-né peut être décrit comme comportant une composante crânienne.' },
        { type: 'para', text: 'La compression des parties condylaires de l’occiput et du foramen jugulaire, surtout à gauche, peut être discutée comme facteur d’irritation du nerf vague, susceptible de contribuer à une béance de la jonction gastro-œsophagienne et à une stimulation des contractions de l’estomac.' },
        { type: 'sub', text: 'ROP du RGO du nouveau-né' },
        { type: 'bullets', items: [
          'MRP.',
          'Parties condylaires de l’occiput.',
          'Foramen magnum.',
          'Foramen jugulaire.',
          'Hiatus œsophagien.',
        ]},
      ],
    },
  ],
  slides: {
    url: '/chapter-8/Chapter8 Slides de synthese FR.pdf',
    label: 'Diapositives',
    description: 'Synthèse visuelle du chapitre 8.',
  },
}
