// Chapitre 1 — Généralités
// Source: public/chapter-1/Chapitre 1 Généralités.docx (Guy Boitout)

import type { Chapter } from './types'

export const chapter1Fr: Chapter = {
  slug: 'chapter-1',
  number: '1',
  title: 'Généralités',
  sections: [
    {
      id: 'presentation',
      title: 'Présentation',
      blocks: [
        { type: 'para', text: 'La bonne physiologie des viscères dépend de leur bonne qualité à se déformer et à bouger les uns par rapport aux autres grâce aux séreuses qui les enveloppent. Si, à la suite d’un traumatisme, d’une infection, d’une chirurgie ou d’un stress émotionnel, un viscère cesse d’être libre, les structures musculo-squelettiques, fasciales, viscérales ou neuro-vasculaires avec lesquelles il est solidaire, en seront affectées.' },
        { type: 'para', text: 'L’organisme cherchera alors à s’adapter en mettant en action le mécanisme de stress que le professeur Sélye a appelé Syndrome général d’adaptation. S’il n’arrive pas à s’adapter, il développera un trouble fonctionnel avec, au début, des symptômes à minima qui, progressivement pourraient évoluer vers une pathologie viscérale structurelle nécessitant un diagnostic et un traitement médical. Des douleurs musculo-squelettiques en apparence banales peuvent être les signes avant-coureurs d’une maladie grave pour laquelle il ne faudra pas passer à côté.' },
      ],
    },
    {
      id: 'mobilite-viscerale',
      title: 'Mobilité viscérale',
      blocks: [
        { type: 'para', text: 'Elle est rendue possible par :' },
        { type: 'bullets', items: [
          'le système nerveux somatique',
          'le système nerveux autonome',
          'la motilité',
          'les biorythmes.',
        ]},
        { type: 'para', text: 'Ces mouvements sont soit passifs, soit automatiques, soit actifs.' },
        { type: 'lead', label: 'Système nerveux somatique', text: 'les mouvements actifs commandés par le système nerveux somatique — marcher, courir, danser, les mouvements du tronc — obligent les viscères à bouger. L’inverse est vrai aussi : à la suite d’une chirurgie abdominale, les mouvements actifs sont limités et douloureux par les fixations et adhérences des viscères qu’elle provoque.' },
        { type: 'para', text: 'Cette mobilité viscérale est passive :' },
        { type: 'para', text: 'L’alternance d’inspiration et d’expiration actives du diaphragme est un grand facteur de glissement et de mobilisation des viscères de la cavité thoracique et de la cavité abdominale.' },
        { type: 'para', text: 'L’activité physique régulière est nécessaire à la mobilité viscérale. Elle développe les activités cardiaques et respiratoires et facilite le transit intestinal. Nous connaissons tous les méfaits d’un alitement prolongé : activité cardio-pulmonaire ralentie, perte du transit intestinal, risques infectieux de la vessie, etc.' },
        { type: 'lead', label: 'Système nerveux autonome', text: 'sous la commande des centres supérieurs situés dans le diencéphale et le tronc cérébral (Cf. Chapitre 4 Système nerveux autonome), le Parasympathique et le Sympathique (Figure 1.1) régulent les mouvements automatiques des viscères :' },
        { type: 'lead', label: 'Mouvements respiratoires', text: 'le diaphragme effectue 21 000 mouvements par 24 heures. Nous connaissons son rôle essentiel sur la respiration mais la répercussion de ses mouvements sur le glissement et la mobilité des viscères est grande. (figure 1.2)' },
        { type: 'lead', label: 'Orientation du diaphragme', text: 'la surface du diaphragme n’étant pas horizontale mais convexe céphaliquement et dorsalement, les mouvements des viscères ne se font pas dans un seul axe vertical mais sont la résultante des forces exercées dans les trois plans de l’espace (sagittal, frontal et horizontal).' },
        { type: 'lead', label: 'Inspiration', text: 'à raison de 21 000 fois par 24 heures, l’abaissement de la coupole diaphragmatique et l’expansion de la cage thoracique font entrer l’air dans les poumons. Le diaphragme pousse les viscères abdominaux ventralement et caudalement.' },
        { type: 'para', text: 'Le volume de l’ensemble des viscères est semi-liquide, les viscères sont donc incompressibles. L’espace entre eux étant minime (Cf. effet turgor), ils sont poussés contre la paroi abdominale antérieure constituée uniquement de muscles, alors que la paroi abdominale postérieure est formée de la colonne vertébrale et du bassin peu déformables sous la poussée du diaphragme et de la masse viscérale. La perte d’une bonne sangle abdominale fait perdre aux viscères leur soutien antérieur et leur mobilité.' },
        { type: 'lead', label: 'Expiration', text: 'les forces s’inversent. Le diaphragme emmène les viscères de l’abdomen céphaliquement et dorsalement tout en chassant l’air des poumons.' },
        { type: 'lead', label: 'Mouvements cardiaques', text: 'à raison de 100 000 battements par 24 heures, les mouvements du cœur (figure 1.3.) vont se propager aux poumons, à l’œsophage, au médiastin, au tronc cérébral et au diaphragme sur lequel il repose. Par le diaphragme sur lequel il repose, il transmet indirectement les vibrations systoliques aux viscères de la cavité abdominale. L’onde sanguine ainsi créée se propage dans le réseau artériel jusqu’aux artérioles les plus fines des viscères les plus éloignés.' },
        { type: 'para', text: 'Les mouvements des viscères thoraco-abdominaux créés par le diaphragme et le cœur sont passifs.' },
        { type: 'lead', label: 'Péristaltisme', text: 'sous l’action du système nerveux autonome et des facteurs chimiques et hormonaux, de grandes ondes de contractions font progresser et brasser le contenu des viscères de l’abdomen : bol alimentaire et sécrétions.' },
        { type: 'para', text: 'Le péristaltisme est un mouvement automatique car le "starter" du mouvement est dans les centres diencéphaliques qui commandent les muscles lisses de la paroi des viscères.' },
        { type: 'lead', label: 'Motilité', text: 'c’est un mouvement actif intrinsèque propre à la structure du viscère. Il est lent, de faible amplitude, invisible à l’œil, mais perceptible sous la main.' },
        { type: 'para', text: 'La motilité est la capacité pour un organe de se mouvoir de lui-même par des mouvements qui lui sont inhérents, dépendant ni de l’activité musculaire, ni de l’activité diaphragmatique ou cardiaque.' },
        { type: 'para', text: 'Deux théories tentent d’apporter une explication : la théorie crânienne et la théorie embryologique.' },
        { type: 'lead', label: 'Théorie crânienne', text: 'le liquide cérébro-spinal circule sous l’action d’une pompe : le mécanisme respiratoire primaire. (figure 1.4)' },
        { type: 'para', text: 'Comme tout tissu vivant, le cerveau est animé par un mouvement inné d’expansion, appelé "inspir", et de rétraction, appelé "expir", qui est en quelque sorte sa motilité.' },
        { type: 'lead', label: 'Inspir', text: 'le liquide cérébro-spinal, issu du sang artériel, diffuse dans les ventricules cérébraux qui se "gonflent", créant une hyperpression intra-ventriculaire. Cela entraine une turgescence du cerveau qui va solliciter les membranes et les sutures crâniennes.' },
        { type: 'lead', label: 'Expir', text: 'quand les mécanorécepteurs à l’intérieur des sutures atteignent un certain seuil de tension, ils vont, par un mécanisme de feedback, déclencher "l’expir" pendant lequel le liquide cérébro-spinal diffuse des ventricules vers les espaces subarachnoïdiens. Des barorécepteurs, situés dans les tubercules arachnoïdiens qui se situent à l’extrémité antérieure du sinus droit, ouvrent les "vannes". Le liquide cérébrospinal se répand selon deux circuits :' },
        { type: 'lead', label: 'Sinus veineux', text: 'ils sont situés dans le dédoublement des faux du cerveau et du cervelet, et de la tente du cervelet. Le liquide cérébrospinal rejoint le sang veineux par des veines jugulaires internes dans les foramens jugulaires.' },
        { type: 'lead', label: 'Canal épendymaire de la moelle spinale', text: 'depuis le canal épendymaire, le liquide cérébro-spinal rejoint le milieu interstitiel puis la circulation lymphatique qui aboutit dans la circulation veineuse au niveau des carrefours jugulo-subclaviers droit et gauche. Enfin, retour à l’atrium (anciennement oreillette) droit du cœur. Cela nous montre que sang, lymphe et liquide cérébro-spinal communiquent entre eux.' },
        { type: 'para', text: 'Cette ondée du liquide cérébrospinal se répercute sur les os du crâne et l’ensemble du squelette et, par eux, sur les viscères. Elle peut être perçue partout dans le corps. (Cf. livre Réflexothérapie Occipito-Podale et système neuro-méningé, éditions Elsevier-Masson, Chapitre 7, page 78)' },
        { type: 'rop', body: [
          'Notre action sur le liquide cérébro-spinal favorise le drainage des œdèmes.',
        ]},
        { type: 'lead', label: 'Théorie embryologique (Barral, Mercier)', text: 'depuis l’œuf fécondé jusqu’aux milliards de cellules que contient l’organisme, le développement des cellules se fait selon une cinétique et une chronologie bien organisées.' },
        { type: 'para', text: 'Le tissu viscéral a gardé cette mémoire cinétique. La motilité s’effectue de part et d’autre d’un point neutre ou "still point" : lors de "l’inspir", les viscères s’éloignent de l’axe du corps et lors de "l’expir", ils s’en rapprochent.' },
        { type: 'para', text: 'Son rythme est de 7 à 8/mn, donc différent du rythme respiratoire (16/mn) et du rythme crânien (10/mn).' },
        { type: 'lead', label: 'Biorythmes', text: 'la motilité est intrinsèque aux viscères mais peut subir des influences extérieures ou biorythmes :' },
        { type: 'lead', label: 'Cycle circadien', text: 'l’énergie circule dans le corps selon un rythme journalier : elle part du poumon entre 3 heures et 5 heures du matin, puis se continue par l’estomac, le gros intestin, etc. pour se terminer, au niveau du foie, de 1 heure à 3 heures. Cette circulation d’énergie est bien connue de la médecine orientale.' },
        { type: 'para', text: 'L’organe, pendant son heure, est en pleine activité. Sa motilité augmente en amplitude. Il y a une prédominance vagale nocturne. L’alternance de phases sommeil profond-sommeil paradoxal est un autre exemple des cycles circadiens.' },
        { type: 'lead', label: 'Cycles circannuels ou saisonniers', text: 'menstruations, puberté, ménopause en sont des exemples. Plus longs, ils s’étalent dans l’année, voire sur plusieurs années. L’épiphyse serait notre horloge interne.' },
        { type: 'rop', body: [
          'Mobilité et motilité peuvent être mises en évidence au niveau des zones réflexes podales. Elles reflètent bien la vitalité d’un viscère :',
          'Texture de la peau : elle est déjà un premier critère pour évaluer la vitalité d’un viscère : la présence d’une peau indurée, adhérente avec parfois la perception de microcristaux, témoigne d’une perte de sa vitalité.',
          'Écoute tissulaire : simplement en posant le pouce sur la zone réflexe, nous sommes renseignés sur sa mobilité et sa motilité : le rein est un bon exemple — un pouce est posé sur sa zone réflexe plantaire du rein, l’autre pouce est posé sur la face dorsale du pied dans la zone réflexe du quadrilatère de Grynfelt.',
          'Mobilité : lors de l’inspiration active ample du diaphragme, le rein est poussé ventralement et caudalement, et retour lors de l’expiration.',
          'Motilité : les pouces étant dans la même position, la respiration étant tenue en apnée, nous percevons néanmoins sous nos pouces le mouvement descendant et ascendant du rein, certes avec une amplitude moindre que la mobilité, mais néanmoins réelle.',
          'Relation viscéro-émotionnelle : cette technique de motilité est utilisée pour harmoniser les tensions entre le cerveau limbique et un viscère.',
        ]},
        { type: 'para', text: 'La mobilité et la motilité nécessitent de la part des viscères la possibilité de se déformer et de glisser les uns par rapport aux autres, selon des axes définis. D’où la notion d’articulations viscérales.' },
      ],
    },
    {
      id: 'articulations-viscerales',
      title: 'Articulations viscérales',
      blocks: [
        { type: 'para', text: 'Il peut paraître paradoxal de parler d’articulations viscérales, pourtant il existe des points communs avec les articulations ostéo-articulaires :' },
        { type: 'lead', label: 'Surfaces articulaires', text: 'les membranes séreuses — la plèvre, le péricarde et le péritoine — qui enveloppent les viscères à l’intérieur de leurs cavités respectives, jouent le même rôle que le cartilage pour les articulations. Elles sont constituées de deux feuillets :' },
        { type: 'lead', label: 'Feuillet pariétal', text: 'il tapisse la paroi de la cavité. Il se réfléchit, au niveau du hile du viscère, pour devenir le feuillet viscéral.' },
        { type: 'lead', label: 'Feuillet viscéral', text: 'il est très fin et très adhérant au viscère.' },
        { type: 'lead', label: 'Liquide séreux', text: 'les deux feuillets délimitent un espace virtuel occupé par le liquide séreux : le liquide pleural, le liquide péricardique et le liquide péritonéal.' },
        { type: 'lead', label: 'Moyens d’union', text: 'leur solidité n’est pas comparable aux ligaments ostéo-articulaires, néanmoins ils maintiennent les viscères en place en luttant contre la pesanteur. C’est le cas, par exemple, du ligament coronaire ou ligament suspenseur du foie qui attache le foie au diaphragme. (figure 1.5)' },
        { type: 'para', text: 'Les moyens d’union sont variés dans leur forme et dans leurs fonctions :' },
        { type: 'lead', label: 'Ligaments viscéraux', text: 'ce sont des replis séreux par accolement des deux feuillets sans interposition de liquide séreux. Ils relient les viscères à leur paroi ou avec un autre viscère. Ils sont dépourvus de vaisseaux sanguins, mais sont innervés. (Cf. Innervation des séreuses)' },
        { type: 'lead', label: 'Mésos', text: 'ce sont aussi des replis séreux, mais uniquement présents dans le tube digestif (figure 1.6.). Leur rôle de soutien est minime. Par contre, ils ont une fonction de nutrition des viscères par la présence d’un pédicule vasculo-nerveux et lymphatique entre les deux feuillets. Ils prennent le nom du viscère qu’ils rejoignent : mésogastre, mésentère, mésocolon transverse, mésosigmoïde.' },
        { type: 'lead', label: 'Omentums (anciennement épiploons)', text: 'uniquement présents dans la cavité abdominale, ils sont des replis péritonéaux qui relient deux éléments du tube digestif. (figure 1.6.) Leur rôle de maintien est faible. Ils ont un rôle vasculo-nerveux et immunitaire important :' },
        { type: 'lead', label: 'Grand omentum', text: 'il est le fameux tablier qui relie l’estomac au côlon transverse, et qui pend en avant de l’intestin grêle.' },
        { type: 'lead', label: 'Petit omentum', text: 'situé en arrière du foie et de l’estomac et en avant de l’œsophage abdominal et du duodénum, il est constitué du ligament hépatogastrique et du ligament hépato-duodénal. Il contient les vaisseaux hépatiques et gastriques, ainsi que le canal hépatique. (figure 1.7)' },
        { type: 'lead', label: 'Omentum gastro-splénique', text: 'entre l’estomac et la rate.' },
        { type: 'lead', label: 'Omentum pancréatico-splénique', text: 'entre le pancréas et la rate.' },
        { type: 'lead', label: 'Foramen omentum', text: 'il fait communiquer le grand omentum avec le petit omentum. (figure 1.7.)' },
        { type: 'rop', body: [
          'Les attaches péritonéo-viscérales (ligaments, mésos) et leurs racines sont hautement réflexogènes. La sollicitation de leurs zones réflexes facilite une réponse viscérale.',
        ]},
        { type: 'lead', label: 'Interstitium (Figure 1.8)', text: 'les travaux du Dr J.C. Gimberteau ont mis en évidence l’existence d’un continuum histologique, sans délimitation nette des tissus. Il est constitué de micro-fibrilles faisant la connexion entre la peau et les tissus plus profondément situés — muscles, fascias, viscères, os. La déformation et le glissement des différents tissus peuvent exister grâce à l’interstitium dont l’agencement de fibrilles collagéniques, entrecroisées dans les trois plans de l’espace, permettent aux viscères de s’adapter aux changements de direction générés par les mouvements.' },
        { type: 'para', text: 'L’interstitium est rempli de liquide interstitiel. En plus de son rôle d’amortisseur et d’absorbeur des contraintes et des chocs tissulaires, il est aussi un draineur de liquide.' },
        { type: 'sub', text: 'Effet turgor et pressions intra-cavitaires' },
        { type: 'para', text: 'Ils constituent le facteur essentiel de maintien et de cohésion des viscères avant même les autres moyens d’union. Ils ont un rôle de ventouse. Les deux feuillets ne peuvent se séparer dans les conditions physiologiques. Ils ne peuvent que glisser l’un par rapport à l’autre grâce au liquide séreux :' },
        { type: 'lead', label: 'Effet turgor', text: 'c’est le fait, pour un viscère, d’occuper le maximum de place qui lui est permis dans sa cavité, grâce à la "turgescence" créée par la pression vasculaire et gazeuse intra-viscérale. Cet effet turgor explique l’espace virtuel régnant entre les deux feuillets et nécessitant si peu de liquide séreux, mais suffisamment pour permettre le glissement entre les deux feuillets grâce à son haut pouvoir lubrifiant.' },
        { type: 'lead', label: 'Pressions intra-cavitaires', text: 'elles sont égales à la somme des pressions intra-viscérales. Elles équilibrent l’ensemble des pressions extra-cavitaires constituées par la pesanteur, la pression atmosphérique et la tension des muscles de la paroi de la cavité.' },
        { type: 'para', text: 'Malgré la différence de pression, très inférieure dans la cavité thoracique comparée à celle de la cavité abdominale, l’effet turgor et les pressions intra-cavitaires contribuent à donner à la colonne viscérale thoraco-abdominale une certaine cohésion des masses viscérales. Le diaphragme qui s’appuie sur elles contribue à harmoniser les pressions entre les deux cavités.' },
        { type: 'sub', text: 'Délestage et absorption des pressions' },
        { type: 'para', text: 'Les pressions intra-viscérales (effet turgor) sont supérieures aux pressions intra-cavitaires. (figure 1.9)' },
        { type: 'para', text: 'La pression régnant dans la cavité abdominale est supérieure à la pression dans la cavité thoracique. Si :' },
        { type: 'bullets', items: [
          'Pv est la pression intra-viscérale abdominale',
          'Ppe est la pression dans la cavité péritonéale',
          'Ppm est la pression intra-viscérale pulmonaire',
          'Ppl est la pression dans la cavité pleurale',
        ]},
        { type: 'para', text: 'Nous avons : Pv > Ppe > Ppm > Ppl.' },
        { type: 'para', text: 'En conséquence :' },
        { type: 'bullets', items: [
          'Les viscères sous-diaphragmatiques proches du diaphragme sont attirés céphaliquement par l’aspiration thoracique et l’aimantation diaphragmatique.',
          'Le diaphragme est bombé vers le haut par la poussée des viscères sous-diaphragmatiques.',
          'Les viscères sous-diaphragmatiques sont délestés d’une grande partie de leur poids. Ainsi, le foie, qui pèse normalement 1,5 kg, ne pèse plus que 500 g en place sous le diaphragme.',
          'Ce délestage est un moyen de lutter contre la pesanteur.',
          'Les viscères abdominaux inférieurs, qui s’éloignent de l’aimantation diaphragmatique, profitent moins de cette attraction. Ils sont attirés vers le bas (ptose), surtout si les conditions physiologiques ne sont pas réunies à la suite de séquelles traumatiques, infectieuses ou chirurgicales.',
        ]},
        { type: 'para', text: 'Pour pallier à ce risque de ptose, d’autres mécanismes existent : l’inclinaison de la cavité pelvienne en bas et en avant et la position centrale du dôme utérin répartissent une grande partie du poids des viscères de la cavité abdominale sur le pourtour de l’ouverture supérieure de la cavité pelvienne. (figure 17.8)' },
        { type: 'para', text: 'La cavité pelvienne n’est pas hermétiquement close : elle présente des orifices (fosses ischiatiques, fosse obturée) qui amortissent le poids des viscères. (figure 17.4)' },
        { type: 'para', text: 'La tonicité du périnée participe au délestage du poids des viscères abdominaux sur les viscères pelviens. (figure 17.9)' },
        { type: 'sub', text: 'Innervation des séreuses' },
        { type: 'para', text: 'Elle est double :' },
        { type: 'lead', label: 'Feuillet viscéral', text: 'il a une innervation sympathique comme les viscères.' },
        { type: 'lead', label: 'Feuillet pariétal', text: 'il a une innervation sensitive somatique commune avec sa paroi, expliquant les douleurs projetées :' },
        { type: 'para', text: 'Le péritoine pariétal postérieur est innervé par les nerfs du plexus lombal. Son irritation peut provoquer des lombalgies. (Cf. Chapitre 7 Innervation du péritoine)' },
        { type: 'para', text: 'La plèvre pariétale est innervée par le nerf phrénique et les nerfs intercostaux. Elle est douloureuse quand elle est irritée par des lésions costales.' },
        { type: 'para', text: 'Des douleurs scapulaires et de l’épaule droite peuvent avoir une origine péritonéale ou pleurale ou de la capsule de Glisson enveloppant le foie et innervées par le nerf phrénique. (Cf. chapitre 11 Foie)' },
        { type: 'para', text: 'Le nerf phrénique est constitué par les racines C3-C4-C5. La capsule gléno-humérale tient son innervation de ses fibres sensitives issues de C5. L’anastomose entre le nerf phrénique et le plexus brachial explique la projection douloureuse scapulaire droite.' },
        { type: 'rop', body: [
          'L’interdépendance entre les viscères créée par les membranes séreuses impose une approche holistique : un tissu lésé ne reste jamais isolé. Toute perte de mobilité, partielle ou totale, toute fixation ou adhérence d’un viscère, aussi minime soit-elle, signe une modification de ses mouvements qui, répétés des milliards de fois (à raison, par exemple, de 21 000 mouvements du diaphragme par 24 heures), va se répercuter dans sa chaîne de contiguïté fasciale. Une chaîne lésionnelle se met en place avec le temps selon la loi d’adaptation-compensation.',
          'Tant que la compensation est possible, les symptômes restent silencieux. Mais quand tous les processus d’adaptation sont épuisés, les symptômes apparaissent, parfois bien loin de la lésion initiale et, apparemment, sans relation avec elle.',
          'Nombreux sont les lumbagos, qui surviennent au cours d’un mouvement anodin, qu’il faut souvent mettre en lien avec des troubles intestinaux ou rénaux.',
        ]},
      ],
    },
    {
      id: 'fixations-viscerales',
      title: 'Fixations viscérales',
      blocks: [
        { type: 'para', text: 'Par analogie avec les articulations ostéo-articulaires, les articulations viscérales peuvent perdre leurs capacités de mouvement et de motilité par :' },
        { type: 'bullets', items: [
          'fixations articulaires ou adhérences',
          'fixations ligamentaires ou ptoses',
          'spasmes musculaires.',
        ]},
        { type: 'para', text: 'Ces fixations peuvent se combiner. Elles apparaissent surtout après un traumatisme, une infection ou une chirurgie :' },
        { type: 'sub', text: 'Fixations articulaires ou adhérences par traumatismes viscéraux' },
        { type: 'lead', label: 'Traumatisme direct', text: 'par exemple par le volant ou le guidon de vélo ou un coup de poing violent dans le ventre.' },
        { type: 'lead', label: 'Traumatisme indirect', text: 'dans les accidents de la circulation, type "coup du lapin", l’onde de choc générée par les forces collisionnelles peut se propager dans les cavités crânienne, thoracique, abdominale et pelvienne. Il est observé que l’onde de choc s’oriente de façon préférentielle vers les attaches gauches du foie, la rate et le rein gauche. Même en-dehors de tout choc direct, il peut exister des ruptures de la rate et du rein gauche par le déplacement violent des masses liquidiennes contre la paroi des viscères et leurs séreuses.' },
        { type: 'lead', label: 'Chute sur le coccyx, les pieds, le dos', text: 'on rencontre aussi ces fixations rénales lors de chute sur le coccyx, les pieds ou le dos. À la suite d’une fracture d’une vertèbre thoracique inférieure ou lombaire, les reins tout proches peuvent aussi être atteints.' },
        { type: 'para', text: 'Sans atteindre cette gravité, les traumatismes viscéraux passent souvent inaperçus et donc négligés. Les forces collisionnelles, plus fortes que la capacité d’absorption des déformations tissulaires, impactent le cœur des tissus :' },
        { type: 'lead', label: 'Déprogrammation des mécanorécepteurs', text: 'les nombreux mécanorécepteurs sensitifs, contenus dans les ligaments des séreuses, sont déprogrammés après un traumatisme. Les viscères, ne recevant plus les bons stimuli des centres nerveux supérieurs, perdent une partie de leurs fonctions et de leur vitalité.' },
        { type: 'lead', label: 'Microlésions et microhémorragies de l’enveloppe des viscères', text: 'reprenons l’exemple très significatif du rein gauche. La cicatrisation des séreuses va créer des adhérences et des fixations rénales s’accompagnant d’un état permanent d’irritation mécanique des nerfs du plexus lombaire longeant la face postérieure du rein. Cette irritation donne des douleurs dans le pli de l’aine, les bourses ou les grandes lèvres ainsi que sur le haut de la cuisse. (Cf. Chapitre 16 Rein)' },
        { type: 'sub', text: 'Fixations ligamentaires ou ptoses' },
        { type: 'para', text: 'Les ligaments viscéraux, mésos et omentums, ne sont que des replis séreux, sans grande capacité de soutien et d’élasticité équivalente à celle des ligaments du système ostéo-articulaire.' },
        { type: 'para', text: 'À l’exception de l’appareil suspenseur du dôme pleural qui amarre la plèvre et le dôme pleural aux processus transverses des vertèbres C6 et C7, et des ligaments suspenseurs et de soutien des organes pelviens qui ont gardé une structure fibro-musculaire contractile, les ligaments sont, pour la plupart, dépourvus de fibres musculaires contractiles depuis que l’homme s’est verticalisé. Les causes des fixations ligamentaires sont :' },
        { type: 'lead', label: 'Séquelles d’infections', text: 'à la suite d’une pleurésie, d’une péricardite ou d’une péritonite, la sécrétion du liquide séreux augmente et s’épaissit. La collection de pus va constituer un abcès qui, en cicatrisant, provoquera des adhérences des deux feuillets séreux, responsables d’une perte de glissement :' },
        { type: 'para', text: 'Les adhérences séquellaires d’une pleurésie réduisent la capacité pulmonaire et provoquent des douleurs vertébro-thoraciques à la toux et à l’éternuement.' },
        { type: 'para', text: 'Les adhérences séquellaires d’une péritonite sont sources de multiples conflits péritonéo-viscéraux. Le glissement des viscères les uns par rapport aux autres, à raison de 21 000 mouvements du diaphragme par 24 heures, se fait mal. Les axes de mobilité et de motilité sont déviés. Les fixations et adhérences enserrent les nerfs, les vaisseaux sanguins et lymphatiques, affectant l’innervation et la circulation viscérales.' },
        { type: 'para', text: 'Les tiraillements créent des douleurs locales et des spasmes musculaires. Le frein à la circulation sanguine et lymphatique entraîne une stase veineuse et une inhibition du système immunitaire.' },
        { type: 'lead', label: 'Séquelles chirurgicales', text: 'en plus de l’infection et de l’inflammation qui ont nécessité la chirurgie, l’air, en pénétrant dans les cavités thoracique ou abdominale par la chirurgie, assèche les séreuses, ce qui est un facteur d’adhérence. La cicatrisation, malgré une chirurgie de moins en moins invasive, ne peut empêcher l’accolement des deux feuillets entre eux.' },
        { type: 'para', text: 'L’adhérence crée un état permanent d’irritation par frottement des tissus entre eux. Les viscères perdent leur bon fonctionnement. Leurs rapports avec les autres viscères sont changés. Une ptose d’un rein ou de l’intestin grêle fait perdre leur continuité avec leurs organes voisins. Ils vont bouger autour de leurs points de fixation, qui deviennent leur nouvel axe de mouvement.' },
        { type: 'para', text: 'Quand il y a une perte de glissement par adhérence ou par manque de lubrification du liquide séreux, on parle alors de fibrose viscérale, comparable à l’arthrose des articulations par détérioration du cartilage et du liquide synovial.' },
        { type: 'sub', text: 'Spasmes musculaires' },
        { type: 'para', text: 'Les viscères du tube digestif, les canaux excréteurs de la vésicule biliaire, du pancréas, des reins et les bronchioles, sont pourvus en fibres musculaires lisses innervées par le système nerveux autonome. Elles permettent le péristaltisme du tube digestif, l’expansion des bronchioles et la progression des sécrétions.' },
        { type: 'para', text: 'Sous l’effet d’irritation dont les causes sont multiples — allergiques, métaboliques, traumatiques ou de stress — les fibres musculaires se spasment de façon réflexe, entraînant un ralentissement ou un arrêt du péristaltisme et des sécrétions ou un spasme des bronchioles. Le spasme est comparable à la contracture musculaire dans le système musculo-squelettique. La colopathie spasmodique est l’exemple même d’un obstacle à un bon transit et à une bonne circulation.' },
      ],
    },
    {
      id: 'relations-viscero-somatiques',
      title: 'Relations viscéro-somatiques',
      blocks: [
        { type: 'para', text: 'Les viscères sont connectés au système ostéo-musculo-articulaire par les fascias, le feuillet pariétal des séreuses et le système nerveux : toute dysfonction viscérale crée des fixations ostéo-musculo-articulaires.' },
        { type: 'para', text: 'Le motif de la consultation est souvent une douleur vertébrale ou articulaire des membres : une lombalgie, une dorsalgie ou une cervicalgie peuvent avoir une origine ostéo-musculo-articulaire, à la suite d’un traumatisme, d’un effort répété, une posture fatigante, comme elles peuvent être une « douleur projetée d’origine viscérale » — cardiaque, gastrique, hépato-biliaire, rénale, etc. (figure 1.10) Le Dr Jarricot a très bien décrit ces douleurs projetées qui s’expliquent par les liens neurologiques médullaires unissant un nerf spinal à son territoire d’influence comprenant : la peau (dermatome), les muscles (myotome), les viscères (viscérotome), les vaisseaux (angiotome), le squelette (sclérotome). (Figure 1.11)' },
      ],
    },
    {
      id: 'relations-viscero-emotionnelles',
      title: 'Relations viscéro-émotionnelles',
      blocks: [
        { type: 'para', text: 'Comme la nourriture ingérée, subissant des transformations selon un ordre chronologique, avant de devenir des substances utilisables dans l’organisme, les émotions devront être avalées, broyées, malaxées, digérées, assimilées, transformées, intégrées, rythmées, renouvelées, sélectionnées, filtrées, débarrassées de leurs déchets.' },
        { type: 'para', text: 'À l’opposé des réactions psychiques, les émotions sont déclenchées par un évènement agréable ou déplaisant, traumatique ou psychologique, accompagné de manifestations physiques, biologiques, métaboliques commandées par notre cerveau limbique et l’hypothalamus. Celui-ci active l’axe adrénergique ou axe SAM et l’axe corticotrope ou axe HHS du Mécanisme de stress. (Cf. chapitre 5 Mécanisme de stress)' },
        { type: 'para', text: 'Les viscères sont des amortisseurs d’émotions, des airbags émotionnels en quelque sorte. Quand le trop-plein émotionnel submerge notre système limbique, celui-ci déverse ce trop-plein sur nos viscères. Un évènement douloureux n’est jamais oublié. Le problème est de l’accepter, de le faire entrer dans notre vie et de l’intégrer dans notre évolution.' },
        { type: 'para', text: 'À chaque viscère correspond un type d’émotion particulier, tout en sachant qu’il s’agit d’une dominante car les organes réagissent entre eux. La Médecine orientale a depuis très longtemps établi cette relation. Jean-Pierre Barral, ostéopathe, a décrit dans un langage occidental les relations viscéro-émotionnelles dans son ouvrage « Comprendre les messages du corps », éditions Albin Michel, 2005, auquel nous ferons largement référence dans les chapitres consacrés à chaque viscère.' },
        { type: 'para', text: 'Les viscères thoraco-abdominaux sont particulièrement affectés par les stress émotionnels. Ils peuvent être classés en deux catégories :' },
        { type: 'bullets', items: [
          'Les viscères en lien avec le « Moi superficiel », le paraître, la relation avec les autres : estomac, duodénum, vésicule biliaire, cœur, vessie, utérus, prostate.',
          'Les viscères en lien avec le « Moi profond », la relation à soi-même, à l’être : foie, rein, poumon, pancréas, rate.',
        ]},
        { type: 'rop', body: [
          'Zones réflexes podales : la technique de la balance cerveau limbique-viscère consiste à mettre en relation le cerveau limbique avec le viscère en dysfonction :',
          'Poser nos pouces, l’un sur le cerveau limbique et l’autre sur le viscère en dysfonction ;',
          'Suivre l’écoute entre les deux pouces et chercher lequel des deux perturbe l’autre ;',
          'Induire l’écoute jusqu’au retour à l’équilibre. (figure 1.12)',
          'N.B. La figure 1.12 montre la balance Cerveau limbique-foie. Cette balance peut être appliquée en mettant en balance le cerveau limbique avec chacun des viscères.',
        ]},
      ],
    },
  ],
}
