// Chapter 2 content — Italian
// Source: public/chapter-2/Chapter_2_Treatment_by_ROP_Italian.docx

import type { Chapter } from './types'

export type { Block, Section, Chapter } from './types'

export const chapter2It: Chapter = {
  slug: "chapter-2",
  number: "2",
  title: "Trattamento mediante Riflessoterapia Occipito-Podalica (ROP)",
  sections: [
    {
      id: "technique",
      title: "Tecnica",
      blocks: [
        { type: "para", text: "Di seguito sono riportati diversi principi che guidano il trattamento mediante Riflessoterapia Occipito-Podalica (ROP)." },
        { type: "sub", text: "Tecnica manuale" },
        { type: "para", text: "La tecnica è esclusivamente manuale, eseguita con il polpastrello del pollice o con l'articolazione interfalangea prossimale dell'indice, senza utilizzare olio né crema." },
        { type: "sub", text: "Pressione" },
        { type: "para", text: "La pressione viene applicata sulle zone riflesse con l'obiettivo di stimolare i meccanorecettori situati nello strato epidermico-dermico delle zone occipitali e plantari." },
        { type: "para", text: "Questi meccanorecettori sono i seguenti:" },
        { type: "leadBullets", items: [
          { label: "Corpuscoli di Meissner", text: "I corpuscoli di Meissner sono inseriti nelle papille dermiche, cioè nelle proiezioni ascendenti del derma verso l'epidermide. Sono sensibili a una pressione fine, non dolorosa, diretta alla sensibilità epicritica. Si trovano preferenzialmente nella cute glabra, in particolare nelle piante dei piedi, nei palmi delle mani, nelle labbra e negli organi genitali." },
          { label: "Dischi di Merkel", text: "I dischi di Merkel sono situati alla base dell'epidermide, immediatamente al di sopra del derma. Sono sensibili a una pressione delicata applicata sulla cute." },
        ]},
        { type: "para", text: "Non appena la pressione manuale deforma lo strato epidermico-dermico — identificato dalla sensazione di una tensione cutanea \"come un tamburo\" che respinge il dito — i corpuscoli di Meissner e i dischi di Merkel generano potenziali d'azione che viaggiano attraverso le vie sensitive del sistema lemniscale." },
        { type: "lead", label: "Il sistema lemniscale", text: "Il sistema lemniscale è un fascio di fibre afferenti del midollo spinale. Nella nostra tecnica viene deliberatamente preso di mira per le sue proprietà:" },
        { type: "bullets", items: [
          "trasmette la sensibilità tattile fine, non dolorosa;",
          "assicura una trasmissione rapida e precisa degli impulsi nervosi che veicola;",
          "presenta una ricca organizzazione somatotopica nel cervello;",
          "ha un'azione analgesica: modula il dolore trasmesso dal sistema extralemniscale. Questa proprietà analgesica è spiegata dalla teoria del gate control: gli impulsi nervosi che viaggiano attraverso il sistema lemniscale raggiungono più rapidamente il corno dorsale del midollo spinale e contribuiscono a chiudere il cancello agli impulsi dolorosi più lenti.",
        ]},
        { type: "sub", text: "Rilevanza in ROP" },
        { type: "para", text: "Durante il trattamento riflesso devono essere evitati la pressione energica e lo sfregamento triturante dei tessuti. Più si preme forte, più si sentono le proprie dita, meno si percepiscono i punti di riferimento ossei che guidano la ricerca delle zone riflesse, e più diventa difficile leggere tali zone." },
        { type: "para", text: "L'obiettivo di ripristinare una buona qualità tissutale riflette il rispetto che attribuiamo all'organismo. Lo scopo non è forzare l'organismo, ma coinvolgerlo delicatamente. Anche un trattamento ben condotto costituisce uno stressor — positivo, certamente — ma deve tenere conto della capacità di autocorrezione dell'individuo." },
        { type: "sub", text: "Le tre fasi del trattamento manuale" },
        { type: "leadBullets", items: [
          { label: "1. Fase diagnostica testurale", text: "Questa fase consiste nel ricercare zone riflesse caratterizzate da una modificazione della texture della cute occipitale e plantare: rugosità, densificazione, perdita di scorrimento o sensazione di cristalli. Questi reperti devono confermare la diagnosi ottenuta al termine dell'esame clinico." },
          { label: "2. Fase terapeutica", text: "La pressione è fine e non dolorosa, diretta alla sensibilità epicritica; un dolore acuto indicherebbe un sovradosaggio. La manovra manuale consiste nel mobilizzare lo strato epidermico-dermico al fine di stimolare i meccanorecettori all'origine del sistema lemniscale, e nel fornire un input sensoriale correttivo ai centri nervosi superiori coinvolti nella regolazione delle regioni disfunzionali del corpo." },
          { label: "3. La fase del \"lasciar essere\"", text: "Dopo la stimolazione, l'organismo ha bisogno di tempo per integrare e stabilizzare gli adattamenti neurovegetativi (autonomici), vascolari e tissutali. Non è la stimolazione delle zone riflesse in sé a produrre l'effetto terapeutico, bensì la risposta dell'organismo. A livello delle zone riflesse, questa risposta si esprime con un miglioramento della texture cutanea — maggiore elasticità e scorrimento — e con una riduzione della sensibilità." },
        ]},
        { type: "para", text: "Questo periodo di latenza di pochi secondi corrisponde al tempo necessario perché l'organismo avvii l'anello riflesso terapeutico responsabile della decostruzione dell'anello riflesso patologico implicato nella disfunzione." },
        { type: "para", text: "La capacità e la qualità della risposta dell'organismo dipendono dalla sua vitalità e dalle sue capacità adattativo-compensatorie, in relazione alla fase della sindrome generale di adattamento in cui evolve la malattia: allarme, adattamento, resistenza o esaurimento." },
      ],
    },
    {
      id: "modalites",
      title: "Modalità di trattamento",
      blocks: [
        { type: "leadBullets", items: [
          { label: "Durata", text: "L'efficacia del trattamento non è correlata alla durata della seduta." },
          { label: "Frequenza", text: "Un intervallo di tre settimane tra le sedute corrisponde al tempo necessario perché l'organismo integri il trattamento. Trattamenti troppo ravvicinati non lasciano tempo sufficiente ai processi neurovascolari e strutturali coinvolti nei disturbi funzionali per sostenere la regolazione fisiologica dei visceri e delle strutture disfunzionali." },
        ]},
        { type: "para", text: "Per la maggior parte delle indicazioni, tre sedute sono sufficienti per ottenere un miglioramento soddisfacente, con la possibilità di rivedere il paziente sei mesi più tardi se necessario." },
        { type: "para", text: "Se dopo tre sedute non si osserva un miglioramento significativo, la diagnosi deve essere riconsiderata e, se necessario, il paziente deve essere nuovamente indirizzato al proprio medico." },
        { type: "para", text: "Le condizioni croniche richiedono un follow-up più regolare." },
      ],
    },
    {
      id: "hierarchisation",
      title: "Gerarchia del trattamento",
      blocks: [
        { type: "para", text: "Non esiste un protocollo immutabile: un protocollo di questo tipo contraddirebbe il concetto olistico. Sono i test a determinare la priorità." },
        { type: "para", text: "Tuttavia, possono essere proposte grandi linee guida di trattamento, ma non devono essere utilizzate per confinare il paziente in un protocollo rigido scollegato dalla realtà clinica." },
        { type: "leadBullets", items: [
          { label: "1. Sequele di trauma, chirurgia o infezione", text: "I sintomi riferiti spontaneamente dal paziente e comparsi dopo un trauma, un intervento chirurgico o un'infezione coincidono generalmente con l'esame clinico. Tali sintomi conservano la loro priorità." },
          { label: "2. Anamnesi e test di ascolto globale/locale", text: "In assenza di trauma, anamnesi chirurgica o infezione riferiti spontaneamente, sono l'anamnesi, l'esame clinico e i test di ascolto globale e locale a condurci alla fissazione dominante. Attraverso meccanismi di adattamento-compensazione e poi di scompensazione, questa fissazione può avere prodotto sintomi talvolta situati lontano dalla fissazione stessa." },
          { label: "3. Ascolto emozionale", text: "Può essere necessario ricercare vecchi traumi fisici o psico-emozionali che siano stati dimenticati, rimossi in determinati strati dell'inconscio o persino deliberatamente soppressi. L'ascolto tissutale, seguito dall'ascolto emozionale, può aiutare a rivelare eventi significativi — e soprattutto negativi — codificati nell'amigdala e nell'ippocampo del sistema limbico." },
          { label: "4. Meccanismo dello stress", text: "Una fissazione tissutale locale — o sindrome locoregionale — deve sempre essere collocata nel suo contesto generale, cioè nella sindrome generale di adattamento, che in realtà riflette la storia dell'individuo." },
        ]},
        { type: "sub", text: "Zone riflesse occipitali e plantari" },
        { type: "rop", body: [
          "1. Zone riflesse occipitali",
          "2. Sindrome generale di adattamento — Sostenere la regolazione neurovegetativa e l'adattamento generale prima di affrontare la disfunzione locale:",
          "· MRP: occipite-C1-C2, nervo trigemino V, nervo vago X e nervo ipoglosso XII, falce cerebrale e tentorio del cervelletto, seconda vertebra sacrale S2, base cranica e volta cranica",
          "· Circolazione del liquido cerebrospinale: sistema venoso — forame giugulare, respirazione profonda — compressione del quarto ventricolo, e sincronizzazione SSB-S2",
          "· Diencefalo, tronco encefalico, ipofisi",
          "· Nervo vago — visceri del territorio cervico-toraco-addominale: forame magno, forame giugulare, seno carotideo, iato esofageo",
          "· Sistema parasimpatico pelvico — visceri pelvici e parte distale del colon",
          "· Colonna vertebrale, articolazioni costo-trasversarie, innervazione simpatica — catena gangliare paravertebrale toracica",
          "· Plesso prevertebrale",
        ]},
        { type: "rop", body: [
          "3. Sindrome locoregionale — Affrontare gli anelli meccanici e neurovegetativi collegati alla regione sintomatica:",
          "· Plessi e nervi del sistema nervoso somatico — relazioni viscerosomatiche",
          "· Sistema viscerale",
          "· Cavità addominale o pelvica, a seconda del sistema viscerale coinvolto",
        ]},
        { type: "rop", body: [
          "4. Sistema limbico — Integrare le dimensioni dello stress, dell'emozione e della memoria corporea che possono mantenere gli anelli neurovegetativi e tissutali:",
          "· Amigdala, ippocampo, insula",
          "· Equilibrio cervello limbico-viscere disfunzionale: ascolto-induzione, con un pollice posto sul viscere disfunzionale dominante e l'altro pollice sull'area del cervello limbico",
        ]},
      ],
    },
    {
      id: "exemple-clinique",
      title: "Esempio",
      blocks: [
        { type: "sub", text: "Lombosciatalgia sinistra comparsa alcuni mesi dopo il parto nella signora X, trentenne" },
        { type: "sub", text: "Anamnesi" },
        { type: "bullets", items: [
          "Nessuna storia nota di trauma;",
          "Il dolore lombosciatalgico si aggrava durante la mestruazione;",
          "L'incontinenza urinaria da sforzo viene rivelata durante l'anamnesi;",
          "Il travaglio è stato lungo — paziente primipara;",
          "L'esame ginecologico è normale. La radiografia mostra un lieve restringimento a livello L5-S1 senza spostamento della radice nervosa S1;",
          "Il dolore la colpisce emotivamente perché è lavoratrice autonoma e desidera riprendere rapidamente l'attività professionale.",
        ]},
        { type: "sub", text: "Test" },
        { type: "bullets", items: [
          "I test di ascolto globale in posizione eretta e seduta mostrano una flessione anteriore del tronco e una bassa flessione laterale sinistra.",
          "I test vertebrali mostrano una lieve perdita di mobilità sinistra ai livelli vertebrali L2-L3 e L5-S1, e una fissazione sinistra dell'articolazione sacroiliaca e del coccige.",
          "I test di ascolto locale in decubito supino mostrano un miglioramento del test di Lasègue completato quando la mano di ascolto posta sulla sinfisi pubica viene attirata leggermente verso sinistra e in profondità verso la regione cervico-istmica dell'utero.",
          "In decubito laterale sinistro, le dita del terapeuta, poste nella regione addominale inferiore, percepiscono una resistenza alla mobilità uterina.",
          "Il test dell'anca sinistra mostra una perdita della rotazione mediale.",
        ]},
        { type: "sub", text: "Meccanismo anatomo-fisiopatologico" },
        { type: "lead", label: "Sindrome locoregionale", text: "Nel modello ROP, la sciatalgia sinistra è correlata a una malposizione dell'utero, deviato a sinistra dalla tensione del legamento uterosacrale sinistro. Di conseguenza, si osservano:" },
        { type: "bullets", items: [
          "fissazione parziale dell'articolazione sacroiliaca sinistra;",
          "fibrosi del muscolo piriforme sinistro, che interferisce con il nervo sciatico;",
          "deviazione dell'utero, che trascina con sé anche la vescica e il sacro;",
          "fissazione sacrococcigea, che conduce a una perdita di elasticità e contrattilità del pavimento pelvico.",
        ]},
        { type: "lead", label: "Sindrome generale", text: "" },
        { type: "bullets", items: [
          "Il ciclo mestruale è sotto il controllo ormonale e neurovegetativo dei centri diencefalici.",
          "La fissazione sacrococcigea mette in tensione la dura madre spinale e, attraverso di essa, il Meccanismo Respiratorio Primario — MRP.",
          "Il sistema portale drena il sangue venoso dalla pelvi. Qualsiasi fissazione epatica rallenta il ritorno venoso dalla piccola pelvi.",
          "Anche il rene sinistro contribuisce al ritorno venoso dalla piccola pelvi.",
          "Nella sua nuova vita di madre, il suo sistema limbico è attivato dall'ansia, dalla sciatalgia e dal ritorno all'attività professionale perturbato dalla maternità.",
        ]},
        { type: "sub", text: "Trattamento ROP" },
        { type: "rop", body: [
          "1. Zone riflesse occipitali",
          "2. Sindrome generale di adattamento: MRP, Diencefalo, Tronco encefalico, Ipofisi, Ghiandole surrenali, Colonna vertebrale, Fegato, Rene sinistro",
          "3. Sindrome locoregionale: Regione cervico-istmica dell'utero, Muscolo piriforme, Legamenti sacrotuberoso e sacrospinoso, Nervo pudendo, Articolazioni sacrococcigea e sacroiliaca, Plessi sacrale e sciatico sinistri",
          "4. Sistema limbico: Amigdala, Ippocampo, Insula",
        ]},
      ],
    },
    {
      id: "contre-indications",
      title: "Controindicazioni",
      blocks: [
        { type: "para", text: "ROP appartiene a un quadro di cure funzionali. Qualsiasi sospetto di malattia organica o la presenza di un segno d'allarme richiede una valutazione medica." },
        { type: "para", text: "Sintomi che possono apparire innocui possono talvolta nascondere una malattia grave. È nostra responsabilità riconoscere i segni che devono portarci a non intervenire, conformemente al principio primum non nocere — prima di tutto, non nuocere." },
        { type: "para", text: "Dettaglieremo le controindicazioni per ciascun viscere, ma i seguenti sintomi devono già destare sospetto:" },
        { type: "bullets", items: [
          "dolore non meccanico, aggravato durante la prima parte della notte;",
          "dolore toracico atipico, dispnea, malessere;",
          "sangue nelle urine o nelle feci;",
          "febbre o malattia infettiva;",
          "perdita di peso inspiegata;",
          "rischio di migrazione di un trombo;",
          "pallore e marcata stanchezza;",
          "deficit neurologico: disfunzione sfinterica o disturbi sensitivi progressivi;",
          "ansia o paura di morire;",
          "ammettere la propria impotenza di fronte a un caso clinico che non si comprende.",
        ]},
        { type: "para", text: "È importante conoscere le presentazioni delle malattie gravi, a causa del rischio di ritardare la diagnosi medica, soprattutto quando i pazienti ci consultano come professionisti di prima linea senza precedente screening medico." },
        { type: "para", text: "ROP non deve sostituire un trattamento medico appropriato. Mantiene tuttavia il suo posto come terapia integrativa accanto alla medicina convenzionale, contribuendo a ridurre le conseguenze funzionali della malattia o gli effetti indesiderati ma talvolta inevitabili di trattamenti farmacologici intensivi, in particolare in oncologia, o semplicemente a sostenere i pazienti nel loro benessere." },
        { type: "para", text: "Dopo un intervento chirurgico addominale, un intervento basato sui riflessi può ridurre gli spasmi della muscolatura liscia dei visceri, sostenere il ripristino del transito intestinale e ridurre il ricorso a farmaci analgesici e sintomatici. Agendo a distanza attraverso le vie riflesse, lontano dal viscere disfunzionale, il rischio di effetti iatrogeni è limitato: ciò offre sicurezza sia al paziente sia al terapeuta." },
      ],
    },
    {
      id: "indications",
      title: "Indicazioni",
      blocks: [
        { type: "para", text: "Le indicazioni si basano sull'anamnesi, sui test, sulla coerenza delle zone riflesse e sulla gerarchia del terreno." },
        { type: "para", text: "Le patologie funzionali costituiscono il principale campo delle cosiddette terapie integrative. Sono la conseguenza di uno squilibrio del sistema neurovascolare che compare a monte della malattia. La loro caratteristica particolare è di essere reversibili, extracellulari e poco — o per nulla — rilevabili con radiografia, TC o RM, perché l'alterazione anatomica non è ancora iniziata." },
        { type: "para", text: "Finché la vitalità dell'organismo è capace di adattamento-compensazione, la salute viene preservata. Il nostro ruolo è aiutare il paziente a migliorare la propria vitalità per ripristinare l'equilibrio fisiologico." },
        { type: "para", text: "Dettaglieremo i sintomi funzionali per ciascun viscere. I tipi più comuni di sintomi funzionali incontrati sono:" },
        { type: "bullets", items: [
          "dolore muscoloscheletrico;",
          "sequele di trauma osteo-muscolo-articolare;",
          "sequele di trauma dei nervi spinali e cranici;",
          "disfunzioni viscerali correlate a fissazioni tissutali e ad anelli neurovegetativi;",
          "disturbi viscerosomatici e somatoviscerali;",
          "disturbi della regolazione neurovegetativa;",
          "stress emozionale e ansia.",
        ]},
      ],
    },
    {
      id: "actions",
      title: "Effetti del trattamento riflessoterapico",
      blocks: [
        { type: "para", text: "Come già affermato nell'introduzione, osserviamo spesso risultati clinici che non possiamo ancora misurare oggettivamente. La nostra azione ha effetti sia locali sia generali:" },
        { type: "bullets", items: [
          "azione analgesica;",
          "riequilibrio neurovegetativo: spostamento verso segni parasimpatici — calma, sbadigli, sonnolenza, rilassamento marcato, bisogno di riposo;",
          "miglioramento del transito intestinale, della diuresi e delle sensazioni viscerali;",
          "riduzione delle fissazioni vertebrali a livello metamerico del viscere — relazione viscerosomatica.",
        ]},
      ],
    },
    {
      id: "reactions",
      title: "Reazioni al trattamento",
      blocks: [
        { type: "leadBullets", items: [
          { label: "Reazioni immediate", text: "Rilassamento." },
          { label: "Reazioni entro 24-48 ore", text: "Indolenzimento muscolare o lieve affaticabilità; sogni, emersione di ricordi." },
          { label: "Reazioni nelle settimane successive", text: "Il recupero della vitalità dovrebbe agire non solo localmente, a livello visceroghiandolare, ma anche sulla regolazione ormonale e biochimica, sull'immunità locale e generale e sulla psiche, sebbene questi effetti non possano necessariamente essere misurati oggettivamente." },
        ]},
        { type: "para", text: "Queste reazioni transitorie sono benefiche e persino desiderabili, e sono specifiche di ciascun individuo. Possono riflettere l'adattamento dell'organismo a uno stressor certamente positivo, ma a esso non familiare." },
        { type: "para", text: "Nel modello ROP, vengono interpretate come segni di eliminazione e regolazione fisiologica, tradizionalmente descritti come eliminazione di \"tossine\" accumulate." },
        { type: "para", text: "Se le reazioni sono intense, durano oltre 72 ore o sono accompagnate da segni preoccupanti, la situazione deve essere rivalutata e il paziente indirizzato al medico." },
        { type: "para", text: "L'intervallo di tre-quattro settimane deve essere rispettato per permettere all'organismo di integrare i cambiamenti prima di intraprendere la seduta successiva." },
      ],
    },
    {
      id: "conseils",
      title: "Consigli",
      blocks: [
        { type: "para", text: "\"Prima di cercare di guarire qualcuno, chiedigli se è pronto a rinunciare alle cose che lo hanno fatto ammalare.\" — tradizionalmente attribuito a Ippocrate" },
        { type: "para", text: "Anche il miglior trattamento non può garantire un miglioramento significativo e duraturo se non è accompagnato da consigli essenziali per prolungare l'effetto del trattamento." },
        { type: "para", text: "Questi consigli si basano il più delle volte sul buon senso:" },
        { type: "bullets", items: [
          "riposo relativo — evitare il sovraccarico fisico il giorno del trattamento;",
          "alimentazione sana;",
          "idratazione adeguata;",
          "attività fisica regolare;",
          "diventare parte attiva della propria salute;",
          "mantenere pensieri positivi;",
          "avere una vita sociale appagante, sia personale sia professionale;",
          "registrare i cambiamenti: dolore da 0 a 10, sonno, transito intestinale, energia;",
          "ritornare con questi elementi per valutare l'effetto in modo più oggettivo e adattare la gerarchia del trattamento.",
        ]},
      ],
    },
  ],
  revisionSheet: {
    src: '/chapter-2/Chap2 - Fiche de revision.png',
    alt: 'Scheda di revisione — Capitolo 2, Trattamento mediante R.O.P.',
    caption: 'Scheda di revisione — Capitolo 2 · Trattamento mediante R.O.P.',
  },
}
