// Chapter 19 - slide <-> text synchronisation map for the combined reading
// experience (/lecture/chapitre-19).
//
// Slides are supplied as pre-rendered PNGs in public/chapter-19/slides.

export type SyncSlide = { src: string; title: string; orientation?: 'portrait' }
export type SyncAnchor = { sectionId: string; blockIndex: number; itemIndex?: number; slide: number | number[]; gapBefore?: 'half'; end?: { sectionId: string; blockIndex: number; itemIndex?: number } }
export type SyncBreakPoint = { sectionId: string; blockIndex: number; itemIndex?: number }

export const chapter19Slides: SyncSlide[] = [
  { src: '/chapter-19/slides/slide-01.png', title: 'Chapitre 19 : appareil génital féminin' },
  { src: '/chapter-19/slides/slide-02.png', title: 'La loge viscérale pelvienne' },
  { src: '/chapter-19/slides/slide-03.png', title: 'Morphologie et paroi de l’utérus' },
  { src: '/chapter-19/slides/slide-04.png', title: 'Orientation physiologique : antéversion et antéflexion' },
  { src: '/chapter-19/slides/slide-05.png', title: 'Moyens de soutien de l’utérus et modèle de la Croix de Richard' },
  { src: '/chapter-19/slides/slide-06.png', title: 'Vascularisation de l’utérus' },
  { src: '/chapter-19/slides/slide-07.png', title: 'Innervation autonome de l’utérus' },
  { src: '/chapter-19/slides/slide-08.png', title: 'La cinématique pelvienne' },
  { src: '/chapter-19/slides/slide-09.png', title: 'Topographie et variabilité de position de l’ovaire' },
  { src: '/chapter-19/slides/slide-10.png', title: 'Fixation et vascularisation ovarienne' },
  { src: '/chapter-19/slides/slide-11.png', title: 'Trompe utérine : segments et rapports avec l’ovaire' },
  { src: '/chapter-19/slides/slide-12.png', title: 'Ovaire : situation, rapports et mobilité' },
  { src: '/chapter-19/slides/slide-13.png', title: 'Physiologie hormonale : axe hypothalamo-hypophyso-ovarien' },
  { src: '/chapter-19/slides/slide-14.png', title: 'Cycle ovarien : trois temps clés' },
  { src: '/chapter-19/slides/slide-15.png', title: 'Pathologies courantes : quatre motifs principaux' },
  { src: '/chapter-19/slides/slide-16.png', title: 'Signes d’alerte gynécologiques — quand orienter rapidement' },
  { src: '/chapter-19/slides/slide-17.png', title: 'De la plainte à l’orientation' },
  { src: '/chapter-19/slides/slide-18.png', title: 'Douleurs pelviennes — douleurs cycliques' },
  { src: '/chapter-19/slides/slide-19.png', title: 'Douleurs pelviennes — douleurs non cycliques' },
  { src: '/chapter-19/slides/slide-20.png', title: 'Dyspareunies — superficielles, intermédiaires et profondes' },
  { src: '/chapter-19/slides/slide-21.png', title: 'Hémorragies génitales — ménorragies et métrorragies' },
  { src: '/chapter-19/slides/slide-22.png', title: 'Aménorrhées — primaires ou secondaires' },
  { src: '/chapter-19/slides/slide-23.png', title: 'Leucorrhées pathologiques — pertes vaginales anormales' },
  { src: '/chapter-19/slides/slide-24.png', title: 'Grossesse extra-utérine — urgence médicale' },
  { src: '/chapter-19/slides/slide-25.png', title: 'Salpingite — infection des trompes utérines' },
  { src: '/chapter-19/slides/slide-26.png', title: 'Fibrome utérin' },
  { src: '/chapter-19/slides/slide-27.png', title: 'Kystes ovariens — fonctionnels ou organiques' },
  { src: '/chapter-19/slides/slide-28.png', title: 'Pathologies fonctionnelles et chaînes lésionnelles' },
  { src: '/chapter-19/slides/slide-29.png', title: 'Conséquences possibles d’une perte de mobilité pelvienne' },
  { src: '/chapter-19/slides/slide-30.png', title: 'Syndrome prémenstruel — manifestations de la phase lutéale' },
  { src: '/chapter-19/slides/slide-31.png', title: 'Règles douloureuses — rôle des prostaglandines' },
  { src: '/chapter-19/slides/slide-32.png', title: 'Endométriose : maladie inflammatoire chronique' },
  { src: '/chapter-19/slides/slide-33.png', title: 'Utérus — relations viscéro-somatiques' },
  { src: '/chapter-19/slides/slide-34.png', title: 'Vécu émotionnel, stress et symptômes uro-génitaux ou mammaires' },
  { src: '/chapter-19/slides/slide-35.png', title: 'Protocole clinique ROP : l’utérus' },
  { src: '/chapter-19/slides/slide-36.png', title: 'Protocole clinique ROP : ovaires et trompes' },
  { src: '/chapter-19/cartographie/figure-19-01.png', title: 'Cartographie ROP : rein gauche' },
  { src: '/chapter-19/cartographie/figure-19-03.png', title: 'Cartographie ROP : surrénale gauche' },
  { src: '/chapter-19/cartographie/figure-19-05.png', title: 'Cartographie ROP : grand foramen ischiatique' },
  { src: '/chapter-19/cartographie/figure-19-07.png', title: 'Cartographie ROP : petit foramen ischiatique' },
  { src: '/chapter-19/cartographie/figure-19-09.png', title: 'Cartographie ROP : fosse obturée et muscles obturateurs' },
  { src: '/chapter-19/cartographie/figure-19-11.png', title: 'Cartographie ROP : ligaments sacro-tubéral et sacro-épineux' },
  { src: '/chapter-19/cartographie/figure-19-13.png', title: 'Cartographie ROP : ovaire' },
  { src: '/chapter-19/cartographie/figure-19-15.png', title: 'Cartographie ROP : ligament et canal inguinaux' },
  { src: '/chapter-19/cartographie/figure-19-17.png', title: 'Cartographie ROP : noyau fibreux central du périnée et fente uro-génitale' },
  { src: '/chapter-19/cartographie/figure-19-19.png', title: 'Cartographie ROP : ligaments sacro-tubéral et sacro-épineux — repère pelvien' },
  { src: '/chapter-19/cartographie/figure-19-21.png', title: 'Cartographie ROP : trompe utérine' },
]

export const chapter19SlideAnchors: SyncAnchor[] = [
  { sectionId: 'uterus-presentation', blockIndex: -1, slide: 1 },
  { sectionId: 'uterus-presentation', blockIndex: 1, slide: 2 },
  { sectionId: 'uterus-anatomie', blockIndex: 0, slide: 3 },
  { sectionId: 'uterus-anatomie', blockIndex: 2, slide: 4 },
  { sectionId: 'uterus-anatomie', blockIndex: 6, slide: 5 },
  { sectionId: 'uterus-vascularisation', blockIndex: -1, slide: 6 },
  { sectionId: 'uterus-innervation', blockIndex: -1, slide: 7 },
  { sectionId: 'uterus-physiologie', blockIndex: 0, slide: 8 },
  { sectionId: 'ovaires-trompes-situation', blockIndex: 0, slide: 9 },
  { sectionId: 'ovaires-trompes-anatomie', blockIndex: 2, slide: 10 },
  { sectionId: 'ovaires-trompes-anatomie', blockIndex: 4, slide: 11 },
  { sectionId: 'ovaires-trompes-rapports', blockIndex: 0, slide: 12 },
  { sectionId: 'ovaires-trompes-physiologie', blockIndex: 3, slide: 13 },
  { sectionId: 'ovaires-trompes-physiologie', blockIndex: 4, slide: 14 },
  { sectionId: 'ovaires-trompes-pathologies-courantes', blockIndex: 0, slide: 15 },
  { sectionId: 'ovaires-trompes-pathologies-courantes', blockIndex: 1, slide: [16, 17] },
  { sectionId: 'ovaires-trompes-pathologies-courantes', blockIndex: 3, itemIndex: 0, slide: 18 },
  { sectionId: 'ovaires-trompes-pathologies-courantes', blockIndex: 3, itemIndex: 6, slide: 19 },
  { sectionId: 'ovaires-trompes-pathologies-courantes', blockIndex: 3, itemIndex: 13, slide: 20 },
  { sectionId: 'ovaires-trompes-pathologies-courantes', blockIndex: 4, slide: 21 },
  { sectionId: 'ovaires-trompes-pathologies-courantes', blockIndex: 6, slide: 22 },
  { sectionId: 'ovaires-trompes-pathologies-courantes', blockIndex: 8, slide: 23 },
  { sectionId: 'ovaires-trompes-pathologies-courantes', blockIndex: 13, itemIndex: 16, slide: 24 },
  { sectionId: 'ovaires-trompes-pathologies-courantes', blockIndex: 13, itemIndex: 23, slide: 25 },
  { sectionId: 'ovaires-trompes-pathologies-courantes', blockIndex: 13, itemIndex: 27, slide: [26, 27] },
  { sectionId: 'ovaires-trompes-indications', blockIndex: -1, slide: [28, 29] },
  { sectionId: 'ovaires-trompes-indications', blockIndex: 0, slide: 30 },
  { sectionId: 'ovaires-trompes-indications', blockIndex: 2, slide: 31 },
  { sectionId: 'ovaires-trompes-indications', blockIndex: 9, slide: 32 },
  { sectionId: 'uterus-relations-viscero-somatiques', blockIndex: 0, slide: 33 },
  { sectionId: 'ovaires-trompes-relations-viscero-emotionnelles', blockIndex: 0, slide: 34 },
  { sectionId: 'zones-reflexes-podales', blockIndex: 0, slide: 35 },
  { sectionId: 'zones-reflexes-podales', blockIndex: 11, slide: 44, end: { sectionId: 'zones-reflexes-podales', blockIndex: 11 } },
  { sectionId: 'zones-reflexes-podales', blockIndex: 12, slide: 45, end: { sectionId: 'zones-reflexes-podales', blockIndex: 12 } },
  { sectionId: 'zones-reflexes-podales', blockIndex: 17, slide: 39, end: { sectionId: 'zones-reflexes-podales', blockIndex: 17 } },
  { sectionId: 'zones-reflexes-podales', blockIndex: 18, slide: 40, end: { sectionId: 'zones-reflexes-podales', blockIndex: 18 } },
  { sectionId: 'zones-reflexes-podales', blockIndex: 19, slide: 41, end: { sectionId: 'zones-reflexes-podales', blockIndex: 19 } },
  { sectionId: 'zones-reflexes-podales', blockIndex: 20, slide: 42, end: { sectionId: 'zones-reflexes-podales', blockIndex: 20 } },
  { sectionId: 'zones-reflexes-podales', blockIndex: 21, slide: 46, end: { sectionId: 'zones-reflexes-podales', blockIndex: 21 } },
  { sectionId: 'zones-reflexes-podales', blockIndex: 25, slide: 36 },
  { sectionId: 'zones-reflexes-podales', blockIndex: 38, slide: 43, end: { sectionId: 'zones-reflexes-podales', blockIndex: 38 } },
  { sectionId: 'zones-reflexes-podales', blockIndex: 39, slide: 47, end: { sectionId: 'zones-reflexes-podales', blockIndex: 39 } },
  { sectionId: 'zones-reflexes-podales', blockIndex: 49, slide: 37, end: { sectionId: 'zones-reflexes-podales', blockIndex: 49 } },
  { sectionId: 'zones-reflexes-podales', blockIndex: 50, slide: 38, end: { sectionId: 'zones-reflexes-podales', blockIndex: 50 } },
]

export const chapter19HalfBreaks: SyncBreakPoint[] = [
  { sectionId: 'ovaires-trompes-pathologies-courantes', blockIndex: 1 },
  { sectionId: 'ovaires-trompes-pathologies-courantes', blockIndex: 3, itemIndex: 6 },
  { sectionId: 'ovaires-trompes-pathologies-courantes', blockIndex: 3, itemIndex: 13 },
  { sectionId: 'ovaires-trompes-pathologies-courantes', blockIndex: 13, itemIndex: 17 },
  { sectionId: 'ovaires-trompes-indications', blockIndex: -1 },
  { sectionId: 'ovaires-trompes-indications', blockIndex: 10, itemIndex: 1 },
]
