// Chapter 4 — private reworked-edition slide ↔ text map.
// The synthesis assets are isolated from the published Chapter 4 deck.

const synthesis = (file: number, title: string) => ({
  src: `/chapter-4/rework-slides/slide-${String(file).padStart(2, '0')}.png`,
  title,
})

const endAt = (sectionId: string, blockIndex: number) => ({ end: { sectionId, blockIndex } })

export const chapter4ReworkSlides = [
  synthesis(1, 'Système nerveux autonome'),
  synthesis(2, 'Synthèse visuelle du chapitre'),
  synthesis(3, 'Niveau 2 — Régulation neuro-végétative et adaptation'),
  synthesis(4, 'Deux systèmes : Parasympathique et Sympathique'),
  synthesis(5, 'Physiologie générale du SNA'),
  synthesis(6, 'Cartographie des innervations'),
  synthesis(7, 'Relation Parasympathique–Sympathique'),
  synthesis(8, 'Interdépendance fonctionnelle au sein des plexus autonomes'),
  synthesis(9, 'Neuro-endocrinologie et neuromédiateurs'),
  synthesis(10, 'Le sommeil : prérequis de l’équilibre autonome'),
  synthesis(11, 'Organisation fonctionnelle du système nerveux autonome'),
  synthesis(12, 'Organisation crânio-sacrale du parasympathique'),
  synthesis(13, 'Innervation parasympathique céphalique : les ganglions crâniens'),
  synthesis(14, 'Origines motrices du nerf vague : noyau dorsal et noyau ambigu'),
  synthesis(15, 'Le trajet du nerf vague X : du crâne à l’abdomen'),
  synthesis(16, 'Les troncs vagaux : passage diaphragmatique et distribution abdominale'),
  synthesis(17, 'Le Parasympathique pelvien'),
  synthesis(18, 'Nerf vague viscéro-sensitif : intéroception'),
  // The six new sympathetic slides are ordered by the revised text flow.
  synthesis(22, 'Origine médullaire du sympathique'),
  synthesis(21, 'Organisation métamérique du sympathique'),
  synthesis(23, 'Chaîne ganglionnaire thoracique'),
  synthesis(24, 'Chaîne ganglionnaire cervicale'),
  synthesis(25, 'Chaîne ganglionnaire lombale'),
  synthesis(19, 'Intéroception, nociception et douleurs rapportées'),
  synthesis(20, 'Les dermalgies réflexes'),
  // Source Slide 27 is intentionally absent.
  synthesis(29, 'Plexus prévertébraux : convergence vagale et sympathique'),
  synthesis(30, 'Le plexus hypogastrique inférieur'),
  synthesis(31, 'Fonctions pelviennes : contrôle autonome et somatique'),
  synthesis(32, 'Le système nerveux entérique : autonomie locale et modulation extrinsèque'),
  synthesis(33, 'Les glandes surrénales et le stress'),
  synthesis(34, 'Synthèse : trois modalités coordonnées de régulation viscérale'),
  synthesis(35, 'Zones réflexes podales du SNA'),
  { src: '/chapter-4/rework-reflex/slide-01.png', title: 'Cartographie ROP : territoire céphalique du parasympathique' },
  { src: '/chapter-4/rework-reflex/slide-04.png', title: 'Cartographie ROP : nerf vague X dans la moelle allongée' },
  { src: '/chapter-4/rework-reflex/slide-06.png', title: 'Cartographie ROP : nerf vague X dans le foramen jugulaire' },
  { src: '/chapter-4/rework-reflex/slide-08.png', title: 'Cartographie ROP : sinus carotidien' },
  { src: '/chapter-4/rework-reflex/slide-10.png', title: 'Cartographie ROP : territoire gauche du nerf vague X' },
  { src: '/chapter-4/rework-reflex/slide-13.png', title: 'Cartographie ROP : territoire droit du nerf vague X' },
  { src: '/chapter-4/rework-reflex/slide-15.png', title: 'Cartographie ROP : hiatus œsophagien et nerfs vagues' },
  { src: '/chapter-4/rework-reflex/slide-17.png', title: 'Cartographie ROP : territoire abdominal droit du nerf vague X' },
  { src: '/chapter-4/rework-reflex/slide-19.png', title: 'Cartographie ROP : origine parasympathique pelvienne ou sacrée' },
  { src: '/chapter-4/rework-reflex/slide-21.png', title: 'Cartographie ROP : origine médullaire du sympathique' },
  { src: '/chapter-4/rework-reflex/slide-23.png', title: 'Cartographie ROP : chaîne ganglionnaire thoracique' },
  { src: '/chapter-4/rework-reflex/slide-25.png', title: 'Cartographie ROP : chaîne ganglionnaire cervicale' },
  { src: '/chapter-4/rework-reflex/slide-27.png', title: 'Cartographie ROP : chaîne ganglionnaire lombale' },
  { src: '/chapter-4/rework-reflex/slide-29.png', title: 'Cartographie ROP : chaîne ganglionnaire sacro-coccygienne' },
  { src: '/chapter-4/rework-reflex/slide-31.png', title: 'Cartographie ROP : plexus hypogastrique inférieur, fibres antérieures' },
  { src: '/chapter-4/rework-reflex/slide-33.png', title: 'Cartographie ROP : plexus hypogastrique inférieur, fibres moyennes et postérieures' },
]

export const chapter4ReworkSlideAnchors = [
  { sectionId: 'presentation', blockIndex: -1, slide: 1 },
  { sectionId: 'presentation', blockIndex: 0, slide: 2 },
  { sectionId: 'presentation', blockIndex: 1, slide: 3 },
  { sectionId: 'presentation', blockIndex: 2, slide: 4 },
  { sectionId: 'presentation', blockIndex: 3, slide: 5 },
  { sectionId: 'presentation', blockIndex: 7, slide: 6 },
  { sectionId: 'presentation', blockIndex: 10, slide: 7, gapBefore: 'half' as const },
  { sectionId: 'presentation', blockIndex: 11, slide: 8 },
  { sectionId: 'presentation', blockIndex: 14, slide: 9, ...endAt('presentation', 18) },
  { sectionId: 'presentation', blockIndex: 25, slide: 10 },
  { sectionId: 'organisation-du-sna', blockIndex: 0, slide: 11 },
  { sectionId: 'parasympathique-viscero-moteur', blockIndex: -1, slide: 12 },
  { sectionId: 'parasympathique-viscero-moteur', blockIndex: 1, slide: 13, gapBefore: 'half' as const },
  { sectionId: 'parasympathique-viscero-moteur', blockIndex: 6, slide: 14 },
  { sectionId: 'parasympathique-viscero-moteur', blockIndex: 8, slide: 15 },
  { sectionId: 'parasympathique-viscero-moteur', blockIndex: 23, slide: 16 },
  { sectionId: 'parasympathique-viscero-moteur', blockIndex: 32, slide: 17 },
  { sectionId: 'nerf-vague-viscero-sensitif', blockIndex: -1, slide: 18, ...endAt('sympathique-viscero-moteur', -1) },
  { sectionId: 'sympathique-viscero-moteur', blockIndex: 1, slide: 19 },
  { sectionId: 'sympathique-viscero-moteur', blockIndex: 4, slide: 20 },
  { sectionId: 'sympathique-viscero-moteur', blockIndex: 6, slide: 21 },
  { sectionId: 'sympathique-viscero-moteur', blockIndex: 13, slide: 22 },
  { sectionId: 'sympathique-viscero-moteur', blockIndex: 24, slide: 23 },
  { sectionId: 'sympathique-viscero-moteur', blockIndex: 32, slide: 24 },
  { sectionId: 'sympathique-somato-viscero-sensitif', blockIndex: -1, slide: 25 },
  { sectionId: 'chaine-plexique-prevertebrale-ou-pre-aortique', blockIndex: 1, slide: 26 },
  { sectionId: 'plexus-previsceral-pelvien', blockIndex: -1, slide: 27 },
  { sectionId: 'plexus-previsceral-pelvien', blockIndex: 2, slide: 28 },
  { sectionId: 'systeme-nerveux-intrinseque-ou-enterique-sne', blockIndex: -1, slide: 29 },
  { sectionId: 'glandes-surrenales', blockIndex: -1, slide: 30 },
  { sectionId: 'glandes-surrenales', blockIndex: 6, slide: 31, ...endAt('glandes-surrenales', 8) },
  { sectionId: 'zones-reflexes-podales', blockIndex: -1, slide: 32 },
  {
    sectionId: 'zones-reflexes-podales',
    blockIndex: 1,
    slide: 33,
    end: { sectionId: 'zones-reflexes-podales', blockIndex: 1, itemIndex: 8 },
  },
  { sectionId: 'zones-reflexes-podales', blockIndex: 3, slide: 34, ...endAt('zones-reflexes-podales', 6) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 6, slide: 35, ...endAt('zones-reflexes-podales', 7) },
  {
    sectionId: 'zones-reflexes-podales',
    blockIndex: 9,
    itemIndex: 3,
    slide: 36,
    ...endAt('zones-reflexes-podales', 11),
  },
  // The left-vagus cartography remains solo until its correct companion photo is available.
  { sectionId: 'zones-reflexes-podales', blockIndex: 11, slide: 37, ...endAt('zones-reflexes-podales', 14) },
  // The updated slide-11 photo now accompanies the right-vagus cartography.
  { sectionId: 'zones-reflexes-podales', blockIndex: 14, slide: 38, ...endAt('zones-reflexes-podales', 15) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 15, slide: 39, ...endAt('zones-reflexes-podales', 20) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 20, slide: 40, ...endAt('zones-reflexes-podales', 24) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 24, slide: 41, ...endAt('zones-reflexes-podales', 27) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 27, slide: 42, ...endAt('zones-reflexes-podales', 30) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 30, slide: 43, ...endAt('zones-reflexes-podales', 33) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 33, slide: 44, ...endAt('zones-reflexes-podales', 37) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 37, slide: 45, ...endAt('zones-reflexes-podales', 41) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 41, slide: 46, ...endAt('zones-reflexes-podales', 45) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 51, slide: 47, ...endAt('zones-reflexes-podales', 54) },
  // Ends after the paired photo and before 11.16. Système nerveux intrinsèque ou entérique (SNE).
  { sectionId: 'zones-reflexes-podales', blockIndex: 54, slide: 48, ...endAt('zones-reflexes-podales', 55) },
]

export const chapter4ReworkHalfBreaks = [
  { sectionId: 'chaine-plexique-prevertebrale-ou-pre-aortique', blockIndex: -1 },
  { sectionId: 'zones-reflexes-podales', blockIndex: 0 },
]
