// Chapter 1 — Spanish
// Source: Capitulo_1_Consideraciones_generales_ES_medico_Revisado.docx

import type { Chapter } from './types'

export const chapter1Es: Chapter = {
  slug: 'chapter-1',
  number: '1',
  title: 'Consideraciones generales',
  sections: [
    {
      id: 'intention',
      title: '1. Objetivo del capítulo',
      blocks: [
        { type: 'para', text: 'Este primer capítulo establece un marco biomecánico y neurofisiológico para el profesional.' },
        { type: 'para', text: 'La función visceral no depende únicamente de la bioquímica y la inervación, sino también de la capacidad de los órganos para deformarse, desplazarse y deslizarse unos respecto de otros.' },
        { type: 'para', text: 'Cuando esta libertad se reduce (traumatismo, infección, cirugía, estrés), los tejidos asociados (fascias, estructuras neurovasculares y sistema musculoesquelético) se adaptan y compensan.' },
        { type: 'para', text: 'En algunos casos, estas compensaciones pueden contribuir a la aparición de síntomas en zonas alejadas, de acuerdo con un modelo clínico de cadenas mecánicas y autonómicas.' },
        { type: 'para', text: 'Importante: algunos de los conceptos que se describen a continuación corresponden a (a) la fisiología establecida y otros a (b) el modelo clínico utilizado en ROP (Reflexoterapia Occipitopodal).' },
      ],
    },
    {
      id: 'mobilite-viscerale',
      title: '2. Movilidad visceral: definiciones y factores impulsores',
      blocks: [
        { type: 'para', text: 'En este contexto, se distingue entre:' },
        { type: 'bullets', items: [
          'Movilidad: desplazamiento pasivo o inducido por los movimientos del cuerpo y de las cavidades corporales (respiración, marcha, esfuerzo, postura).',
          'Motilidad: actividad motora intrínseca del órgano (en sentido amplio), modulada por el sistema nervioso autónomo y el estado de los tejidos.',
        ]},
        { type: 'para', text: 'La movilidad visceral depende de cuatro determinantes principales (factores impulsores y moduladores):' },
        { type: 'bullets', items: [
          'el sistema nervioso somático (movimientos corporales activos);',
          'el sistema nervioso autónomo (movimientos viscerales automáticos);',
          'la motilidad (actividad tisular intrínseca);',
          'los ritmos biológicos (variaciones cíclicas del tono, las secreciones y la vascularización).',
        ]},
        { type: 'sub', text: '2.1. Sistema nervioso somático: movilidad «pasiva» mediante el movimiento' },
        { type: 'para', text: 'Los movimientos activos controlados por el sistema nervioso somático —caminar, correr, bailar, mover el tronco— producen desplazamientos y deformaciones de las vísceras.' },
        { type: 'para', text: 'A la inversa, tras una intervención quirúrgica abdominal, el dolor, las adherencias y las fijaciones pueden limitar la amplitud de movimiento y alterar la cinemática global.' },
        { type: 'para', text: 'El diafragma constituye un importante motor del deslizamiento visceral mediante la alternancia de las fases de inspiración y espiración.' },
        { type: 'para', text: 'Esta alternancia moviliza repetidamente las vísceras torácicas y abdominales (≈ 21 000 ciclos respiratorios cada 24 h, como orden de magnitud).' },
        { type: 'para', text: 'La actividad física regular contribuye a mantener esta movilidad.' },
        { type: 'para', text: 'Favorece la ventilación, la circulación y el tránsito intestinal, al tiempo que limita algunos efectos de la inactividad (disminución de la actividad cardiopulmonar, estasis digestiva, etc.).' },
        { type: 'sub', text: '2.2. Sistema nervioso autónomo: movilidad «automática»' },
        { type: 'para', text: 'Bajo el control de los centros superiores (diencéfalo, tronco encefálico) y a través de las vías simpáticas y parasimpáticas, el sistema nervioso autónomo regula funciones automáticas: respiración, frecuencia cardíaca, peristaltismo, tono vascular y secreciones.' },
        { type: 'leadBullets', items: [
          { label: 'Movimiento respiratorio', text: 'el diafragma modula la movilidad visceral y los gradientes de presión entre las cavidades corporales.' },
          { label: 'Movimiento cardíaco', text: 'con aproximadamente 100 000 latidos cada 24 h (como orden de magnitud), el movimiento cardíaco genera tensiones mecánicas locales dentro del tórax.' },
        ]},
        { type: 'para', text: 'Estas tensiones pueden transmitirse a las estructuras adyacentes (pulmones, mediastino, esófago) e, indirectamente, a la región diafragmática.' },
        { type: 'leadBullets', items: [
          { label: 'Peristaltismo', text: 'el tránsito gastrointestinal depende de las redes nerviosas entéricas y del sistema nervioso autónomo.' },
        ]},
        { type: 'para', text: 'Puede verse modulado por el estado emocional, el dolor, la inflamación, la alimentación y los ritmos circadianos.' },
        { type: 'sub', text: '2.3. Motilidad: movimiento intrínseco e interpretación clínica' },
        { type: 'para', text: 'En este capítulo, la motilidad se refiere a la actividad intrínseca del órgano: micromovimientos y variaciones de la tensión, el volumen y la vascularización (en sentido amplio).' },
        { type: 'para', text: 'Desde el punto de vista clínico, el profesional se centra menos en la «medición» instrumental que en el comportamiento global de los tejidos: elasticidad, dirección preferente, retroceso elástico, simetría y capacidad adaptativa.' },
        { type: 'para', text: 'En el enfoque ROP, esta «motilidad» se evalúa mediante las pruebas manuales y las respuestas reflejas definidas por el método.' },
        { type: 'para', text: 'El objetivo es identificar restricciones de la movilidad o la motilidad asociadas a cadenas fasciales y autonómicas y, posteriormente, buscar la normalización clínica de la restricción observada.' },
        { type: 'sub', text: '2.4. Ritmos biológicos: variaciones cíclicas útiles para la evaluación clínica' },
        { type: 'para', text: 'Numerosos parámetros viscerales varían según ritmos cíclicos (ritmos circadianos y ultradianos, ciclos digestivos, ciclos hormonales).' },
        { type: 'para', text: 'Para el profesional, esto exige:' },
        { type: 'bullets', items: [
          'situar el síntoma en su contexto temporal (momento del día, después de las comidas, tras un esfuerzo, ciclo menstrual, etc.);',
          'distinguir, como orientación clínica, un trastorno más «reactivo» (fatiga, estrés, sobrecarga) de otro más establecido (inflamación, fijaciones, ptosis visceral).',
        ]},
      ],
    },
    {
      id: 'mrp',
      title: '3. Nota sobre los ritmos corporales, los líquidos y la adaptabilidad tisular',
      blocks: [
        { type: 'para', text: 'Algunos enfoques de terapia manual describen distintos ritmos corporales, incluidos ritmos sutiles relacionados con los líquidos y los tejidos.' },
        { type: 'para', text: 'Entre estos modelos, algunas escuelas osteopáticas hacen referencia al mecanismo respiratorio primario (MRP), cuya existencia y descripción detallada siguen siendo objeto de debate en los distintos marcos teóricos.' },
        { type: 'para', text: 'En este capítulo no es necesario pronunciarse entre estos modelos ni convertirlos en un fundamento de ROP. Para el profesional de ROP, la consideración práctica es que la movilidad tisular depende de la capacidad de adaptación a las presiones, la respiración, el retorno venoso y linfático, las variaciones del tono y las restricciones mecánicas.' },
        { type: 'para', text: 'Esta breve exposición simplemente sitúa el enfoque ROP: aquí se abordan la movilidad, la motilidad, los ritmos y los líquidos, pero el enfoque sigue siendo principalmente clínico, basado en reflejos y centrado en los tejidos; no debe confundirse con la osteopatía craneal basada en el MRP.' },
      ],
    },
    {
      id: 'articulations-viscerales',
      title: '4. «Articulaciones» viscerales: superficies, deslizamiento, medios de fijación e inervación',
      blocks: [
        { type: 'para', text: 'Las vísceras pueden considerarse estructuras suspendidas que mantienen una interacción mecánica continua con su entorno.' },
        { type: 'para', text: 'Cuatro elementos son esenciales para el deslizamiento y la adaptación:' },
        { type: 'numbered', items: [
          'Superficies de contacto y membranas serosas.',
          'Intersticio y continuidades fasciales.',
          'Medios de fijación (ligamentos, mesenterios, omentos).',
          'Inervación (sensibilidad visceral y parietal, vías autonómicas).',
        ]},
        { type: 'sub', text: '4.1. Membranas serosas: deslizamiento y presiones' },
        { type: 'para', text: 'Las membranas serosas (pleura, pericardio, peritoneo) permiten un deslizamiento con escasa fricción y contribuyen a las relaciones de presión entre las cavidades corporales.' },
        { type: 'para', text: 'También pueden contribuir al dolor referido cuando se ve afectada la hoja parietal, ya que la sensibilidad parietal presenta una localización más precisa.' },
        { type: 'sub', text: '4.2. Intersticio: continuidad tisular y capacidad de deformación' },
        { type: 'para', text: 'En el sentido clínico utilizado aquí, el término intersticio remite al concepto de un continuo microfibrilar entre los tejidos (piel, fascia, músculo, vísceras, hueso).' },
        { type: 'para', text: 'La implicación práctica es que la deformación y el deslizamiento son posibles porque las fibras, en particular las fibras de colágeno, están organizadas en una red tridimensional que permite cambios de dirección y la adaptación a las restricciones mecánicas.' },
        { type: 'sub', text: '4.3. Medios de fijación visceral: ligamentos, mesenterios y omentos' },
        { type: 'para', text: 'Los medios de fijación visceral no poseen una resistencia comparable a la de los ligamentos articulares.' },
        { type: 'para', text: 'No obstante, contribuyen a la suspensión de los órganos, a la distribución de las fuerzas gravitatorias y a la organización de los trayectos neurovasculares.' },
        { type: 'bullets', items: [
          'Ligamentos (p. ej., ligamento coronario o ligamento suspensorio del hígado).',
          'Mesenterios: pliegues serosos del tubo digestivo que sirven de vía de paso para vasos, nervios y vasos linfáticos.',
          'Omentos: pliegues peritoneales entre estructuras digestivas, con funciones vasculares, nerviosas e inmunitarias.',
          'Omento menor: formado por los ligamentos hepatogástrico y hepatoduodenal, que contiene, en particular, los elementos hepatobiliares.',
          'Foramen omental: comunicación anatómica entre compartimentos peritoneales.',
        ]},
        { type: 'sub', text: '4.4. Inervación: dolor visceral, dolor parietal y dolor referido' },
        { type: 'para', text: 'El dolor visceral suele ser profundo y estar mal localizado; en ocasiones se asocia a náuseas o a una reacción autonómica.' },
        { type: 'para', text: 'El dolor parietal (procedente del peritoneo parietal o de la pleura parietal) suele ser más agudo y presentar una localización más precisa.' },
        { type: 'para', text: 'El dolor referido puede explicarse por la convergencia medular de aferencias viscerales y somáticas: un mismo segmento medular puede recibir información del dermatoma, miotoma, viscerotoma, angiotoma y esclerotoma.' },
        { type: 'para', text: 'El Dr. Jarricot describió estos territorios y sus correlaciones clínicas.' },
      ],
    },
    {
      id: 'securite',
      title: 'Nota de seguridad: no pasar por alto una patología orgánica',
      blocks: [
        { type: 'para', text: 'Un trastorno funcional y una disfunción de la movilidad pueden coexistir con una patología orgánica.' },
        { type: 'para', text: 'El profesional debe permanecer atento a los signos de alarma y derivar al paciente para una evaluación médica cuando sea necesario.' },
        { type: 'bullets', items: [
          'Dolor inusual, progresivo y no mecánico, especialmente nocturno;',
          'Fiebre, pérdida de peso o fatiga sin causa aparente;',
          'Vómitos persistentes, rectorragia o melena, o hematuria;',
          'Dolor torácico, disnea o malestar general;',
          'Déficit neurológico o disfunción esfinteriana.',
        ]},
      ],
    },
    {
      id: 'perte-de-mobilite',
      title: '5. Cuando se pierde la movilidad: adherencias, ptosis visceral y espasmos',
      blocks: [
        { type: 'para', text: 'La pérdida del deslizamiento y de la distensibilidad puede manifestarse de tres formas principales. Un tejido puede quedar fijado por adherencias, ser traccionado hacia abajo por la gravedad o mantenerse bajo tensión debido a una reacción refleja. En la práctica, estos fenómenos rara vez se presentan de forma aislada: una cicatriz puede alterar las presiones locales, la pérdida de sostén puede favorecer la tensión y el dolor puede instaurar una defensa muscular.' },
        { type: 'sub', text: '5.1. Adherencias y fijaciones' },
        { type: 'para', text: 'Después de una intervención quirúrgica, una infección, una inflamación o microtraumatismos repetidos, las adherencias pueden restringir el deslizamiento.' },
        { type: 'para', text: 'El ejemplo más sencillo es una cicatriz abdominal o pélvica: apendicectomía, cesárea, colecistectomía, cirugía ginecológica o cirugía digestiva. Aunque la cicatriz parezca bien curada en la superficie, los planos tisulares profundos pueden conservar una menor flexibilidad. La piel, las fascias, el peritoneo, los mesenterios o los tejidos vecinos pueden dejar de deslizarse con la misma libertad.' },
        { type: 'para', text: 'Un episodio inflamatorio previo puede producir un efecto comparable. Tras un episodio digestivo, ginecológico o pélvico, una zona puede permanecer más densa, sensible o menos móvil, sin que el paciente la relacione espontáneamente con el acontecimiento inicial.' },
        { type: 'para', text: 'Estas fijaciones alteran la mecánica local. También pueden generar compensaciones a distancia: respiración abdominal más limitada, sensación de tracción durante la extensión del tronco, adaptación pélvica, tensión lumbar, molestias diafragmáticas o cambios posturales.' },
        { type: 'para', text: 'Asimismo, pueden perpetuar un ciclo de dolor–estrés–hipertonía: la zona se protege, los tejidos se contraen, el movimiento disminuye y la restricción se vuelve más estable.' },
        { type: 'sub', text: '5.2. Ptosis visceral y restricciones gravitatorias' },
        { type: 'para', text: 'La gravedad somete de forma continua a los órganos y sus estructuras de sostén a distintas tensiones.' },
        { type: 'para', text: 'En condiciones normales, estas tensiones se distribuyen a través de las cavidades corporales, las relaciones de presión interna, los ligamentos viscerales, los mesenterios, los omentos, el diafragma, la pared abdominal y el suelo pélvico.' },
        { type: 'para', text: 'Cuando disminuye la capacidad funcional de este sistema de sostén —debido a hipotonía, cicatrices, pérdida de tono abdominal o del suelo pélvico, secuelas del embarazo, bipedestación prolongada, estreñimiento crónico, tos crónica o levantamiento repetido de cargas—, las vísceras pueden quedar sometidas a una mayor tensión descendente.' },
        { type: 'para', text: 'En la práctica, algunos pacientes refieren pesadez abdominal o pélvica, molestias al final del día, fatiga lumbar, sensación de tracción abdominal al permanecer de pie o un patrón respiratorio que se vuelve más alto y menos abdominal.' },
        { type: 'para', text: 'En el marco de ROP, el objetivo no es establecer un diagnóstico médico de ptosis visceral o prolapso basándose únicamente en el examen manual. El profesional valora, más bien, si la gravedad, las presiones internas, la pérdida de tono o las cicatrices contribuyen a la restricción de movilidad observada.' },
        { type: 'sub', text: '5.3. Espasmos e hipertonía refleja' },
        { type: 'para', text: 'Una restricción visceral puede acompañarse de respuestas reflejas somáticas y autonómicas: hipertonía, restricciones de la movilidad segmentaria, alteraciones del retorno venoso o linfático y cambios del patrón respiratorio.' },
        { type: 'para', text: 'El ejemplo más claro es la defensa abdominal: cuando una zona está dolorida o irritada, la pared abdominal se contrae espontáneamente para protegerla. El paciente respira con menor profundidad, evita determinados movimientos y, en ocasiones, adopta una postura antiálgica.' },
        { type: 'para', text: 'El mismo principio puede observarse, de manera más funcional, en torno al diafragma, el suelo pélvico, la región lumbar o la pared abdominal. Una cicatriz sensible, un trastorno digestivo, una irritación pélvica, un dolor persistente o un estrés prolongado pueden acompañarse de tensión refleja local o regional.' },
        { type: 'para', text: 'Desde el punto de vista clínico, se trata de determinar si la tensión observada constituye el problema primario o una respuesta protectora. A continuación, el profesional examina la cadena: qué zona parece perder primero la movilidad, qué zonas compensan y cómo puede restablecerse la adaptabilidad tisular.' },
      ],
    },
    {
      id: 'approche-clinique',
      title: '6. Aplicación clínica en ROP',
      blocks: [
        { type: 'para', text: 'Dentro de su marco metodológico, ROP utiliza circuitos reflejos que incluyen zonas occipitales y podales para orientar la evaluación y el tratamiento.' },
        { type: 'sub', text: 'Ilustración clínica — Equilibrio visceroemocional entre el sistema límbico y el hígado' },
        { type: 'para', text: 'Esta técnica se ha seleccionado para ilustrar la transición de los principios generales a la aplicación clínica en ROP. Relaciona una víscera —el hígado— con sus restricciones de movilidad, sus medios de fijación, su entorno diafragmático y su regulación autonómica, incorporando asimismo la dimensión emocional a través del sistema límbico. Ilustra así que ROP no considera el órgano de forma aislada, sino que procura identificar una restricción, sus vías reflejas asociadas y su integración en el patrón funcional global. En esta etapa del libro, el objetivo no es describir un protocolo hepático detallado, sino ofrecer al lector una ilustración concreta de la lógica visceroemocional del método.' },
        { type: 'para', text: 'El profesional busca:' },
        { type: 'bullets', items: [
          'una restricción primaria (movilidad/motilidad);',
          'las vías segmentarias y autonómicas asociadas;',
          'compensaciones a distancia (columna vertebral, extremidades, diafragma, pelvis).',
        ]},
        { type: 'para', text: 'El enfoque terapéutico pretende lograr un «retorno al equilibrio»: inducir, escuchar, corregir y, a continuación, verificar la integración global.' },
        { type: 'para', text: 'El mismo principio puede aplicarse a otras vísceras, en función de las pruebas ROP y del contexto clínico.' },
      ],
    },
    {
      id: 'synthese-operationnelle',
      title: '7. Resumen práctico (para el profesional)',
      blocks: [
        { type: 'bullets', items: [
          'Pensar en «deslizamiento + presiones + inervación» antes que en un «órgano aislado».',
          'Relacionar un síntoma musculoesquelético con una posible hipótesis visceral (dolor referido, cadenas fasciales).',
          'Identificar el acontecimiento desencadenante (cirugía, infección, estrés) y la estrategia de adaptación (Selye) como marco interpretativo.',
          'Aplicar un enfoque basado en la verificación: corrección local → integración global → nueva evaluación.',
          'Mantener la vigilancia clínica: toda sospecha de patología orgánica requiere derivación médica.',
        ]},
      ],
    },
  ],
}
