// Chapter 16 - slide <-> text synchronisation map for the combined reading
// experience (/lecture/chapitre-16).
//
// The synthesis slides follow the text flow. Cartography assets remain appended
// to the deck and are anchored inside the reflex-zone section.

export type SyncSlide = { src: string; title: string; orientation?: 'portrait' }
export type SyncAnchorPoint = { sectionId: string; blockIndex: number; itemIndex?: number }
export type SyncAnchor = SyncAnchorPoint & { slide: number | number[]; gapBefore?: 'half'; end?: SyncAnchorPoint }

const chapter16SlidesBySource: SyncSlide[] = [
  { src: '/chapter-16/slides/slide-01.png', title: 'Chapitre 16 : les reins' },
  { src: '/chapter-16/slides/slide-02.png', title: 'Situation et topographie' },
  { src: '/chapter-16/slides/slide-03.png', title: 'La loge rénale et ses enveloppes' },
  { src: '/chapter-16/slides/slide-04.png', title: 'L’enveloppe fasciale : une loge ouverte' },
  { src: '/chapter-16/slides/slide-05.png', title: 'Structure interne des reins' },
  { src: '/chapter-16/slides/slide-06.png', title: 'Le néphron : l’unité fonctionnelle' },
  { src: '/chapter-16/slides/slide-07.png', title: 'Rapports dorsaux et plexus lombaire' },
  { src: '/chapter-16/slides/slide-08.png', title: 'Points faibles de la paroi lombaire' },
  { src: '/chapter-16/slides/slide-09.png', title: 'Le carrefour veineux et le syndrome de la pince' },
  { src: '/chapter-16/slides/slide-10.png', title: 'Asymétrie clinique : rein droit vs rein gauche' },
  { src: '/chapter-16/slides/slide-11.png', title: 'Dynamique respiratoire et motilité' },
  { src: '/chapter-16/slides/slide-12.png', title: 'Régulation de la pression artérielle : le SRAA' },
  { src: '/chapter-16/slides/slide-13.png', title: 'Équilibre acido-basique et fonctions endocrines du rein' },
  { src: '/chapter-16/slides/slide-14.png', title: 'Fixations tissulaires et signes d’alerte' },
  { src: '/chapter-16/slides/slide-15.png', title: 'Fixations tissulaires : perte de mobilité' },
  { src: '/chapter-16/slides/slide-16.png', title: 'Ptose rénale : formes, causes et signes posturaux' },
  { src: '/chapter-16/slides/slide-17.png', title: 'Ptose rénale : lecture ROP en trois degrés' },
  { src: '/chapter-16/slides/slide-18.png', title: 'Ptose rénale : lecture ROP en 3 degrés' },
  { src: '/chapter-16/slides/slide-19.png', title: 'Lombalgies gravidiques : contraintes rénales et vasculaires' },
  { src: '/chapter-16/slides/viscero-somatiques -- reins.png', title: 'Relations viscéro-somatiques — reins' },
  { src: '/chapter-16/slides/slide-20.png', title: 'Approche ROP : lecture symbolique et émotionnelle' },
  { src: '/chapter-16/slides/slide-21.png', title: 'Conseils thérapeutiques au patient' },
  { src: '/chapter-16/slides/slide-22.png', title: 'Protocole clinique ROP : les reins' },
  { src: '/chapter-16/cartographie/figure-16-01.png', title: 'Cartographie : Rein et surrénale droits' },
  { src: '/chapter-16/cartographie/figure-16-03.png', title: 'Cartographie : Rein et surrénale gauches — rein gauche' },
  { src: '/chapter-16/cartographie/figure-16-05.png', title: 'Cartographie : Rein et surrénale gauches — surrénale gauche' },
  { src: '/chapter-16/cartographie/figure-16-07.png', title: 'Cartographie : Manœuvre combinée du rein' },
  { src: '/chapter-16/cartographie/figure-16-09.png', title: 'Cartographie : Plexus lombal et fenêtre dorsale du rein' },
]

export const chapter16Slides: SyncSlide[] = chapter16SlidesBySource

function withChapter16Titles(titles: string[]): SyncSlide[] {
  return chapter16Slides.map((slide, index) => ({ ...slide, title: titles[index] ?? slide.title }))
}

export const chapter16SlidesEnLegacy = withChapter16Titles([
  'Chapter 16: the Kidneys',
  'Location and topography',
  'The renal lodge and its envelopes',
  'The fascial envelope: an open lodge',
  'Internal structure of the kidneys',
  'The nephron: the functional unit',
  'Posterior relations and lumbar plexus',
  'Weak points of the lumbar wall',
  'The venous crossroads and nutcracker syndrome',
  'Clinical asymmetry: right kidney vs left kidney',
  'Respiratory dynamics and motility',
  'Regulation of arterial pressure: the RAAS',
  'Acid-base balance and endocrine functions of the kidney',
  'Tissue fixations and warning signs',
  'Tissue fixations: loss of mobility',
  'Renal ptosis: forms, causes and postural signs',
  'Renal ptosis: ROP reading in three degrees',
  'Renal ptosis: detailed reading in three degrees',
  'Pregnancy-related low back pain: renal and vascular constraints',
  'Viscerosomatic relations — kidneys',
  'ROP approach: symbolic and emotional reading',
  'Therapeutic advice for the patient',
])

export const chapter16SlidesDe = withChapter16Titles([
  'Kapitel 16: die Nieren',
  'Lage und Topographie',
  'Die Nierenloge und ihre Hüllen',
  'Die Faszienhülle: eine offene Loge',
  'Innere Struktur der Nieren',
  'Das Nephron: die funktionelle Einheit',
  'Dorsale Beziehungen und Plexus lumbalis',
  'Schwachstellen der Lendenwand',
  'Der venöse Kreuzungspunkt und das Nussknacker-Syndrom',
  'Klinische Asymmetrie: rechte Niere vs linke Niere',
  'Atemdynamik und Motilität',
  'Regulation des arteriellen Drucks: RAAS',
  'Säure-Basen-Gleichgewicht und endokrine Nierenfunktionen',
  'Gewebefixierungen und Warnzeichen',
  'Gewebefixierungen: Verlust der Mobilität',
  'Nierenptose: Formen, Ursachen und Haltungszeichen',
  'Nierenptose: ROP-Lesart in drei Graden',
  'Nierenptose: detaillierte Lesart in drei Graden',
  'Schwangerschaftsbedingte Kreuzschmerzen: renale und vaskuläre Belastungen',
  'Viszerosomatische Beziehungen — Nieren',
  'ROP-Ansatz: symbolische und emotionale Lesart',
  'Therapeutische Ratschläge für den Patienten',
])

export const chapter16SlidesEs = withChapter16Titles([
  'Capítulo 16: los riñones',
  'Situación y topografía',
  'La logia renal y sus envolturas',
  'La envoltura fascial: una logia abierta',
  'Estructura interna de los riñones',
  'La nefrona: la unidad funcional',
  'Relaciones dorsales y plexo lumbar',
  'Puntos débiles de la pared lumbar',
  'La encrucijada venosa y el síndrome de la pinza',
  'Asimetría clínica: riñón derecho vs riñón izquierdo',
  'Dinámica respiratoria y motilidad',
  'Regulación de la presión arterial: el SRAA',
  'Equilibrio ácido-base y funciones endocrinas del riñón',
  'Fijaciones tisulares y signos de alerta',
  'Fijaciones tisulares: pérdida de movilidad',
  'Ptosis renal: formas, causas y signos posturales',
  'Ptosis renal: lectura ROP en tres grados',
  'Ptosis renal: lectura detallada en tres grados',
  'Lumbalgias del embarazo: restricciones renales y vasculares',
  'Relaciones viscerosomáticas — riñones',
  'Enfoque ROP: lectura simbólica y emocional',
  'Consejos terapéuticos para el paciente',
])

export const chapter16SlidesIt = withChapter16Titles([
  'Capitolo 16: i reni',
  'Situazione e topografia',
  'La loggia renale e i suoi involucri',
  'L’involucro fasciale: una loggia aperta',
  'Struttura interna dei reni',
  'Il nefrone: l’unità funzionale',
  'Rapporti dorsali e plesso lombare',
  'Punti deboli della parete lombare',
  'Il crocevia venoso e la sindrome della pinza',
  'Asimmetria clinica: rene destro vs rene sinistro',
  'Dinamica respiratoria e motilità',
  'Regolazione della pressione arteriosa: il SRAA',
  'Equilibrio acido-base e funzioni endocrine del rene',
  'Fissazioni tissutali e segnali di allarme',
  'Fissazioni tissutali: perdita di mobilità',
  'Ptosi renale: forme, cause e segni posturali',
  'Ptosi renale: lettura ROP in tre gradi',
  'Ptosi renale: lettura dettagliata in tre gradi',
  'Lombalgia in gravidanza: vincoli renali e vascolari',
  'Relazioni viscerosomatiche — reni',
  'Approccio ROP: lettura simbolica ed emozionale',
  'Consigli terapeutici al paziente',
])

export const chapter16SlideAnchors: SyncAnchor[] = [
  { sectionId: 'presentation', blockIndex: -1, slide: 1 },
  { sectionId: 'situation', blockIndex: 0, slide: 2 },
  { sectionId: 'anatomie', blockIndex: 0, slide: 3 },
  { sectionId: 'anatomie', blockIndex: 4, slide: 4 },
  { sectionId: 'anatomie', blockIndex: 10, slide: 5 },
  { sectionId: 'anatomie', blockIndex: 14, slide: 6 },
  { sectionId: 'rapports', blockIndex: 0, slide: 7 },
  { sectionId: 'rapports', blockIndex: 3, slide: 8 },
  { sectionId: 'vascularisation', blockIndex: 0, slide: 9 },
  { sectionId: 'vascularisation', blockIndex: 8, slide: 10 },
  { sectionId: 'physiologie', blockIndex: 0, slide: 11 },
  { sectionId: 'physiologie', blockIndex: 3, slide: 12 },
  { sectionId: 'physiologie', blockIndex: 5, slide: 13 },
  { sectionId: 'pathologies-courantes', blockIndex: 2, slide: 14 },
  { sectionId: 'indications-troubles-fonctionnels', blockIndex: 7, slide: 15 },
  { sectionId: 'indications-troubles-fonctionnels', blockIndex: 0, slide: [16, 17, 18] },
  { sectionId: 'indications-troubles-fonctionnels', blockIndex: 4, slide: 19 },
  { sectionId: 'relations-viscero-somatiques', blockIndex: 0, slide: 20 },
  { sectionId: 'relations-viscero-emotionnelles', blockIndex: 0, slide: 21 },
  { sectionId: 'conseils', blockIndex: 0, slide: 22, end: { sectionId: 'conseils', blockIndex: 0, itemIndex: 4 } },
  { sectionId: 'zones-reflexes-podales', blockIndex: -1, slide: 23 },
  { sectionId: 'zones-reflexes-podales', blockIndex: 35, slide: 24, end: { sectionId: 'zones-reflexes-podales', blockIndex: 35 } },
  { sectionId: 'zones-reflexes-podales', blockIndex: 36, slide: 25, end: { sectionId: 'zones-reflexes-podales', blockIndex: 36 } },
  { sectionId: 'zones-reflexes-podales', blockIndex: 37, slide: 26, end: { sectionId: 'zones-reflexes-podales', blockIndex: 37 } },
  { sectionId: 'zones-reflexes-podales', blockIndex: 38, slide: 27, end: { sectionId: 'zones-reflexes-podales', blockIndex: 38 } },
  { sectionId: 'zones-reflexes-podales', blockIndex: 39, slide: 28, end: { sectionId: 'zones-reflexes-podales', blockIndex: 39 } },
]

// EN REVISED DECK CHAPTER 16
export const chapter16SlidesEn: SyncSlide[] = [
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 1.png', title: 'Chapter 16: The Kidneys' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 2.png', title: 'Location and Topography' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 3.png', title: 'The Renal Compartment and Its Envelopes' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 4.png', title: 'The Fascial Envelope: An Open Compartment' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 5.png', title: 'Internal Structure of the Kidneys' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 6.png', title: 'The Nephron: The Functional Unit' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 7.png', title: 'Dorsal Relationships and the Lumbar Plexus' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 8.png', title: 'Weak Points of the Lumbar Wall' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 9.png', title: 'The Venous Crossroads and Nutcracker Syndrome' },
  { src: '/chapter-16/EN/Images/NCH 9 EN IMG 10.png', title: 'Clinical Asymmetry: Right Kidney vs Left Kidney' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 11.png', title: 'Respiratory Dynamics and Motility' },
  { src: '/chapter-16/EN/Images/NCH EN IMG 12.png', title: 'Regulation of Arterial Blood Pressure: The RAAS' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 13.png', title: 'Acid–Base Balance and Endocrine Functions of the Kidney' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 14.png', title: 'Tissue Fixations and Warning Signs' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 15.png', title: 'Tissue Fixations: Loss of Mobility' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 16.png', title: 'Renal Ptosis: Forms, Causes and Postural Signs' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 17.png', title: 'Renal Ptosis: ROP Interpretation in Three Degrees' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 18.png', title: 'Pregnancy-Related Low Back Pain: Renal and Vascular Constraints' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 19.png', title: 'Viscerosomatic Relationships — Kidneys' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 20.png', title: 'ROP Approach: Symbolic and Emotional Interpretation' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 21.png', title: 'Therapeutic Advice for the Patient' },
  { src: '/chapter-16/EN/Images/NCH 16 EN IMG 22.png', title: 'ROP Clinical Protocol: The Kidneys' },
]

export const chapter16SlideAnchorsEn: SyncAnchor[] = [
  { sectionId: 'presentation', blockIndex: -1, slide: 1 },
  { sectionId: 'situation', blockIndex: 0, slide: 2 },
  { sectionId: 'anatomie', blockIndex: 0, slide: 3 },
  { sectionId: 'anatomie', blockIndex: 7, slide: 4 },
  { sectionId: 'anatomie', blockIndex: 10, slide: 5 },
  { sectionId: 'anatomie', blockIndex: 14, slide: 6 },
  { sectionId: 'rapports', blockIndex: 0, slide: 7 },
  { sectionId: 'rapports', blockIndex: 4, slide: 8 },
  { sectionId: 'vascularisation', blockIndex: 3, slide: 9 },
  { sectionId: 'rapports', blockIndex: 9, slide: 10 },
  { sectionId: 'physiologie', blockIndex: 0, slide: 11 },
  { sectionId: 'physiologie', blockIndex: 8, slide: 12 },
  { sectionId: 'physiologie', blockIndex: 13, slide: 13 },
  { sectionId: 'pathologies-courantes', blockIndex: 2, slide: 14 },
  { sectionId: 'indications-troubles-fonctionnels', blockIndex: 26, slide: 15 },
  { sectionId: 'indications-troubles-fonctionnels', blockIndex: 1, slide: 16 },
  { sectionId: 'indications-troubles-fonctionnels', blockIndex: 9, slide: 17 },
  { sectionId: 'indications-troubles-fonctionnels', blockIndex: 21, slide: 18 },
  { sectionId: 'relations-viscero-somatiques', blockIndex: 0, slide: 19 },
  { sectionId: 'relations-viscero-emotionnelles', blockIndex: 0, slide: 20 },
  { sectionId: 'conseils', blockIndex: 0, slide: 21 },
  { sectionId: 'zones-reflexes-podales', blockIndex: -1, slide: 22 },
]
