// Chapter 16 content — English
// Source: public/chapter-16/EN/Chapter_16_Kidneys_Medical_English_Revised.docx

import type { Chapter } from './types'

export const chapter16En: Chapter = {
  "slug": "chapter-16",
  "number": "16",
  "title": "Kidneys",
  "sections": [
    {
      "id": "presentation",
      "title": "1. Overview",
      "blocks": [
        {
          "type": "para",
          "text": "The two kidneys lie within the lumbar regions and are surrounded by a capsule. They are dark red and bean-shaped. Their medial border contains the hilum, through which the renal artery and vein, lymphatic vessels, nerves, and renal pelvis pass. The renal pelvis collects urine produced by the kidneys, which is then conveyed through the ureters to the bladder."
        },
        {
          "type": "para",
          "text": "The kidneys perform numerous functions essential to homeostasis. Because of their dense structure and their position against the posterior abdominal wall, close to the vertebral column, they are vulnerable to collision forces generated by trauma such as accidents, falls onto the back, and direct blows."
        }
      ]
    },
    {
      "id": "situation",
      "title": "2. Location",
      "blocks": [
        {
          "type": "para",
          "text": "The kidneys lie lateral to the thoracolumbar spine, between the peritoneum and the posterior abdominal wall. They are retroperitoneal and predominantly supramesocolic. They are inclined so that the inferior pole lies more laterally than the superior pole."
        },
        {
          "type": "bullets",
          "items": [
            "Anatomical landmarks:",
            "Dorsally:",
            "Right kidney: it lies slightly lower than the left kidney because of the liver. It extends from the eleventh or twelfth rib to L4;",
            "Left kidney: it extends from the eleventh rib to L3."
          ]
        },
        {
          "type": "sub",
          "text": "2.1. Ventral relationships"
        },
        {
          "type": "bullets",
          "items": [
            "Both kidneys: the superior pole lies at the level of a line joining the ninth costal cartilages;",
            "Right kidney: the inferior pole lies one fingerbreadth below the umbilicus;",
            "Left kidney: the inferior pole lies at the level of the umbilicus."
          ]
        },
        {
          "type": "para",
          "text": "The kidneys are surmounted by the adrenal glands and enclosed within the renal compartment, which is composed of fat and fascia."
        }
      ]
    },
    {
      "id": "anatomie",
      "title": "3. Anatomy",
      "blocks": [
        {
          "type": "sub",
          "text": "3.1. Renal compartment"
        },
        {
          "type": "para",
          "text": "The renal compartment is shaped like a funnel that is open inferiorly. It lies between the posterior parietal peritoneum ventrally and a fascial layer dorsally that separates it from the quadratus lumborum and psoas muscles. It consists of two layers:"
        },
        {
          "type": "bullets",
          "items": [
            "Anterior (prerenal) layer: it passes over the anterior surface of the kidney, adheres to the posterior parietal peritoneum, and extends towards the hilum to join the prerenal layer of the opposite kidney. It is related to the colon through Toldt’s fascia.",
            "Posterior (retrorenal) layer: it passes behind the kidney. It covers the quadratus lumborum and psoas major muscles—the latter acting as a track for renal mobility—and the anterolateral surface of the vertebral column. It is thick and resistant. It attaches to the diaphragm at the costodiaphragmatic pleural recesses.",
            "These two layers form the renal fascia and fuse at the lateral border and superior pole of the kidney, where they form an intervening layer between the kidney and adrenal gland. Both layers also adhere to the inferior surface of the diaphragm."
          ]
        },
        {
          "type": "sub",
          "text": "Relevance to ROP"
        },
        {
          "type": "para",
          "text": "In ROP clinical interpretation, the two renal compartments are addressed together because their fasciae, posterior relationships, and diaphragmatic-lumbar connections contribute to a shared regional dynamic. The reflex zones of both kidneys therefore often need to be engaged. The kidneys are also related to the colon through Toldt’s fascia."
        },
        {
          "type": "sub",
          "text": "3.2. Perirenal and pararenal fat"
        },
        {
          "type": "para",
          "text": "Within the renal compartment, the kidney is embedded in semi-fluid perirenal fat contained within a thin membrane, the renal capsule. Outside the capsule, between the capsule and renal compartment, lies a second layer of fat: pararenal fat."
        },
        {
          "type": "sub",
          "text": "3.3. Means of fixation"
        },
        {
          "type": "para",
          "text": "The kidneys have no attachments within the abdominal cavity. Within the renal compartment, they have neither ligaments nor mesenteries. Their fixation depends on:"
        },
        {
          "type": "bullets",
          "items": [
            "thoracic suction and diaphragmatic attraction (see Chapter 1, General Principles, p. …);",
            "the tone of the abdominal muscles;",
            "to a lesser extent, the vascular pedicle;",
            "the volume of perirenal and pararenal fat.",
            "At the inferior part of the renal compartment, the prerenal and retrorenal fasciae do not join. The compartment is therefore open inferiorly, forming a true funnel into which the kidney may descend. Renal position depends entirely on the surrounding environment. The volume of fat varies with the individual’s nutritional and general condition. Marked weight loss reduces this fat volume: the kidney becomes mobile and tends to slide downwards along the lateral border of the psoas. Failure of these means of fixation predisposes to renal ptosis. (See Pathology, p. …)"
          ]
        },
        {
          "type": "sub",
          "text": "3.4. Internal structure of the kidneys"
        },
        {
          "type": "para",
          "text": "On a medial sagittal section of the kidney, two regions of the parenchyma can be distinguished:"
        },
        {
          "type": "bullets",
          "items": [
            "the cortex, peripherally;",
            "the medulla, centrally."
          ]
        },
        {
          "type": "para",
          "text": "The cortex sends extensions—the renal columns—towards the centre of the kidney, dividing the medulla into approximately ten pyramids, known as the renal pyramids or pyramids of Malpighi. Their medial tips contain numerous openings that drain into the minor calyces, which receive urine. Several minor calyces unite to form a major calyx. The major calyces collectively form the renal pelvis, which collects all the urine and continues as the ureter."
        },
        {
          "type": "sub",
          "text": "3.5. Nephron"
        },
        {
          "type": "para",
          "text": "The cortex and medulla of the renal parenchyma consist of nephrons embedded within connective tissue, blood and lymphatic vessels, and autonomic nerves. Each kidney contains approximately one million nephrons."
        },
        {
          "type": "para",
          "text": "The nephron is the functional unit of the kidney. Its role is to maintain the volume and composition of the internal environment within narrow limits (homeostasis). It comprises two parts:"
        },
        {
          "type": "bullets",
          "items": [
            "Glomerulus: filters blood plasma (see Physiology, p. …);",
            "Tubule: reabsorbs and secretes substances required by the body."
          ]
        }
      ]
    },
    {
      "id": "rapports",
      "title": "4. Anatomical relationships",
      "blocks": [
        {
          "type": "sub",
          "text": "4.1. Dorsal relationships"
        },
        {
          "type": "para",
          "text": "Superiorly, both kidneys are related to the diaphragm and costodiaphragmatic pleural recesses; inferiorly, to the psoas and quadratus lumborum; and more laterally, to the transversus abdominis muscle."
        },
        {
          "type": "para",
          "text": "The twelfth intercostal (subcostal) nerve and branches of the lumbar plexus—the iliohypogastric, ilioinguinal, and lateral femoral cutaneous nerves—run through the pararenal fat."
        },
        {
          "type": "para",
          "text": "The inferior lumbar triangle (Petit’s triangle) and superior lumbar triangle (Grynfeltt’s quadrilateral) are two regions of the lumbar area that form weak points in the posterior abdominal wall. They provide access to the kidney with little intervening soft tissue, where fibres of the internal and external oblique muscles are absent. Here, the transversus abdominis is contacted directly and the subcostal nerve and lumbar plexus nerves indirectly."
        },
        {
          "type": "sub",
          "text": "Relevance to ROP"
        },
        {
          "type": "para",
          "text": "Trauma caused by a direct blow, a fall onto the back or abdomen, an accident involving major deceleration, fracture of the lower ribs, or deep flank pain should prompt caution. Owing to their density and retroperitoneal position close to the vertebral column, the kidneys may be affected by these traumatic mechanisms."
        },
        {
          "type": "para",
          "text": "It is important to ask whether the patient’s urine is red, brown, or tea-coloured, which may suggest haematuria. Blood in the urine, flank pain, malaise, fever, deterioration in general condition, or significant trauma requires medical assessment."
        },
        {
          "type": "para",
          "text": "Within the ROP framework and following medical exclusion, previous trauma to the lumbar region may be interpreted as posterior fixation of the renal compartment, with loss of local mobility and possible irritation of adjacent tissues. Reflex work then seeks to support mobility of the renal region, without ever replacing medical diagnosis."
        },
        {
          "type": "bullets",
          "items": [
            "Ventrally:"
          ]
        },
        {
          "type": "sub",
          "text": "4.2.1. Right kidney"
        },
        {
          "type": "bullets",
          "items": [
            "Superiorly: the liver, through the hepatorenal ligament;",
            "Ventrally: the second part of the duodenum through the suspensory fascia of Treitz, and the hepatic flexure of the colon;",
            "Inferiorly: the ileum;",
            "Laterally: the ascending colon, from which it is separated by Toldt’s fascia."
          ]
        },
        {
          "type": "sub",
          "text": "4.2.2. Left kidney"
        },
        {
          "type": "bullets",
          "items": [
            "Ventrally: the left triangular ligament of the liver, spleen, and stomach, from which it is separated by the lesser sac; the splenic flexure of the colon; and the pancreas;",
            "Inferiorly: the jejunum and left gonadal venous system;",
            "Medially: the duodenojejunal flexure."
          ]
        }
      ]
    },
    {
      "id": "vascularisation",
      "title": "5. Vascular supply",
      "blocks": [
        {
          "type": "para",
          "text": "The vascular pedicle—the renal artery and vein—enters the hilum at the level of L1."
        },
        {
          "type": "sub",
          "text": "5.1. Arterial supply"
        },
        {
          "type": "para",
          "text": "Each kidney is supplied by a single renal artery, which arises from the aorta just below the superior mesenteric artery. It divides into five terminal segmental arteries supplying the renal parenchyma. These arteries do not anastomose with one another; each supplied region is independent, permitting surgical partial nephrectomy."
        },
        {
          "type": "sub",
          "text": "5.2. Venous drainage"
        },
        {
          "type": "para",
          "text": "The renal vein lies anterior to the renal artery and differs on the right and left."
        },
        {
          "type": "bullets",
          "items": [
            "Right renal vein: drains directly into the inferior vena cava;",
            "Left renal vein: longer than the right; it receives the left gonadal vein and the left lumbar vein, which drains venous blood from the lumbar vertebrae and contributes to the fluid supply of the intervertebral discs.",
            "Nutcracker syndrome (see Chapter 10, Duodenum, p. …) involves compression of the left renal vein between the aorta and superior mesenteric artery, in the environment of the third part of the duodenum. In ROP clinical interpretation, this left-sided venous compression may be considered in relation to certain presentations of pelvic, lumbar, or left genital congestion, without replacing medical assessment of true nutcracker syndrome. Left-sided varicoceles and varicose veins predominantly affecting the left lower limb may prompt assessment of left renal fixation and small-intestinal ptosis."
          ]
        },
        {
          "type": "sub",
          "text": "Relevance to ROP"
        },
        {
          "type": "para",
          "text": "Differences between the two kidneys:"
        },
        {
          "type": "bullets",
          "items": [
            "Right kidney: it could be described as the “digestive kidney” because of its proximity to the liver and ascending colon. Its tendency to migrate downwards may exacerbate digestive symptoms through spasm associated with its descent, which may be mistaken for appendicitis.",
            "Left kidney: it could be described as the “genital kidney”. Its fixation has little effect on the digestive system apart from spasm of the duodenojejunal flexure, experienced as epigastric pain. Through its venous relationship with the urogenital region, nutcracker syndrome and fixation of the left kidney may contribute to venous problems affecting the left testis (varicocele) or left labium majus. Sexual symptoms may be attributed within this model to fixation of the left kidney: premenstrual pelvic heaviness in women and reduced sexual function and libido in men. Left-sided lumbosciatica, even after trauma, should prompt assessment of the left kidney. During pregnancy, lumbar pain may be associated with compression of the aortomesenteric region by the enlarging uterus."
          ]
        }
      ]
    },
    {
      "id": "innervation",
      "title": "6. Innervation",
      "blocks": [
        {
          "type": "para",
          "text": "The kidneys receive predominantly sympathetic autonomic innervation. Sympathetic fibres arise from the thoracolumbar segments, join the splanchnic nerves, and then reach the prevertebral plexuses, particularly the coeliac, aorticorenal, and renal plexuses."
        },
        {
          "type": "para",
          "text": "This innervation accompanies the renal vessels into the hilum and parenchyma. Its principal effects concern vascular calibre, resistance to blood flow, renin secretion by the juxtaglomerular apparatus, and tubular reabsorption of sodium and water."
        },
        {
          "type": "para",
          "text": "In ROP clinical interpretation, this sympathetic predominance supports linking the kidney with blood-pressure regulation, the prevertebral plexuses, the thoracolumbar junction, and deep tension within the lumbar region. Prolonged sympathetic overactivity may contribute to renal vasoconstriction and a hypertensive tendency."
        }
      ]
    },
    {
      "id": "physiologie",
      "title": "7. Physiology",
      "blocks": [
        {
          "type": "sub",
          "text": "7.1. Renal mobility"
        },
        {
          "type": "para",
          "text": "The psoas muscle forms a true track running obliquely caudally and laterally along which the kidney moves. During inspiration, the diaphragm displaces the kidney caudally: the superior pole is pushed ventrally, while the inferior pole descends obliquely from medial to lateral."
        },
        {
          "type": "para",
          "text": "The amplitude of this movement is 3–4 cm. It is repeated approximately 20,000 times per day. Motility follows the same direction but occurs more slowly, at approximately seven cycles per minute: during “inspiration” the kidney descends, and during “expiration” it rises."
        },
        {
          "type": "sub",
          "text": "7.2. Renal functions"
        },
        {
          "type": "bullets",
          "items": [
            "Homeostasis: through their numerous functions, the kidneys help maintain the internal environment and interact with other organs and systems, including the liver, pancreas, heart, lungs, endocrine system, and sympathetic nervous system."
          ]
        },
        {
          "type": "sub",
          "text": "7.2.1. Urine formation"
        },
        {
          "type": "para",
          "text": "It depends on two mechanisms: filtration and reabsorption."
        },
        {
          "type": "bullets",
          "items": [
            "Glomerular filtration: approximately 1,700 litres of blood pass through the kidneys each day. About 170 litres of plasma, free of cells and most proteins, are filtered by the glomeruli to form the initial filtrate.",
            "Tubular reabsorption: because final urine output (diuresis) is only 1–1.5 litres per day, most of the initial filtrate is subsequently reabsorbed by the renal tubule. This process recovers substances required by the body and returns them to the bloodstream, including water, sodium, potassium, calcium, chloride, and phosphate, thereby helping maintain plasma osmolality.",
            "Plasma osmolality reflects the concentration of dissolved particles and contributes to regulation of the body’s water balance. This reabsorption is influenced by aldosterone, which is produced by the adrenal cortex. Aldosterone adjusts sodium excretion to the body’s requirements and therefore contributes to regulation of circulating blood volume.",
            "Circulating blood volume is the total volume of blood within the circulation. By adjusting this volume, the kidney plays a major role in blood-pressure regulation."
          ]
        },
        {
          "type": "sub",
          "text": "7.2.2. Regulation of blood pressure"
        },
        {
          "type": "para",
          "text": "The kidney contributes to blood-pressure regulation through several complementary mechanisms."
        },
        {
          "type": "bullets",
          "items": [
            "First, it regulates sodium and water reabsorption, which directly affects circulating blood volume. When circulating volume increases, blood pressure tends to rise; when it decreases, blood pressure tends to fall.",
            "The kidney also acts through renin secretion by the juxtaglomerular apparatus. Renin is released when renal perfusion pressure falls or when sodium delivery to the distal tubule decreases.",
            "Renin acts on angiotensinogen, produced by the liver, to form angiotensin I. Angiotensin I is then converted into angiotensin II by angiotensin-converting enzyme.",
            "Angiotensin II causes vasoconstriction and stimulates aldosterone secretion by the adrenal cortex. Aldosterone promotes reabsorption of sodium and, with it, water. This system—the renin-angiotensin-aldosterone system—helps support blood pressure when the body detects reduced perfusion or circulating volume.",
            "Conversely, when blood pressure rises, baroreceptors in the carotid sinus and aortic arch contribute to a reflex response that modulates vascular tone and cardiac activity.",
            "Under hypothalamic control, the posterior pituitary releases antidiuretic hormone (ADH), which promotes renal water reabsorption. ADH deficiency or an inadequate renal response to the hormone may cause marked polyuria, as occurs in diabetes insipidus."
          ]
        },
        {
          "type": "sub",
          "text": "7.2.3. Regulation of blood glucose"
        },
        {
          "type": "para",
          "text": "Under normal conditions, filtered glucose is completely reabsorbed. In diabetes mellitus, glucose appears in the urine when the maximum tubular reabsorptive capacity is exceeded, resulting in glycosuria. The degree of glycosuria is related to the blood glucose concentration."
        },
        {
          "type": "sub",
          "text": "7.2.4. Regulation of acid-base balance"
        },
        {
          "type": "para",
          "text": "Blood pH is approximately 7.4. To buffer acidity, the kidneys excrete hydrogen ions (H+) in the urine and retain bicarbonate ions (HCO₃−). At the same time, ventilation increases so that the lungs eliminate carbon dioxide. In persistent acidosis, acid may accumulate within the body’s connective tissues. Excess acidity is described here as increasing inflammatory reactions, bone demineralisation, and exaggerated stress responses."
        },
        {
          "type": "para",
          "text": "Foods described as acid-producing include:"
        },
        {
          "type": "bullets",
          "items": [
            "sugar, particularly when consumed on an empty stomach;",
            "alcohol;",
            "animal fats;",
            "red meat and offal;",
            "fried foods."
          ]
        },
        {
          "type": "para",
          "text": "Foods described as alkaline include:"
        },
        {
          "type": "bullets",
          "items": [
            "potatoes, but not chips;",
            "onions and garlic;",
            "carrots;",
            "cabbage;",
            "almonds and hazelnuts;",
            "lemon, in small quantities."
          ]
        },
        {
          "type": "sub",
          "text": "7.2.5. Endocrine function"
        },
        {
          "type": "para",
          "text": "The kidney produces erythropoietin, primarily in specialised interstitial cells of the cortex and outer medulla. This hormone increases red blood cell production. The kidney also activates vitamin D, which contributes to regulation of blood calcium."
        }
      ]
    },
    {
      "id": "pathologies-courantes",
      "title": "8. Common disorders",
      "blocks": [
        {
          "type": "para",
          "text": "As with other organs, functional kidney disorders may initially produce symptoms similar to those of early renal impairment. Thoracic or lumbar pain is not always mechanical, even when it follows physical exertion. An underlying renal disorder may be approaching decompensation."
        },
        {
          "type": "para",
          "text": "If there is any doubt, the patient should be referred to a physician for investigations such as urinalysis and urine culture, ultrasonography, CT, or other appropriate imaging."
        },
        {
          "type": "sub",
          "text": "8.1. Diagnosis of exclusion"
        },
        {
          "type": "bullets",
          "items": [
            "acute renal colic with dysuria or proteinuria;",
            "haematuria (blood in the urine);",
            "fever;",
            "urinary tract or renal infection, including pyelonephritis or glomerulonephritis;",
            "weight loss and loss of appetite;",
            "general fatigue or depression;",
            "palpable flank mass;",
            "nocturnal flank pain that wakes the patient and is accompanied by fever;",
            "hyperuricaemia or excess uric acid;",
            "polyuria in a patient with diabetes;",
            "polycystic kidney disease;",
            "sudden-onset varicocele;",
            "renal cancer."
          ]
        }
      ]
    },
    {
      "id": "indications-troubles-fonctionnels",
      "title": "9. Indications: functional disorders",
      "blocks": [
        {
          "type": "bullets",
          "items": [
            "lumbar pain occurring at dawn, around 4–5 a.m.;",
            "morning thirst;",
            "profound morning fatigue described as constitutional;",
            "congested eyes with “bags” beneath them;",
            "high blood pressure;",
            "sequelae of a fall onto the back, coccyx, heels, or abdomen;",
            "microlithiasis (calculi smaller than 5 mm);",
            "sequelae of renal calculi and microlithiasis;",
            "lumbar pain with radiation along the femoral nerve;",
            "infertility;",
            "reduced libido;",
            "joint pain associated with excess uric acid;",
            "afebrile urinary symptoms with clear urine;",
            "pregnancy-related lumbar pain (see Chapter 19, Female Reproductive Organs, p. …);",
            "benign prostatic enlargement (see Chapter 20, Male Reproductive Organs, p. …);",
            "post-traumatic depression."
          ]
        },
        {
          "type": "sub",
          "text": "9.1. Renal ptosis"
        },
        {
          "type": "para",
          "text": "Strictly speaking, the kidneys have no attachments; their means of fixation depend on their environment. (p. …)"
        },
        {
          "type": "bullets",
          "items": [
            "A radiological sign of renal ptosis is loss of contact between the superior pole and the eleventh rib, resulting in loss of the thoracic suction and diaphragmatic attraction described in this model.",
            "Renal ptosis may be congenital or acquired:"
          ]
        },
        {
          "type": "sub",
          "text": "9.1.1. Congenital or ectopic ptosis"
        },
        {
          "type": "para",
          "text": "The adrenal gland follows the kidney. The scope for intervention is limited, other than supporting renal function."
        },
        {
          "type": "sub",
          "text": "9.1.2. Acquired ptosis"
        },
        {
          "type": "para",
          "text": "The adrenal gland remains in place. Pain is aggravated by prolonged standing and by drinking a large volume of fluid, and relieved when lying down. Causes include:"
        },
        {
          "type": "bullets",
          "items": [
            "a fall onto the coccyx or heels;",
            "abdominal hypotonia;",
            "a difficult or very rapid delivery;",
            "marked weight loss;",
            "severe or chronic coughing;",
            "post-infectious or postoperative adhesions;",
            "fixation of the eleventh and twelfth ribs or the T10–L1 region;",
            "psoas disorder, including psoitis."
          ]
        },
        {
          "type": "sub",
          "text": "9.1.3. Anterior fixations and degrees of ptosis"
        },
        {
          "type": "para",
          "text": "The right kidney is more prone to anterior fixation and ptosis. Whether ptosed or fixed, however, the kidney has lost its normal mobility."
        },
        {
          "type": "bullets",
          "items": [
            "Women are more frequently affected by ptosis because of pregnancy, childbirth, uterine retroversion, and menopause. Three degrees of ptosis are distinguished:"
          ]
        },
        {
          "type": "sub",
          "text": "9.1.3.1. First degree: intercostal kidney"
        },
        {
          "type": "para",
          "text": "“Intercostal kidney”: irritation of the twelfth intercostal nerve radiates towards the greater trochanter."
        },
        {
          "type": "bullets",
          "items": [
            "Symptoms: the individual holds the flank, has difficulty taking a deep breath, and poorly tolerates coughing and sneezing."
          ]
        },
        {
          "type": "sub",
          "text": "9.1.3.2. Second degree: abdomino-genital kidney"
        },
        {
          "type": "para",
          "text": "“Abdomino-genital” or “lateral femoral cutaneous” kidney."
        },
        {
          "type": "bullets",
          "items": [
            "Symptoms: irritation of the iliohypogastric, ilioinguinal, and lateral femoral cutaneous nerves of the lumbar plexus radiates to the lower abdomen, scrotum or labia majora, and lateral thigh. The kidney is externally rotated. Traction on the vascular pedicle may raise blood pressure."
          ]
        },
        {
          "type": "sub",
          "text": "9.1.3.3. Third degree: femoral or pelvic kidney"
        },
        {
          "type": "para",
          "text": "“Femoral” or “pelvic kidney”: the kidney is displaced following loss of contact with the liver and diaphragm. It is medially rotated and fixed against the psoas."
        },
        {
          "type": "bullets",
          "items": [
            "Symptoms: knee pain without a history of trauma due to femoral nerve irritation; psoas spasm; urinary tract infection; and calculi. Kinking of the ureter reduces urinary flow, thereby promoting calculi and urinary tract infection, as well as irritation of the colon or uterus. An unexplained urinary tract infection should prompt consideration of renal ptosis."
          ]
        },
        {
          "type": "sub",
          "text": "9.2. Pregnancy-related low back pain"
        },
        {
          "type": "para",
          "text": "It is only rarely osteoarticular in a pregnant patient."
        },
        {
          "type": "bullets",
          "items": [
            "Causes:",
            "uterovascular compression;",
            "pericaecal, sigmoid, or obturator tension;",
            "sequelae of appendicectomy, resulting in pressure from the fetal head on the right kidney, right lumbar region, inferior vena cava, and lumbar plexus nerves. The pregnant patient is advised to lie on the left side;",
            "compression of the left common iliac vein by the right common iliac artery (May-Thurner or Cockett syndrome);",
            "pressure on the left kidney."
          ]
        },
        {
          "type": "sub",
          "text": "Relevance to ROP"
        },
        {
          "type": "para",
          "text": "The purpose of reflex work is not to “raise” a ptosed kidney, but to release it from the musculoskeletal or visceral mechanical constraints acting upon it."
        },
        {
          "type": "sub",
          "text": "9.3. Posterior fixations"
        },
        {
          "type": "para",
          "text": "The left kidney is more prone to posterior fixation. A fall onto the back, a direct blow to the lumbar region, costal trauma, or fracture of T12, L1, or L2 may cause the kidney to strike the transverse processes of the lumbar vertebrae. The posterior renal parenchyma may be injured, and pararenal fat may subsequently become fibrotic."
        },
        {
          "type": "para",
          "text": "The kidney loses mobility and the lumbar plexus nerves may be compressed, causing pain in the lumbar region, iliac crest, trochanteric region, and proximal thigh. Intrauterine devices and erectile difficulties in men are described within this model as potentially affecting left renal motility."
        },
        {
          "type": "para",
          "text": "Spasm of the paravertebral, psoas, and quadratus lumborum muscles may cause lumbago during an otherwise innocuous movement. The patient may regard the “wrong movement” as the cause of the restriction, when an underlying renal problem was already approaching decompensation. Traumatic renal fixations are described as more common in men."
        },
        {
          "type": "sub",
          "text": "Relevance to ROP"
        },
        {
          "type": "bullets",
          "items": [
            "The plantar reflex zone of the right kidney is particularly relevant to anterior fixations. Following appendicectomy, work on the right kidney is combined with the caecum and right ovary.",
            "The dorsal reflex zone is particularly relevant to posterior fixations. Work on the left kidney is combined with the spleen and urogenital region."
          ]
        }
      ]
    },
    {
      "id": "relations-viscero-somatiques",
      "title": "10. Viscerosomatic relationships",
      "blocks": [
        {
          "type": "bullets",
          "items": [
            "T11–T12 vertebrae and the two lowest ribs;",
            "L1–L3;",
            "hip and knee;",
            "irritation along the medial arch of the foot through the saphenous nerve, the terminal branch of the femoral nerve, often considered in relation to a renal disorder."
          ]
        }
      ]
    },
    {
      "id": "relations-viscero-emotionnelles",
      "title": "11. Viscero-emotional relationships: clinical interpretation and the brain-kidney axis",
      "blocks": [
        {
          "type": "para",
          "text": "The kidney cannot scientifically be associated with a particular emotion. It nevertheless contributes to several physiological regulatory systems closely involved in adaptation: sympathetic activity, blood pressure, fluid and electrolyte balance, and neuroendocrine responses."
        },
        {
          "type": "para",
          "text": "Prolonged stress, sleep disturbance, fatigue, and intense emotional states may therefore form part of a brain-kidney balance in which the autonomic, cardiovascular, and neuroendocrine systems interact. This relationship is bidirectional and does not establish a direct correspondence between a specific emotion and either kidney."
        },
        {
          "type": "para",
          "text": "Within the symbolic clinical framework of ROP, certain emotional associations have nevertheless been used as points of reference during history-taking. The right kidney, sometimes described as the “digestive kidney”, has been associated with contained anger or longstanding interpersonal conflict; the left kidney, sometimes described as the “genital kidney”, has been associated with profound fear, insecurity, abandonment, or issues involving family roots and intergenerational transmission."
        },
        {
          "type": "para",
          "text": "In practice, when emotional or stress-related factors accompany a renal or lumbar presentation, they may be incorporated into the history and the patient’s overall assessment. The aim is to place the kidney within the body’s general adaptive mechanisms."
        }
      ]
    },
    {
      "id": "conseils",
      "title": "12. Advice",
      "blocks": [
        {
          "type": "bullets",
          "items": [
            "Advise drinking small amounts frequently and limiting animal protein, particularly red meat, cheese, and fats, especially in the evening;",
            "Prefer lying on the left side to reduce venous constraints. Add breathing exercises;",
            "On all fours, inhale while allowing the abdomen to descend, then exhale while drawing it in; repeat approximately ten times;",
            "For both men and women: self-mobilisation of the kidneys in the supine position with the knees flexed. Place the thumbs between the twelfth rib and iliac crest and direct them ventrally.",
            "While tilting the knees approximately 45° to the right and left, engage the thumbs within Grynfeltt’s quadrilateral to direct the kidneys ventrally. Repeat approximately ten times."
          ]
        }
      ]
    },
    {
      "id": "zones-reflexes-podales",
      "title": "13. Plantar reflex zones",
      "blocks": [
        {
          "type": "sub",
          "text": "13.1. Level 1 — Regulation of higher centres"
        },
        {
          "type": "para",
          "text": "• Occipital reflex zones."
        },
        {
          "type": "para",
          "text": "• Brainstem and integration centres, depending on the context."
        },
        {
          "type": "para",
          "text": "• Diencephalon, particularly the hypothalamus."
        },
        {
          "type": "para",
          "text": "• Hypothalamic-pituitary axis."
        },
        {
          "type": "para",
          "text": "See Chapter 3 — Central Nervous System, Level 1: Regulation of Higher Centres."
        },
        {
          "type": "para",
          "text": "The vagus nerve (CN X), included in the former “general adaptation syndrome”, is no longer regarded as a principal renal pathway and is therefore not included in the standard renal sequence."
        },
        {
          "type": "sub",
          "text": "13.2. Level 2 — Autonomic regulation and adaptation"
        },
        {
          "type": "para",
          "text": "Level 2 is particularly important for the kidney. Its autonomic innervation is predominantly sympathetic, through the splanchnic nerves and prevertebral plexuses."
        },
        {
          "type": "para",
          "text": "13.2.1. Thoracolumbar sympathetic system and splanchnic nerves"
        },
        {
          "type": "para",
          "text": "• Lower thoracic sympathetic chain and thoracolumbar junction."
        },
        {
          "type": "para",
          "text": "• Splanchnic nerves supplying the prevertebral plexuses."
        },
        {
          "type": "para",
          "text": "• Segmental territories identified in the clinical mapping presented in this chapter."
        },
        {
          "type": "para",
          "text": "13.2.2. Prevertebral plexuses"
        },
        {
          "type": "para",
          "text": "• Coeliac plexus."
        },
        {
          "type": "para",
          "text": "• Aorticorenal plexus."
        },
        {
          "type": "para",
          "text": "• Renal plexus."
        },
        {
          "type": "para",
          "text": "13.2.3. Adrenal glands"
        },
        {
          "type": "para",
          "text": "The adrenal glands remain part of the renal protocol, but are placed at Level 2 as a neuroendocrine and adaptive interface, even though their anatomical landmark is adjacent to the superior pole of the kidney."
        },
        {
          "type": "para",
          "text": "13.2.4. Diaphragm"
        },
        {
          "type": "para",
          "text": "• Diaphragmatic domes, according to side."
        },
        {
          "type": "para",
          "text": "• Diaphragmatic crura."
        },
        {
          "type": "para",
          "text": "• Thoracolumbar interfaces when indicated by testing."
        },
        {
          "type": "para",
          "text": "See Chapter 4 — Autonomic Nervous System; see Chapter 8 — Diaphragm."
        },
        {
          "type": "sub",
          "text": "13.3. Level 3 — Local and regional visceral regulation"
        },
        {
          "type": "para",
          "text": "13.3.1.1. Plantar surface"
        },
        {
          "type": "para",
          "text": "• Inferior pole: around the L3–L4 landmarks, in line with the first and second toes, above the anterior border of the heel."
        },
        {
          "type": "para",
          "text": "• Superior pole: around the T12 landmark."
        },
        {
          "type": "para",
          "text": "• Lateral border: convex."
        },
        {
          "type": "para",
          "text": "• Medial border: concave."
        },
        {
          "type": "para",
          "text": "• Hilum: around the L1 landmark."
        },
        {
          "type": "para",
          "text": "13.3.1.2. Dorsal surface"
        },
        {
          "type": "para",
          "text": "• Inferior lumbar triangle (Petit’s triangle)."
        },
        {
          "type": "para",
          "text": "• Superior lumbar triangle (Grynfeltt’s quadrilateral)."
        },
        {
          "type": "para",
          "text": "• In ROP mapping, these landmarks are sought opposite the cuboid region."
        },
        {
          "type": "para",
          "text": "13.3.1.3. Combined plantar-dorsal manoeuvre"
        },
        {
          "type": "para",
          "text": "• Place one thumb on the plantar surface and the other on the dorsal surface of the renal zone."
        },
        {
          "type": "para",
          "text": "• Direct the two thumbs towards one another and engage the zone in a coordinated manner."
        },
        {
          "type": "para",
          "text": "• In conjunction with breathing, guide the zone caudally during inspiration and cranially during expiration."
        },
        {
          "type": "para",
          "text": "• The same manoeuvre may be used without respiratory synchronisation during palpatory assessment within the method."
        },
        {
          "type": "para",
          "text": "13.3.2. Kidney and renal compartment"
        },
        {
          "type": "para",
          "text": "• Right and left kidneys."
        },
        {
          "type": "para",
          "text": "• Capsule and perirenal environment."
        },
        {
          "type": "para",
          "text": "• Renal fascia and renal compartment."
        },
        {
          "type": "para",
          "text": "• Renal hilum."
        },
        {
          "type": "para",
          "text": "• Superior and inferior poles."
        },
        {
          "type": "para",
          "text": "• Renal pedicle."
        },
        {
          "type": "para",
          "text": "• Renal pelvis and proximal ureter when warranted by the context."
        },
        {
          "type": "para",
          "text": "13.3.3. Posterior interfaces"
        },
        {
          "type": "para",
          "text": "• Diaphragm."
        },
        {
          "type": "para",
          "text": "• Eleventh and twelfth ribs."
        },
        {
          "type": "para",
          "text": "• Psoas major."
        },
        {
          "type": "para",
          "text": "• Quadratus lumborum."
        },
        {
          "type": "para",
          "text": "• Posterior fascia of the renal compartment."
        },
        {
          "type": "para",
          "text": "13.3.4. Visceral relationships of the right kidney"
        },
        {
          "type": "para",
          "text": "• Liver."
        },
        {
          "type": "para",
          "text": "• Duodenum."
        },
        {
          "type": "para",
          "text": "• Right colic flexure and ascending colon."
        },
        {
          "type": "para",
          "text": "• Ileum."
        },
        {
          "type": "para",
          "text": "13.3.5. Visceral relationships of the left kidney"
        },
        {
          "type": "para",
          "text": "• Spleen."
        },
        {
          "type": "para",
          "text": "• Stomach."
        },
        {
          "type": "para",
          "text": "• Pancreas."
        },
        {
          "type": "para",
          "text": "• Left colic flexure."
        },
        {
          "type": "para",
          "text": "• Jejunum."
        },
        {
          "type": "para",
          "text": "• Duodenojejunal flexure."
        },
        {
          "type": "para",
          "text": "13.3.6. Left renal vein and vascular-genital context"
        },
        {
          "type": "para",
          "text": "When clinically warranted, regional assessment may include the left renal vein, left gonadal vein, and aortomesenteric region. True nutcracker syndrome remains a medical diagnosis."
        },
        {
          "type": "sub",
          "text": "13.4. Level 4 — Viscerosomatic and viscero-emotional integration"
        },
        {
          "type": "para",
          "text": "Level 4 is particularly important for the kidney because of its relationships with the posterior abdominal wall, thoracolumbar junction, and lumbar plexus."
        },
        {
          "type": "para",
          "text": "13.4.1. Viscerosomatic component"
        },
        {
          "type": "para",
          "text": "• Thoracolumbar junction."
        },
        {
          "type": "para",
          "text": "• T11–T12."
        },
        {
          "type": "para",
          "text": "• L1–L3."
        },
        {
          "type": "para",
          "text": "• Eleventh and twelfth ribs."
        },
        {
          "type": "para",
          "text": "• Subcostal nerve."
        },
        {
          "type": "para",
          "text": "• Iliohypogastric and ilioinguinal nerves."
        },
        {
          "type": "para",
          "text": "• Lateral femoral cutaneous nerve, depending on the context."
        },
        {
          "type": "para",
          "text": "• Lumbar plexus."
        },
        {
          "type": "para",
          "text": "• Psoas major."
        },
        {
          "type": "para",
          "text": "• Quadratus lumborum."
        },
        {
          "type": "para",
          "text": "• Hip and knee when warranted by the clinical presentation."
        },
        {
          "type": "para",
          "text": "The lumbar plexus has thus been moved from the former “general adaptation syndrome” to Level 4, as it belongs to somatic integration."
        },
        {
          "type": "para",
          "text": "13.4.2. Brain-kidney balance"
        },
        {
          "type": "para",
          "text": "Stress, sleep, perception of fatigue, autonomic balance, blood pressure, and neuroendocrine regulation interact with renal function within a complex system."
        },
        {
          "type": "para",
          "text": "“Listening–induction”: one landmark on the renal zone and one central landmark."
        },
        {
          "type": "para",
          "text": "See Chapter 3 — Central Nervous System; see Chapter 5 — Stress Mechanism."
        },
        {
          "type": "sub",
          "text": "13.5. Associated support according to testing"
        },
        {
          "type": "para",
          "text": "Regional support is selected according to the history and testing."
        },
        {
          "type": "para",
          "text": "• Right kidney: liver, duodenum, and right colon when a regional relationship is clinically relevant."
        },
        {
          "type": "para",
          "text": "• Left kidney: spleen, stomach, pancreas, left colon, and duodenojejunal region according to testing."
        },
        {
          "type": "para",
          "text": "• Left urogenital context: left renal vein and gonadal relationships when relevant."
        },
        {
          "type": "para",
          "text": "• Diaphragm: include when thoracolumbar and respiratory dynamics appear to contribute to the presentation."
        },
        {
          "type": "sub",
          "text": "13.6. Clinical interpretation according to presentation"
        },
        {
          "type": "para",
          "text": "The hierarchy of levels varies with the context and must not be applied as a rigid sequence."
        },
        {
          "type": "para",
          "text": "• Lumbar pain or previous trauma: Level 3—renal compartment, fascia, and dorsal surface; Level 4—ribs, psoas, quadratus lumborum, and lumbar plexus."
        },
        {
          "type": "para",
          "text": "• Clinical suspicion of ptosis or loss of regional mobility following medical exclusion: Level 2—diaphragm and adaptation; Level 3—kidney, compartment, and relationships; Level 4—psoas, quadratus lumborum, and thoracolumbar junction."
        },
        {
          "type": "para",
          "text": "• Hypertensive or stress-related context: Level 2—sympathetic system, renal plexus, and adrenal glands; Level 1 and brain-kidney axis according to testing."
        },
        {
          "type": "para",
          "text": "• Left urogenital context: left kidney, venous relationships, and pelvic region only when supported by the history and testing."
        },
        {
          "type": "para",
          "text": "SAFETY PRINCIPLE — A sensitive reflex zone or palpatory change is not a diagnostic test for calculi, infection, renal failure, haematuria, tumour, vascular syndrome, or any other renal disease. Haematuria, fever, acute flank pain, significant trauma, deterioration in general condition, or any unexplained symptom requires appropriate medical assessment."
        }
      ]
    }
  ]
}
