import type { Chapter } from './types'

export const chapter7Fr: Chapter = {
  slug: 'chapter-7',
  number: '7',
  title: 'Cavités abdominale et péritonéale',
  sections: [
    {
      id: 'presentation',
      title: 'Présentation',
      blocks: [
        { type: 'lead', label: 'Cavité abdominale', text: 'elle abrite le tractus gastro-intestinal, le foie, le pancréas, la rate, les reins, les glandes surrénales et les uretères, ainsi que la structure neuro-vasculaire (figure 7.1). Elle est le lieu d’une grande activité métabolique et neuroendocrinienne aux conséquences locales et centrales.' },
        { type: 'para', text: 'Bien que séparés de la cavité thoracique par le diaphragme, les viscères de la cavité abdominale, où règne une pression positive, sont aspirés par la pression négative régnant dans la cavité thoracique.' },
        { type: 'lead', label: 'Cavité péritonéale', text: 'la paroi interne de la cavité abdominale est tapissée de la séreuse péritonéale. Le péritoine est, de toutes les séreuses, la plus grande et la plus complexe car il présente des replis, des récessus, des mésos, des ligaments et des hiatus qui solidarisent les viscères au péritoine ou entre eux.' },
      ],
    },
    {
      id: 'situation',
      title: 'Situation',
      blocks: [
        { type: 'lead', label: 'Contenant', text: 'schématiquement, la cavité abdominale est un demi-cylindre creux vertical dont les parois sont : (figure 7.2)' },
        { type: 'bullets', items: [
          'Céphaliquement : le diaphragme ; (Cf. chapitre 8 Diaphragme page…)',
          'Dorsalement : un mur ostéo-musculaire solide, formé des muscles carrés de lombes et grand psoas de part et d’autre de la colonne thoraco-lombaire ;',
          'Latéralement : les muscles abdominaux : transverses de l’abdomen, obliques internes et externes ;',
          'Ventralement : les muscles grands droits de l’abdomen ;',
          'Caudalement : les fosses iliaques internes droite et gauche des os coxaux circonscrivant l’ouverture supérieure de la cavité pelvienne.',
        ]},
        { type: 'para', text: 'Le péritoine est renforcé par des fascias interposés entre lui et les muscles abdominaux : fascia thoraco-abdominal, fascia tranversalis, aponévrose des muscles de la colonne vertébrale et de la hanche. Ces fascias peuvent être source de tensions affectant la cavité péritonéale et son contenu viscéral.' },
        { type: 'lead', label: 'Contenu', text: 'l’allongement important du tractus gastro-intestinal au cours du développement embryonnaire, l’a obligé à faire des rotations et à se courber pour qu’il puisse être contenu dans la cavité péritonéale. Ces mouvements ont délimité plusieurs cavités : (figure 7.2)' },
        { type: 'lead', label: 'Cavité intra-péritonéale', text: 'elle contient l’estomac, le foie, les voies biliaires et l’intestin grêle. Ces viscères sont enveloppés par le péritoine et appendus au péritoine pariétal postérieur par des replis, appelés mésos. C’est un abus de langage de dire qu’ils sont intra-péritonéaux : ils sont simplement péritonisés.' },
        { type: 'lead', label: 'Cavité rétro-péritonéale', text: 'elle contient le colon, la loge rénale, le duodénum, le pancréas et la rate. Ces viscères semblent indépendants du péritoine. C’est aussi inexact de dire qu’ils sont rétro-péritonéaux car, à la suite des rotations du tractus gastro-intestinal primitif, ces viscères se sont accolés à la face postérieure du péritoine pariétal postérieure qui ne recouvre plus que leur face antérieure. Ils ne sont pas appendus au péritoine. Leur maintien dépend de la pression positive régnant dans la cavité péritonéale, qui les plaque contre le mur ostéo-musculaire de la paroi abdominale postérieure. La loge rétro-péritonéale se prolonge caudalement dans la cavité sous-péritonéale.' },
        { type: 'lead', label: 'Cavité sous-péritonéale', text: 'ses viscères occupent la cavité pelvienne (figure 7.1). Ils ne sont séparés de la cavité abdominale que par le péritoine posé comme un linge sur eux. Leur mobilité peut être affectée par les tensions du péritoine.' },
      ],
    },
    {
      id: 'anatomie',
      title: 'Anatomie',
      blocks: [
        { type: 'lead', label: 'Péritoine', text: 'c’est une membrane séreuse qui tapisse les parois internes de la cavité abdominale et la surface des viscères péritonisés. Il est constitué de deux feuillets : (figure 7.3)' },
        { type: 'lead', label: 'Feuillet pariétal', text: 'c’est un tissu conjonctif solide au contact des parois de la cavité abdominale, doublé de tissu cellulaire plus épais dans la région lombo-iliaque. Il se réfléchit, au niveau du hile du viscère, pour devenir le feuillet viscéral.' },
        { type: 'lead', label: 'Feuillet viscéral', text: 'il est formé d’un tissu épithélial mince et translucide, appelé mésothélium, adhérant aux viscères qu’il entoure à la façon d’un film de cellophane.' },
        { type: 'lead', label: 'Cavité péritonéale', text: 'c’est l’espace virtuel entre les deux feuillets péritonéaux. Il est occupé par le liquide péritonéal.' },
        { type: 'lead', label: 'Liquide péritonéal', text: 'le mésothélium sécrète le liquide péritonéal. Bien que produit en très petite quantité (5 à 10 ml/jour), il possède un haut pouvoir lubrifiant pour permettre le glissement des deux feuillets entre eux et la mobilité inter-viscérale. Il est composé d’eau, d’électrolytes, d’immunoglobulines, de macrophage et de surfactant.' },
        { type: 'lead', label: 'Surfactant', text: 'c’est un liquide lipoprotéinique tensio-actif, capable de diminuer la tension de surface entre deux couches de tissu. Il est surtout présent au niveau pulmonaire pour favoriser l’expansion des alvéoles. Son insuffisance est responsable de détresse respiratoire, appelée maladie des membranes hyalines, redoutable chez les bébés prématurés.' },
        { type: 'para', text: 'Au niveau abdominal, le surfactant facilite le glissement des deux feuillets péritonéaux et la mobilité inter-viscérale. Il joue aussi un rôle considérable sur l’effet turgor. (Cf. Chapitre 1 Généralités,  Effet turgor, page…)' },
        { type: 'lead', label: 'Replis péritonéaux', text: 'ils relient les viscères aux parois de la cavité abdominale ou entre eux.' },
        { type: 'lead', label: 'Ligaments péritonéaux', text: 'ils sont l’accolement des deux feuillets. Ils relient un ou deux viscères au péritoine pariétal antérieur. Ils sont dépourvus des vaisseaux sanguins et lymphatiques mais ils ont des filets nerveux.' },
        { type: 'lead', label: 'Mésos', text: 'les viscères péritonisés sont appendus au péritoine pariétal postérieur par des mésos (figure 1.6). Ceux-ci sont aussi constitués par l’accolement des deux feuillets. Ils sont parcourus par le pédicule vasculo-nerveux, destiné aux viscères.' },
        { type: 'lead', label: 'Racines des mésos', text: 'les mésos sont attachés au péritoine pariétal postérieur par un tissu conjonctif solide, la racine du méso. La mobilité du méso est proportionnelle à la mobilité du viscère qui lui est appendu. Les mésos prennent le nom du viscère qu’ils rejoignent (figure 7.4) : mésogastre, mésentère, mésocolon transverse, mésosigmoïde. Le mésocolon transverse et sa racine, divisent l’espace intra-péritonéal en deux compartiments :' },
        { type: 'bullets', items: [
          'il contient l’œsophage abdominal, l’estomac, le duodénum, le foie, le pancréas dans ses 2/3 supérieurs, les voies biliaires, la rate et les reins en majeure partie.',
          'il contient le 1/3 inférieur du pancréas, l’intestin grêle et le colon.',
        ]},
        { type: 'rop', body: [
          'Les racines des mésos sont hautement réflexogènes. Solliciter leurs zones réflexes facilite le fonctionnement des viscères.',
          'la grande mobilité du colon transverse et du colon sigmoïde rend leurs positions fluctuantes. Leurs zones réflexes sont difficiles à ressentir dans leur partie moyenne. Par contre, nous pouvons solliciter leurs extrémités proximale et distale et leurs racines.',
        ]},
        { type: 'lead', label: 'Omentums', text: 'ce sont des lames péritonéales à double feuillet, infiltrées de graisse. Ils contiennent un pédicule vasculo-nerveux. Ils réunissent un ou deux viscères entre eux. Ils prennent le nom des viscères qu’ils réunissent :' },
        { type: 'bullets', items: [
          'grand omentum ou omentum gastro-colique ; (figure 1.6)',
          'petit omentum ou omentum gastro-hépatique ; (figure 1.7)',
          'omentum gastro-splénique : il relie l’estomac à la rate',
          'omentum pancréatico-splénique : il relie le pancréas à la rate',
        ]},
        { type: 'lead', label: 'Fascias', text: 'le fascia tranversalis est une fine membrane qui sépare le muscle transverse de l’abdomen du péritoine. Il ne fait pas partie du péritoine, mais peut créer des tensions péritonéales et viscérales. (figure 1.9)' },
        { type: 'lead', label: 'Orifices et hiatus de la cavité abdominale', text: 'le péritoine est hermétiquement clos, à l’exception des deux ostiums abdominaux chez la femme, qui font communiquer l’abdomen avec la cavité pelvienne. Ces deux orifices permettent le passage du liquide péritonéal dans la trompe de Fallope, pour faciliter la circulation de l’ovule dans la trompe et la rencontre avec les spermatozoïdes.' },
        { type: 'para', text: 'Les orifices et hiatus sont des zones faibles situées à des carrefours entre deux cavités :' },
        { type: 'bullets', items: [
          'Jonction avec la cavité thoracique : hiatus oesophago-cardio-tubérositaire, siège des hernies hiatales (figure 8.7)',
          'Jonction avec la cavité pelvienne : canal inguinal,  siège des hernies inguinales (figure 20.7 A et B),',
          'Jonction avec la cuisse : à travers l’anneau fémoral, au-dessous du ligament inguinal, siège des hernies fémorales.',
        ]},
        { type: 'rop', body: [
          'la sollicitation des zones réflexes du péritoine (mésentère, méso-colon, méso-sigmoïde) permet d’équilibrer les tensions péritonéales et ses zones faibles.',
        ]},
      ],
    },
    {
      id: 'vascularisation',
      title: 'Vascularisation',
      blocks: [
        { type: 'lead', label: 'Aorte abdominale', text: 'son trajet va de l’orifice aortique du diaphragme (à hauteur de la vertèbre Th12) à la bifurcation en deux artères iliaques communes à hauteur de l’ombilic et de la vertèbre L4, et légèrement à gauche de la ligne xyphopubienne. Sa largeur normale est d’environ 2 à 3 cm.' },
        { type: 'lead', label: 'Anévrisme', text: 'Il est très important de vérifier cette largeur ainsi que son pouls en raison du risque d’anévrisme.' },
        { type: 'sub', text: 'Palpation clinique' },
        { type: 'lead', label: 'Test', text: 'l’aorte abdominale est plus facilement palpable entre le bord caudal du pancréas et l’ombilic. Prendre l’aorte abdominale en pince entre les deux pouces et les deux index pour bien sentir les bords droit et gauche. Le patient ayant les membres inférieurs allongés, met les deux mains dans le dos pour lordoser la colonne lombaire. Si la largeur de l’aorte atteint 4 à 5cm, orienter impérativement le patient vers son médecin. Les symptômes peuvent être absents ou discrets : dorsalgie, lombalgie, douleurs abdominales sourdes, siégeant à gauche ou au centre de l’abdomen, parfois accompagnées de dyspnée et de dysphagie.' },
        { type: 'para', text: 'Les trois branches de l’aorte abdominale destinées au système digestif  sont : (figure 7.5)' },
        { type: 'lead', label: 'Tronc cœliaque', text: 'il nait à la hauteur du bord supérieur de la vertèbre L1. Son pouls est perceptible à gauche et un travers de doigt au-dessous de l’appendice xyphoïde. Il est le témoin de la vascularisation de l’estomac, du foie, de la rate et du pancréas.  Il donne trois branches :' },
        { type: 'lead', label: 'Artère gastrique gauche', text: 'elle nait à la hauteur de la vertèbre Th12. Elle suit la petite courbure de l’estomac jusqu’au pylore où elle s’anastomose avec l’artère gastrique droite, issue de l’artère hépatique propre. Son pouls est perceptible à gauche du tronc cœliaque et un peu plus céphalique. (figure 7.6)' },
        { type: 'lead', label: 'Artère hépatique commune', text: 'elle nait à hauteur de la vertèbre Th12, à droite de la ligne xypho-pubienne et se dirige vers le foie entre les deux feuillets du petit omentum, jusqu’au sillon transversal de la face inférieure du foie, où elle pénètre dans le foie au niveau de son hile. Elle se divise en artère hépatique propre et artère gastro-duodénale.' },
        { type: 'lead', label: 'Artère splénique', text: 'elle nait à la même hauteur que l’artère hépatique commune mais à gauche de la ligne xypho-pubienne. Elle a un trajet tortueux le long du bord supérieur du pancréas. Elle irrigue le pancréas, la rate et le fundus de l’estomac. Son pouls est perceptible à gauche de l’aorte abdominale. Elle est témoin de l’activité de la rate.' },
        { type: 'lead', label: 'Artère mésentérique supérieure', text: '(Cf. chapitre 14 Intestin grêle, Vascularisation, page…) elle nait à hauteur de la vertèbre L1, deux travers de doigt plus bas que le tronc cœliaque, légèrement à droite de la jonction duodéno-jéjunale. C’est là que son pouls est perceptible. Il est témoin de l’activité de l’intestin grêle et de la partie droite du colon.' },
        { type: 'lead', label: 'Artère mésentérique inférieure', text: '(Cf. chapitre 15 Colon, Vascularisation, page…) elle nait à hauteur de la vertèbre L3 ou L4, au-dessus et légèrement à gauche de l’ombilic. Son pouls, difficile à sentir, est le témoin de l’activité de la partie gauche du colon.' },
        { type: 'lead', label: 'Drainage veineux', text: 'il est assuré par le système porte qui ramène vers le foie le sang veineux chargé des nutriments provenant de la digestion et de la rate. (Cf. Chapitre 11 Foie Système porte, page…)' },
        { type: 'lead', label: 'Vascularisation du péritoine', text: 'le péritoine n’a pas de vascularisation propre. Elle lui est apportée par les pédicules vasculaires empruntant les mésos. Par contre, il a son propre réseau lymphatique pour le drainage et la réabsorption du liquide péritonéal. L’intestin est la plus grande zone de stockage du sang veineux et le plus grand réseau lymphatique de l’organisme.' },
        { type: 'rop', body: [
          'Notre action sur les mésos active les circulations sanguine et lymphatiques ainsi que l’innervation du péritoine.',
        ]},
      ],
    },
    {
      id: 'innervation',
      title: 'Innervation',
      blocks: [
        { type: 'lead', label: 'Péritoine pariétal', text: 'il est innervé par le système nerveux somatique commun avec les parois de la cavité abdominale. Il est sensible au chaud, au froid, à la pression et à la douleur. Cette innervation commune explique les projections de la douleur viscérale au niveau musculo-squelettique. Les nerfs du péritoine pariétal sont :' },
        { type: 'lead', label: 'Six derniers nerfs intercostaux droit et gauche', text: 'ils innervent le péritoine pariétal antérieur. La douleur pariétale antérieure se projette localement sur le revêtement cutané en regard de l’organe : dermalgies réflexes du Dr Jarricot (figure 1.11).' },
        { type: 'lead', label: 'Nerfs phréniques', text: 'ils innervent le péritoine pariétal supérieur ou diaphragmatique et la capsule de Glisson du foie (figure 8.2). Son irritation peut donner des douleurs scapulaires, périarthrite scapulo-humérale droites et cervicalgies par anastomose avec le plexus brachial et le plexus cervical droits.' },
        { type: 'lead', label: 'Plexus lombal (L1 à L4)', text: 'il innerve le péritoine pariétal postérieur. Son irritation peut donner des lombalgies hautes irradiant vers la région inguinale, les grandes lèvres ou le scrotum et vers face antérieure de la cuisse par les nerfs du plexus lombal. (figure 16.6)' },
        { type: 'lead', label: 'Péritoine viscéral', text: 'il est innervé par le sympathique commun avec les viscères. Il ne comporte pas de fibres sensitives mais il est stimulé par l’étirement et les irritants chimiques.' },
      ],
    },
    {
      id: 'physiologie',
      title: 'Physiologie',
      blocks: [
        { type: 'lead', label: 'Protection', text: 'une bonne tonicité de la sangle abdominale est indispensable au maintien et à la cohésion des viscères abdominaux. Elle exerce une contre-force opposée au diaphragme lors des efforts, de la toux, de l’éternuement, de la défécation et lors de l’accouchement. Le muscle transverse de l’abdomen a un rôle essentiel pour s’opposer à la ptose des viscères. L’hypotonie de la sangle abdominale tend à faciliter le glissement des viscères vers le bas en tirant sur leurs mésos. Cette traction sur les mésos déclenche des tensions pariéto-viscérales par irritation des filets nerveux, et des spasmes musculaires' },
        { type: 'para', text: 'Mobilité  (Cf. chapitre 1 Généralités, page…)' },
        { type: 'sub', text: 'Propriétés du liquide péritonéal' },
        { type: 'lead', label: 'Sécrétion', text: 'le mésothélium du péritoine sécrète le liquide péritonéal. Il est constitué de nombreuses microvillosités, comparables aux villosités de l’intestin grêle. Elles augmentent la surface d’échange entre la cavité péritonéale et les circulations sanguine et lymphatique jusqu’à 40m2.' },
        { type: 'lead', label: 'Circulation', text: 'sous la poussée du diaphragme lors de l’inspiration, le foie agit comme un piston qui pousse le liquide péritonéal vers le bas, en longeant la gouttière pariéto-colique droite jusqu’au cul-de-sac de Douglas.' },
        { type: 'para', text: 'Lors de l’expiration et sous l’action de l’aspiration thoracique et de l’aimantation diaphragmatique, le liquide péritonéal remonte jusqu’au diaphragme.' },
        { type: 'lead', label: 'Réabsorption', text: 'le liquide péritonéal est réabsorbé par le péritoine et la circulation lymphatique pour éliminer les déchets intra-péritonéaux. La cavité péritonéale agit comme une barrière immunitaire par les immunoglobulines et les macrophages qu’elle contient.' },
      ],
    },
    {
      id: 'pathologie',
      title: 'Pathologie',
      blocks: [
        { type: 'para', text: 'La cavité péritonéale présente une grande surface qui favorise la diffusion d’infections ou de métastases cancéreuses.' },
        { type: 'sub', text: 'Contre-indications (diagnostic d’exclusion)' },
        { type: 'lead', label: 'Péritonites', text: 'l’inflammation par infection peut survenir par :' },
        { type: 'bullets', items: [
          'Traumatisme de l’abdomen avec effraction viscérale ;',
          'Ulcère perforé gastro-duodénal ;',
          'Septicémie par voie sanguine ;',
          'Appendicite non traitée avec perforation ;',
          'Grossesse extra-utérine avec perforation et hémorragie interne.',
        ]},
        { type: 'para', text: 'Symptômes : douleur, vomissement, altération de l’état général.' },
        { type: 'para', text: 'Examen clinique : contraction abdominale, « ventre de bois »' },
        { type: 'lead', label: 'Métastases', text: 'dans le cancer du colon ou de l’ovaire, les cellules cancéreuses diffusent rapidement dans tout l’abdomen.' },
        { type: 'para', text: 'Hernie inguinale irréductible' },
        { type: 'sub', text: 'Indications (pathologies fonctionnelles)' },
        { type: 'lead', label: 'Fixations et adhérences', text: 'les séquelles de traumatisme direct (coup violent dans l’abdomen) ou indirect par les forces collisionnelles d’accident, les infections, les maladies inflammatoires, la chirurgie, sont responsables de fixations et d’adhérences du péritoine et de brides cicatricielles pouvant aboutir à une occlusion intestinale. Ces fixations et adhérences enserrent les vaisseaux sanguins et lymphatiques, les nerfs et les viscères avec toutes les dysfonctions qui en découlent :' },
        { type: 'bullets', items: [
          'Douleurs ;  (Cf. innervation, page…)',
          'Déficiences hiatales et inguinales : après une chirurgie abdomino-pelvienne, les différentes cicatrices déséquilibrent les tensions harmonieuses du péritoine, créant des béances au niveau des points faibles de la paroi abdominale :',
          'Reflux gastro-œsophagien et hernie hiatale au niveau de la jonction oesophao-cardio-tubérositaire ; (Cf. Hernie hiatale, page…)',
          'Hernie inguinale réductible par béance de l’orifice profond du canal inguinal. (Cf. Hernie inguinale, page… et figure 20.7)',
          'Tiraillement des mésos avec leurs conséquences neuro-vasculaires, douloureuses et ptoses viscérales.',
        ]},
        { type: 'lead', label: 'Infertilité par séquelle d’appendicectomie', text: 'la section du ligament appendico-ovarien droit puis sa fibrose font perdre la mobilité de l’ovaire et obstruer l’ostium abdominal, empêchant la communcation du liquide péritonéal avec la trompe.' },
      ],
    },
    {
      id: 'zones-reflexes',
      title: 'Zones réflexes podales',
      blocks: [
        { type: 'bullets', items: [
          'Racine du mésentère ;',
          'Racine de mésocolon transverse ;',
          'Racine du mésosigmoïde.',
        ]},
      ],
    },
    {
      id: 'relations-peritoneo-somatiques',
      title: 'Relations péritonéo-somatiques',
      blocks: [
        { type: 'para', text: 'Par les liens entre le péritoine pariétal et le système musculo-articulaire, on peut diviser  le corps en quatre quadrants selon les contraintes exercées par les viscères :' },
        { type: 'lead', label: 'Topographie abdominale à quatre quadrants', text: 'Si nous traçons une ligne horizontale passant par l’ombilic et une ligne verticale passant par la ligne xypho-ombilicale, nous délimitons quatre quadrants : (figure 7.17)' },
        { type: 'lead', label: 'Pathologies viscérales sous-ombilicales', text: 'elles sont en relation avec la région lombaire, le bassin et le membre inférieur du même côté.' },
        { type: 'lead', label: 'Pathologies viscérales sus-ombilicales', text: 'elles sont en relation avec les colonnes thoracique et cervicale, la tête et le membre supérieur du même côté.' },
        { type: 'para', text: 'Les exemples ne manquent pas :' },
        { type: 'bullets', items: [
          'cruralgie et dysfonction rénale homolatérales ;',
          'sciatalgie et dysfonction uro-génitale homolatérales ;',
          'douleur du pied d’origine rénale ou colique homolatérale ;',
          'scapulalgie et PSH droite d’origine hépatique, pulmonaire droite ;',
          'scapulalgie et PSH gauche d’origine pulmonaire gauche, cardiaque ou stomacale.',
        ]},
      ],
    },
  ],
}
