import type { Chapter } from './types'

export const chapter3Fr: Chapter = {
  slug: 'chapter-3',
  number: '3',
  title: 'Système nerveux central (SNC)',
  sections: [
    {
      id: 'section-1-presentation-generale',
      title: '1. Présentation générale',
      blocks: [
        { type: 'para', text: 'Version restructurée : anatomie et physiologie dans le corps du chapitre ; zones réflexes regroupées en fin de chapitre.' },
        { type: 'para', text: 'Le système nerveux autonome (SNA) comprend deux grands versants : le parasympathique et le sympathique. Le parasympathique à une origine crânio-sacrale, tandis que le sympathique à une origine thoracique. Malgré ces origines différentes, ils partagent des centres d’intégration dans le système nerveux central, afin de permettre à l’organisme de s’adapter en permanence aux modulations provenant de l’environnement et aux besoins des différents territoires corporels.' },
        { type: 'para', text: 'Dans ce chapitre, les centres du SNC sont présentés selon une logique anatomique et fonctionnelle :' },
        { type: 'bullets', items: [
          'Tronc cérébral et cervelet : dans la fosse cérébrale postérieure.',
          'Diencéphale et système limbique : dans la fosse cérébrale moyenne.',
          'Cortex ou télencéphale : au-dessus de la tente du cervelet, en position supra-tentorielle.',
        ]},
        { type: 'para', text: 'Les fosses cérébrales postérieure et moyenne sont subtentorielles, c’est-à-dire situées au-dessous de la tente du cervelet. Le cortex, lui, est supra-tentoriel.' },
        { type: 'para', text: 'Sur le plan phylogénétique, le cerveau a évolué par complexification progressive afin de répondre aux contraintes de l’environnement. Sur le plan ontogénétique, le développement du cerveau humain rappelle certains jalons de cette évolution, ce qui permet de comprendre la persistance de réponses archaïques, automatiques et émotionnelles au sein du fonctionnement humain.' },
      ],
    },
    {
      id: 'section-2-cadre-terminologique',
      title: '2. Cadre terminologique : cerveau limbique, système limbique, réseaux limbiques',
      blocks: [
        { type: 'para', text: 'La théorie des trois cerveaux, proposée par Paul D. MacLean au milieu du XXe siècle, distingue classiquement un cerveau reptilien, un cerveau limbique ou émotionnel et un néocortex. Cette théorie est aujourd’hui dépassée comme modèle scientifique strict, car le cerveau ne fonctionne pas par strates indépendantes. Elle conserve cependant un intérêt pédagogique pour expliquer les niveaux d’intégration entre survie, émotion et cognition.' },
        { type: 'para', text: 'Cette clarification est importante pour éviter de présenter le système limbique comme un cerveau autonome. Les émotions, la mémoire affective et les comportements d’adaptation émergent de circuits distribués, en interaction constante avec le cortex préfrontal, l’hypothalamus, le tronc cérébral, le système nerveux autonome, les voies olfactives et les informations viscérales.' },
      ],
    },
    {
      id: 'section-3-organisation-anatomique',
      title: '3. Organisation anatomique et fonctionnelle du SNC',
      blocks: [
        { type: 'sub', text: '3.1. Tronc cérébral' },
        { type: 'para', text: 'Le tronc cérébral permet la communication entre le cortex, le cervelet et la moelle spinale. Il est à l’origine de la plupart des nerfs crâniens, à l’exception des nerfs olfactif I et optique II. Il est également le siège de la décussation des voies motrices volontaires du système pyramidal et de certaines voies sensitives.' },
        { type: 'para', text: 'Il comprend trois parties : la moelle allongée, le pont et le mésencéphale.' },
        { type: 'sub', text: '3.1.1. Moelle allongée' },
        { type: 'para', text: 'La moelle allongée, anciennement appelée bulbe, est située au niveau du foramen magnum. Elle est à l’origine des nerfs crâniens glossopharyngien IX, vague X, accessoire XI et hypoglosse XII. Elle abrite des centres de régulation automatique respiratoire, cardiaque et digestive.' },
        { type: 'sub', text: '3.1.2. Pont' },
        { type: 'para', text: 'Le pont relie le cervelet aux deux hémisphères cérébraux. Sa face antérieure est parcourue et irriguée par le tronc basilaire, formé par la réunion des deux artères vertébrales dans le foramen magnum. Sa face postérieure abrite le quatrième ventricule. Le pont contient l’origine des nerfs crâniens trijumeau V, abducens VI et facial VII.' },
        { type: 'para', text: 'Dans le pont se trouve le locus coeruleus, acteur majeur du mécanisme de stress. Sous l’action de l’hypothalamus, il participe à la libération de noradrénaline, laquelle contribue à l’activation de l’axe sympathico-adrénalo-médullaire (axe SAM).' },
        {
          type: 'xref',
          label: 'Voir la référence dans le chapitre 5',
          text: 'Mécanisme de stress',
          href: '/lecture/chapitre-5?xrefBack=%2Flecture%2Fchapitre-3%23p-section-3-organisation-anatomique-7&xrefBackLabel=Retour%20au%20chapitre%203#p-presentation-0',
        },
        { type: 'sub', text: '3.1.3. Mésencéphale' },
        { type: 'para', text: 'Le mésencéphale est situé à hauteur de la grande scissure de la tente du cervelet, à l’extrémité antérieure du sinus droit. Sa face antérieure se trouve en arrière et au-dessus de la selle turcique du sphénoïde, où loge l’hypophyse. Sa face postérieure est en avant de l’épiphyse. Il contient l’origine des nerfs oculomoteur III et trochléaire IV.' },
        { type: 'sub', text: '3.1.4. Ganglions de la base et neurotransmetteurs' },
        { type: 'para', text: 'Les ganglions de la base, anciennement appelés noyaux gris centraux, comprennent notamment le noyau caudé, le noyau lenticulaire, la substance noire, les noyaux rouges et le putamen. Ils participent à la programmation et à la bonne exécution des mouvements volontaires et automatiques.' },
        { type: 'para', text: 'Ces structures sont associées à de nombreux neurotransmetteurs : dopamine, noradrénaline, acétylcholine, sérotonine, adrénaline, endorphines, GABA, etc. Certains neurotransmetteurs sont excitateurs, d’autres inhibiteurs. Leur équilibre conditionne la qualité de la transmission synaptique entre neurones.' },
        { type: 'para', text: 'Pathologie : la maladie de Parkinson se caractérise par une pauvreté et une lenteur d’exécution des mouvements, associées à des tremblements, en lien avec une déficience des circuits dopaminergiques des ganglions de la base.' },
        { type: 'sub', text: '3.1.5. Formation réticulaire' },
        { type: 'para', text: 'La formation réticulaire est une bande de substance grise située au sein du tronc cérébral, de la moelle spinale au mésencéphale. Elle reçoit de nombreuses informations sensitives, sensorielles, motrices, neurovégétatives et émotionnelles. Elle les transmet au thalamus, à l’hypothalamus, au cortex et au cervelet. Les voies olfactives constituent une exception importante, car elles sont directement connectées aux réseaux limbiques sans relais thalamique initial.' },
        { type: 'sub', text: '3.2. Cervelet' },
        { type: 'para', text: 'Le cervelet est situé en arrière du pont, dont il est séparé par le quatrième ventricule. Il comprend un lobe médian, le vermis, deux hémisphères cérébelleux et, en avant, l’archéocervelet.' },
        { type: 'para', text: 'Il reçoit des informations de la moelle spinale, du tronc cérébral et du cerveau pour contrôler et réguler l’activité motrice et posturale. Il reçoit également des informations de l’appareil vestibulaire concernant la position et le déplacement de la tête.' },
        { type: 'para', text: 'Pathologie : la destruction du cervelet ne produit pas de paralysie, mais des troubles de l’équilibre et de la coordination des mouvements appelés ataxie. Parmi les signes possibles : adiadococinésie, hypermétrie au test doigt-nez, dyschronométrie par difficulté à commencer ou à arrêter un mouvement.' },
        { type: 'sub', text: '3.3. Système limbique et réseaux émotionnels' },
        { type: 'para', text: 'Dans le modèle historique des trois cerveaux, cette partie était appelée « cerveau limbique » ou « cerveau émotionnel ». Dans la terminologie réténue pour ce chapitre, il est préférable de parler de système limbique et de réseaux limbiques.' },
        { type: 'para', text: 'Le terme limbique signifie « en bordure de », car plusieurs structures concernées occupent une position profonde ou médiale, en relation avec la face interne du cortex. Le système limbique n’est pas une entité anatomique parfaitement délimitée : il s’agit plutôt d’un ensemble de structures et de circuits impliqués dans les émotions, la mémoire, les pulsions, les comportements affectifs, la motivation et les réponses neurovégétatives.' },
        { type: 'para', text: 'Les principales structures associées aux réseaux limbiques comprennent notamment l’amygdale, l’hippocampe, le cortex cingulaire, l’insula, le noyau accumbens, les corps mamillaires, le fornix et les voies olfactives. Certaines de ces structures sont des noyaux, d’autres des régions corticales ou des faisceaux de connexion ; il est donc plus rigoureux de parler de structures ou de circuits limbiques plutôt que de « noyaux limbiques » au sens strict.' },
        { type: 'sub', text: '3.3.1. Amygdale' },
        { type: 'para', text: 'Anatomie : l’amygdale est une structure paire située dans la région ventrale du lobe temporal, en regard de la tempe, au fond du sillon latéral. Elle est petite, de la taille d’une amande. Elle est fortement connectée au bulbe olfactif, au cortex préfrontal, aux noyaux de la base, au tronc cérébral, à l’hypothalamus et au thalamus.' },
        { type: 'para', text: 'Physiologie : l’amygdale fonctionne comme un système d’alarme. Elle est activée par les émotions fortes, la peur, le danger, les traumatismes effrayants ou toute situation de stress réelle ou imaginaire. Elle stimule l’hypothalamus, qui peut ensuite activer les mécanismes de stress.' },
        { type: 'para', text: 'Pathologie : en cas de stress répétés ou chroniques, le seuil de réactivité de l’amygdale peut s’abaisser, favorisant hyperémotivité, anxiété, phobies, hypocondrie, réactions paranoïaques ou peur panique. L’hyperréactivité de l’amygdale peut altérer les capacités de discernement et de jugement, la compétition entre émotion et cognition se faisant souvent au détriment de cette dernière.' },
        { type: 'sub', text: '3.3.2. Hippocampe' },
        { type: 'para', text: 'Anatomie : l’hippocampe est une structure paire située sous le cortex, au niveau du lobe temporal. Il est en relation étroite avec le fornix et avec l’amygdale, située à son extrémité antérieure.' },
        { type: 'para', text: 'Physiologie : ses fonctions principales concernent la mémorisation, la géolocalisation, l’attention et la vigilance. En relayant certaines informations entre l’amygdale et le cortex préfrontal, il participe à la modulation de l’activité émotionnelle. Il possède également des propriétés de neurogenèse impliquées dans l’apprentissage.' },
        { type: 'para', text: 'Pathologie : sous stress chronique ou après des traumatismes physiques ou psychologiques, l’hippocampe peut s’atrophier. La maladie d’Alzheimer se caractérise notamment par des troubles de la mémoire, du sommeil, de l’orientation, ainsi que par de l’anxiété ou une dépression. L’accumulation de protéines bêta-amyloïdes et Tau altère la communication inter-neuronale.' },
        { type: 'para', text: 'Système glymphatique cérébral : le système glymphatique correspond à une organisation circulatoire entre le liquide cérébro-spinal, le parenchyme cérébral et les vaisseaux lymphatiques méningés. Il participe à l’élimination de déchets métaboliques du cerveau.' },
        { type: 'sub', text: '3.3.3. Fornix' },
        { type: 'para', text: 'Anatomie : le fornix est une structure en forme de fer à cheval située au centre du cerveau, sous le corps calleux. Il contient des fibres nerveuses issues de l’hippocampe et reliant celui-ci à d’autres structures, notamment les corps mamillaires.' },
        { type: 'para', text: 'Physiologie : il participe aux circuits de la mémoire. Il doit être présenté comme un faisceau de connexion, et non comme un noyau limbique.' },
        { type: 'sub', text: '3.3.4. Insula' },
        { type: 'para', text: 'Anatomie : l’insula est une région corticale profonde, longtemps peu étudiée en raison de sa position médiale, recouverte par les lobes frontal, pariétal et temporal. Elle est située en regard de la partie antérieure de la suture pariéto-squameuse, latérale aux ganglions de la base et à l’amygdale. Elle est connectée à l’amygdale, au cortex cingulaire, aux centres supérieurs du SNA, au thalamus et au cortex somato-sensoriel.' },
        { type: 'para', text: 'Physiologie : l’insula recueille des informations venant des viscères, de leur activité et de leurs dysfonctions, notamment viau nerf vague. Elle participe à la conscience intéroceptive des émotions et des réactions viscérales qui les accompagnent. Elle intervient dans la peur, la colère, la tristesse, la joie, les addictions et la conscience de soi.' },
        { type: 'para', text: 'Pathologie : l’insula est impliquée dans certaines douleurs chroniques, la fibromyalgie, la dépression et les difficultés à ressentir les tensions internes ou les déséquilibres neurovégétatifs.' },
        { type: 'sub', text: '3.3.5. Cortex cingulaire' },
        { type: 'para', text: 'Anatomie : le cortex cingulaire est situé à la face médiale des hémisphères cérébraux, au-dessus du corps calleux. Il fait partie des régions corticales les plus proches des autres structures limbiques.' },
        { type: 'para', text: 'Physiologie : il constitue une interface entre émotion, attention et cognition. Il participe à la perception des émotions et des sentiments d’autrui, à l’empathie et à l’attention portée aux autres. Il peut être décrit comme l’expression externe des états internes.' },
        { type: 'para', text: 'Pathologie : il est impliqué dans les troubles de l’humeur, l’anxiété, la dépression et certaines douleurs chroniques.' },
        { type: 'sub', text: '3.3.6. Corps mamillaires' },
        { type: 'para', text: 'Anatomie : les corps mamillaires sont pairs et symétriques, situés à l’extrémité ventrale du fornix. Ils sont proches des circuits hippocampiques.' },
        { type: 'para', text: 'Physiologie : ils contribuent à la mémorisation et à la consolidation de certaines dimensions émotionnelles de l’expérience.' },
        { type: 'para', text: 'Pathologie : leur atteinte ou leur atrophie peut entraîner des troubles de la mémoire, notamment dans certains contextes de carence vitaminique et d’alcoolisme chronique, comme dans le syndrome de Korsakoff.' },
        { type: 'sub', text: '3.3.7. Noyau accumbens' },
        { type: 'para', text: 'Anatomie : le noyau accumbens est pair et symétrique, situé en avant de l’amygdale, en regard du point pivot sphéno-squameux.' },
        { type: 'para', text: 'Physiologie : il est impliqué dans les circuits de la motivation et de la récompense. La dopamine y joue un rôle important dans le plaisir, l’élan vital, la découverte, l’innovation et l’engagement dans des projets.' },
        { type: 'para', text: 'Pathologie : sa dysfonction peut participer à la baisse de motivation, l’apathie, la perte de plaisir, la dépression, la boulimie, les troubles obsessionnels compulsifs et les addictions. Les substances addictives peuvent stimuler artificiellement la dopamine tout en augmentant progressivement le seuil nécessaire à l’effet recherché.' },
        { type: 'sub', text: '3.3.8. Voies olfactives et bulbe olfactif' },
        { type: 'para', text: 'Anatomie : le bulbe olfactif est une structure paire située sur la lame criblée de l’ethmoïde. Il est directement connecté aux réseaux limbiques, sans relais thalamique initial.' },
        { type: 'para', text: 'Physiologie : l’olfaction relie fortement les odeurs à la mémoire et aux émotions. Elle participe à l’identification de signaux de sécurité, de danger, d’attirance ou d’aversion. Les phéromones s’inscrivent également dans une dimension instinctive et relationnelle.' },
        { type: 'para', text: 'Pathologie : l’anosmie peut survenir après un traumatisme crânien, lorsque des fibrilles olfactives sont cisaillées au niveau de la lame criblée de l’ethmoïde.' },
        { type: 'sub', text: '3.3.9. Corps calleux' },
        { type: 'para', text: 'Anatomie : le corps calleux est la principale commissure reliant les deux hémisphères cérébraux. Il contient plusieurs centaines de millions de fibres de substance blanche. Il ne doit pas être présenté comme un noyau limbique, mais comme une structure de connexion interhémisphérique pouvant participer à la circulation des informations émotionnelles entre les deux hémisphères.' },
        { type: 'para', text: 'Physiologie : il coordonne et transfère des informations concernant la mémoire, l’apprentissage, la concentration intellectuelle, la vision et certaines dimensions émotionnelles.' },
        { type: 'para', text: 'Pathologie : sous stress important, une forme de déconnexion interhémisphérique peut être observée, avec tendance à l’inhibition ou à la difficulté de réaction face à une situation.' },
        { type: 'sub', text: '3.4. Diencéphale et axe hypothalamo-hypophysaire' },
        { type: 'para', text: 'Le diencéphale est une région médiane qui relie le tronc cérébral aux deux hémisphères cérébraux. Les ganglions de la base lui sont latéraux. Il ne fait pas partie du système limbique au sens strict, mais plusieurs de ses structures sont étroitement connectées aux réseaux limbiques, notamment le thalamus, l’hypothalamus, l’épithalamus et le subthalamus.' },
        { type: 'sub', text: '3.4.1. Thalamus' },
        { type: 'para', text: 'Anatomie : le thalamus est une structure paire située entre les deux hémisphères cérébraux. Il occupe une grande partie du diencéphale et comporte de nombreux noyaux connectés au cortex, aux autres structures du diencéphale, au tronc cérébral et aux circuits limbiques. Entre les deux thalamus se trouve le troisième ventricule.' },
        { type: 'para', text: 'Physiologie : le thalamus est un relais majeur des informations sensitives, sensorielles, limbiques et des ganglions de la base vers le cortex cérébral. Il relaie également la douleur provenant de la moelle spinale. Il agit comme un filtré, triant et sélectionnant les informations qui parviennent au cerveau, notamment pendant le sommeil.' },
        { type: 'para', text: 'Pathologie : très vascularisé, le thalamus peut être atteint lors d’AVC, de traumatismes crâniens, de maladies neurodégénératives ou de tumeurs. Les symptômes peuvent être moteurs, sensitifs, douloureux, cognitifs ou langagiers.' },
        { type: 'sub', text: '3.4.2. Hypothalamus' },
        { type: 'para', text: 'Anatomie : l’hypothalamus est situé sous le thalamus et au-dessus de l’hypophyse. Malgré sa petite taille, il possède une fonction centrale. Il est connecté à la post-hypophyse par la tige pituitaire, au cortex et aux réseaux limbiques.' },
        { type: 'para', text: 'Vascularisation : la double fonction hormonale et neurologique de l’hypothalamus nécessite une vascularisation développée. Celle-ci implique notamment la carotide interne et le système porte hypothalamo-hypophysaire, qui permet de transmettre à l’hypophyse des signaux hormonaux venant de l’hypothalamus sans dilution dans la circulation générale.' },
        { type: 'para', text: 'Physiologie : l’hypothalamus est un chef d’orchestre du SNA et du système hormonal. Il participe au contrôle de l’homéostasie. Il module les réactions émotionnelles en interaction avec l’amygdale et le cortex préfrontal. Lors de stress importants, il met en action l’axe neurologique sympathico-adrénalo-médullaire (SAM), puis l’axe hormonal hypothalamo-hypophyso-surrénalien (HHS).' },
        {
          type: 'xref',
          label: 'Voir la référence dans le chapitre 5',
          text: 'Mécanisme de stress',
          href: '/lecture/chapitre-5?xrefBack=%2Flecture%2Fchapitre-3%23p-section-3-organisation-anatomique-70&xrefBackLabel=Retour%20au%20chapitre%203#p-presentation-0',
        },
        { type: 'sub', text: '3.4.3. Hypophyse' },
        { type: 'para', text: 'L’hypophyse ne fait pas partie du diencéphale au sens strict, mais sa fonction et son origine embryologique sont indissociables de l’hypothalamus. Elle est logée dans la selle turcique du sphénoïde, au centre du crâne, et entourée par la dure-mère. Elle est formée de deux lobes : la post-hypophyse ou neurohypophyse, et l’antéhypophyse ou adénohypophyse.' },
        { type: 'para', text: 'Post-hypophyse : elle est constituée de cellules nerveuses en prolongement avec l’hypothalamus par la tige pituitaire. Elle libère notamment la vasopressine, ou hormone antidiurétique, et l’ocytocine, toutes deux synthétisées par l’hypothalamus.' },
        { type: 'para', text: 'Antéhypophyse : sous l’influence de l’hypothalamus, elle sécrète différentes hormones : ACTH pour la sécrétion de cortisol par le cortex surrénalien, GH, prolactine, FSH, LH, TSH, MSH et endorphines.' },
        { type: 'para', text: 'Pathologie : l’adénome hypophysaire est une lésion fréquente. Il s’agit d’une tumeur bénigne qui peut comprimer le chiasma optique et entraîner une hémianopsie uni- ou bilatérale. Son traitement peut être chirurgical, selon la taille et l’extension de l’adénome.' },
        { type: 'sub', text: '3.4.4. Épithalamus' },
        { type: 'para', text: 'L’épithalamus est situé à la partie postérieure du diencéphale. Il comprend l’épiphyse ou glande pinéale, l’habenula et la strie médullaire.' },
        { type: 'bullets', items: [
          'Épiphyse ou glande pinéale : elle synthétise la mélatonine à partir de la sérotonine et participe à la régulation des rythmes circadiens et saisonniers selon la luminosité solaire.',
          'Habenula : elle relie l’épiphyse au thalamus et intervient dans les circuits récompense/punition. Elle peut être altérée dans la dépression.',
          'Strie médullaire : elle relie le thalamus à l’habenula.',
        ]},
        { type: 'sub', text: '3.4.5. Subthalamus' },
        { type: 'para', text: 'Le subthalamus, ou corps de Luys, est une structure paire située à la partie antérieure du diencéphale. Il participe à la régulation des fonctions motrices somatiques.' },
        { type: 'sub', text: '3.5. Cortex ou télencéphale' },
        { type: 'para', text: 'Le cortex constitue la partie la plus développée du cerveau humain. Il est présent chez les mammifères supérieurs, mais il est particulièrement développé chez l’être humain, notamment au niveau du lobe frontal.' },
        { type: 'para', text: 'Anatomie : situé au-dessus des réseaux limbiques, le cortex est divisé en deux hémisphères cérébraux réunis par le corps calleux. Chaque hémisphère comprend plusieurs lobes : frontal, pariétal, temporal et occipital. La vascularisation est assurée notamment par la carotide interne et le tronc basilaire.' },
        { type: 'para', text: 'Physiologie : le cortex est le centre de nombreuses fonctions conscientes : perception, motricité volontaire, raison, abstraction, langage, analyse, créativité, décision et intelligence. Les cortex préfrontal et orbitofrontal exercent un contrôle sur les réponses émotionnelles en permettant la prise de recul, la sélection de réponses adaptées et la régulation de la peur ou de l’anxiété générées par l’amygdale.' },
        { type: 'para', text: 'Pathologie : dans le cadre de cet ouvrage, les cortex préfrontal et orbitofrontal sont surtout concernés par leur implication dans les troubles anxieux, les phobies et la dépression. Sous stress, ils peuvent être sollicités de manière excessive ou affaiblis selon le contexte.' },
      ],
    },
    {
      id: 'section-4-zones-reflexes',
      title: '4. Zones réflexes podales',
      blocks: [
        { type: 'para', text: 'Les passages relatifs aux zones réflexes sont volontairement regroupés dans cette dernière partie afin d’isoler clairement l’anatomie et la physiologie du traitement ROP. Cette organisation permet une lecture plus nette : le corps du chapitre expose les structures, leurs fonctions et leurs interactions ; la présente section rassemble les repères thérapeutiques.' },
        { type: 'sub', text: '4.1. Tronc cérébral, cervelet et ganglions de la base' },
        { type: 'bullets', items: [
          'Tronc cérébral : face plantaire médiale de la phalange distale du gros orteil, de l’articulation interphalangienne à la jonction diaphyse-tête.',
        ]},
        { type: 'figure', src: '/chapter-3/figures/figure-01.png', caption: 'Tronc cérébral (entre les deux pouces)', alt: 'Photo du repérage podal du tronc cérébral entre les deux pouces', orientation: 'portrait' },
        { type: 'bullets', items: [
          'Cervelet : l’action est envisagée par son innervation. Le ganglion cervical supérieur contrôle la vascularisation du tronc basilaire qui irrigue le cervelet et le tronc cérébral ; repère à la jonction diaphyse-tête médio-plantaire de C2 et C3.',
          'Ganglions de la base : principalement concentrés latéralement au mésencéphale ; repérage latéral à la jonction diaphyse-tête médiale, à hauteur de la grande scissure de la tente du cervelet.',
        ]},
        { type: 'sub', text: '4.2. Système limbique et réseaux émotionnels' },
        { type: 'bullets', items: [
          'Structures limbiques principales : amygdale, hippocampe, fornix, noyau accumbens et corps mamillaires sont recherchés latéralement aux ganglions de la base, au niveau de la diaphyse de la phalange distale du gros orteil. À la palpation, recherchér les zones les plus endurées.',
          'Insula : latérale aux structures limbiques principales.',
          'Bulbe olfactif : tête médiale plantaire de la phalange distale du gros orteil.',
          'Cortex cingulaire et corps calleux : bord médial plantaire de la phalange distale du gros orteil.',
        ]},
        { type: 'figure', src: '/chapter-3/figures/figure-02.png', caption: 'Amygdale du cerveau limbique (pouce gauche)', alt: 'Photo du repérage podal de l’amygdale du cerveau limbique', orientation: 'portrait' },
        { type: 'sub', text: '4.3. Diencéphale, hypophyse, vascularisation et dure-mère' },
        { type: 'bullets', items: [
          'Diencéphale : dans le même plan sagittal que le sinus droit, à la jonction de la faux du cerveau et de la tente du cervelet ; les deux repères se confondent à la jonction diaphyse-tête médiale.',
          'Hypophyse : jonction diaphyse-base médiale, en avant de la synchondrose sphéno-basilaire.',
          'Vascularisation : chaîne ganglionnaire cervicale et sinus carotidien.',
          'Dure-mère crânienne : se reporter au livre Réflexothérapie occipito-podale et système neuro-méningé, Elsevier Masson, page 85 et page 109.',
        ]},
        { type: 'bullets', items: [
          'Faux du cerveau et faux du cervelet : mêmes repères que tronc cérébral et bulbe olfactif.',
          'Tente du cervelet : jonction diaphyse-tête.',
          'Innervation : nerfs trijumeau V, vague X et hypoglosse XII.',
          'Ganglions cervicaux : ganglion cervical supérieur C2-C3 et ganglion cervical inférieur C7-T1.',
        ]},
        { type: 'figure', src: '/chapter-3/figures/figure-05.png', caption: 'Diencéphale (pouce gauche)', alt: 'Photo du repérage podal du diencéphale', orientation: 'portrait' },
        { type: 'figure', src: '/chapter-3/figures/figure-04.png', caption: 'Sinus et glomus carotidien Index Gauche', alt: 'Photo du repérage podal du sinus et du glomus carotidien à l’index gauche', orientation: 'landscape' },
        { type: 'figure', src: '/chapter-3/figures/figure-03.png', caption: 'Nerf vague X dans le foramen jugulaire', alt: 'Photo du repérage podal du nerf vague X dans le foramen jugulaire', orientation: 'portrait' },
        { type: 'sub', text: '4.4. Cortex : absence de zone réflexe directe et action indirecte' },
        { type: 'para', text: 'Il n’y a pas de zone réflexe directe du cortex, partie cognitive du cerveau, pour deux raisons :' },
        { type: 'bullets', items: [
          'la ROP fait appel à l’activité réflexe ;',
          'le cerveau n’a pas de sensibilité propre comparable à celle des tissus périphériques ; il n’y a donc pas de boucle réflexe directe du cortex.',
        ]},
        { type: 'para', text: 'L’action sur le cortex est envisagée indirectement par les zones réflexes du MRP et par l’innervation du système vasculaire, notamment carotidien et vertébral.' },
        { type: 'bullets', items: [
          'MRP : action sur les os de la voûte crânienne, leurs sutures, les membranes intracrâniennes et le liquide cérébro-spinal. Cette action est considérée comme ayant un effet sur les conditions mécaniques et liquidiennes autour du cortex, sans pouvoir être objectivée de façon directe.',
          'Os de la voûte : face dorsale des trois phalanges des quatre derniers orteils et de la phalange distale du gros orteil.',
        ]},
        { type: 'bullets', items: [
          'Chaîne ganglionnaire cervicale : innervation de l’artère vertébrale et de la carotide.',
          'Artère carotide interne dans le sinus caverneux : face plantaire médiale de la diaphyse de la deuxième phalange du deuxième orteil.',
        ]},
        { type: 'bullets', items: [
          'Circulation du liquide cérébro-spinal : système veineux, foramens jugulaires, membranes intracrâniennes et spinales, aspiration veineuse et cérébro-spinale liée à l’inspiration, technique de compression du quatrième ventricule, synchronisation synchondrose sphéno-basilaire (SSB) - deuxième vertèbre sacrée S2.',
        ]},
        { type: 'figure', src: '/chapter-3/figures/figure-06.png', caption: 'Technique compression du IVème ventricule', alt: 'Photo de la technique de compression du quatrième ventricule', orientation: 'landscape' },
        { type: 'figure', src: '/chapter-3/figures/figure-07.png', caption: 'Technique de synchronisation SSB-S2', alt: 'Photo de la technique de synchronisation SSB-S2', orientation: 'portrait' },
      ],
    },
  ],
  slides: {
    url: '/chapter-3/Chapter3 Slides FR.pdf',
    label: 'Diapositives',
    description: 'Synthèse visuelle du chapitre 3.',
  },
}
