// Chapter 2 content — Spanish
// Source: public/chapter-2/Chapter_2_Treatment_by_ROP_Spanish.docx

import type { Chapter } from './types'

export type { Block, Section, Chapter } from './types'

export const chapter2Es: Chapter = {
  slug: "chapter-2",
  number: "2",
  title: "Tratamiento con Reflexoterapia Occipito-Podal (ROP)",
  sections: [
    {
      id: "technique",
      title: "Técnica",
      blocks: [
        { type: "para", text: "A continuación se presentan varios principios que guían el tratamiento con Reflexoterapia Occipito-Podal (ROP)." },
        { type: "sub", text: "Técnica manual" },
        { type: "para", text: "La técnica es exclusivamente manual, realizada con la yema del pulgar o con la articulación interfalángica proximal del dedo índice, sin utilizar aceite ni crema." },
        { type: "sub", text: "Presión" },
        { type: "para", text: "La presión se aplica sobre las zonas reflejas con el objetivo de estimular los mecanorreceptores situados en la capa epidérmico-dérmica de las zonas occipitales y plantares." },
        { type: "para", text: "Estos mecanorreceptores son los siguientes:" },
        { type: "leadBullets", items: [
          { label: "Corpúsculos de Meissner", text: "Los corpúsculos de Meissner están alojados en las papilas dérmicas, es decir, en las proyecciones ascendentes de la dermis hacia la epidermis. Son sensibles a una presión fina, no dolorosa, dirigida a la sensibilidad epicrítica. Se encuentran preferentemente en la piel glabra, en particular en las plantas de los pies, las palmas de las manos, los labios y los órganos genitales." },
          { label: "Discos de Merkel", text: "Los discos de Merkel se sitúan en la base de la epidermis, inmediatamente por encima de la dermis. Son sensibles a una presión suave aplicada sobre la piel." },
        ]},
        { type: "para", text: "En cuanto la presión manual deforma la capa epidérmico-dérmica —identificada por la sensación de una tensión cutánea \"como de tambor\" que empuja de vuelta contra el dedo—, los corpúsculos de Meissner y los discos de Merkel generan potenciales de acción que viajan a través de las vías sensitivas del sistema lemniscal." },
        { type: "lead", label: "El sistema lemniscal", text: "El sistema lemniscal es un haz de fibras aferentes de la médula espinal. En nuestra técnica se dirige deliberadamente a este sistema por sus propiedades:" },
        { type: "bullets", items: [
          "transmite la sensibilidad táctil fina, no dolorosa;",
          "asegura una transmisión rápida y precisa de los impulsos nerviosos que transporta;",
          "presenta una rica organización somatotópica en el cerebro;",
          "tiene una acción analgésica: modula el dolor transmitido por el sistema extralemniscal. Esta propiedad analgésica se explica por la teoría del control de compuerta: los impulsos nerviosos que viajan por el sistema lemniscal alcanzan con mayor rapidez el asta posterior de la médula espinal y contribuyen a cerrar la compuerta a los impulsos dolorosos más lentos.",
        ]},
        { type: "sub", text: "Relevancia en ROP" },
        { type: "para", text: "Durante el tratamiento reflejo deben evitarse la presión intensa y la trituración tisular. Cuanto más fuerte se presiona, más se sienten los propios dedos, menos se perciben los puntos de referencia óseos que guían la búsqueda de las zonas reflejas, y más difícil resulta leer dichas zonas." },
        { type: "para", text: "El objetivo de restaurar una buena calidad tisular refleja el respeto que concedemos al organismo. No se trata de forzar al organismo, sino de invitarlo suavemente a responder. Incluso un tratamiento bien realizado constituye un factor de estrés —positivo, sin duda—, pero debe tener en cuenta la capacidad de autocorrección del individuo." },
        { type: "sub", text: "Las tres fases del tratamiento manual" },
        { type: "leadBullets", items: [
          { label: "1. Fase diagnóstica textural", text: "Esta fase consiste en buscar zonas reflejas caracterizadas por una modificación de la textura de la piel occipital y plantar: rugosidad, densificación, pérdida de deslizamiento o sensación de cristales. Estos hallazgos deben confirmar el diagnóstico obtenido al final de la exploración clínica." },
          { label: "2. Fase terapéutica", text: "La presión es fina y no dolorosa, dirigida a la sensibilidad epicrítica; un dolor agudo indicaría una estimulación excesiva. La maniobra manual consiste en movilizar la capa epidérmico-dérmica con el fin de estimular los mecanorreceptores en el origen del sistema lemniscal, y aportar una aferencia sensorial correctiva a los centros nerviosos superiores implicados en la regulación de las regiones disfuncionales del cuerpo." },
          { label: "3. La fase de \"dejar ser\"", text: "Después de la estimulación, el organismo necesita tiempo para integrar y estabilizar las adaptaciones neurovegetativas (autonómicas), vasculares y tisulares. No es la estimulación de las zonas reflejas en sí misma la que produce el efecto terapéutico, sino la respuesta del organismo — mayor flexibilidad y deslizamiento, y una reducción de la sensibilidad." },
        ]},
        { type: "para", text: "Este período de latencia de unos segundos corresponde al tiempo necesario para que el organismo inicie el bucle reflejo terapéutico responsable de deconstruir el bucle reflejo patológico implicado en la disfunción." },
        { type: "para", text: "La capacidad y la calidad de respuesta del organismo dependen de su vitalidad y de sus capacidades adaptativo-compensatorias, en relación con la fase del síndrome general de adaptación en la que evoluciona la enfermedad: alarma, adaptación, resistencia o agotamiento." },
      ],
    },
    {
      id: "modalites",
      title: "Modalidades de tratamiento",
      blocks: [
        { type: "leadBullets", items: [
          { label: "Duración", text: "La eficacia del tratamiento no está relacionada con la duración de la sesión." },
          { label: "Frecuencia", text: "Un intervalo de tres semanas entre sesiones corresponde al tiempo necesario para que el organismo integre el tratamiento. Los tratamientos demasiado próximos entre sí no dejan tiempo suficiente para que los procesos neurovasculares y estructurales sostengan la regulación fisiológica de las vísceras y estructuras disfuncionales." },
        ]},
        { type: "para", text: "Para la mayoría de las indicaciones, tres sesiones son suficientes para obtener una mejoría satisfactoria, con la posibilidad de volver a ver al paciente seis meses después si fuera necesario." },
        { type: "para", text: "Si no se observa una mejoría significativa tras tres sesiones, debe reconsiderarse el diagnóstico y, si procede, remitir de nuevo al paciente a su médico." },
        { type: "para", text: "Las afecciones crónicas requieren un seguimiento más regular." },
      ],
    },
    {
      id: "hierarchisation",
      title: "Jerarquía del tratamiento",
      blocks: [
        { type: "para", text: "No existe un protocolo inmutable: un protocolo de ese tipo contradiría el concepto holístico. Son las pruebas las que determinan la prioridad." },
        { type: "para", text: "No obstante, pueden proponerse grandes líneas directrices de tratamiento, pero no deben utilizarse para encerrar al paciente en un protocolo rígido desconectado de la realidad clínica." },
        { type: "leadBullets", items: [
          { label: "1. Secuelas de traumatismo, cirugía o infección", text: "Los síntomas comunicados espontáneamente por el paciente y aparecidos después de un traumatismo, una cirugía o una infección coinciden generalmente con la exploración clínica. Estos síntomas conservan su prioridad." },
          { label: "2. Anamnesis y pruebas de escucha global/local", text: "En ausencia de traumatismo, antecedentes quirúrgicos o infección referidos espontáneamente, son la anamnesis, la exploración clínica y las pruebas de escucha global y local las que nos conducen a la fijación dominante. A través de mecanismos de adaptación-compensación y posteriormente de descompensación, esta fijación puede haber generado síntomas a veces situados lejos de la propia fijación." },
          { label: "3. Escucha emocional", text: "Puede ser necesario buscar antiguos traumatismos físicos o psicoemocionales que hayan sido olvidados, reprimidos en determinadas capas del inconsciente o incluso suprimidos deliberadamente. La escucha tisular, seguida de la escucha emocional, puede ayudar a revelar acontecimientos significativos —y especialmente negativos— codificados en la amígdala y el hipocampo del sistema límbico." },
          { label: "4. Mecanismo del estrés", text: "Una fijación tisular local —o síndrome locorregional— debe situarse siempre en su contexto general, es decir, el síndrome general de adaptación, que en realidad refleja la historia del individuo." },
        ]},
        { type: "sub", text: "Zonas reflejas occipitales y plantares" },
        { type: "rop", body: [
          "1. Zonas reflejas occipitales",
          "2. Síndrome general de adaptación — apoyar la regulación neurovegetativa y la adaptación general antes de abordar la disfunción local:",
          "· MRP: occipucio–C1–C2, nervio trigémino V, nervio vago X y nervio hipogloso XII, hoz del cerebro y tienda del cerebelo, segunda vértebra sacra S2, base y bóveda craneales",
          "· Circulación del líquido cefalorraquídeo: sistema venoso (foramen yugular, respiración profunda), compresión del cuarto ventrículo, sincronización SSB–S2",
          "· Diencéfalo, tronco encefálico, hipófisis",
          "· Nervio vago — vísceras del territorio cérvico-toraco-abdominal: foramen magno, foramen yugular, seno carotídeo, hiato esofágico",
          "· Sistema parasimpático pélvico — vísceras pélvicas y parte distal del colon",
          "· Columna vertebral, articulaciones costotransversas, inervación simpática (cadena ganglionar paravertebral torácica)",
          "· Plexo prevertebral",
        ]},
        { type: "rop", body: [
          "3. Síndrome locorregional — abordar los bucles mecánicos y neurovegetativos relacionados con la región sintomática:",
          "· Plexos y nervios del sistema nervioso somático (relaciones viscerosomáticas)",
          "· Sistema visceral",
          "· Cavidad abdominal o pélvica, según el sistema visceral implicado",
        ]},
        { type: "rop", body: [
          "4. Sistema límbico — integrar las dimensiones del estrés, de la emoción y de la memoria corporal que pueden mantener los bucles neurovegetativos y tisulares:",
          "· Amígdala, hipocampo, ínsula",
          "· Equilibrio cerebro límbico–víscera disfuncional: escucha-inducción, con un pulgar colocado sobre la víscera disfuncional dominante y el otro pulgar sobre la zona del cerebro límbico",
        ]},
      ],
    },
    {
      id: "exemple-clinique",
      title: "Ejemplo",
      blocks: [
        { type: "sub", text: "Lumbociatalgia izquierda aparecida unos meses después del parto en la señora X, en la treintena" },
        { type: "sub", text: "Anamnesis" },
        { type: "bullets", items: [
          "Sin antecedentes traumáticos conocidos;",
          "los síntomas lumbociáticos se agravan durante la menstruación;",
          "la incontinencia urinaria de esfuerzo se revela durante la anamnesis;",
          "el parto fue largo — paciente primípara;",
          "la exploración ginecológica es normal. La radiografía muestra un ligero estrechamiento en L5–S1 sin desplazamiento de la raíz nerviosa S1;",
          "el dolor le afecta emocionalmente porque trabaja por cuenta propia y desea reincorporarse rápidamente a su actividad laboral.",
        ]},
        { type: "sub", text: "Pruebas" },
        { type: "bullets", items: [
          "Las pruebas de escucha global en bipedestación y sedestación muestran una flexión anterior del tronco y una flexión lateral baja izquierda.",
          "Las pruebas vertebrales muestran una ligera pérdida de movilidad izquierda en los niveles vertebrales L2–L3 y L5–S1, así como una fijación izquierda de la articulación sacroilíaca y del cóccix.",
          "Las pruebas de escucha local en decúbito supino muestran una mejora de la prueba de Lasègue completada cuando la mano de escucha colocada sobre la sínfisis púbica se lleva ligeramente hacia la izquierda y en profundidad hacia la región cérvico-ístmica del útero.",
          "En decúbito lateral izquierdo, los dedos del terapeuta, colocados en la región abdominal inferior, perciben resistencia a la movilidad uterina.",
          "La prueba de la cadera izquierda muestra pérdida de rotación medial.",
        ]},
        { type: "sub", text: "Mecanismo anatomofisiopatológico" },
        { type: "lead", label: "Síndrome locorregional", text: "Dentro del modelo ROP, la ciática izquierda se relaciona con una malposición del útero, desviado hacia la izquierda por la tensión del ligamento uterosacro izquierdo. Como consecuencia, se observa:" },
        { type: "bullets", items: [
          "fijación parcial de la articulación sacroilíaca izquierda;",
          "fibrosis del músculo piriforme izquierdo, que interfiere con el nervio ciático;",
          "desviación del útero, que también tracciona la vejiga y el sacro;",
          "fijación sacrococcígea, que conduce a una pérdida de elasticidad y contractilidad del suelo pélvico.",
        ]},
        { type: "lead", label: "Síndrome general", text: "" },
        { type: "bullets", items: [
          "El ciclo menstrual está bajo el control hormonal y neurovegetativo de los centros diencefálicos.",
          "La fijación sacrococcígea pone en tensión la duramadre espinal y, a través de ella, el Mecanismo Respiratorio Primario — MRP.",
          "El sistema porta drena la sangre venosa de la pelvis. Cualquier fijación hepática enlentece el retorno venoso de la pelvis menor.",
          "El riñón izquierdo también contribuye al retorno venoso de la pelvis menor.",
          "En su nueva vida como madre, su sistema límbico se activa por la ansiedad, por la ciática y por la reincorporación a la actividad profesional alterada por la maternidad.",
        ]},
        { type: "sub", text: "Tratamiento ROP" },
        { type: "rop", body: [
          "1. Zonas reflejas occipitales",
          "2. Síndrome general de adaptación: MRP, Diencéfalo, Tronco encefálico, Hipófisis, Glándulas suprarrenales, Columna vertebral, Hígado, Riñón izquierdo",
          "3. Síndrome locorregional: Región cérvico-ístmica del útero, Músculo piriforme, Ligamentos sacrotuberoso y sacroespinoso, Nervio pudendo, Articulaciones sacrococcígea y sacroilíaca, Plexos sacro y ciático izquierdos",
          "4. Sistema límbico: Amígdala, Hipocampo, Ínsula",
        ]},
      ],
    },
    {
      id: "contre-indications",
      title: "Contraindicaciones",
      blocks: [
        { type: "para", text: "ROP pertenece a un marco de cuidados funcionales. Toda sospecha de enfermedad orgánica o la presencia de un signo de alarma requiere una valoración médica." },
        { type: "para", text: "Síntomas que pueden parecer inofensivos pueden ocultar en ocasiones una enfermedad grave. Es nuestra responsabilidad reconocer los signos que deben llevarnos a no intervenir, de acuerdo con el principio primum non nocere — ante todo, no hacer daño." },
        { type: "para", text: "Detallaremos las contraindicaciones para cada víscera, pero los siguientes síntomas ya deben suscitar sospecha:" },
        { type: "bullets", items: [
          "dolor no mecánico, agravado durante la primera parte de la noche;",
          "dolor torácico atípico, disnea, malestar;",
          "sangre en la orina o en las heces;",
          "fiebre o enfermedad infecciosa;",
          "pérdida de peso inexplicada;",
          "riesgo de migración de un trombo;",
          "palidez y fatiga marcada;",
          "déficit neurológico: trastornos esfinterianos o alteraciones sensitivas progresivas;",
          "ansiedad o miedo a morir;",
          "admitir la propia impotencia ante un caso clínico que no se comprende.",
        ]},
        { type: "para", text: "Es importante conocer las presentaciones de enfermedades graves, debido al riesgo de retrasar el diagnóstico médico, especialmente cuando los pacientes nos consultan como profesionales de primera línea sin valoración médica previa." },
        { type: "para", text: "ROP no debe sustituir un tratamiento médico adecuado. No obstante, conserva su lugar como terapia integrativa junto a la medicina convencional, ayudando a reducir las consecuencias funcionales de la enfermedad o los efectos indeseables pero a veces inevitables de tratamientos farmacológicos intensivos, en particular en oncología, o simplemente a acompañar a los pacientes en su bienestar." },
        { type: "para", text: "Después de una cirugía abdominal, una intervención basada en reflejos puede reducir los espasmos de la musculatura lisa de las vísceras, apoyar la restauración del tránsito intestinal y disminuir la necesidad de medicación analgésica y sintomática. Al actuar a distancia a través de vías reflejas, lejos de la víscera disfuncional, se limita el riesgo de efectos iatrogénicos: esto aporta seguridad tanto al paciente como al terapeuta." },
      ],
    },
    {
      id: "indications",
      title: "Indicaciones",
      blocks: [
        { type: "para", text: "Las indicaciones se basan en la anamnesis, las pruebas, la coherencia de las zonas reflejas y la jerarquía del terreno." },
        { type: "para", text: "Las patologías funcionales constituyen el campo principal de las llamadas terapias integrativas. Son la consecuencia de un desequilibrio previo del sistema neurovascular, anterior a la enfermedad manifiesta. Su característica particular es que son reversibles, extracelulares y poco —o nada— detectables mediante radiografía, tomografía computarizada o resonancia magnética, porque la alteración anatómica aún no ha comenzado." },
        { type: "para", text: "Mientras la vitalidad del organismo sea capaz de adaptación-compensación, la salud se preserva. Nuestro papel consiste en ayudar al paciente a mejorar su vitalidad para restaurar el equilibrio fisiológico." },
        { type: "para", text: "Detallaremos los síntomas funcionales para cada víscera. Los tipos más comunes de síntomas funcionales encontrados son:" },
        { type: "bullets", items: [
          "dolor musculoesquelético;",
          "secuelas de traumatismos osteomusculoarticulares;",
          "secuelas de traumatismos de nervios espinales y craneales;",
          "disfunciones viscerales relacionadas con fijaciones tisulares y bucles neurovegetativos;",
          "trastornos viscerosomáticos y somatoviscerales;",
          "trastornos de la regulación neurovegetativa;",
          "estrés emocional y ansiedad.",
        ]},
      ],
    },
    {
      id: "actions",
      title: "Efectos del tratamiento reflexoterapéutico",
      blocks: [
        { type: "para", text: "Como ya se indicó en la introducción, a menudo observamos resultados clínicos que aún no podemos medir objetivamente. Nuestra acción tiene efectos tanto locales como generales:" },
        { type: "bullets", items: [
          "acción analgésica;",
          "reequilibrio neurovegetativo: desplazamiento hacia signos parasimpáticos — calma, bostezos, somnolencia, relajación marcada, necesidad de descanso;",
          "mejora del tránsito intestinal, de la diuresis y de las sensaciones viscerales;",
          "reducción de las fijaciones vertebrales a nivel metamérico de la víscera — relación viscerosomática.",
        ]},
      ],
    },
    {
      id: "reactions",
      title: "Reacciones al tratamiento",
      blocks: [
        { type: "leadBullets", items: [
          { label: "Reacciones inmediatas", text: "Relajación." },
          { label: "Reacciones en las 24 a 48 horas siguientes", text: "Dolor muscular tardío o fatigabilidad leve; sueños, emergencia de recuerdos." },
          { label: "Reacciones en las semanas siguientes", text: "Se espera que la recuperación de la vitalidad actúe no solo localmente, a nivel visceroglandular, sino también sobre la regulación hormonal y bioquímica, sobre la inmunidad local y general, y sobre la psique, aunque estos efectos no puedan necesariamente medirse objetivamente." },
        ]},
        { type: "para", text: "Estas reacciones transitorias son beneficiosas e incluso deseables, y son específicas de cada individuo. Pueden reflejar la adaptación del organismo a un factor de estrés ciertamente positivo, pero desconocido para él." },
        { type: "para", text: "Si las reacciones son intensas, duran más de 72 horas o se acompañan de signos preocupantes, la situación debe reevaluarse y el paciente debe ser remitido." },
        { type: "para", text: "Debe respetarse el intervalo de tres a cuatro semanas para permitir que el organismo integre los cambios antes de emprender la siguiente sesión." },
      ],
    },
    {
      id: "conseils",
      title: "Consejos",
      blocks: [
        { type: "para", text: "\"Antes de intentar curar a alguien, pregúntale si está dispuesto a renunciar a aquello que lo enfermó.\" — atribuido tradicionalmente a Hipócrates" },
        { type: "para", text: "Incluso el mejor tratamiento no puede garantizar una mejoría significativa y duradera si no va acompañado de consejos esenciales destinados a prolongar el efecto del tratamiento." },
        { type: "para", text: "Estos consejos se basan con mayor frecuencia en el sentido común:" },
        { type: "bullets", items: [
          "reposo relativo — evitar la sobrecarga física el día del tratamiento;",
          "alimentación saludable;",
          "hidratación adecuada;",
          "actividad física regular;",
          "convertirse en participante activo de la propia salud;",
          "mantener pensamientos positivos;",
          "tener una vida social plena, tanto personal como profesional;",
          "registrar los cambios: dolor de 0 a 10, sueño, tránsito intestinal, energía;",
          "volver con estos elementos para evaluar el efecto de forma más objetiva y ajustar la jerarquía del tratamiento.",
        ]},
      ],
    },
  ],
  slides: {
    url: '/chapter-2/Chapter2 - Slides de synthese ES.pdf',
    label: 'Diapositivas',
    description: 'Síntesis visual del capítulo — técnica, modalidades, jerarquía del tratamiento e indicaciones de la R.O.P.',
  },
  revisionSheet: {
    src: '/chapter-2/Chap2 - Fiche de revision.png',
    alt: 'Ficha de revisión — Capítulo 2, Tratamiento con R.O.P.',
    caption: 'Ficha de revisión — Capítulo 2 · Tratamiento con R.O.P.',
  },
}
