// Chapitre 1 — Généralités
// Source : public/chapter-1/Chapitre 1 Généralités.docx (Guy Boitout)

import type { Chapter } from './types'

export const chapter1Fr: Chapter = {
  slug: 'chapter-1',
  number: '1',
  title: 'Généralités',
  sections: [
    {
      id: 'intention',
      title: 'Intention du chapitre',
      blocks: [
        { type: 'para', text: 'Ce premier chapitre pose un cadre biomécanique et neurophysiologique utile au praticien.' },
        { type: 'para', text: 'La fonction viscérale dépend de la biochimie et de l’innervation, mais aussi de la capacité des organes à se déformer, à se mobiliser et à glisser les uns par rapport aux autres.' },
        { type: 'para', text: 'Lorsque cette liberté diminue (traumatisme, infection, chirurgie, stress), les tissus solidaires (fascias, structures neuro-vasculaires, appareil musculo-squelettique) s’adaptent et compensent.' },
        { type: 'para', text: 'Dans certains cas, ces compensations peuvent contribuer à des symptômes à distance, selon une logique de chaînes mécaniques et neurovégétatives utilisée en clinique.' },
      ],
    },
    {
      id: 'mobilite-viscerale',
      title: 'Mobilité viscérale : définitions et moteurs',
      blocks: [
        { type: 'para', text: 'On distinguera ici :' },
        { type: 'bullets', items: [
          'Mobilité : déplacement “subi” ou “induit” par les mouvements du corps et des cavités (respiration, marche, efforts, posture).',
          'Motilité : activité motrice intrinsèque de l’organe (au sens large), modulée par le système nerveux autonome et l’état tissulaire.',
        ]},
        { type: 'para', text: 'La mobilité viscérale est rendue possible par quatre grands déterminants (moteurs et modulateurs).' },
        { type: 'bullets', items: [
          'le système nerveux somatique (mouvements actifs du corps) ;',
          'le système nerveux autonome (mouvements automatiques viscéraux) ;',
          'la motilité (activité intrinsèque tissulaire) ;',
          'les biorythmes (variations cycliques de tonus, sécrétions, vascularisation).',
        ]},
        { type: 'sub', text: 'Système nerveux somatique : la mobilité “passive” par le mouvement' },
        { type: 'para', text: 'Les mouvements actifs commandés par le système somatique — marcher, courir, danser, mobiliser le tronc — imposent aux viscères des déplacements et des déformations.' },
        { type: 'para', text: 'Inversement, après une chirurgie abdominale, la douleur, les adhérences et les fixations peuvent limiter les amplitudes et modifier la cinématique globale.' },
        { type: 'para', text: 'Le diaphragme est un moteur majeur du glissement viscéral via l’alternance inspiration/expiration.' },
        { type: 'para', text: 'Cette alternance mobilise de façon répétée les viscères thoraciques et abdominaux (≈ 21 000 cycles respiratoires/24 h, ordre de grandeur).' },
        { type: 'para', text: 'L’activité physique régulière entretient ces mobilisations.' },
        { type: 'para', text: 'Elle stimule la ventilation, la circulation et le transit, et limite certains effets de l’inactivité (ralentissement cardio-pulmonaire, stase digestive, etc.).' },
        { type: 'sub', text: 'Système nerveux autonome : la mobilité “automatique”' },
        { type: 'para', text: 'Sous la commande de centres supérieurs (diencéphale, tronc cérébral) et via les voies sympathique et parasympathique, le SNA régule des fonctions automatiques : respiration, rythme cardiaque, péristaltisme, tonus vasculaire, sécrétions.' },
        { type: 'leadBullets', items: [
          { label: 'Mouvement respiratoire', text: 'le diaphragme module la mobilité viscérale et les gradients de pression entre cavités.' },
          { label: 'Mouvement cardiaque', text: 'à raison d’environ 100 000 battements/24 h (ordre de grandeur), les mouvements cardiaques induisent des contraintes mécaniques locales dans le thorax.' },
          { label: 'Péristaltisme', text: 'le transit dépend de réseaux neuro-entériques et du SNA.' },
        ]},
        { type: 'para', text: 'Ces contraintes peuvent se répercuter sur les structures adjacentes (poumons, médiastin, œsophage) et, indirectement, sur la zone diaphragmatique.' },
        { type: 'para', text: 'Il peut être modulé par l’état émotionnel, la douleur, l’inflammation, l’alimentation et les rythmes circadiens.' },
        { type: 'sub', text: 'Motilité : mouvement intrinsèque et lecture clinique' },
        { type: 'para', text: 'La motilité désigne ici l’activité propre de l’organe : micro-mouvements, variations de tension, de volume et de vascularisation (au sens large).' },
        { type: 'para', text: 'Sur le plan clinique, le praticien recherche moins une “mesure” instrumentale qu’une cohérence de comportement tissulaire : qualité d’élasticité, direction de préférence, retour, symétrie, capacité d’adaptation.' },
        { type: 'para', text: 'Dans l’approche ROP (Réflexo-Occipito-Podale), cette “motilité” est appréciée via des tests manuels codifiés et des réponses réflexes utilisées dans la méthode.' },
        { type: 'para', text: 'Le but est d’identifier des restrictions de mobilité/motilité associées à des chaînes fasciales et neuro-végétatives, puis de chercher une normalisation clinique.' },
        { type: 'sub', text: 'Biorythmes : variations cycliques utiles au diagnostic' },
        { type: 'para', text: 'De nombreux paramètres viscéraux varient selon des rythmes (circadien, ultradien, cycles digestifs, cycles hormonaux).' },
        { type: 'para', text: 'Pour le praticien, cela impose :' },
        { type: 'bullets', items: [
          'de replacer le symptôme dans son contexte temporel (moment de la journée, après repas, après effort, cycle menstruel, etc.) ;',
          'de distinguer un trouble plutôt “réactif” (fatigue, stress, surcharge) d’un trouble plus installé (inflammation, fixations, ptoses), comme repère clinique.',
        ]},
      ],
    },
    {
      id: 'mrp',
      title: 'Parenthèse : théorie crânienne et MRP',
      blocks: [
        { type: 'para', text: 'Certaines écoles décrivent une dynamique de circulation du liquide cérébro-spinal associée à un mécanisme respiratoire primaire (MRP).' },
        { type: 'para', text: 'Dans un livre pour praticiens, il est utile de préciser que :' },
        { type: 'bullets', items: [
          'l’existence et la description fine de ce mécanisme sont discutées selon les référentiels ;',
          'cliniquement, l’enjeu pratique est la relation entre respiration, pressions, retour veineux/lymphatique, et adaptabilité tissulaire.',
        ]},
      ],
    },
    {
      id: 'articulations-viscerales',
      title: '“Articulations” viscérales : surfaces, glissement, moyens d’union, innervation',
      blocks: [
        { type: 'para', text: 'On peut modéliser les viscères comme des structures suspendues, en interaction mécanique permanente avec leur environnement.' },
        { type: 'para', text: 'Quatre éléments sont indispensables au glissement et à l’adaptation :' },
        { type: 'bullets', items: [
          'Surfaces de contact et séreuses.',
          'Interstitium et continuités fasciales.',
          'Moyens d’union (ligaments, mésos, omentums).',
          'Innervation (sensibilité viscérale, pariétale, autonomique).',
        ]},
        { type: 'sub', text: 'Séreuses : glissement et pressions' },
        { type: 'para', text: 'Les séreuses (plèvre, péricarde, péritoine) permettent un glissement à faible friction et participent aux jeux de pression entre cavités.' },
        { type: 'para', text: 'Elles contribuent aussi à certaines douleurs projetées lorsque le feuillet pariétal est sollicité (sensibilité plus fine).' },
        { type: 'sub', text: 'Interstitium : continuité tissulaire et capacité de déformation' },
        { type: 'para', text: 'Le terme interstitium renvoie ici, au sens clinique, à l’idée d’un continuum micro-fibrillaire entre les tissus (peau, fascia, muscle, viscères, os).' },
        { type: 'para', text: 'La notion pratique : déformation et glissement sont possibles parce que les fibres (notamment collagéniques) s’organisent en réseau tridimensionnel, permettant des changements de direction et des adaptations aux contraintes.' },
        { type: 'sub', text: 'Moyens d’union : ligaments, mésos, omentums' },
        { type: 'para', text: 'Les moyens d’union viscéraux ne sont pas comparables, en solidité, aux ligaments ostéo-articulaires.' },
        { type: 'para', text: 'Ils contribuent néanmoins à la suspension, à la répartition des contraintes de pesanteur, et à l’organisation des trajets vasculo-nerveux.' },
        { type: 'bullets', items: [
          'Ligaments (ex. ligament coronaire / suspenseur du foie).',
          'Mésos : replis séreux du tube digestif, rôle de passage vasculo-nerveux/lymphatique.',
          'Omentums : replis péritonéaux entre deux éléments digestifs, rôle vasculo-nerveux et immunitaire.',
          'Petit omentum : ligament hépatogastrique + hépato-duodénal, contenant notamment les éléments hépato-biliaires.',
          'Foramen omental  : communication anatomique entre espaces péritonéaux.',
        ]},
        { type: 'sub', text: 'Innervation : douleur viscérale, douleur pariétale, douleur projetée' },
        { type: 'para', text: 'La douleur viscérale est souvent mal localisée, profonde, parfois associée à des nausées ou une réaction végétative.' },
        { type: 'para', text: 'La douleur pariétale (péritoine pariétal, plèvre pariétale) est en général plus précise et plus “coupante”.' },
        { type: 'para', text: 'La douleur projetée s’explique par des convergences médullaires entre afférences viscérales et somatiques : un même segment spinal peut recevoir des informations du dermatome, myotome, viscérotome, angiotope, sclérotome.' },
        { type: 'para', text: 'Le Dr Jarricot a décrit ces territoires et leurs correspondances cliniques.' },
      ],
    },
    {
      id: 'securite',
      title: 'Encadré sécurité : ne pas passer à côté d’une pathologie organique',
      blocks: [
        { type: 'para', text: 'Un trouble fonctionnel et une dysfonction de mobilité peuvent coexister avec une pathologie organique.' },
        { type: 'para', text: 'Le praticien doit être attentif aux signes d’alerte et orienter vers un avis médical si nécessaire.' },
        { type: 'bullets', items: [
          'douleur inhabituelle, progressive, non mécanique, notamment nocturne ;',
          'fièvre, amaigrissement, fatigue inexpliquée ;',
          'vomissements persistants, rectorragies/méléna, hématurie ;',
          'douleur thoracique, dyspnée, malaise ;',
          'déficit neurologique, troubles sphinctériens.',
        ]},
      ],
    },
    {
      id: 'perte-de-mobilite',
      title: 'Quand la mobilité se perd : adhérences, ptoses, spasmes',
      blocks: [
        { type: 'para', text: 'Les pertes de glissement et de compliance se traduisent classiquement par trois familles de phénomènes (souvent intriqués).' },
        { type: 'sub', text: 'Adhérences et fixations' },
        { type: 'para', text: 'Après chirurgie, infection, inflammation, micro-traumatismes répétés, des adhérences peuvent limiter le glissement.' },
        { type: 'para', text: 'Elles modifient la mécanique locale et peuvent influencer certains paramètres de vascularisation selon les cas.' },
        { type: 'para', text: 'Elles peuvent aussi entretenir un cercle douleur-stress-hypertonie.' },
        { type: 'sub', text: 'Ptoses et contraintes de la pesanteur' },
        { type: 'para', text: 'La pesanteur impose des contraintes sur les suspensions viscérales.' },
        { type: 'para', text: 'Les cavités et les moyens d’union répartissent normalement ces charges.' },
        { type: 'para', text: 'Lorsque le système de soutien se déconditionne (hypotonie, cicatrices, pertes de tonicité abdominale/périnéale), un abaissement viscéral peut être observé, parfois objectivable selon le contexte clinique.' },
        { type: 'sub', text: 'Spasmes et hypertonies réflexes' },
        { type: 'para', text: 'Une contrainte viscérale peut s’accompagner de réponses réflexes (somatiques et autonomes) : hypertonies, restrictions de mobilité segmentaire, perturbations du retour veineux/lymphatique, variations du schéma respiratoire.' },
        { type: 'para', text: 'Cliniquement, l’enjeu est de reconnaître les chaînes de compensation et de retrouver une meilleure adaptabilité tissulaire.' },
      ],
    },
    {
      id: 'approche-clinique',
      title: 'Application clinique en ROP (Réflexo-Occipito-Podale)',
      blocks: [
        { type: 'para', text: 'La ROP (Réflexo-Occipito-Podale) utilise, dans son cadre méthodologique, des circuits réflexes à partir de zones occipitales et podales pour guider l’évaluation et le traitement.' },
        { type: 'para', text: 'Le praticien recherche :' },
        { type: 'bullets', items: [
          'une restriction principale (mobilité/motilité) ;',
          'les relais segmentaires et neuro-végétatifs associés ;',
          'les compensations à distance (rachis, membres, diaphragme, bassin).',
        ]},
        { type: 'para', text: 'La démarche thérapeutique vise un “retour à l’équilibre” : induire, écouter, corriger, puis vérifier l’intégration globale.' },
        { type: 'para', text: 'Le même principe peut être décliné pour d’autres viscères, selon les tests ROP et le contexte clinique.' },
        { type: 'sub', text: 'Synthèse opérationnelle (pour le praticien)' },
        { type: 'bullets', items: [
          'Penser “glissement + pressions + innervation” avant de penser “organe isolé”.',
          'Relier un symptôme ostéo-articulaire à une hypothèse viscérale possible (douleur projetée, chaînes fasciales).',
          'Identifier l’événement déclencheur (chirurgie, infection, stress) et la stratégie d’adaptation (Selye), comme grille de lecture.',
          'Traiter avec une logique de vérification : correction locale → intégration globale → re-test.',
          'Garder une vigilance clinique : toute suspicion de pathologie organique impose une orientation médicale.',
        ]},
      ],
    },
  ],
  slides: {
    url: '/chapter-1/Chapter1 Slides de synthese FR.pdf',
    label: 'Diapositives',
    description: 'Synthèse visuelle du chapitre 1.',
  },
}
