// Chapter 13 content — English publication edition.
// Mirrors the authoritative final French runtime structure. Keep block
// boundaries stable: slide anchors and return routes address exact passages.
import type { Chapter } from './types'

export const chapter13En: Chapter = {
  slug: 'chapter-13', number: '13', title: 'Spleen',
  sections: [
    { id: 'presentation', title: '1. Overview', blocks: [
      { type: 'para', text: 'The spleen is a lymphoid organ, but it performs its functions through the bloodstream rather than the lymphatic circulation. It has no excretory duct. Its arteries do not anastomose with one another, making partial splenectomy possible. It is highly vascular, can vary in volume, and has a variable mean weight, often approximately 150 g in adults, with substantial interindividual variation. It is ovoid and purplish and is approximately the size of a fist, measuring about 10–12 cm in length.' },
      { type: 'para', text: 'Its soft, friable consistency makes it particularly vulnerable to trauma. The surrounding capsule contains smooth-muscle fibres and extends into the spleen, dividing it into several segments.' },
      { type: 'para', text: 'The spleen is part of the reticulohistiocytic system, formerly known as the reticuloendothelial system. Its principal functions include:' },
      { type: 'bullets', items: ['phagocytosis and clearance of senescent blood cells and foreign particles;', 'defence against infection through its immune function;', 'blood storage and filtration, particularly within the red pulp;', 'haematopoiesis during fetal life; in adults, this is no longer a routine function and recurs only in certain pathological settings involving extramedullary haematopoiesis.'] },
    ] },
    { id: 'situation', title: '2. Location', blocks: [
      { type: 'para', text: 'The spleen lies beneath the left hemidiaphragm in the posterosuperior part of the abdomen. It is covered by the lower lateral thoracic wall at the level of the left ninth, tenth and eleventh ribs. Its long axis follows that of the left tenth rib.' },
      { type: 'para', text: 'It lies posterior to the anterior axillary line, approximately 2 cm from the transverse process of the T10 vertebra. It is entirely intraperitoneal except at the hilum.' },
    ] },
    { id: 'anatomie', title: '3. Anatomy', blocks: [
      { type: 'sub', text: '3.1. External morphology' },
      { type: 'para', text: 'The spleen has two surfaces, three borders and two extremities, or poles.' },
      { type: 'bullets', items: ['Lateral or diaphragmatic surface: convex and moulded against the diaphragm.', 'Medial or visceral surface: concave, containing the hilum and presenting two aspects.', 'Anterior aspect: related to the greater curvature of the stomach.', 'Posterior aspect: related to the left kidney.', 'Anterior border: bears several notches.', 'Medial border: separates the two aspects of the medial surface.', 'Superior pole: related to the oesophagogastric junction and gastric fundus.', 'Inferior pole: related to the splenic flexure of the colon.'] },
      { type: 'sub', text: '3.2. Structure of the splenic parenchyma' },
      { type: 'lead', label: 'The spleen is composed of two principal tissue types:', text: 'white pulp and red pulp.' },
      { type: 'bullets', items: ['White pulp: composed of lymphoid tissue and involved in immunity.', 'Red pulp: involved in the destruction of senescent or malformed erythrocytes and damaged platelets.'] },
      { type: 'sub', text: '3.3. Supporting structures' },
      { type: 'para', text: 'The spleen is only loosely secured by peritoneal folds, allowing it to follow diaphragmatic motion. These folds connect it:' },
      { type: 'bullets', items: ['to the stomach through the gastrosplenic ligament, anterior to the splenic hilum;', 'to the pancreas through the pancreaticosplenic ligament, posterior to the splenic hilum; the pancreatic tail lies between these two ligaments;', 'to the colon through the phrenicocolic ligament, which forms a supporting shelf beneath the spleen;', 'to the diaphragm through the phrenicosplenic ligament, or suspensory ligament of the spleen, which resists downward displacement of the organ;', 'to the left kidney through the splenorenal ligament;', 'to the splenic vascular pedicle, which also contributes to its attachment.'] },
    ] },
    { id: 'rapports', title: '4. Anatomical relationships', blocks: [
      { type: 'bullets', items: ['Posteriorly: diaphragm.', 'Anteriorly: stomach.', 'Inferiorly: left colic flexure.', 'Medially: left kidney.', 'At the hilum: pancreatic tail.'] },
    ] },
    { id: 'vascularisation', title: '5. Vascular supply', blocks: [
      { type: 'sub', text: '5.1. Arterial supply' },
      { type: 'para', text: 'The splenic artery is the largest branch of the coeliac trunk. Its tortuous course follows the superior border of the pancreas and then passes between the two layers of the splenorenal ligament before dividing into several branches at the splenic hilum.' },
      { type: 'para', text: 'Branches of the splenic artery enter the white pulp, surrounded by lymphoid sheaths. They then divide within the red pulp into very fine penicillar arterioles, which open into a dense network of sinusoidal capillaries. This network contributes to filtration and clearance of harmful agents and abnormal or senescent erythrocytes before drainage into the efferent veins.' },
      { type: 'sub', text: '5.2. Venous drainage' },
      { type: 'para', text: 'Several veins unite to form the splenic vein, which courses posterior to the tail and body of the pancreas. It receives the inferior mesenteric vein and joins the superior mesenteric vein to form the portal vein.' },
    ] },
    { id: 'innervation', title: '6. Innervation', blocks: [
      { type: 'para', text: 'The spleen receives predominantly sympathetic autonomic innervation arising from spinal cord levels T6–T9. The fibres reach the coeliac plexus and then follow the splenic pedicle and branches of the splenic artery to the hilum and parenchyma.' },
      { type: 'para', text: 'From the ROP clinical perspective, the practical point is not to assess the spleen in isolation from its autonomic connections: the lower thoracic vertebrae, costotransverse joints, coeliac plexus, left hemidiaphragm and splenic pedicle form a single region for clinical assessment. Vagal involvement is described less directly and varies among sources; in practice, the coeliac plexus remains the central landmark.' },
    ] },
    { id: 'physiologie', title: '7. Physiology', blocks: [
      { type: 'para', text: 'The spleen consists of white pulp and red pulp, which perform complementary functions.' },
      { type: 'bullets', items: ['White pulp: composed of lymphoid cells involved in defence against infection, particularly T and B lymphocytes, together with macrophages that phagocytose cellular debris and pathogens.', 'Red pulp: recovers iron, which is transported to the liver and subsequently reused by the bone marrow for haemoglobin synthesis. It contributes to blood filtration and the removal of aged or damaged erythrocytes.'] },
      { type: 'para', text: 'The spleen performs several major functions:' },
      { type: 'bullets', items: ['immunity and phagocytosis of pathogens;', 'physiological haemolysis through filtration and removal of cellular debris, senescent erythrocytes, foreign material and toxins;', 'storage and regulation of a proportion of the formed elements of blood, particularly platelets;', 'haematopoiesis during fetal life; in adults, this is not a major normal splenic function.'] },
    ] },
    { id: 'pathologies-courantes', title: '8. Common disorders', blocks: [
      { type: 'sub', text: '8.1. Diagnosis of exclusion' },
      { type: 'sub', text: '8.2. Splenomegaly' },
      { type: 'para', text: 'Splenomegaly is an abnormal enlargement of the spleen. The spleen is not normally palpable during routine clinical examination, although rare variations may occur in some slender individuals. A spleen palpable below the left costal margin, particularly if it descends during inspiration, warrants medical evaluation.' },
      { type: 'para', text: 'The principal causes and clinical settings associated with splenomegaly can be grouped into several categories:' },
      { type: 'bullets', items: ['infectious causes: Epstein–Barr virus mononucleosis, viral hepatitis and parasitic infections;', 'hepatic and portal causes: chronic liver disease, portal hypertension and alcohol misuse when associated with liver disease;', 'haematological causes: haemolytic anaemias, leukaemias and lymphomas, including certain lymphomas occurring in adolescence;', 'inflammatory, immune-mediated or infiltrative causes, depending on the clinical context;', 'associated hepatomegaly or portal venous system involvement.'] },
      { type: 'para', text: 'Several warning signs should prompt medical referral:' },
      { type: 'bullets', items: ['painful retroclavicular or lateral supraclavicular lymph nodes;', 'marked pallor, pale lips or unusual fatigue;', 'night sweats unrelated to digestive symptoms;', 'petechiae or signs of bleeding;', 'spontaneous rib or back pain in a child or adolescent after minor exertion;', 'neck pain in a child or adolescent associated with an infectious context or systemic symptoms.'] },
      { type: 'para', text: 'Spontaneous splenic rupture is rare but may occur when the spleen is enlarged or structurally weakened. It is a medical emergency.' },
      { type: 'sub', text: '8.3. Trauma' },
      { type: 'para', text: 'The spleen is highly vulnerable to direct and indirect trauma because of its friability and rich vascular supply.' },
      { type: 'bullets', items: ['Direct trauma: fractures of the lower left ribs; abdominal impact from a punch, bicycle or motorcycle handlebars, or a steering wheel.', 'Indirect trauma: motor-vehicle collisions, falls, deceleration mechanisms or collision forces may cause splenic injury or rupture even without an open wound or a highly localised impact.'] },
      { type: 'para', text: 'Pain in the left hypochondrium or lower left ribs after trauma—particularly when accompanied by faintness, pallor, hypotension, left shoulder pain or sudden fatigue—must be regarded as a warning sign and should prompt medical evaluation.' },
      { type: 'sub', text: '8.4. Infectious mononucleosis' },
      { type: 'para', text: 'Infectious mononucleosis, sometimes called the “kissing disease” because it can be transmitted through saliva, is caused by Epstein–Barr virus, a member of the herpesvirus family. It particularly affects adolescents and young adults.' },
      { type: 'para', text: 'Symptoms may include:' },
      { type: 'bullets', items: ['sore throat and tonsillitis;', 'profound fatigue;', 'low systolic blood pressure;', 'lymphadenopathy;', 'back pain occurring without a specific precipitating activity, including at night;', 'tenderness on compression of the lower left ribs and a left-sided stitch during exertion.'] },
      { type: 'para', text: 'Infectious mononucleosis may be accompanied by splenic enlargement. Contact sports, strenuous exertion and heavy lifting should be avoided until clinical recovery and medical clearance in order to reduce the risk of splenic rupture.' },
      { type: 'sub', text: '8.5. Indications: functional disorders' },
      { type: 'para', text: 'Caution is essential, but working through distant reflex zones avoids aggressive intervention over this fragile organ. Functional indications discussed within the ROP framework include:' },
      { type: 'bullets', items: ['immunodeficiency with recurrent upper respiratory tract infections, particularly in adolescents;', 'severe fatigue;', 'recovery following hepatitis;', 'diarrhoea;', 'recovery following infectious mononucleosis in adolescents;', 'sequelae of thoracoabdominal trauma, fractures of the lower left ribs or whiplash injury;', 'muscle weakness with a tendency to sprains and a sensation of heavy limbs, particularly in the legs;', 'a left-sided stitch triggered by physical activity in adolescents.'] },
    ] },
    { id: 'relations-viscero-somatiques', title: '9. Viscerosomatic relationships', blocks: [
      { type: 'para', text: 'Viscerosomatic relationships associated with the spleen principally involve the T9, T10 and T11 vertebrae, the corresponding costotransverse joints and the lower left ribs.' },
      { type: 'para', text: 'The spleen is suspended beneath the left hemidiaphragm and follows respiratory movement. From an ROP clinical perspective, associated tension may therefore be sought in the left posteroinferior thorax, left hemidiaphragm, splenic flexure of the colon and lower costovertebral junction. This relationship does not constitute a diagnosis of splenic disease; it serves primarily as a guide for clinical assessment when left costal pain, postinfectious fatigue or a left-sided stitch occurs without an evident mechanical cause.' },
    ] },
    { id: 'relations-viscero-emotionnelles', title: '10. Viscero-emotional relationships', blocks: [
      { type: 'para', text: 'The spleen and pancreas are difficult to distinguish from an emotional perspective.' },
      { type: 'xref', label: 'See the reference in Chapter 12', text: 'Pancreas: Viscero-emotional Relationships', href: '/lecture/chapitre-12?lang=en&xrefBack=%2Flecture%2Fchapitre-13%3Flang%3Den%23p-relations-viscero-emotionnelles-1&xrefBackLabel=Back%20to%20Chapter%2013#p-relations-viscero-emotionnelles-0' },
      { type: 'para', text: 'Within the clinical and symbolic interpretation specific to ROP, the spleen is described as an energetic centre of the abdomen. Certain presentations may suggest a deeply pessimistic emotional tone that is not merely reactive, together with loss of motivation, rumination, anxiety-related throat tightness or sleep-onset disturbance.' },
      { type: 'para', text: 'This description should not be interpreted as a psychological diagnosis. It instead indicates a quality of clinical listening: profound fatigue, withdrawal, longstanding grief, remorse or a sense of carrying an excessive burden. Within this framework, ROP seeks to support the individual cautiously, without reducing the person’s history to a visceral typology.' },
    ] },
    { id: 'conseils', title: '11. Recommendations', blocks: [
      { type: 'bullets', items: ['Any suspected splenomegaly, splenic trauma, symptomatic infectious mononucleosis or associated systemic symptoms warrants medical referral.', 'Following infectious mononucleosis or suspected splenic enlargement, contact sports, strenuous exertion and heavy lifting should be avoided until recovery and medical clearance.', 'ROP treatment of spleen-related reflex zones must remain cautious and non-aggressive because of the organ’s friability and rich vascular supply.', 'Following an infectious episode, thoracoabdominal trauma or exertional pain of the left ribs, return to activity should be gradual and appropriate to the clinical context.'] },
    ] },
    { id: 'zones-reflexes-podales', title: '12. Foot reflex zones', blocks: [
      { type: 'sub', text: '12.1. Spleen-specific landmark' },
      { type: 'para', text: 'The spleen-specific foot landmark is retained. On the ROP map, it is located in relation to the splenic flexure of the colon, which lies medial and superior to the styloid process of the left fifth metatarsal. The splenic zone is situated within this territory, beneath the lateral end of the left hemidiaphragm reflex zone.' },
      { type: 'figure', src: '/chapter-13/EN/Cartography/figure-13-04.png', caption: 'Photo: Spleen', alt: 'Foot landmark for the spleen', orientation: 'portrait' },
      { type: 'sub', text: '12.2. Level 1 — Regulation of higher centres' },
      { type: 'para', text: 'Level 1 remains brief and optional. It may be incorporated in certain presentations involving prolonged fatigue, postinfectious recovery, substantial stress or sleep disturbance when justified by the overall clinical context.' },
      { type: 'bullets', items: ['Occipital reflex zones.', 'Brainstem and integration centres.', 'Hypothalamus and general regulation of adaptation.'] },
      { type: 'xref', label: 'See Chapter 3 — Central Nervous System', href: '/lecture/chapitre-3?lang=en&xrefBack=%2Flecture%2Fchapitre-13%3Flang%3Den%23p-zones-reflexes-podales-6&xrefBackLabel=Back%20to%20Chapter%2013#sec-presentation' },
      { type: 'sub', text: '12.3. Level 2 — Autonomic regulation and adaptation' },
      { type: 'para', text: 'The spleen receives predominantly sympathetic autonomic innervation. In this chapter, the relevant pathway is described as involving spinal levels T6–T9, with fibres passing through the coeliac plexus and then along the splenic pedicle.' },
      { type: 'bullets', items: ['Thoracic sympathetic outflow, T6–T9.', 'Corresponding thoracic sympathetic chain.', 'Coeliac plexus.', 'Splenic pedicle as a regional neurovascular interface.'] },
      { type: 'para', text: 'The vagus nerve is not included in the standard spleen sequence. Depending on the context, the liver and portal system may be included as functional supports, but they are not mandatory steps.' },
      { type: 'xref', label: 'See Chapter 4 — Autonomic Nervous System', href: '/lecture/chapitre-4?lang=en&xrefBack=%2Flecture%2Fchapitre-13%3Flang%3Den%23p-zones-reflexes-podales-11&xrefBackLabel=Back%20to%20Chapter%2013#sec-presentation' },
      { type: 'xref', label: 'See Chapter 8 — Diaphragm', href: '/lecture/chapitre-8?lang=en&xrefBack=%2Flecture%2Fchapitre-13%3Flang%3Den%23p-zones-reflexes-podales-12&xrefBackLabel=Back%20to%20Chapter%2013#sec-presentation' },
      { type: 'sub', text: '12.4. Level 3 — Locoregional visceral regulation' },
      { type: 'para', text: 'Level 3 places the spleen within its left subdiaphragmatic environment. Depending on the findings, the spleen-specific zone may be supplemented by its principal anatomical relationships: left hemidiaphragm, stomach, pancreatic tail, left kidney, splenic flexure of the colon and root of the transverse mesocolon.' },
      { type: 'para', text: 'Spleen-specific landmark. The specific landmark remains that described in Section 12.1. It is the organ-specific target and is combined at this level with regional relationships only when justified by the findings and clinical context.' },
      { type: 'xref', label: 'See Chapter 7 — Regional Abdominal and Peritoneal Foundation', href: '/lecture/chapitre-7?lang=en&xrefBack=%2Flecture%2Fchapitre-13%3Flang%3Den%23p-zones-reflexes-podales-16&xrefBackLabel=Back%20to%20Chapter%2013#sec-presentation' },
      { type: 'sub', text: '12.5. Level 4 — Viscerosomatic and viscero-emotional integration' },
      { type: 'para', text: 'Viscerosomatic integration. The principal landmarks are T9–T11, the corresponding costotransverse joints, the left ninth, tenth and eleventh ribs, the left posteroinferior thorax and the left hemidiaphragm. A left scapular manifestation may be included when relevant to the diaphragmatic context, without treating it as a universal association.' },
      { type: 'figure', src: '/chapter-13/EN/Cartography/figure-13-02.png', caption: 'Photo: Costovertebral joints', alt: 'Foot landmarks for the costovertebral joints', orientation: 'landscape' },
      { type: 'para', text: 'Viscero-emotional integration. From the clinical perspective specific to ROP, the spleen and pancreas may be difficult to distinguish at this level. Certain presentations may be accompanied by profound fatigue, a tendency towards rumination or withdrawal, longstanding grief, remorse, loss of motivation or sleep-onset disturbance. These features provide contextual cues for clinical inquiry.' },
      { type: 'para', text: 'Adaptive and neuroimmune context. The spleen contributes to immune function, and the immune response interacts with the nervous, endocrine and behavioural systems.' },
      { type: 'para', text: 'Fatigue, postinfectious recovery, stress and sleep can therefore be incorporated into a general interpretation of adaptation without assuming a simple causal relationship between an emotional state and the spleen.' },
      { type: 'para', text: 'Limbic brain/spleen balance: the spleen and pancreas are difficult to distinguish from an emotional perspective.' },
      { type: 'xref', label: 'See Chapter 3 — Central Nervous System', href: '/lecture/chapitre-3?lang=en&xrefBack=%2Flecture%2Fchapitre-13%3Flang%3Den%23p-zones-reflexes-podales-24&xrefBackLabel=Back%20to%20Chapter%2013#sec-presentation' },
      { type: 'xref', label: 'See Chapter 5 — Stress Mechanisms', href: '/lecture/chapitre-5?lang=en&xrefBack=%2Flecture%2Fchapitre-13%3Flang%3Den%23p-zones-reflexes-podales-25&xrefBackLabel=Back%20to%20Chapter%2013#sec-le-stress-une-reponse-d-adaptation' },
      { type: 'sub', text: '12.6. Associated support zones according to findings' },
      { type: 'bullets', items: ['Liver and portal system: portal venous or hepatic context.', 'Stomach: gastrosplenic relationship.', 'Pancreas: proximity to the hilum and pancreatic tail.', 'Left kidney: splenorenal relationship.', 'Left colon: splenic flexure.', 'Diaphragm: major regional interface.'] },
      { type: 'para', text: 'These territories are associated support zones rather than routine steps.' },
      { type: 'sub', text: '12.7. Clinical interpretation' },
      { type: 'bullets', items: ['Postinfectious fatigue or recovery following infectious mononucleosis after medical follow-up: Level 1 where relevant, together with Level 2 and the splenic zone, applied with great caution.', 'Longstanding sequelae of thoracoabdominal trauma after medical causes have been excluded: the splenic zone, the Level 3 regional environment, and the ribs and diaphragm at Level 4.', 'A left-sided stitch or left subcostal discomfort without warning signs: the diaphragm, spleen and splenic flexure as indicated by assessment findings.'] },
      { type: 'note', label: 'Safety principle', body: ['Any suspected splenomegaly, acute pain in the left hypochondrium following trauma, faintness, hypotension, left shoulder pain or infectious mononucleosis accompanied by splenic pain requires medical evaluation. The spleen is a friable, highly vascular organ.'] },
    ] },
  ],
  clinicalCase: { src: '/chapter-13/EN/clinical-case.png', alt: 'Clinical case — post-mononucleosis fatigue and a left-sided stitch', caption: 'Clinical Case — Chapter 13' },
}
