// Chapter 5 rework - private review page (/lecture/chapitre-5-rework).
// The regenerated deck follows the revised text flow and ends with two annexes.

export type SyncSlide = { src: string; title: string; orientation?: 'portrait' }
export type SyncAnchorPoint = { sectionId: string; blockIndex: number; itemIndex?: number }
export type SyncAnchor = SyncAnchorPoint & { slide: number | number[]; gapBefore?: 'half'; end?: SyncAnchorPoint }

const endAt = (sectionId: string, blockIndex: number): Pick<SyncAnchor, 'end'> => ({ end: { sectionId, blockIndex } })

export const chapter5ReworkSlides: SyncSlide[] = [
  { src: '/chapter-5-rework/slides/slide-01.png', title: 'Mécanisme de stress' },
  { src: '/chapter-5-rework/slides/slide-02.png', title: 'Homéostasie et allostasie' },
  { src: '/chapter-5-rework/slides/slide-03.png', title: 'Charge allostatique : le prix cumulé de l’adaptation' },
  { src: '/chapter-5-rework/slides/slide-04.png', title: 'La trilogie des stresseurs' },
  { src: '/chapter-5-rework/slides/slide-05.png', title: 'Le stress n’est pas l’événement, c’est la réponse' },
  { src: '/chapter-5-rework/slides/slide-06.png', title: 'La double réponse au stresseur : urgence et soutien' },
  { src: '/chapter-5-rework/slides/slide-07.png', title: 'Le syndrome général d’adaptation' },
  { src: '/chapter-5-rework/slides/slide-08.png', title: 'De l’alarme à la récupération' },
  { src: '/chapter-5-rework/slides/slide-09.png', title: 'Phase 3 : adaptation-résistance' },
  { src: '/chapter-5-rework/slides/slide-10.png', title: 'Phase 4 : décompensation ou épuisement' },
  { src: '/chapter-5-rework/slides/slide-11.png', title: 'Le véritable coût du stress : l’absence de récupération' },
  { src: '/chapter-5-rework/slides/slide-12.png', title: 'L’enjeu adaptatif : pouvoir terminer la réaction' },
  { src: '/chapter-5-rework/slides/slide-13.png', title: 'Le coût de régulation : une mobilisation active' },
  { src: '/chapter-5-rework/slides/slide-14.png', title: 'Le coût de régulation et la charge allostatique' },
  { src: '/chapter-5-rework/slides/slide-15.png', title: 'L’hypermétabolisme cellulaire sous contrainte' },
  { src: '/chapter-5-rework/slides/slide-16.png', title: 'Le modèle du seuil : trouble fonctionnel et altération structurelle' },
  { src: '/chapter-5-rework/slides/slide-17.png', title: 'La cible autonome : la flexibilité' },
  { src: '/chapter-5-rework/slides/slide-18.png', title: 'L’objectif autonome : la flexibilité, non la domination vagale' },
  { src: '/chapter-5-rework/slides/slide-19.png', title: 'La voie ascendante : informer l’interoception' },
  { src: '/chapter-5-rework/slides/slide-20.png', title: 'La séance ROP : stimuler, puis laisser intégrer' },
  { src: '/chapter-5-rework/slides/slide-21.png', title: 'La séquence clinique ROP : une progression en quatre niveaux' },
  { src: '/chapter-5-rework/slides/slide-22.png', title: 'Niveau 1 : diminuer la persistance du signal' },
  { src: '/chapter-5-rework/slides/slide-23.png', title: 'Niveau 2 : réduire la mobilisation devenue inutile' },
  { src: '/chapter-5-rework/slides/slide-24.png', title: 'Niveau 3 : restaurer la disponibilité respiratoire' },
  { src: '/chapter-5-rework/slides/slide-25.png', title: 'Niveau 4 : le retour des fonctions viscérales' },
  { src: '/chapter-5-rework/slides/slide-26.png', title: 'Fibromyalgie et charge allostatique' },
  { src: '/chapter-5-rework/slides/slide-27.png', title: 'Vers la recherche : mesurer la cinétique de récupération' },
  { src: '/chapter-5-rework/slides/cartographie-fr/slide-01.png', title: 'Cartographie ROP — zones occipitales' },
  { src: '/chapter-5-rework/slides/cartographie-fr/slide-02.png', title: 'Base exocrânienne — face plantaire des orteils' },
  { src: '/chapter-5-rework/slides/cartographie-fr/slide-03.png', title: 'Système limbique et tronc cérébral — cartographie' },
  { src: '/chapter-5-rework/slides/cartographie-fr/slide-05.png', title: 'Système limbique — cartographie' },
  { src: '/chapter-5-rework/slides/cartographie-fr/slide-07.png', title: 'Diencéphale et hypophyse — cartographie' },
  { src: '/chapter-5-rework/slides/cartographie-fr/slide-09.png', title: 'Sinus et glomus carotidien — cartographie' },
  { src: '/chapter-5-rework/slides/cartographie-fr/slide-11.png', title: 'Nerf vague X dans le foramen jugulaire — cartographie' },
  { src: '/chapter-5-rework/slides/cartographie-fr/slide-13.png', title: 'Nerfs vagues au hiatus œsophagien — cartographie' },
  { src: '/chapter-5-rework/slides/cartographie-fr/slide-15.png', title: 'Parasympathique pelvien ou sacré — cartographie' },
  { src: '/chapter-5-rework/slides/cartographie-fr/slide-17.png', title: 'Nerf phrénique (C3-C4-C5) — cartographie' },
  { src: '/chapter-5-rework/slides/cartographie-fr/slide-19.png', title: 'Nerf phrénique (triangle de Sédillot) — cartographie' },
  { src: '/chapter-5-rework/slides/slide-28.png', title: 'Annexe 1 : réponse neurologique SAM' },
  { src: '/chapter-5-rework/slides/slide-29.png', title: 'Annexe 2 : axe hormonal HHS' },
]

export const chapter5ReworkSlideAnchors: SyncAnchor[] = [
  { sectionId: 'le-stress-une-reponse-d-adaptation', blockIndex: -1, slide: 1, ...endAt('de-l-homeostasie-a-l-allostasie', -1) },
  { sectionId: 'de-l-homeostasie-a-l-allostasie', blockIndex: -1, slide: 2, ...endAt('de-l-homeostasie-a-l-allostasie', 5) },
  { sectionId: 'de-l-homeostasie-a-l-allostasie', blockIndex: 5, slide: 3, ...endAt('la-trilogie-des-stresseurs', -1) },
  { sectionId: 'la-trilogie-des-stresseurs', blockIndex: -1, slide: 4, ...endAt('le-stress-n-est-pas-seulement-l-evenement-c-est-la-reponse', -1) },
  { sectionId: 'le-stress-n-est-pas-seulement-l-evenement-c-est-la-reponse', blockIndex: -1, slide: 5, ...endAt('la-double-reponse-au-stresseur-urgence-et-soutien', -1) },
  { sectionId: 'la-double-reponse-au-stresseur-urgence-et-soutien', blockIndex: -1, slide: 6, ...endAt('le-syndrome-general-d-adaptation-un-modele-pedagogique', -1) },
  { sectionId: 'le-syndrome-general-d-adaptation-un-modele-pedagogique', blockIndex: -1, slide: 7, ...endAt('le-syndrome-general-d-adaptation-un-modele-pedagogique', 1) },
  { sectionId: 'le-syndrome-general-d-adaptation-un-modele-pedagogique', blockIndex: 1, slide: 8, ...endAt('le-syndrome-general-d-adaptation-un-modele-pedagogique', 6) },
  { sectionId: 'le-syndrome-general-d-adaptation-un-modele-pedagogique', blockIndex: 6, slide: 9, ...endAt('le-syndrome-general-d-adaptation-un-modele-pedagogique', 9) },
  { sectionId: 'le-syndrome-general-d-adaptation-un-modele-pedagogique', blockIndex: 9, slide: 10, ...endAt('le-veritable-cout-du-stress-l-absence-de-recuperation', -1) },
  { sectionId: 'le-veritable-cout-du-stress-l-absence-de-recuperation', blockIndex: -1, slide: 11, ...endAt('le-veritable-cout-du-stress-l-absence-de-recuperation', 7) },
  { sectionId: 'le-veritable-cout-du-stress-l-absence-de-recuperation', blockIndex: 7, slide: 12, ...endAt('le-cout-de-regulation-une-mobilisation-active-pas-une-batterie-qui-se-vide', -1) },
  { sectionId: 'le-cout-de-regulation-une-mobilisation-active-pas-une-batterie-qui-se-vide', blockIndex: -1, slide: 13, ...endAt('le-cout-de-regulation-une-mobilisation-active-pas-une-batterie-qui-se-vide', 3) },
  { sectionId: 'le-cout-de-regulation-une-mobilisation-active-pas-une-batterie-qui-se-vide', blockIndex: 3, slide: 14, ...endAt('a-l-echelle-cellulaire-le-prix-de-la-compensation', -1) },
  { sectionId: 'a-l-echelle-cellulaire-le-prix-de-la-compensation', blockIndex: -1, slide: 15, ...endAt('le-modele-du-seuil-trouble-fonctionnel-et-alteration-structurelle', -1) },
  { sectionId: 'le-modele-du-seuil-trouble-fonctionnel-et-alteration-structurelle', blockIndex: -1, slide: 16, ...endAt('la-cible-autonome-la-flexibilite-non-la-domination-vagale', -1) },
  { sectionId: 'la-cible-autonome-la-flexibilite-non-la-domination-vagale', blockIndex: -1, slide: 17, ...endAt('la-cible-autonome-la-flexibilite-non-la-domination-vagale', 1) },
  { sectionId: 'la-cible-autonome-la-flexibilite-non-la-domination-vagale', blockIndex: 1, slide: 18, ...endAt('le-pont-avec-la-rop-agir-sur-la-reponse-non-sur-l-existence-du-stresseur', -1) },
  { sectionId: 'le-pont-avec-la-rop-agir-sur-la-reponse-non-sur-l-existence-du-stresseur', blockIndex: -1, slide: 19, ...endAt('la-seance-rop-stimuler-puis-laisser-integrer', -1) },
  { sectionId: 'la-seance-rop-stimuler-puis-laisser-integrer', blockIndex: -1, slide: 20, ...endAt('quatre-niveaux-de-progressions-durant-la-seance-rop', -1) },
  { sectionId: 'quatre-niveaux-de-progressions-durant-la-seance-rop', blockIndex: -1, slide: 21, ...endAt('quatre-niveaux-de-progressions-durant-la-seance-rop', 4) },
  { sectionId: 'quatre-niveaux-de-progressions-durant-la-seance-rop', blockIndex: 4, slide: 22, ...endAt('quatre-niveaux-de-progressions-durant-la-seance-rop', 8) },
  { sectionId: 'quatre-niveaux-de-progressions-durant-la-seance-rop', blockIndex: 8, slide: 23, ...endAt('quatre-niveaux-de-progressions-durant-la-seance-rop', 12) },
  { sectionId: 'quatre-niveaux-de-progressions-durant-la-seance-rop', blockIndex: 12, slide: 24, ...endAt('quatre-niveaux-de-progressions-durant-la-seance-rop', 17) },
  { sectionId: 'quatre-niveaux-de-progressions-durant-la-seance-rop', blockIndex: 17, slide: 25, ...endAt('reactions-apres-seance-recuperation', -1) },
  { sectionId: 'illustration-clinique-fibromyalgie-et-charge-allostatique', blockIndex: -1, slide: 26, ...endAt('vers-une-recherche-sur-la-cinetique-de-recuperation', -1) },
  { sectionId: 'vers-une-recherche-sur-la-cinetique-de-recuperation', blockIndex: -1, slide: 27, ...endAt('conclusion', -1) },
  { sectionId: 'zones-reflexes-podales', blockIndex: -1, slide: 28, ...endAt('zones-reflexes-podales', 4) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 4, slide: 29, gapBefore: 'half', ...endAt('zones-reflexes-podales', 5) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 5, slide: 30, ...endAt('zones-reflexes-podales', 7) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 7, slide: 31, ...endAt('zones-reflexes-podales', 8) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 8, slide: 32, ...endAt('zones-reflexes-podales', 9) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 9, slide: 33, ...endAt('zones-reflexes-podales', 11) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 11, slide: 34, ...endAt('zones-reflexes-podales', 13) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 13, slide: 35, ...endAt('zones-reflexes-podales', 14) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 14, slide: 36, ...endAt('zones-reflexes-podales', 16) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 16, slide: 37, ...endAt('zones-reflexes-podales', 18) },
  { sectionId: 'zones-reflexes-podales', blockIndex: 18, slide: 38, ...endAt('zones-reflexes-podales', 19) },
  { sectionId: 'annexe-1', blockIndex: -1, slide: 39, ...endAt('annexe-2', -1) },
  { sectionId: 'annexe-2', blockIndex: -1, slide: 40, ...endAt('tableau-synthetique-de-la-progression-clinique', -1) },
]
