import type { Chapter } from './types'

export const chapter8Fr: Chapter = {
  slug: 'chapter-8',
  number: '8',
  title: 'Diaphragme',
  sections: [
    {
      id: 'presentation',
      title: 'Présentation',
      blocks: [
        { type: 'para', text: 'Le diaphragme sépare la cavité thoracique de la cavité abdominale, tout en les rendant solidaires :' },
        { type: 'bullets', items: [
          'Fonction respiratoire : il est surtout connu comme un muscle inspirateur, mais il assure beaucoup d\'autres fonctions.',
          'Fonction viscérale : nombreux sont les viscères qui ont des attaches directes sur le diaphragme. Organes sus-diaphragmatiques : cœur et poumons. Organes sous-diaphragmatiques : œsophage, estomac, foie, rate, angles coliques, duodénum, reins et surrénales. La verticalisation de l\'Homme a changé toute la statique et la dynamique des viscères.',
          'Fonction de cohésion et de mobilité viscérale : l\'alternance inspiration-expiration, à raison de 16/mn, soit 2 100/24 heures, est un masseur viscéral permanent qui entretient la mobilité des viscères, drainant les déchets, apportant les nutriments et les oxygénant.',
          'Fonction veino-lymphatique : l\'alternance inspiration-expiration exerce une alternance de pression-dépression qui influence le retour veineux et lymphatique.',
          'Fonction barométrique : il existe un gradient de pression, négative dans la cavité thoracique et positive dans la cavité abdominale. L\'inspiration crée une dépression thoracique et une surpression abdominale. Ce gradient aspire le sang vers le cœur. Le diaphragme doit sa forme convexe à ce gradient de pression.',
          'Fonction de tension membraneuse : par ses mouvements, le diaphragme mobilise les séreuses — plèvre, péricarde, péritoine.',
          'Fonction sur le système ostéo-musculo-articulaire : par ses connexions vertébrales et costales avec les muscles intercostaux, psoas, carré des lombes et transverse de l\'abdomen, le diaphragme participe à la stabilisation de la colonne vertébrale et du bassin.',
          'Fonction barométrique articulaire : la pression intra-capsulaire des articulations est infra-atmosphérique, permettant la cohésion et la mobilité articulaires. Le mouvement diaphragmatique entretient ce gradient de pression intra-articulaire.',
          'Stress : l\'alternance d\'inspiration-expiration a un effet apaisant sur les états de stress.',
        ]},
      ],
    },
    {
      id: 'anatomie',
      title: 'Anatomie',
      blocks: [
        { type: 'para', text: 'Le diaphragme comprend trois parties et des orifices :' },
        { type: 'bullets', items: ['Le centre phrénique (tendon central) ;', 'La coupole diaphragmatique ;', 'Les piliers ;', 'Trois orifices principaux et des orifices accessoires.'] },
        { type: 'sub', text: 'Centre phrénique' },
        { type: 'para', text: 'Le centre phrénique a la forme d\'un trèfle à trois folioles :' },
        { type: 'bullets', items: [
          'Foliole antérieure : attachée en avant au sternum et au processus xyphoïdien par deux faisceaux de muscles.',
          'Folioles droite et gauche : situées plus en arrière, elles donnent naissance aux fibres musculaires qui rejoignent les structures costales et lombaires.',
          'Particularité : le centre phrénique, sur lequel est posé le cœur, est oblique en bas, en avant et à gauche.',
        ]},
        { type: 'sub', text: 'Coupole diaphragmatique' },
        { type: 'para', text: 'La coupole diaphragmatique est la partie musculaire en forme de voûte. Ses fibres musculaires doivent être en tensions harmonieuses pour permettre au diaphragme de fonctionner correctement.' },
        { type: 'rop', body: [
          'En raison de l\'obliquité caudalement, ventralement et à gauche du centre phrénique, la coupole diaphragmatique droite est plus haute que la gauche.',
          'Zones réflexes podales du diaphragme — face plantaire des deux pieds :',
          'Centre phrénique : à la palpation de la texture de la peau, la partie gauche du centre phrénique est plus bas située que la droite.',
          'Coupoles diaphragmatiques : respecter la différence de hauteur des deux coupoles. Placer la coupole gauche à la même hauteur que la droite reviendrait à mettre les ventricules cardiaques à l\'horizontale.',
          'Chaque coupole suit une ligne courbe allant du centre phrénique à la styloïde du 5ème métatarse.',
          'L\'attache antérieure xyphoïdienne est sur le tubercule du naviculaire.',
          'Les attaches latérales sur les six dernières côtes sont sur la face latérale du 5ème métatarse.',
        ]},
        { type: 'sub', text: 'Piliers du diaphragme' },
        { type: 'para', text: 'Le diaphragme s\'attache dorsalement sur la colonne lombaire par les piliers principaux et accessoires :' },
        { type: 'bullets', items: [
          'Piliers principaux — Pilier médian droit : s\'attache sur les corps vertébraux L1-L4 et les disques intervertébraux. Pilier médian gauche : s\'attache sur L1-L3. Les deux piliers médians participent à la formation du hiatus aortique.',
          'Piliers accessoires — Ligament arqué médian : va du corps de L1 (et parfois L2) à son processus transverse, formant l\'arcade du psoas. Ligament arqué latéral (ligament lombo-costal de Henlé) : va du processus transverse de L1 à la 12ème côte, formant l\'arcade du carré des lombes.',
        ]},
        { type: 'rop', body: [
          'Les tensions anormales du diaphragme proviennent rarement de lui-même (à l\'exception des traumatismes), mais de l\'ensemble des organes et structures qui lui sont rattachés. Ces tensions engendrent : baisse de la ventilation et hypoxie, élévation du CO2, acidose, mauvais retours veineux et lymphatiques, brassage viscéral déficient.',
          'Il convient de toujours associer le diaphragme avec tous les traitements des dysfonctions viscérales thoraciques et abdominales.',
          'Zones réflexes podales des piliers : espace entre le bord plantaire des quatre premières vertèbres lombaires à droite et des trois premières à gauche.',
        ]},
        { type: 'sub', text: 'Orifices du diaphragme' },
        { type: 'para', text: 'Le diaphragme est percé d\'orifices qui font communiquer la cavité thoracique avec la cavité abdominale :' },
        { type: 'bullets', items: [
          'Des orifices (ou hiatus) principaux : aortique, œsophagien et de la veine cave inférieure.',
          'Des orifices accessoires : hiatus de Marfran et de Larrey, orifices entre les piliers accessoires, hiatus du ligament lombo-costal de Henlé.',
        ]},
        { type: 'lead', label: 'Hiatus aortique', text: 'Central, dorsalement entre les deux folioles droite et gauche du centre phrénique, issu des deux piliers médians. Il livre passage à l\'aorte abdominale, au canal thoracique et à la veine azygos. Zone réflexe podale : niveau de la vertèbre Th12, face plantaire.' },
        { type: 'lead', label: 'Hiatus œsophagien', text: 'Situé à gauche de Th10, entre les deux folioles droite et gauche. Plusieurs structures y exercent des tractions : la plèvre (gaine de Treitz et Paimer), le péritoine (muscles de Juvara et Rouget), et le lobe gauche du foie. Zone réflexe podale : face plantaire gauche, à gauche du centre phrénique, à l\'aplomb d\'une ligne partant en direction du cuboïde gauche.' },
        { type: 'lead', label: 'Hiatus de la veine cave inférieure', text: 'Situé à la jonction des folioles antérieure et droite du centre phrénique, à hauteur de Th8-Th9. Livre passage à la veine cave inférieure et aux rameaux du nerf phrénique droit. Zone réflexe podale : confondue avec le centre phrénique côté droit.' },
        { type: 'lead', label: 'Orifices accessoires', text: 'Hiatus de Marfran et de Larrey : amarrent le centre phrénique au sternum ; passage des vaisseaux thoraciques internes. Hiatus de Henlé : entre les deux dernières côtes et le ligament de Henlé, fait communiquer les espaces rétropéritonéaux thoracique et abdominal. Orifices entre les piliers accessoires : passage de la chaîne ganglionnaire sympathique latéro-vertébrale et des nerfs splanchniques.' },
        { type: 'rop', body: [
          'Les traumatismes de la charnière thoraco-lombaire et costale inférieure incluent toujours le diaphragme et toutes les structures qui y sont attachées.',
        ]},
      ],
    },
    {
      id: 'vascularisation',
      title: 'Vascularisation',
      blocks: [
        { type: 'sub', text: 'Artérielle' },
        { type: 'para', text: 'Le diaphragme reçoit le sang artériel par les branches des artères thoraciques internes, les artères phréniques supérieures (issues de l\'aorte thoracique) et les artères phréniques inférieures (issues du tronc cœliaque, 1ère branche de l\'aorte abdominale).' },
        { type: 'sub', text: 'Veineux — système azygos' },
        { type: 'para', text: 'Le retour veineux emprunte les veines thoraciques internes et le système azygos, qui chemine de chaque côté de la colonne vertébrale :' },
        { type: 'bullets', items: [
          'À gauche, la veine hémi-azygos — réunion de la veine lombale ascendante gauche et de la veine subcostale gauche.',
          'À droite, la veine azygos naît à hauteur de L1 ou L2, traverse le diaphragme près des piliers et se jette dans la veine cave supérieure.',
        ]},
        { type: 'lead', label: 'Intérêt clinique', text: 'Le système azygos participe au système porto-cave. La jonction azygo-cave — artères et veines pulmonaires droites, nerf phrénique droit, nerf vague droit — proche de la bifurcation trachéale, est une zone de tensions multiples à toujours prendre en compte en ROP.' },
        { type: 'rop', body: [
          'Zones réflexes podales : jonction azygo-cave — 2ème et 3ème articulations chondro-costales droites.',
        ]},
      ],
    },
    {
      id: 'innervation',
      title: 'Innervation',
      blocks: [
        { type: 'para', text: 'Le diaphragme reçoit une double innervation somatique : les nerfs phréniques droit et gauche et les six derniers nerfs intercostaux.' },
        { type: 'sub', text: 'Nerfs phréniques' },
        { type: 'para', text: 'Les nerfs phréniques sont les principaux nerfs inspirateurs du diaphragme. Ils interviennent aussi dans les afférences nociceptives du péricarde, du médiastin et du péritoine.' },
        { type: 'lead', label: 'Origine', text: 'Branche antérieure du 4ème nerf cervical et accessoirement des 3ème et 5ème nerfs cervicaux.' },
        { type: 'lead', label: 'Trajet cervical', text: 'Le nerf phrénique croise la face antérieure du muscle scalène antérieur puis passe dans le triangle de Sédillot, délimité par le muscle sterno-cleïdo-mastoïdien, le muscle omohyoïdien et le muscle scalène antérieur.' },
        { type: 'lead', label: 'Trajet thoracique', text: 'Dans le médiastin antérieur, les deux nerfs phréniques descendent entre le péricarde et les poumons, en avant des pédicules pulmonaires.' },
        { type: 'lead', label: 'Trajet abdominal', text: 'Nerf phrénique droit : traverse l\'orifice de la veine cave inférieure, innerve le pilier droit, les ligaments triangulaires et coronaires du foie, le péricarde fibreux et la capsule du foie. Nerf phrénique gauche : perfore le diaphragme en arrière du cœur, innerve le pilier gauche et le péricarde. Les deux nerfs phréniques se terminent au plexus cœliaque et aux surrénales.' },
        { type: 'lead', label: 'Anastomoses', text: 'Nerfs crâniens : hypoglosse XII et accessoire XI. SNA : nerf vague X, ganglion cervical inférieur, plexus cœliaque, et anastomoses entre les deux nerfs phréniques. Nerf du subclavier : innerve le muscle subclavier entre la clavicule et la 1ère côte.' },
        { type: 'rop', body: [
          'Les deux nerfs phréniques deviennent acteurs dans les états de stress : l\'interaction des émotions sur la respiration explique pourquoi des tensions psychiques retentissent sur le diaphragme et les viscères.',
          'Zones réflexes podales du nerf phrénique :',
          '3ème, 4ème et 5ème vertèbres cervicales sur la vue sagittale médiale de la première phalange du gros orteil et sur la vue dorsale plantaire.',
          'Triangle de Sédillot : bord supérieur de la malléole tibiale.',
          'Médiastin : face plantaire de la tête des 1ers métatarsiens.',
        ]},
        { type: 'sub', text: 'Six derniers nerfs intercostaux' },
        { type: 'para', text: 'Les six derniers nerfs intercostaux (Th7 à Th12) participent à l\'innervation somatique du diaphragme. Zone réflexe : vertèbres Th7 à Th12. Le nerf intercostal brachial de Hyrtl est impliqué dans l\'asthme, l\'eczéma et les allergies ; sa zone réflexe est à la jonction diaphyse-tête latérale du 5ème métatarse.' },
      ],
    },
    {
      id: 'jonction-oesophago-cardio',
      title: 'Jonction œsophago-cardio-tubérositaire (JOCT)',
      blocks: [
        { type: 'para', text: 'Cette jonction est soumise à de nombreuses tensions :' },
        { type: 'bullets', items: [
          'Verticalisation de l\'Homme : elle a obligé la jonction gastro-œsophagienne à se réorganiser. Le sphincter inférieur œsophagien (SIO) est un sphincter fonctionnel à haute pression, non anatomique, assurant la continence entre l\'œsophage et l\'estomac.',
          'Mouvements du diaphragme : les fascias cervicaux et médiastinaux, tendus entre la base du crâne et le centre phrénique, transmettent les tensions crâniennes et cervicales au diaphragme.',
          'Rotation embryonnaire de l\'estomac : l\'estomac fait une rotation de 90° dans le sens horaire selon un axe vertical, entraînant le déplacement de l\'œsophage abdominal à gauche.',
          'Système anti-reflux : dès que la pression gastrique augmente, des mécanismes s\'opposent au reflux.',
        ]},
        { type: 'lead', label: 'Cravate d\'Helvetius', text: 'Le système anti-reflux est assuré conjointement par la tension des fibres obliques de l\'estomac (cravate d\'Helvetius), le tonus du SIO et les forces de pression-dépression du diaphragme.' },
        { type: 'lead', label: 'Angle de His', text: 'L\'angle de His ou incisure cardiaque forme un angle aigu entre la partie distale de l\'œsophage et le fundus de l\'estomac. Cet angle contribue au mécanisme anti-reflux.' },
      ],
    },
    {
      id: 'reflux-hernie-hiatale',
      title: 'Reflux gastro-œsophagien et hernie hiatale',
      blocks: [
        { type: 'lead', label: 'Reflux gastro-œsophagien (RGO)', text: 'Toute tension anormale pleuro-pulmonaire, du diaphragme, du péritoine, de l\'estomac, du foie ou des attaches de la JOCT peut modifier l\'angle de His et provoquer un reflux acide dans l\'œsophage.' },
        { type: 'lead', label: 'Hernie hiatale', text: 'Lésion très fréquente : déplacement d\'une partie de la grosse tubérosité de l\'estomac à travers le hiatus œsophagien.' },
        { type: 'bullets', items: [
          'Hernie par roulement : une partie du péritoine comprenant une partie du fundus roule ventralement le long de l\'œsophage abdominal jusqu\'au hiatus, sans que la JOCT soit déplacée.',
          'Hernie par glissement : l\'œsophage abdominal, le cardia et le fundus glissent crânialement à travers le hiatus œsophagien.',
        ]},
        { type: 'sub', text: 'Étiologie' },
        { type: 'bullets', items: [
          'Gastroparésie ;',
          'Dilatation stomacale ;',
          'Obésité ou amaigrissement rapide ;',
          'Fixations costo-vertébrales, chondro-costales et thoraco-lombaires ;',
          'Grossesse (par conséquence mécanique et hormonale) ;',
          'Ménopause ;',
          'Abus de graisse, d\'alcool et de boissons gazeuses ;',
          'Prise au long cours de médicaments (anti-inflammatoires, antidépresseurs, aspirine, antidouleurs, cortisone, vaso-dilatateurs).',
        ]},
        { type: 'sub', text: 'Symptômes' },
        { type: 'bullets', items: [
          'Pyrosis (brûlure acide dans l\'œsophage) ;',
          'Dyspepsie ;',
          'Dysphagie ;',
          'Fausses cardiopathies (précordialgies) ;',
          'Dyspnée par sensation d\'oppression ;',
          'Laryngite, gingivite, sinusite, otite séreuse, crises asthmatiformes, œsophagite par la remontée acide ;',
          'Sialorrhée (excès de salive).',
        ]},
        { type: 'rop', body: [
          'ROP du RGO et de la hernie hiatale :',
          'Colonne cervico-thoraco-abdominale, articulations costo-vertébrales ;',
          'Diaphragme, nerf phrénique, six derniers nerfs intercostaux ;',
          'Nerf vague ;',
          'Hiatus œsophagien ;',
          'Estomac ;',
          'Lobe gauche du foie.',
          'RGO du nouveau-né — origine crânienne : compression des parties condylaires de l\'occiput et du foramen jugulaire lors de l\'accouchement. Traitement ROP : MRP, parties condylaires de l\'occiput, foramen magnum, foramen jugulaire, hiatus œsophagien.',
        ]},
      ],
    },
  ],
}
