// Chapter 17 - slide <-> text synchronisation map for the combined reading
// experience (/lecture/chapitre-17).
//
// Slides are pre-rendered from:
// public/chapter-17/Chapter17 Slides de synthese - FR.pdf

export type SyncSlide = { src: string; title: string; orientation?: 'portrait' }
export type SyncAnchor = { sectionId: string; blockIndex: number; slide: number; gapBefore?: 'half' }

export const chapter17Slides: SyncSlide[] = [
  { src: '/chapter-17/slides/slide-01.png', title: 'Chapitre 17 : la cavite pelvienne' },
  { src: '/chapter-17/slides/slide-02.png', title: 'L unite vertebro-coxo-pelvienne' },
  { src: '/chapter-17/slides/slide-03.png', title: 'Les voies de communication exterieures' },
  { src: '/chapter-17/slides/slide-04.png', title: 'Le peritoine et le systeme de suspension' },
  { src: '/chapter-17/slides/slide-05.png', title: 'Organisation des loges viscerales' },
  { src: '/chapter-17/slides/slide-06.png', title: 'Le drapage peritoneal et les culs-de-sacs' },
  { src: '/chapter-17/slides/slide-07.png', title: 'La couverture peritoneale' },
  { src: '/chapter-17/slides/slide-08.png', title: 'Biomecanique : gestion des pressions et gravite' },
  { src: '/chapter-17/slides/slide-09.png', title: 'L equilibre ligamentaire : les freins sacres' },
  { src: '/chapter-17/slides/slide-10.png', title: 'La musculature pelvienne profonde' },
  { src: '/chapter-17/slides/slide-11.png', title: 'Le plancher pelvien : diaphragme et perinee' },
  { src: '/chapter-17/slides/slide-12.png', title: 'Dynamique vasculaire et systeme porte' },
  { src: '/chapter-17/slides/slide-13.png', title: 'Reseau somatique : voies nerveuses et sciatalgies' },
  { src: '/chapter-17/slides/slide-14.png', title: 'Innervation somatique I : le piege du piriforme' },
  { src: '/chapter-17/slides/slide-15.png', title: 'Innervation somatique II : le trajet du pudendal' },
  { src: '/chapter-17/slides/slide-16.png', title: 'Innervation somatique : le trajet du nerf pudendal' },
  { src: '/chapter-17/slides/slide-17.png', title: 'Innervation autonome et controle central' },
  { src: '/chapter-17/slides/slide-18.png', title: 'Le controle central neuro-vegetatif' },
  { src: '/chapter-17/slides/slide-19.png', title: 'Biomecanique : gestion des pressions gravitaires' },
  { src: '/chapter-17/slides/slide-20.png', title: 'Pathologie biomecanique : la ptose viscerale' },
  { src: '/chapter-17/slides/slide-21.png', title: 'Le relais obturateur : la relation vessie-hanche' },
  { src: '/chapter-17/slides/slide-22.png', title: 'Synthese clinique : defaillances mecaniques et neurologiques' },
  { src: '/chapter-17/slides/slide-23.png', title: 'Synthese clinique ROP : zones reflexes et cibles' },
]

function withChapter17Titles(titles: string[]): SyncSlide[] {
  return chapter17Slides.map((slide, index) => ({ ...slide, title: titles[index] ?? slide.title }))
}

export const chapter17SlidesEn = withChapter17Titles([
  'Chapter 17: the pelvic cavity',
  'The vertebro-coxo-pelvic unit',
  'External communication pathways',
  'The peritoneum and suspension system',
  'Organization of the visceral compartments',
  'Peritoneal draping and cul-de-sacs',
  'The peritoneal covering',
  'Biomechanics: pressure management and gravity',
  'Ligament balance: the sacral restraints',
  'Deep pelvic musculature',
  'Pelvic floor: diaphragm and perineum',
  'Vascular dynamics and portal system',
  'Somatic network: nerve pathways and sciatic pain',
  'Somatic innervation I: the piriformis trap',
  'Somatic innervation II: the pudendal pathway',
  'Somatic innervation: the path of the pudendal nerve',
  'Autonomic innervation and central control',
  'Central neurovegetative control',
  'Biomechanics: management of gravitational pressures',
  'Biomechanical pathology: visceral ptosis',
  'The obturator relay: the bladder-hip relationship',
  'Clinical synthesis: mechanical and neurological failures',
  'ROP clinical synthesis: reflex zones and targets',
])

export const chapter17SlidesDe = withChapter17Titles([
  'Kapitel 17: die Beckenhoehle',
  'Die vertebro-coxo-pelvine Einheit',
  'Aeussere Kommunikationswege',
  'Das Peritoneum und das Aufhaengesystem',
  'Organisation der viszeralen Logen',
  'Peritoneale Drapierung und Douglas-Raeume',
  'Die peritoneale Bedeckung',
  'Biomechanik: Druckmanagement und Schwerkraft',
  'Ligamentaeres Gleichgewicht: die sakralen Bremsen',
  'Tiefe Beckenmuskulatur',
  'Beckenboden: Diaphragma und Perineum',
  'Gefaessdynamik und Portalsystem',
  'Somatisches Netzwerk: Nervenbahnen und Ischialgien',
  'Somatische Innervation I: die Piriformis-Falle',
  'Somatische Innervation II: der Pudendus-Verlauf',
  'Somatische Innervation: Verlauf des Nervus pudendus',
  'Autonome Innervation und zentrale Kontrolle',
  'Zentrale neurovegetative Kontrolle',
  'Biomechanik: Management der Gravitationsdruecke',
  'Biomechanische Pathologie: viszerale Ptose',
  'Der Obturator-Relaispunkt: Beziehung Blase-Huefte',
  'Klinische Synthese: mechanische und neurologische Defizite',
  'ROP-Kliniksynthese: Reflexzonen und Ziele',
])

export const chapter17SlidesEs = withChapter17Titles([
  'Capitulo 17: la cavidad pelvica',
  'La unidad vertebro-coxo-pelvica',
  'Vias de comunicacion exteriores',
  'El peritoneo y el sistema de suspension',
  'Organizacion de los compartimentos viscerales',
  'Drapaje peritoneal y fondos de saco',
  'La cobertura peritoneal',
  'Biomecanica: gestion de presiones y gravedad',
  'Equilibrio ligamentario: frenos sacros',
  'Musculatura pelvica profunda',
  'Suelo pelvico: diafragma y perineo',
  'Dinamica vascular y sistema porta',
  'Red somatica: vias nerviosas y ciatalgias',
  'Inervacion somatica I: la trampa del piriforme',
  'Inervacion somatica II: el trayecto del pudendo',
  'Inervacion somatica: trayecto del nervio pudendo',
  'Inervacion autonoma y control central',
  'Control neurovegetativo central',
  'Biomecanica: gestion de presiones gravitatorias',
  'Patologia biomecanica: ptosis visceral',
  'El relevo obturador: relacion vejiga-cadera',
  'Sintesis clinica: fallos mecanicos y neurologicos',
  'Sintesis clinica ROP: zonas reflejas y objetivos',
])

export const chapter17SlidesIt = withChapter17Titles([
  'Capitolo 17: la cavita pelvica',
  'L unita vertebro-coxo-pelvica',
  'Vie di comunicazione esterne',
  'Il peritoneo e il sistema di sospensione',
  'Organizzazione delle logge viscerali',
  'Drappeggio peritoneale e cavi di fondo',
  'La copertura peritoneale',
  'Biomeccanica: gestione delle pressioni e gravita',
  'Equilibrio legamentoso: freni sacrali',
  'Muscolatura pelvica profonda',
  'Pavimento pelvico: diaframma e perineo',
  'Dinamica vascolare e sistema portale',
  'Rete somatica: vie nervose e sciatalgie',
  'Innervazione somatica I: la trappola del piriforme',
  'Innervazione somatica II: il tragitto del pudendo',
  'Innervazione somatica: tragitto del nervo pudendo',
  'Innervazione autonoma e controllo centrale',
  'Controllo neurovegetativo centrale',
  'Biomeccanica: gestione delle pressioni gravitarie',
  'Patologia biomeccanica: ptosi viscerale',
  'Il relais otturatorio: relazione vescica-anca',
  'Sintesi clinica: cedimenti meccanici e neurologici',
  'Sintesi clinica ROP: zone riflesse e bersagli',
])

export const chapter17SlideAnchors: SyncAnchor[] = [
  { sectionId: 'presentation', blockIndex: -1, slide: 1 },
  { sectionId: 'presentation', blockIndex: 0, slide: 2 },
  { sectionId: 'situation', blockIndex: 0, slide: 3 },
  { sectionId: 'situation', blockIndex: 1, slide: 4 },
  { sectionId: 'anatomie', blockIndex: 0, slide: 5 },
  { sectionId: 'anatomie', blockIndex: 2, slide: 6 },
  { sectionId: 'anatomie', blockIndex: 4, slide: 7 },
  { sectionId: 'anatomie', blockIndex: 6, slide: 8 },
  { sectionId: 'anatomie', blockIndex: 10, slide: 9 },
  { sectionId: 'anatomie', blockIndex: 13, slide: 10 },
  { sectionId: 'anatomie', blockIndex: 14, slide: 11 },
  { sectionId: 'vascularisation', blockIndex: 0, slide: 12 },
  { sectionId: 'innervation', blockIndex: 0, slide: 13 },
  { sectionId: 'innervation', blockIndex: 1, slide: 14 },
  { sectionId: 'innervation', blockIndex: 3, slide: 15 },
  { sectionId: 'innervation', blockIndex: 4, slide: 16 },
  { sectionId: 'innervation', blockIndex: 6, slide: 17 },
  { sectionId: 'innervation', blockIndex: 8, slide: 18 },
  { sectionId: 'innervation', blockIndex: 13, slide: 19 },
  { sectionId: 'pathologies-courantes', blockIndex: 0, slide: 20 },
  { sectionId: 'pathologies-courantes', blockIndex: 1, slide: 21 },
  { sectionId: 'pathologies-courantes', blockIndex: 4, slide: 22 },
  { sectionId: 'zones-reflexes-podales', blockIndex: 0, slide: 23 },
]
