// Chapter 16 — Kidneys — English
// Source: Drive "CH 16" / Chapter16_Kidneys_fluent_medical_EN.docx
// Mirrors the block structure of chapter16.fr.ts (section IDs and ordering must match).

import type { Chapter } from './types'

export const chapter16En: Chapter = {
  "slug": "chapter-16",
  "number": "16",
  "title": "Kidneys",
  "sections": [
    {
      "id": "presentation",
      "title": "Overview",
      "blocks": [
        {
          "type": "para",
          "text": "The two kidneys are located in the lumbar fossae and are surrounded by a capsule. They are dark red in colour and bean-shaped. Their medial border contains the hilum, through which pass the renal artery and vein, lymphatic vessels, nerves and the renal pelvis, which collects the urine secreted by the kidneys before it is conveyed by the ureters to the bladder."
        },
        {
          "type": "para",
          "text": "The kidneys have multiple functions that are essential for homeostasis. Because of their dense structure and their position against the posterior abdominal wall, close to the vertebral column, they are vulnerable to collision forces generated by trauma such as accidents, falls onto the back, and direct blows."
        }
      ]
    },
    {
      "id": "situation",
      "title": "Location",
      "blocks": [
        {
          "type": "para",
          "text": "The kidneys are located lateral to the thoracolumbar spine, between the peritoneum and the posterior abdominal wall. They are retroperitoneal (figure 16.1) and predominantly supramesocolic. They are inclined, so that the lower pole lies more laterally than the upper pole."
        },
        {
          "type": "bullets",
          "items": [
            "Anatomical landmarks:"
          ]
        },
        {
          "type": "sub",
          "text": "Dorsally"
        },
        {
          "type": "bullets",
          "items": [
            "(figure 16.2)",
            "Right kidney: it lies slightly lower than the left kidney because of the liver. It extends from the 11th and 12th ribs to L4;",
            "Left kidney: it extends from the 11th rib to L3."
          ]
        },
        {
          "type": "sub",
          "text": "Ventrally"
        },
        {
          "type": "bullets",
          "items": [
            "Both kidneys: the upper pole lies at the level of a line joining the ninth costal cartilages;",
            "Right kidney: the lower pole is one fingerbreadth below the umbilicus;",
            "Left kidney: the lower pole lies at the level of the umbilicus."
          ]
        },
        {
          "type": "para",
          "text": "The kidneys are capped by the adrenal glands and contained within the renal compartment, which is composed of fat and fascia."
        }
      ]
    },
    {
      "id": "anatomie",
      "title": "Anatomy",
      "blocks": [
        {
          "type": "sub",
          "text": "Renal compartment"
        },
        {
          "type": "para",
          "text": "The renal compartment is shaped like a funnel open inferiorly. It is interposed between the posterior parietal peritoneum ventrally and the fascia that separates it from the quadratus lumborum and psoas muscles dorsally. It is formed by two layers: (figure 16.3)"
        },
        {
          "type": "bullets",
          "items": [
            "Anterior layer, or prerenal layer: this layer passes over the anterior surface of the kidney, adheres to the posterior parietal peritoneum and continues toward the hilum to join the prerenal layer of the opposite kidney. It is related to the colon through Toldt’s lamina.",
            "Posterior layer, or retrorenal layer: this layer passes behind the kidney. It lines the quadratus lumborum and psoas major muscles, the latter serving as a rail for renal mobility, as well as the anterolateral aspect of the vertebral column. It is thick and resistant. It attaches to the diaphragm at the level of the pleuro-costo-diaphragmatic hiatuses.",
            "These two layers, which form the renal fascia, fuse at the lateral border of the kidney and at the upper pole, where they interpose a layer between the kidney and the adrenal gland. The two layers also adhere to the inferior surface of the diaphragm."
          ]
        },
        {
          "type": "rop",
          "body": [
            "In ROP clinical reading, the two renal compartments are approached together, because their fasciae, posterior relations and diaphragmatic-lumbar connections participate in the same regional dynamic. It is therefore often necessary to stimulate the reflex zones of both kidneys. They are also related to the colon through Toldt’s lamina."
          ]
        },
        {
          "type": "sub",
          "text": "Contents: renal fat: (figure 16.3)"
        },
        {
          "type": "para",
          "text": "Inside the renal compartment, the kidney is embedded in semiliquid perirenal fat contained within a fine membrane, the renal capsule. Outside the capsule, between the capsule and the renal compartment, there is a second layer of fat: the pararenal fat."
        },
        {
          "type": "bullets",
          "items": [
            "Means of fixation:"
          ]
        },
        {
          "type": "para",
          "text": "The kidneys have no attachments within the abdominal cavity. Inside the renal compartment, the kidneys have neither ligaments nor mesenteries. Their means of fixation depend on:"
        },
        {
          "type": "bullets",
          "items": [
            "thoracic suction and diaphragmatic magnetism; (See Chapter 1 Generalities, page…)",
            "the tone of the abdominal muscles;",
            "secondarily, the vascular pedicle;",
            "the volume of perirenal and pararenal fat.",
            "At the inferior part of the renal compartment, the prerenal and retrorenal fasciae do not meet. The renal compartment is therefore open below, forming a true funnel into which the kidney can descend. The position of the kidneys depends solely on their environment. The volume of fat, however, depends on the person’s nutritional and general condition. A reduction in this fat volume, through significant weight loss, causes it to “melt”. The kidney becomes floating and tends to slide downward along the lateral border of the psoas. Failure of these fixation mechanisms predisposes to renal ptosis. (See Pathology, page…)."
          ]
        },
        {
          "type": "xref",
          "label": "See the reference in chapter 1",
          "text": "Generalities",
          "href": "/lecture/chapitre-1?xrefBack=%2Flecture%2Fchapitre-16%23p-anatomie-8&xrefBackLabel=Retour%20au%20chapitre%2016#p-articulations-viscerales-3"
        },
        {
          "type": "sub",
          "text": "Internal structure of the kidneys"
        },
        {
          "type": "bullets",
          "items": [
            "on a medial sagittal section of the kidney, two structures of the parenchyma are distinguished: (figure 16.4)",
            "the cortex: at the periphery;",
            "the medulla: centrally."
          ]
        },
        {
          "type": "para",
          "text": "The cortex sends extensions, the renal columns, toward the centre of the kidney, dividing the medulla into around ten pyramids, the pyramids of Malpighi. Their medial ends are perforated by small openings that drain into the minor calyces, the calyces of Bertin, which receive urine. The union of several minor calyces forms a major calyx. All the major calyces together form the renal pelvis, which collects all the urine. The renal pelvis continues as the ureter."
        },
        {
          "type": "bullets",
          "items": [
            "Nephron: the cortex and medulla of the renal parenchyma are composed of all the nephrons, themselves embedded in connective tissue, blood and lymphatic vessels, and autonomic nerves. Each kidney contains approximately 1,000,000 nephrons."
          ]
        },
        {
          "type": "para",
          "text": "The nephron is the functional unit of the kidney. (figure 16.5) Its purpose is to keep the volume and composition of the internal milieu constant, that is, to maintain homeostasis. It has two parts:"
        },
        {
          "type": "bullets",
          "items": [
            "Glomerulus: it filters the blood plasma; (See Physiology, page…)",
            "Tubule: it reabsorbs and secretes the substances required by the body."
          ]
        }
      ]
    },
    {
      "id": "rapports",
      "title": "Relations",
      "blocks": [
        {
          "type": "sub",
          "text": "Dorsally"
        },
        {
          "type": "bullets",
          "items": [
            "both kidneys are related cranially to the diaphragm and the pleuro-costo-diaphragmatic hiatuses, caudally to the psoas and quadratus lumborum, and more laterally to the transversus abdominis muscle. (figure 16.3)"
          ]
        },
        {
          "type": "para",
          "text": "The 12th intercostal nerve, or subcostal nerve, and the nerves of the lumbar plexus run within the pararenal fatty layer: the iliohypogastric, ilioinguinal and lateral femoral cutaneous nerves. (figure 16.6)"
        },
        {
          "type": "para",
          "text": "Triangle of Jean-Louis Petit and quadrilateral of Grynfelt: these are two regions of the lumbar fossa that constitute weak points of the posterior abdominal wall. (figure 16.7) They allow access to the kidney with little interposition of soft tissue, where there are no bundles of the internal and external oblique muscles. We are in direct contact with the transversus abdominis muscle and, indirectly, with the subcostal nerve and the nerves of the lumbar plexus."
        },
        {
          "type": "rop",
          "body": [
            "Direct-impact trauma, a fall onto the back or abdomen, an accident with major deceleration, a fracture of the lower ribs or deep flank pain should prompt caution. Because of their density and their retroperitoneal position close to the vertebral column, the kidneys may be involved in these traumatic mechanisms.",
            "It is important to ask the patient whether the urine is red, brown or the colour of dark tea, which may suggest haematuria. The presence of blood in the urine, flank pain, malaise, fever, deterioration in general condition or major trauma requires medical assessment.",
            "Within the ROP framework, after medical exclusion, an old trauma of the lumbar fossa may be read as a posterior fixation of the renal compartment, with loss of local mobility and possible irritation of neighbouring tissues. Reflex work then aims to accompany mobility in the renal region, without ever replacing medical diagnosis."
          ]
        },
        {
          "type": "sub",
          "text": "Ventrally"
        },
        {
          "type": "bullets",
          "items": [
            "Right kidney: it is related to: (figure 16.8)",
            "Cranially: the liver through the hepatorenal ligament;"
          ]
        },
        {
          "type": "sub",
          "text": "Ventrally"
        },
        {
          "type": "bullets",
          "items": [
            "the second part of the duodenum through Treitz’s fascia, and the hepatic flexure of the colon;",
            "Caudally: the ileum;",
            "Laterally: the ascending colon, from which it is separated by Toldt’s fascia.",
            "Left kidney: it is related to:"
          ]
        },
        {
          "type": "sub",
          "text": "Ventrally"
        },
        {
          "type": "bullets",
          "items": [
            "the left triangular ligament of the liver, the spleen and the stomach, from which it is separated by the retro-gastric omental bursa, the splenic flexure of the colon, and the pancreas;",
            "Caudally: the jejunum and the left gonadal venous system;",
            "Medially: the duodenojejunal flexure."
          ]
        }
      ]
    },
    {
      "id": "vascularisation",
      "title": "Vascularisation",
      "blocks": [
        {
          "type": "para",
          "text": "The vascular pedicle, formed by the renal artery and vein, enters the hilum at the level of the L1 vertebra."
        },
        {
          "type": "sub",
          "text": "Renal artery"
        },
        {
          "type": "para",
          "text": "Each kidney is supplied by a single artery: the renal artery (figure 16.9), which arises from the aorta just below the superior mesenteric artery. It divides into five terminal segmental arteries that supply the renal parenchyma. These arteries do not anastomose with one another: each vascularised region is independent, allowing partial surgical resection."
        },
        {
          "type": "sub",
          "text": "Renal vein"
        },
        {
          "type": "para",
          "text": "Located anterior to the renal artery, the renal vein differs on the right and left sides. (figure 16.10)"
        },
        {
          "type": "bullets",
          "items": [
            "Right renal vein: it drains directly into the inferior vena cava;",
            "Left renal vein: it is longer than the right. It receives the gonadal, spermatic or ovarian, vein and the left lumbar vein, which drains venous blood from the lumbar vertebrae, so important for hydration of the intervertebral discs.",
            "Aortomesenteric compression syndrome, or nutcracker syndrome (See Chapter 10 Duodenum, page…), corresponds to compression of the left renal vein between the aorta, the superior mesenteric artery and the third part of the duodenum. In ROP clinical reading, this left-sided venous compression may be related to certain patterns of pelvic, lumbar or left genital congestion, without replacing medical assessment of a true nutcracker syndrome. Left-sided varicoceles and varicose veins predominating in the left lower limb should lead us to look for left renal fixation and ptosis of the small intestine."
          ]
        },
        {
          "type": "xref",
          "label": "See the reference in chapter 10",
          "text": "Duodenum",
          "href": "/lecture/chapitre-10?xrefBack=%2Flecture%2Fchapitre-16%23p-vascularisation-5&xrefBackLabel=Retour%20au%20chapitre%2016#sec-presentation"
        },
        {
          "type": "rop",
          "body": [
            "Difference between the two kidneys"
          ]
        },
        {
          "type": "bullets",
          "items": [
            "Right kidney: it could be called the “digestive kidney” because of its proximity to the liver and the ascending colon. Its tendency to migrate downward accentuates digestive problems through the spasms created by its descent, which may be tempting to attribute to appendicitis.",
            "Left kidney: it could be called the “genital kidney”. Its fixation has little effect on the digestive system, apart from spasm of the duodenojejunal flexure, felt as gastralgia. Through its venous relationship with the urogenital sphere, aortomesenteric compression syndrome and fixation of the left kidney can create venous problems of the left testicle, such as varicocele, or of the left labium majus. Sexual problems may be attributed to fixation of the left kidney: premenstrual pelvic heaviness in women, and reduced virility and libido in men. Left-sided lumbosciatica, even after trauma, should prompt us to check the left kidney. Pregnant women may suffer from pregnancy-related lumbar pain linked to compression of the aortomesenteric angle by the developing baby."
          ]
        }
      ]
    },
    {
      "id": "innervation",
      "title": "Innervation",
      "blocks": [
        {
          "type": "para",
          "text": "The kidneys receive autonomic innervation that is predominantly sympathetic. The sympathetic fibres arise from the thoracolumbar levels, join the splanchnic nerves and then the prevertebral plexuses, especially the coeliac, aorticorenal and renal plexuses."
        },
        {
          "type": "para",
          "text": "This innervation accompanies the renal vessels into the hilum and the parenchyma. It acts mainly on vascular calibre, resistance to blood flow, renin secretion by the juxtaglomerular apparatus and tubular reabsorption of sodium and water."
        },
        {
          "type": "para",
          "text": "In ROP clinical reading, this sympathetic predominance explains the value of relating the kidney to blood-pressure regulation, the prevertebral plexuses, the thoracolumbar junction and the deep tensions of the lumbar fossa. Prolonged sympathetic hyperstimulation may contribute to renal vasoconstriction and to a hypertensive terrain."
        }
      ]
    },
    {
      "id": "physiologie",
      "title": "Physiology",
      "blocks": [
        {
          "type": "sub",
          "text": "Mobility"
        },
        {
          "type": "para",
          "text": "The psoas muscle forms a true oblique rail, running caudally and laterally, along which the kidney moves: during inspiration, the diaphragm pushes the kidney caudally. The upper pole is pushed ventrally, while the lower pole descends obliquely from medial to lateral."
        },
        {
          "type": "para",
          "text": "The amplitude of this movement is 3 to 4 cm. This movement is repeated 20,000 times per day. Motility occurs in the same direction, but more slowly, at a rate of 7 times per minute: during “inspir”, the kidney descends; during “expir”, it rises."
        },
        {
          "type": "sub",
          "text": "Role of the kidneys"
        },
        {
          "type": "bullets",
          "items": [
            "Homeostasis: through their many functions, the kidneys participate in the balance of the internal milieu and interact with other organs: the liver, pancreas, heart, lungs, hormonal system and sympathetic nervous system.",
            "Urine formation: this depends on two mechanisms: filtration and reabsorption.",
            "Glomerular filtration: 1,700 L of blood pass through the kidneys each day. 170 L of plasma, free of cells and proteins, are filtered by the glomeruli to form, initially, primary urine.",
            "Tubular reabsorption: because the elimination of final urine, or diuresis, is only 1 to 1.5 L per day, the vast majority of primary urine is then reabsorbed by the renal tubule. This reabsorption enables the body to recover from the glomerular filtrate the substances it needs, which then return to the blood: water, sodium, potassium, calcium, chloride and phosphate, in order to maintain blood osmolarity.",
            "Blood osmolarity corresponds to the concentration of ions required to ensure an adequate level of water in the body; the human body contains approximately 70% water. This reabsorption is dependent on aldosterone, produced by the cortex of the adrenal gland. Aldosterone makes it possible to adjust sodium elimination to the body’s needs. It therefore participates in the regulation of blood volume.",
            "Blood volume is the total volume of blood circulating in the body. By adjusting blood volume, the kidney plays a major role in the regulation of arterial blood pressure.",
            "Regulation of arterial blood pressure: the kidney participates in arterial blood-pressure regulation through several complementary mechanisms.",
            "It acts first through the reabsorption of sodium and water, which directly influences blood volume, that is, the total volume of circulating blood. When blood volume increases, arterial pressure tends to rise; when it decreases, arterial pressure tends to fall.",
            "The kidney also intervenes through renin secretion by the juxtaglomerular apparatus. When renal perfusion pressure falls, or when sodium delivery to the distal tubule decreases, renin is released.",
            "Renin acts on angiotensinogen, produced by the liver, to form angiotensin I. This is then converted into angiotensin II by angiotensin-converting enzyme.",
            "Angiotensin II causes vasoconstriction and stimulates aldosterone secretion by the adrenal cortex. Aldosterone promotes reabsorption of sodium and, with it, water. This entire system, known as the renin-angiotensin-aldosterone system, helps support arterial pressure when the body perceives a fall in perfusion or circulating volume.",
            "Conversely, when arterial pressure rises, the baroreceptors of the carotid sinus and aortic arch participate in a reflex response designed to modulate vascular tone and cardiac activity.",
            "The posterior pituitary gland, under hypothalamic control, secretes ADH, or antidiuretic hormone. This hormone promotes water reabsorption in the kidney. In ADH deficiency, or when the kidney responds insufficiently to this hormone, marked polyuria may occur, as in diabetes insipidus.",
            "Regulation of blood glucose: under normal conditions, glucose is completely reabsorbed. In diabetes mellitus, glucose appears in the urine when the maximum tubular reabsorption capacity is exceeded, producing glycosuria. Glycosuria is proportional to blood glucose levels.",
            "Regulation of acid-base balance: blood pH is around 7.4. To buffer acidity, the kidneys excrete hydrogen ions, H+, in the urine and retain bicarbonate ions, HCO3. At the same time, respiration is activated so that the lungs eliminate carbon dioxide. In persistent acidosis, acid is stored in the body’s connective tissues. Excess acidity increases inflammatory reactions, bone demineralisation and exaggerated responses to stress."
          ]
        },
        {
          "type": "sub",
          "text": "Among foods that cause acidosis, we may mention"
        },
        {
          "type": "bullets",
          "items": [
            "sugar first of all, especially when taken on an empty stomach;",
            "alcoholic drinks;",
            "animal fats;",
            "red meat and offal;",
            "fried foods."
          ]
        },
        {
          "type": "sub",
          "text": "Among alkaline foods, we may mention"
        },
        {
          "type": "bullets",
          "items": [
            "potatoes, but not chips/French fries;",
            "onion and garlic;",
            "carrot;",
            "cabbage;",
            "almond and hazelnut;",
            "lemon, in small quantities.",
            "Endocrine function: the kidney produces erythropoietin, mainly in specialised interstitial cells of the cortex and outer medulla. This hormone increases red blood cell production. The kidney also activates vitamin D, which contributes to regulation of blood calcium."
          ]
        }
      ]
    },
    {
      "id": "pathologies-courantes",
      "title": "Common pathologies",
      "blocks": [
        {
          "type": "para",
          "text": "As with all other organs, functional disorders of the kidneys often resemble those of early renal insufficiency. Dorsal pain or lumbar pain is not always mechanical, even when it appears after exertion. An underlying renal problem is often on the verge of decompensation."
        },
        {
          "type": "para",
          "text": "At the slightest doubt, the patient should be referred to their physician, who will perform investigations such as urinalysis and urine culture, intravenous urography, ultrasound or CT scanning."
        },
        {
          "type": "sub",
          "text": "Exclusion diagnoses / red flags"
        },
        {
          "type": "bullets",
          "items": [
            "acute renal colic with dysuria and proteinuria;",
            "haematuria, meaning blood in the urine;",
            "fever;",
            "urinary tract infection, including pyelonephritis or glomerulonephritis;",
            "weight loss and loss of appetite;",
            "general fatigue, depression;",
            "palpable flank mass, suggesting cancer;",
            "nocturnal flank pain that wakes the patient and is accompanied by fever;",
            "hyperuricaemia, excess uric acid;",
            "polyuria in a diabetic patient;",
            "polycystic kidney disease;",
            "sudden-onset varicocele;",
            "kidney cancer."
          ]
        },
        {
          "type": "sub",
          "text": "Indications"
        },
        {
          "type": "bullets",
          "items": [
            "functional pathologies",
            "lumbar pain at “cockcrow”, around 4 or 5 a.m.;",
            "morning thirst;",
            "deep morning fatigue, sometimes described as essential fatigue;",
            "congested eyes with “bags” under the eyes;",
            "arterial hypertension;",
            "after a fall onto the back, coccyx, heels or abdomen;",
            "microlithiasis, meaning stones smaller than 5 mm;",
            "after renal lithiasis and microlithiasis;",
            "lumbocruralgia;",
            "infertility;",
            "reduced libido;",
            "joint pain due to excess uric acid;",
            "urinary infection with “clear urine”, or apyretic urinary infection;",
            "pregnancy-related lumbar pain; (See Chapter 19 Female Genital Organs, page…)",
            "benign prostatic hypertrophy; (See Chapter 20 Male Genital Organs, page…)",
            "post-traumatic nervous depression.",
            "Renal ptosis: strictly speaking, the kidneys have no attachments; their means of fixation depend on their environment. (page…)",
            "The radiological sign of a ptotic kidney is loss of contact between its upper pole and the 11th rib, which causes it to lose the effect of thoracic suction and diaphragmatic magnetism.",
            "Ptosis may be congenital or acquired:",
            "Congenital, or ectopic, ptosis: the adrenal gland follows the kidney. We have little effect, apart from stimulating the kidney.",
            "Acquired ptosis: the adrenal gland remains in place. Pain is accentuated by prolonged standing and by drinking a large quantity of fluid. It is relieved in the supine position. The causes are:",
            "fall onto the coccyx or heels;",
            "abdominal hypotonia;",
            "after a difficult or excessively rapid delivery;",
            "significant weight loss;",
            "severe or chronic cough;",
            "post-infectious or surgical adhesions;",
            "fixations of the 11th and 12th ribs, from T10 to L1;",
            "psoas problem, or psoitis.",
            "Anterior fixations: the right kidney is more prone to anterior fixations and ptosis. Whether the kidney is ptotic or fixed, however, it has lost its normal mobility.",
            "Women are more affected by ptosis because of pregnancy, childbirth, uterine retroversion and menopause. Three degrees of ptosis are distinguished: (figure 16.11)",
            "First degree: “intercostal” kidney, in which irritation of the 12th intercostal nerve radiates toward the greater trochanter.",
            "Symptoms: the person holds the flank, finds deep breathing difficult, and tolerates coughing and sneezing poorly.",
            "Second degree: “abdominogenital” or “femoral cutaneous” kidney.",
            "Symptoms: irritation of the iliohypogastric, ilioinguinal and lateral femoral cutaneous nerves of the lumbar plexus radiates to the lower abdominal region, the scrotum or labia majora, and the lateral aspect of the thigh. The kidney is in external rotation. Traction on the vascular pedicle creates arterial hypertension.",
            "Third degree: “femoral” or “pelvic” kidney: the kidney is displaced because it has lost contact with the liver and diaphragm. It is in medial rotation and is blocked against the psoas.",
            "Symptoms: knee pain, without any history of trauma, due to irritation of the femoral nerve; psoas spasm; urinary tract infections; lithiasis: the ureter kinks, urinary dynamics decrease, thereby favouring lithiasis and urinary infections; and colonic or uterine irritation. An unexplained urinary infection should suggest renal ptosis.",
            "Pregnancy-related low back pain: in the parturient woman, it is only exceptionally osteoarticular."
          ]
        },
        {
          "type": "xref",
          "label": "See the reference in chapter 19",
          "text": "Female Genital Organs",
          "href": "/lecture/chapitre-19?xrefBack=%2Flecture%2Fchapitre-16%23p-pathologies-courantes-5&xrefBackLabel=Retour%20au%20chapitre%2016#sec-ovaires-trompes-presentation"
        },
        {
          "type": "xref",
          "label": "See the reference in chapter 20",
          "text": "Male Genital Organs",
          "href": "/lecture/chapitre-20?xrefBack=%2Flecture%2Fchapitre-16%23p-pathologies-courantes-5&xrefBackLabel=Retour%20au%20chapitre%2016#sec-presentation"
        },
        {
          "type": "sub",
          "text": "Causes"
        },
        {
          "type": "bullets",
          "items": [
            "uterovascular compression;",
            "pericaecal, sigmoid or obturator tension;",
            "sequelae of appendicectomy, causing constraint on the right kidney, the right lumbar fossa, the inferior vena cava and the nerves of the lumbar plexus by the baby’s head. The parturient woman is advised to lie on her left side;",
            "vascular constraint of the right common iliac artery on the left common iliac vein, known as May-Thurner or Cockett syndrome;",
            "constraint on the left kidney."
          ]
        },
        {
          "type": "rop",
          "body": [
            "The purpose of our reflex action is not to “raise” the ptotic kidney, but to free it from the mechanical osteo-musculo-articular or visceral constraints acting on it."
          ]
        },
        {
          "type": "sub",
          "text": "Posterior fixations: the left kidney is more prone to posterior fixations. A fall onto the back, a direct blow to the lumbar fossa, costal trauma, or a vertebral fracture of T12, L1 or L2 may produce trauma of the kidney against the transverse processes of the lumbar vertebrae. The posterior surface of the renal parenchyma cracks, and the pararenal fat becomes fibrotic after the trauma."
        },
        {
          "type": "para",
          "text": "The kidney loses its mobility and the nerves of the lumbar plexus are compressed, producing pain in the lumbar region, the iliac crest, the trochanteric region and the proximal thigh. Intrauterine devices and erectile difficulties in men often affect the motility of the left kidney."
        },
        {
          "type": "para",
          "text": "Muscle spasms of the paravertebral muscles, the psoas and the quadratus lumborum are responsible for lumbago occurring during an apparently trivial effort. The patient thinks that the “wrong movement” caused the blockage. In reality, the underlying renal problem was simply on the verge of decompensation. Traumatic renal fixations affect men more often."
        },
        {
          "type": "rop",
          "body": [
            "The plantar reflex zone of the right kidney is of particular interest in anterior fixations. The caecum and the right ovary should be associated with the right kidney after appendicectomies.",
            "The dorsal reflex zone is of particular interest in posterior fixations. The left kidney, spleen and urogenital sphere should be associated."
          ]
        }
      ]
    },
    {
      "id": "relations-viscero-somatiques",
      "title": "Viscerosomatic relations",
      "blocks": [
        {
          "type": "bullets",
          "items": [
            "T11-T12 vertebrae and the last two ribs;",
            "L1 to L3;",
            "Hip and knee;",
            "Irritation of the medial arch of the foot through irritation of the saphenous nerve, the terminal branch of the femoral nerve, often in relation to a renal problem."
          ]
        }
      ]
    },
    {
      "id": "relations-viscero-emotionnelles",
      "title": "Visceroemotional relations",
      "blocks": [
        {
          "type": "para",
          "text": "The kidneys express feelings of repressed desire, deep existential sadness at the end of life, and death. They often reflect conflicts with the parents or between the parents. The right kidney must be distinguished from the left kidney:"
        },
        {
          "type": "bullets",
          "items": [
            "Right kidney, or “digestive kidney”: it serves as an emotional overflow for the liver. It is the organ of intense repressed anger dating back to early childhood, in total fusion with the mother or, conversely, in total opposition, preventing the child from developing their own identity. The right kidney expresses the person who wants to dominate but is afraid of dominating.",
            "Left kidney, or “genital kidney”: it is the organ of the “genetic self”, of genitality linking us to those who gave us life, to our roots, and to the sexual potential to transmit the life we have received. This does not mean impotence or frigidity, but rather the fear of giving life.",
            "The left kidney is the organ of deep, essential fear within oneself: fear of violence, abandonment or being killed, distinct from superficial fear. The left kidney is linked to significant repression and inhibition of personal development. It is also the organ that expresses the deep power of the being, hence at times the violence expressed by a drive and by the need to dominate others."
          ]
        }
      ]
    },
    {
      "id": "conseils",
      "title": "Advice",
      "blocks": [
        {
          "type": "bullets",
          "items": [
            "Advise drinking often but only a little at a time, and limiting consumption of animal proteins, especially red meat, cheese and fats, particularly in the evening;",
            "Lie preferably on the left side to reduce venous constraints. Add breathing exercises;",
            "In the quadruped position, inhale while allowing the abdomen to drop, then exhale while drawing the abdomen in, about ten times;",
            "In men and women: self-mobilisation of the kidneys, with the knees bent in the supine position, thumbs placed between the 12th rib and the iliac crest, pressing them ventrally.",
            "While tilting the knees 45° to the right and left, engage the thumbs into the quadrilateral of Grynfelt in order to push the kidneys ventrally. Repeat about ten times."
          ]
        }
      ]
    },
    {
      "id": "zones-reflexes-podales",
      "title": "Foot reflex zones",
      "blocks": [
        {
          "type": "para",
          "text": "The kidney is a dense organ. Its reflex zone is clearly distinguished from the reflex zones of neighbouring hollow organs."
        },
        {
          "type": "sub",
          "text": "General adaptation syndrome"
        },
        {
          "type": "bullets",
          "items": [
            "Vagus nerve X; (figures 4.11 and 4.17)",
            "Spinal column, costotransverse joints (thoracic laterovertebral ganglion chain, T7-T11-L1, coccyx); (figures 4.23 and 4.29 and 4.32)",
            "Prevertebral plexus; (figures 16.12 and 16.13)",
            "Adrenal glands: (figures 16.12, 16.13 and figure 16.13 ter)",
            "Lumbar plexus L1 to L4 and its branches. (See Réflexothérapie occipito-podale et système neuro-méningé, Elsevier Masson, pages 25 to 28)"
          ]
        },
        {
          "type": "sub",
          "text": "Locoregional syndrome"
        },
        {
          "type": "sub",
          "text": "Kidney"
        },
        {
          "type": "sub",
          "text": "Plantar surface"
        },
        {
          "type": "bullets",
          "items": [
            "(figures 16.12, 16.13 and 16.14)",
            "Lower pole: it is at the level of the L3 or L4 vertebra, in line with the first and second toes, above the anterior border of the heel;",
            "Upper pole: it is at the level of the T12 vertebra;",
            "Adrenal gland: it is at the summit of the upper pole of the kidney; (figure 16.15)",
            "Lateral border: it is convex;",
            "Medial border: it is concave. The hilum is located at the level of the L1 vertebra."
          ]
        },
        {
          "type": "sub",
          "text": "Dorsal surface"
        },
        {
          "type": "bullets",
          "items": [
            "the triangle of Jean-Louis Petit and the quadrilateral of Grynfelt correspond to the cuboid bone. (figure 16.17)"
          ]
        },
        {
          "type": "sub",
          "text": "Combined manoeuvre"
        },
        {
          "type": "bullets",
          "items": [
            "associate the plantar and dorsal surfaces of the kidney: (figure 16.18)",
            "Orient the two thumbs toward each other, one on the dorsal surface and the other on the plantar surface;",
            "Stimulate their reflex zone, then, with the help of breathing, follow the movement caudally during inspiration and cephalically during expiration. This is a good way to test kidney mobility.",
            "Using the same manoeuvre, but without breathing, follow the motility of the kidney.",
            "Liver, for the right kidney.",
            "Spleen, for the left kidney.",
            "In pregnant women: associate the left kidney and the urogenital sphere."
          ]
        },
        {
          "type": "sub",
          "text": "Limbic system"
        },
        {
          "type": "bullets",
          "items": [
            "Limbic brain-kidney balance: listening-induction, with one thumb on the kidney and the other thumb on the limbic brain. (figure 1.12)"
          ]
        }
      ]
    }
  ]
}
