import type { Block, Chapter, Section } from './types'

const para = (text: string): Block => ({ type: 'para', text })
const sub = (text: string): Block => ({ type: 'sub', text })
const bullets = (...items: string[]): Block => ({ type: 'bullets', items })
const rop = (...body: string[]): Block => ({ type: 'rop', body })
const note = (label: string, ...body: string[]): Block => ({ type: 'note', label, body })
const section = (id: string, title: string, blocks: Block[]): Section => ({ id, title, blocks })

export const chapter4En: Chapter = {
  slug: 'chapter-4', number: '4', title: 'Autonomic Nervous System (ANS)', sections: [
    section('presentation', '1. Overview', [
      note('INTRODUCTION',
        'The autonomic nervous system (ANS) continuously adjusts the function of the viscera, glands, vessels and many internal functions. In the ROP protocol, it corresponds to Level 2 — Neurovegetative Regulation and Adaptation.',
        'This chapter progressively presents its major pathways: parasympathetic and sympathetic systems, vagus nerve, ganglion chains, splanchnic nerves, prevertebral and pelvic plexuses, enteric nervous system and adrenal glands. The ANS works in both directions: it transmits commands to the viscera while continuously receiving information from them.',
        'The summary diagram below provides an overview of this anatomical and functional thread before each component and its relationship with the reflex zones used in ROP are examined.'),
      sub('1.1. Two Systems: Parasympathetic and Sympathetic'),
      para('The parasympathetic and sympathetic systems are the two major efferent components of the ANS. They do not function as two invariably opposing systems: their actions are complementary, coordinated and variable according to the organ and context.'),
      sub('1.2. General Physiology of the ANS'),
      para('The ANS regulates digestive, cardiovascular, respiratory, urinary, genital, glandular and vascular functions, among others. Its general role is to enable the body to adapt while helping to maintain homeostasis.'),
      para('This adaptation is particularly called upon during exertion, pain, stress, emotions, temperature changes, eating and sleep.'),
      sub('1.3. Functional Differences'),
      bullets(
        'Parasympathetic system: contributes in particular to digestion, secretions, slowing of the heart, recovery and several pelvic functions.',
        'Sympathetic system: contributes in particular to cardiovascular adaptation, vasomotor control, thermoregulation, energy mobilisation and responses to exertion or constraint.',
        'Viscera: most receive dual autonomic modulation organised according to function and context.',
        'Body wall, limbs and integument: vasomotor control, sweating and piloerection are governed primarily by the sympathetic system.',
        'Erectile tissues: the vasodilation involved in erection depends largely on the pelvic parasympathetic pathways.'),
      sub('1.4. Parasympathetic–Sympathetic Relationship'),
      para('The two systems are closely associated within the visceral plexuses and networks. It is therefore often artificial to seek absolute dominance of one over the other. Functional regulation depends above all on their ability to adjust and coordinate.'),
      rop(
        'The ANS is one of the keys to the ROP approach. In keeping with the “nerve first” principle, when faced with a functional visceral disorder, clinical reasoning first looks for a possible origin at Level 1 and/or Level 2 before considering locoregional work on the viscus itself.',
        'In the ROP model, the origin of a functional disorder is therefore considered more often to lie upstream than primarily within the viscus; direct involvement of the viscus, particularly after local trauma, is a special situation to be sought in the history. Level 2 is intended in particular to take account of the autonomic pathways involved in regulating the viscus. Symptoms are not, however, interpreted as the automatic consequence of a “sympathetic/parasympathetic imbalance”, and any organic or pathological cause requiring medical assessment must of course be excluded.'),
      sub('1.5. Relationship Between the ANS and the Endocrine System'),
      para('The ANS is closely connected to the endocrine system through the hypothalamus and pituitary gland. Autonomic nervous responses and hormonal responses jointly contribute to adaptation.'),
      para('In neurotransmitter terms, acetylcholine is used by sympathetic and parasympathetic preganglionic neurons and by parasympathetic postganglionic neurons. Noradrenaline is the principal sympathetic postganglionic transmitter, with several functional exceptions.'),
      sub('1.6. Relationship Between the ANS and the Somatic Nervous System (SNS)'),
      para('The autonomic and somatic systems are anatomically distinct but functionally closely associated. Spinal nerves carry, among other fibres, sympathetic fibres intended for the skin, blood vessels and sweat glands. In the pelvis, autonomic and somatic functions must be coordinated, for example between the pelvic pathways and the pudendal nerve.'),
      para('This proximity does not mean that a somatic nerve becomes an autonomic pathway; it reflects the integration of several systems within the same functional territory.'),
      para('See also Occipito-Podal Reflexotherapy and the Neuro-Meningeal System — spinal and cranial nerves.'),
      sub('1.7. Relationship Between the ANS and Sleep'),
      para('Rumination, worries and stress of various kinds can disturb sleep, reduce its duration and, above all, impair its quality.'),
      para('Regular, sufficient sleep contributes to proper neuroendocrine function and regulation of the autonomic nervous system. Sleep deprivation can alter heart-rate variability and promote a relative increase in sympathetic activity with reduced vagal modulation. In the long term, insufficient sleep is associated with an increased risk of cardiometabolic and mood disorders.'),
      para('Glial cells also participate in adaptations related to the sleep–wake cycle. Experimental work in mice has shown that acute or chronic sleep deprivation increases astrocytic phagocytic activity on certain presynaptic components and is accompanied by microglial activation. These findings do not establish that astrocytes eliminate synapses generally in humans.'),
      rop('Autonomic balance cannot be assessed independently of sleep. Insufficient night-time recovery can perpetuate fatigue, hypervigilance and difficulty adapting; it should therefore be explored in the history and incorporated into the reassessment of Level 2.'),
    ]),
    section('organisation-du-sna', '2. Organization of the ANS', [
      para('The ANS comprises efferent and afferent pathways. This bidirectional circulation is essential to understanding it: the nervous system commands the viscera, but also continuously receives information about their state.'),
      sub('2.1. Visceromotor Function'),
      para('Sympathetic and parasympathetic pathways modulate smooth muscle, cardiac muscle, glands and internal sphincters. Most autonomic efferent pathways comprise a preganglionic neuron followed by a postganglionic neuron.'),
      sub('2.2. Visceral Sensation'),
      para('The viscera possess mechanoreceptors, chemoreceptors and nociceptors. Visceral afferents may travel through the vagus nerve or through spinal pathways accompanying the splanchnic and pelvic nerves.'),
      para('A sensory fibre that travels with a sympathetic or parasympathetic pathway remains a visceral afferent; it must not be confused with an efferent autonomic command.'),
      sub('2.3. Enteric Nervous System (ENS)'),
      para('The digestive tract possesses a highly developed intrinsic network, the enteric nervous system. It can locally organise much of digestive motility and secretion while remaining modulated by parasympathetic and sympathetic pathways.'),
    ]),
    section('parasympathique-viscero-moteur', '3. Visceromotor Parasympathetic System', [
      para('The parasympathetic system has cranial and sacral origins. It contributes in particular to secretions, digestive motility, slowing of the heart and pelvic functions.'),
      sub('3.1. Cranial Parasympathetic System — Cephalic Territory'),
      para('Parasympathetic fibres intended for the head travel mainly in cranial nerves III, VII and IX. They relay in peripheral ganglia before joining their target organs.'),
      bullets('Oculomotor nerve III → ciliary ganglion → miosis and accommodation.', 'Facial nerve VII → pterygopalatine and submandibular ganglia → lacrimal, nasal and salivary secretions.', 'Glossopharyngeal nerve IX → otic ganglion → parotid secretion.'),
      para('See also Occipito-Podal Reflexotherapy and the Neuro-Meningeal System, Chapter 8 — Cranial Nerves and Ganglia.'),
      rop('In ROP cartography, these pathways are approached through landmarks at the skull base and the cephalic parasympathetic ganglia.'),
      sub('3.2. Vagus Nerve X — Cervicothoracoabdominal Territory'),
      para('The vagus nerve is the major parasympathetic pathway to the cervical and thoracic organs and a large part of the abdomen. Its efferent neurons arise in particular from the dorsal motor nucleus of the vagus and the nucleus ambiguus, located in the medulla oblongata.'),
      para('It leaves the skull through the jugular foramen, descends through the neck, crosses the thorax in contact with mediastinal organs, then accompanies the oesophagus through the diaphragm before distributing to abdominal territories.'),
      rop('The vagus is an important Level 2 target because of its role in cardiorespiratory and digestive modulation, but also because of its substantial afferent component.'),
      sub('3.2.1. Cranial Course: Jugular Foramen'),
      para('The vagus leaves the skull through the jugular foramen with the glossopharyngeal nerve IX and accessory nerve XI. The cell bodies of many visceral afferents are located in its inferior ganglion.'),
      para('See Occipito-Podal Reflexotherapy and the Neuro-Meningeal System — skull base and jugular foramen.'),
      sub('3.2.2. Cervical Level'),
      para('In the neck, the vagus descends within the carotid sheath. It gives rise in particular to the superior laryngeal nerve and participates in the pharyngeal and laryngeal networks.'),
      para('The carotid sinus contains baroreceptors whose afferents travel mainly through the glossopharyngeal nerve IX; the vagus contributes in particular to afferents from the aortic arch.'),
      rop('The carotid sinus and carotid body are important physiological landmarks. Any faintness, syncope, chest pain or dyspnoea requires the procedure to be stopped and the patient referred for medical assessment.'),
      sub('3.2.3. Thoracic Level'),
      para('In the thorax, the vagus nerves participate in the cardiac, bronchopulmonary and oesophageal plexuses. The vagus contributes to slowing heart rate, modulating atrioventricular conduction, bronchoconstriction and bronchial secretions, as well as oesophageal motility.'),
      para('The right recurrent laryngeal nerve loops around the right subclavian artery; the left loops around the aortic arch.'),
      rop('The cardiac, bronchopulmonary and oesophageal plexuses are crossroads where vagal, sympathetic and afferent fibres meet. In ROP, they are regarded as regional interfaces rather than isolated targets.'),
      sub('3.2.4. Diaphragmatic Level'),
      para('The two vagal trunks accompany the oesophagus through the oesophageal hiatus. The anterior vagal trunk derives mainly from the left vagus and the posterior trunk mainly from the right vagus.'),
      para('The diaphragm is not part of the ANS, but it forms a functional Level 2 interface through its relationships with breathing, thoracoabdominal pressures and the structures that pass through it.'),
      sub('3.2.5. Abdominal Level'),
      para('In the abdomen, vagal branches join the periarterial and prevertebral plexuses and modulate, in particular, the stomach, duodenum, small intestine and proximal colon.'),
      para('The transition to the pelvic parasympathetic territory is classically situated toward the distal transverse colon and the region of the left colic flexure, with anatomical variability.'),
      rop('At digestive Level 2, the vagus is integrated with the prevertebral plexuses and ENS. The clinical aim is to support functional coordination rather than systematically opposing the vagus and sympathetic system.'),
      sub('3.3. Pelvic (or Sacral) Parasympathetic System'),
      para('The pelvic splanchnic nerves arise mainly from sacral segments S2 to S4. They join the inferior hypogastric plexus and participate in regulating the bladder, rectum, distal colon and genital organs.'),
      bullets('Micturition: contribution to detrusor contraction and the coordinated reduction of urethral resistance.', 'Defecation: contribution to rectal motility and relaxation of the internal anal sphincter.', 'Sexual functions: contribution to pelvic vascular and reflex responses.'),
      para('The pelvic parasympathetic system must be distinguished from the pudendal nerve, a somatic pathway also arising from S2–S4 and involved in the external sphincters and perineum.'),
      rop('The segmental overlap at S2–S4 between pelvic autonomic pathways and somatic pathways is a particularly relevant territory for studying regional convergences in ROP.'),
    ]),
    section('nerf-vague-viscero-sensitif', '4. Viscerosensory Vagus Nerve', [
      para('The vagus nerve is predominantly afferent: a large proportion of its fibres transmit information from the viscera to the brainstem. This sensory function is essential to the continuous dialogue between organs and higher centres.'),
      sub('4.1. Interoception'),
      para('The cell bodies of many vagal afferents are located in the inferior vagal ganglion. Their central processes travel mainly to the nucleus of the solitary tract (NTS), then to brainstem, hypothalamic and cortical networks involved in interoception.'),
      sub('4.2. Functions'),
      bullets('Cardiovascular and respiratory reflexes.', 'Digestive regulation and satiety signals.', 'Coughing, swallowing, nausea and vomiting according to the territories stimulated.', 'Participation in brain–gut communication and neuroimmune loops.'),
      rop('At Level 2, the vagus is approached as a major bidirectional communication pathway. Neuromodulation data make it possible to identify plausible circuits.'),
    ]),
    section('sympathique-viscero-moteur', '5. Visceromotor Sympathetic System', [
      sub('5.1. Spinal Origin of the Sympathetic System'),
      para('Sympathetic preganglionic neurons are located mainly in the intermediolateral column of the spinal cord between T1 and L2. Their axons leave the cord through the ventral roots, join the spinal nerves and then the sympathetic chain through the white rami communicantes.'),
      para('From the paravertebral chain, fibres may relay at the same level, ascend or descend before relaying, or cross the chain without synapsing to form splanchnic nerves destined for the prevertebral plexuses. This organisation is the starting point for sympathetic pathways to cephalic, thoracic, abdominal and pelvic territories.'),
      sub('5.2. Metameric Organization'),
      para('The thoracolumbar origin of the sympathetic system accounts for the existence of segmental functional territories. Exact levels vary according to the organs and individuals and must be used as anatomical landmarks, not as absolute correspondences.'),
      sub('5.3. Thoracic Ganglion Chain'),
      para('The thoracic sympathetic chain runs alongside the costovertebral joints. White rami communicantes bring preganglionic fibres from the spinal nerves; grey rami communicantes redistribute postganglionic fibres to the spinal nerves.'),
      para('Fibres destined for abdominal viscera may pass through the thoracic ganglia without synapsing and form the splanchnic nerves.'),
      sub('5.3.1. Recurrent Meningeal Branches'),
      para('The recurrent meningeal branches return toward the vertebral canal and participate in the innervation of the spinal meninges, discs and several vertebral structures.'),
      rop('The proximity between spinal nerves, costovertebral structures, meningeal branches and the sympathetic chain forms a relevant regional crossroads.'),
      para('See Occipito-Podal Reflexotherapy and the Neuro-Meningeal System — spinal meninges and spinal nerves.'),
      sub('5.4. Cervical Ganglion Chain'),
      para('The cervical chain classically comprises a superior cervical ganglion, an inconstant middle ganglion and an inferior cervical ganglion, often associated with the first thoracic ganglion to form the stellate ganglion.'),
      sub('5.4.1. Inferior Cervical or Stellate Ganglion'),
      para('The stellate ganglion is a cervicothoracic crossroads related to the upper limb, cardiac pathways and several periarterial plexuses.'),
      rop('In ROP interpretation, this region is important because of its anatomical connections, but vertigo, tinnitus, upper-limb pain or capsulitis must not automatically be attributed to the stellate ganglion.'),
      sub('5.4.2. Middle Cervical Ganglion'),
      para('The middle cervical ganglion is inconstant and may merge with neighbouring ganglia. It contributes in particular to thyroid and cardiac branches.'),
      sub('5.4.3. Superior Cervical Ganglion'),
      para('The superior cervical ganglion distributes sympathetic fibres to the head and neck, particularly through the pericarotid plexuses, and also gives rise to pharyngeal, laryngeal and cardiac branches.'),
      rop('The superior cervical ganglion is another craniocervical crossroads. In ROP, it can be incorporated into regional assessment without attributing complex symptoms of cervical, vascular, vestibular or neurological origin to a single structure.'),
      para('See Occipito-Podal Reflexotherapy and the Neuro-Meningeal System — craniocervical junction and cranial nerves.'),
      sub('5.5. Lumbar Ganglion Chain'),
      para('The lumbar sympathetic chain continues over the anterolateral surface of the vertebral bodies, close to the psoas and diaphragmatic crura, and participates in abdominopelvic autonomic pathways.'),
      rop('The relationships between the lumbar chain, psoas and diaphragm justify a locoregional assessment. Tension in the psoas or diaphragm must not, however, be regarded as the automatic cause of dysfunction in the sympathetic ganglia or a viscus.'),
      sub('5.6. Sacral and Coccygeal Ganglion Chain'),
      para('The sympathetic chain continues over the anterior surface of the sacrum and ends caudally at the ganglion impar. It contributes to autonomic pathways serving pelvic territories.'),
      rop('Trauma to the sacrum or coccyx can coexist with pelvic pain and dysfunction. In ROP, these relationships are explored as regional elements, without presuming an automatic effect on the entire sympathetic chain or dura mater.'),
      sub('5.7. Splanchnic Nerves'),
      para('The thoracic and lumbar splanchnic nerves carry mainly sympathetic preganglionic fibres to the prevertebral plexuses. They may also accompany visceral afferents ascending toward the spinal ganglia and spinal cord.'),
      para('The greater, lesser and least thoracic splanchnic nerves and then the lumbar splanchnic nerves are classically distinguished; their distributions overlap and show anatomical variability.'),
    ]),
    section('sympathique-somato-viscero-sensitif', '6. Somatovisceral Sensory Sympathetic System', [
      para('Visceral sensory fibres travel with sympathetic pathways before reaching their cell bodies in the spinal ganglia.'),
      sub('6.1. Nociception and Visceral Afferents'),
      para('Spinal visceral afferents provide information in particular about distension, ischaemia, inflammation and pain. They reach the spinal cord through the dorsal roots.'),
      sub('6.2. Somatovisceral Convergence'),
      para('In the dorsal horn, some neurons receive both visceral and somatic information. This convergence contributes to referred pain and to certain reflex muscular or cutaneous responses.'),
      rop('Spinal relationships between visceral and somatic afferents provide a neuroanatomical framework for referred pain and viscerosomatic relationships.'),
      para('See the Viscerosomatic Relationships sections in the organ chapters.'),
    ]),
    section('chaine-plexique-prevertebrale-ou-pre-aortique', '7. Prevertebral (or Preaortic) Plexus Chain', [
      para('The prevertebral plexuses are situated around the major arterial axes of the abdomen. They bring together sympathetic, parasympathetic and visceral afferent fibres before their distribution to the organs.'),
      sub('7.1. Main Plexuses'),
      bullets('Coeliac plexus: upper abdominal territories, particularly the stomach, liver, pancreas, spleen and duodenum.', 'Superior mesenteric plexus: small intestine and proximal colon.', 'Aorticorenal plexus: kidney, adrenal gland and associated gonadal pathways.', 'Inferior mesenteric plexus: distal colon.', 'Superior hypogastric plexus: transition to the pelvic autonomic networks.'),
      sub('7.2. Function'),
      para('These plexuses are distribution crossroads. Vagal and sympathetic pathways mingle there with visceral afferents according to territory.'),
      rop('In the ROP model, the reflex zones of the prevertebral plexuses are used as landmarks for regional neurovegetative regulation.'),
    ]),
    section('plexus-previsceral-pelvien', '8. Pelvic Previsceral Plexus', [
      sub('8.1. Inferior Hypogastric Plexus'),
      para('The inferior hypogastric plexus is a paired network situated on the lateral walls of the pelvis. It receives sympathetic fibres descending notably through the hypogastric nerves and parasympathetic fibres from the pelvic splanchnic nerves S2–S4.'),
      sub('8.2. Function'),
      para('Its branches are distributed to the bladder, rectum, internal genital organs and erectile tissues. Pelvic function depends on coordination between autonomic and somatic pathways, especially the pudendal pathways.'),
      rop('The inferior hypogastric plexus is one of the best examples of a regional autonomic crossroads at Level 2. It explains why pelvic functions never depend on a single pathway.'),
    ]),
    section('systeme-nerveux-intrinseque-ou-enterique-sne', '9. Intrinsic or Enteric Nervous System (ENS)', [
      para('The enteric nervous system is situated in the wall of the digestive tract. It has its own sensory neurons, interneurons and motor neurons and can locally organise many digestive reflexes.'),
      sub('9.1. Enteric Plexuses'),
      bullets('Auerbach’s myenteric plexus: between the muscle layers; major role in motility.', 'Meissner’s submucosal plexus: in the submucosa; role in secretion, local exchange and regulation of the mucosa.'),
      para('Interstitial cells of Cajal are not neurons; they contribute to the generation and coordination of electrical slow waves.'),
      sub('9.2. ANS–ENS Interface'),
      para('The ENS can function with substantial local autonomy, but it remains modulated by parasympathetic and sympathetic pathways and participates in brain–gut communication.'),
      rop('At digestive Level 2, the ENS is regarded as the intrinsic interface of the viscus with which extrinsic autonomic pathways interact. The reflex zones remain those of the digestive territory concerned.'),
    ]),
    section('glandes-surrenales', '10. Adrenal Glands', [
      para('The adrenal glands illustrate the continuity between the autonomic nervous system and hormonal regulation.'),
      sub('10.1. Adrenal Medulla'),
      para('The adrenal medulla directly receives sympathetic preganglionic fibres. Chromaffin cells release mainly adrenaline and noradrenaline into the circulation, contributing to the acute sympathoadrenal response.'),
      sub('10.2. Adrenal Cortex'),
      para('The adrenal cortex produces cortisol, aldosterone and adrenal androgens, among other hormones. Cortisol depends on the hypothalamic–pituitary–adrenal axis; aldosterone is regulated mainly by the renin–angiotensin system and plasma potassium.'),
      rop('At Level 2, the adrenal glands are regarded as a neuroendocrine interface of adaptation. Their ROP cartography must not be equated with direct stimulation of hormone secretion.'),
    ]),
    section('zones-reflexes-podales', '11. Foot Reflex Zones', [
      sub('11.1. Cranial Parasympathetic System — Cephalic Territory'),
      { type: 'leadBullets', items: [
        { label: 'Foot reflex zones', text: 'plantar surface of the toes (skull base):' },
        { label: 'Cranial nerves III, VII and IX in the skull-base foramina', text: 'phalanges of the four lesser toes. (Cranial nerves and ganglia: see Occipito-Podal Reflexotherapy and the Neuro-Meningeal System, Chapter 8)' },
        { label: 'Cranial nerve III (superior orbital fissure)', text: 'medial shaft–head junction of the middle phalanx of the second toe;' },
        { label: 'Ciliary ganglion', text: 'medial shaft–base junction of the distal phalanx of the second toe' },
        { label: 'Maxillary nerve (foramen rotundum)', text: 'lateral shaft of the middle phalanx of the second toe' },
        { label: 'Pterygopalatine ganglion', text: 'medial part of the shaft of the middle phalanx of the second toe' },
        { label: 'Mandibular nerve (foramen ovale)', text: 'lateral shaft of the middle phalanx of the third toe' },
        { label: 'Submandibular and sublingual ganglia (floor of the mouth)', text: 'region immediately proximal to the head of the distal phalanges of the toes' },
        { label: 'Otic ganglion', text: 'medial part of the shaft of the middle phalanx of the third toe' },
      ] },
      sub('11.2. Vagus Nerve X — Cranial Course / Jugular Foramen'),
      para('Foot reflex zones:'),
      { type: 'leadBullets', items: [{ label: 'Medulla oblongata', text: 'medial surface of the interphalangeal joint of the great toe' }, { label: 'Jugular foramen, superior and inferior ganglia', text: 'proximal interphalangeal joint of the fourth and fifth toes, on the lateral side of the fourth and the medial side of the fifth' }] },
      { type: 'figure', src: '/chapter-4/EN/IMAGES/NCH 4 EN INLINE VAGUS MEDULLA V3.png', caption: 'Photo: vagus nerve X in the medulla oblongata', alt: 'Foot landmark — vagus nerve X in the medulla oblongata', orientation: 'portrait' },
      { type: 'figure', src: '/chapter-4/EN/IMAGES/NCH 4 EN INLINE VAGUS JUGULAR FORAMEN V3.png', caption: 'Photo: vagus nerve X in the jugular foramen', alt: 'Foot landmark — vagus nerve X in the jugular foramen', orientation: 'portrait' },
      sub('11.3. Vagus Nerve X — Cervical Level'), para('Foot reflex zones:'),
      bullets('Cranial and cervical territories of the vagus nerve', 'Superior laryngeal nerve: lateral plantar shaft–head junction of the proximal phalanx of the great toe', 'Carotid sinus and carotid body (carotid bifurcation): at the level of the C4 vertebra, lateral surface of the shaft of the proximal phalanx of the great toe', 'Previsceral plexuses: pharynx, larynx, oesophagus.'),
      { type: 'figure', src: '/chapter-4/EN/IMAGES/NCH 4 EN INLINE CAROTID SINUS V3.png', caption: 'Photo: carotid sinus', alt: 'Foot landmark — carotid sinus', orientation: 'landscape' },
      sub('11.4. Vagus Nerve X — Thoracic Level / Cardiac Plexus'), para('Foot reflex zones:'),
      { type: 'leadBullets', items: [{ label: 'Right and left atria and cardiac plexus', text: 'plantar surface of the head of the first metatarsal on both feet' }, { label: 'Ventricles', text: 'plantar surface of the left foot: area between the diaphragm reflex zone and the heads of the first two metatarsals' }, { label: 'Superficial cardiac plexus', text: 'at the level of the left third chondrosternal joint: junction between the tibial malleolus and the head of the talus' }] },
      { type: 'figure', src: '/chapter-4/EN/IMAGES/NCH 4 EN INLINE RIGHT CERVICAL THORACIC VAGUS V3.png', caption: 'Photo: right cervical and thoracic territories of vagus nerve X', alt: 'Foot landmark — right cervical and thoracic territories of vagus nerve X', orientation: 'portrait' },
      sub('11.5. Vagus Nerve X — Diaphragmatic Level / Oesophageal Hiatus'), para('Foot reflex zones:'),
      { type: 'leadBullets', items: [{ label: 'Oesophageal hiatus', text: 'plantar surface of the left foot, lateral to the central tendon and aligned with a line beginning between the first and second toes and crossing the left diaphragmatic dome.' }, { label: 'N.B.', text: 'take into account the difference in height of the two diaphragmatic domes, the left being lower than the right.' }] },
      { type: 'figure', src: '/chapter-4/EN/IMAGES/NCH 4 EN INLINE OESOPHAGEAL HIATUS V3.png', caption: 'Photo: oesophageal hiatus and right and left vagus nerves', alt: 'Foot landmark — oesophageal hiatus and right and left vagus nerves', orientation: 'portrait' },
      sub('11.6. Vagus Nerve X — Abdominal Level'), para('Foot reflex zones: plantar surface of the left foot:'),
      { type: 'leadBullets', items: [{ label: 'Cardia', text: 'immediately below the oesophageal hiatus;' }, { label: 'Lesser curvature of the stomach', text: 'a line between the cardia and pylorus;' }, { label: 'Cannon–Böhm zone', text: 'junction between the right two-thirds and left one-third of the transverse colon' }, { label: 'Prevertebral plexuses', text: '' }] },
      { type: 'figure', src: '/chapter-4/EN/IMAGES/NCH 4 EN INLINE RIGHT ABDOMINAL VAGUS V3.png', caption: 'Photo: right abdominal territory of vagus nerve X', alt: 'Foot landmark — right abdominal territory of vagus nerve X', orientation: 'landscape' },
      sub('11.7. Pelvic (or Sacral) Parasympathetic System'),
      { type: 'leadBullets', items: [{ label: 'Foot reflex zones', text: '' }, { label: 'Sacral spinal cord S2–S3–S4', text: 'vertebral level L1–L2;' }, { label: 'Cauda equina', text: 'from L1 to the sacrum;' }, { label: 'Anterior sacral foramina', text: 'anterior border of the sacrum.' }] },
      { type: 'figure', src: '/chapter-4/EN/IMAGES/NCH 4 EN INLINE PELVIC PARASYMPATHETIC ORIGIN V3.png', caption: 'Photo: spinal origin of the pelvic or sacral parasympathetic system', alt: 'Foot landmark — spinal origin of the pelvic or sacral parasympathetic system', orientation: 'landscape' },
      sub('11.8. Visceromotor Sympathetic System — Spinal Origin'),
      bullets('Foot reflex zones', 'Vertebral canal (spinal meninges, thoracic spinal cord, spinal and sympathetic nerve roots): in a medial sagittal view, the medial arch of both feet from the shaft–base junction of the proximal phalanx of the great toe (C8 spinal segment, C7 vertebra) to the first metatarsal–first cuneiform joint (L2 spinal segment, T12 vertebra).'),
      { type: 'figure', src: '/chapter-4/EN/IMAGES/NCH 4 EN INLINE SYMPATHETIC SPINAL ORIGIN V3.png', caption: 'Photo: spinal origin of the sympathetic system', alt: 'Foot landmark — spinal origin of the sympathetic system', orientation: 'landscape' },
      sub('11.9. Visceromotor Sympathetic System — Thoracic Ganglion Chain'),
      bullets('Foot reflex zones', 'Posterior vertebral joints and costovertebral joints', 'Thoracic paravertebral sympathetic chain: it is not directly accessible; it is through the costovertebral joints that it may be acted upon, along the dorsal border of the base of the proximal phalanx of the great toe and the first metatarsal.'),
      { type: 'figure', src: '/chapter-4/EN/IMAGES/NCH 4 EN INLINE THORACIC SYMPATHETIC CHAIN V3.png', caption: 'Photo: thoracic paravertebral sympathetic chain', alt: 'Foot landmark — thoracic paravertebral sympathetic chain', orientation: 'landscape' },
      sub('11.10. Visceromotor Sympathetic System — Cervical Ganglion Chain'), para('Foot reflex zones'),
      { type: 'leadBullets', items: [{ label: 'Cervical ganglion chain', text: 'space between the medial plantar border of the proximal phalanx of the great toe and its plantar surface.' }, { label: 'Inferior cervical ganglion', text: 'medial plantar shaft–base junction of the proximal phalanx of the great toe, at C7–T1–first rib.' }, { label: 'Middle cervical ganglion', text: 'same as the inferior cervical ganglion, just above C7.' }, { label: 'Superior cervical ganglion', text: 'medial plantar shaft–head junction of the proximal phalanx of the great toe at C1–C2–C3.' }] },
      { type: 'figure', src: '/chapter-4/EN/IMAGES/NCH 4 EN INLINE INFERIOR CERVICAL GANGLION V3.png', caption: 'Photo: inferior cervical ganglion', alt: 'Foot landmark — inferior cervical ganglion', orientation: 'portrait' },
      sub('11.11. Visceromotor Sympathetic System — Lumbar Ganglion Chain'), para('Foot reflex zones'),
      { type: 'leadBullets', items: [{ label: 'Crura of the diaphragm', text: '' }, { label: 'Innervation of the psoas', text: 'lumbar roots L1 to L4, lumbar plexus, femoral nerve (see Occipito-Podal Reflexotherapy and the Neuro-Meningeal System, pages 28–29 and 34)' }] },
      { type: 'figure', src: '/chapter-4/EN/IMAGES/NCH 4 EN INLINE LUMBAR SYMPATHETIC CHAIN V3.png', caption: 'Photo: lumbar sympathetic chain and diaphragmatic crura', alt: 'Foot landmark — lumbar sympathetic chain and diaphragmatic crura', orientation: 'landscape' },
      sub('11.12. Visceromotor Sympathetic System — Sacral and Coccygeal Ganglion Chain'), para('Foot reflex zones:'),
      { type: 'leadBullets', items: [{ label: 'Sacral ganglion chain', text: 'anterior surface of the sacrum along the anterior border of the posteromedial tuberosity of the calcaneus;' }, { label: 'Ganglion impar', text: 'anterior surface of the coccyx at the tip of the posteromedial tuberosity of the calcaneus;' }, { label: 'Sacrococcygeal joint', text: 'a small depression posterior to the coccyx.' }] },
      { type: 'figure', src: '/chapter-4/EN/IMAGES/NCH 4 EN INLINE SACROCOCCYGEAL SYMPATHETIC CHAIN V3.png', caption: 'Photo: sacrococcygeal paravertebral sympathetic chain', alt: 'Foot landmark — sacrococcygeal paravertebral sympathetic chain', orientation: 'landscape' },
      sub('11.13. Somatovisceral Sensory Sympathetic System'), para('Foot reflex zones'),
      bullets('The reflex zones of the viscerosensory sympathetic nerves are the same as those of the visceromotor sympathetic system.'),
      sub('11.14. Prevertebral (or Preaortic) Plexus Chain'), para('Foot reflex zones'),
      { type: 'lead', label: 'Prevertebral plexus chain', text: 'plantar surface of both feet along the median axis (aligned with the third toe), from the diaphragm reflex zone to the anterior border of the heel.' },
      sub('11.15. Pelvic Previsceral Plexus'),
      { type: 'leadBullets', items: [{ label: 'Foot reflex zones', text: '' }, { label: 'Inferior hypogastric plexus (anterior fibres)', text: 'plantar surface, medial part of the anterior border of the heel, at the junction of the fallopian-tube reflex zone and the uterine dome' }, { label: 'Inferior hypogastric plexus (middle fibres)', text: 'medial surface of the heel, reflex zone of the cervico-isthmic region of the uterus (or prostate)' }, { label: 'Inferior hypogastric plexus (posterior fibres)', text: 'medial surface of the heel, middle part of the anterior border of the posteromedial tuberosity of the calcaneus' }] },
      { type: 'figure', src: '/chapter-4/EN/IMAGES/NCH 4 EN INLINE INFERIOR HYPOGASTRIC ANTERIOR V3.png', caption: 'Photo: inferior hypogastric plexus, anterior fibres', alt: 'Foot landmark — inferior hypogastric plexus, anterior fibres', orientation: 'portrait' },
      { type: 'figure', src: '/chapter-4/EN/IMAGES/NCH 4 EN INLINE INFERIOR HYPOGASTRIC MIDDLE POSTERIOR V3.png', caption: 'Photo: inferior hypogastric plexus, middle and posterior fibres', alt: 'Foot landmark — inferior hypogastric plexus, middle and posterior fibres', orientation: 'landscape' },
      sub('11.16. Intrinsic or Enteric Nervous System (ENS)'),
      { type: 'lead', label: 'Foot reflex zones', text: 'these are the intestinal reflex zones.' },
      sub('11.17. Adrenal Glands'), { type: 'lead', label: 'Reflex zones', text: '' },
      sub('11.18. Principle for Interpreting the Zones'),
      rop('A reflex zone that is tender or altered in texture is a clinical ROP landmark. It does not demonstrate a lesion of the corresponding structure. Selection of zones remains guided by the history, tests and reassessment.'),
    ]),
    section('a-retenir', 'Key Points', [
      bullets(
        'In ROP clinical reasoning, a functional visceral disorder leads first to a search for Level 1 and/or Level 2 factors before the viscus is considered the primary origin of the disorder; this prioritisation does not replace investigation for organic disease.',
        'The ANS works in both directions: efferent commands to the viscera and afferent information to the centres.',
        'The pelvic parasympathetic system S2–S4 is distinct from the somatic pudendal nerve S2–S4.',
        'ROP reflex zones remain clinical landmarks and are not a direct anatomical representation of the autonomic system on the foot.'),
    ]),
    section('bibliographie-selective', 'Selected Bibliography', [
      para('1. Standring S, ed. Gray’s Anatomy: The Anatomical Basis of Clinical Practice. 42nd ed. Elsevier; 2020.'),
      para('2. Jänig W. Neurobiology of visceral afferent neurons: neuroanatomy, functions, organ regulations and sensations. Biol Psychol. 1996;42(1-2):29-51.'),
      para('3. Sato A, Sato Y, Schmidt RF. The impact of somatosensory input on autonomic functions. Rev Physiol Biochem Pharmacol. 1997;130:1-328.'),
      para('4. Fowler CJ, Griffiths D, de Groat WC. The neural control of micturition. Nat Rev Neurosci. 2008;9(6):453-466.'),
      para('5. de Groat WC, Vizzard MA, Araki I, Roppolo JR. Spinal interneurons and preganglionic neurons in sacral autonomic reflex pathways. Prog Brain Res. 1996;107:97-111.'),
      para('6. Brierley SM, Hibberd TJ, Spencer NJ. Spinal afferent innervation of the colon and rectum. Front Cell Neurosci. 2018;12:467.'),
      para('7. Spencer NJ, Hu H. Enteric nervous system: sensory transduction, neural circuits and gastrointestinal motility. Nat Rev Gastroenterol Hepatol. 2020;17(6):338-351.'),
      para('8. Tobaldini E, Costantino G, Solbiati M, et al. Sleep, sleep deprivation, autonomic nervous system and cardiovascular diseases. Neurosci Biobehav Rev. 2017;74(Pt B):321-329.'),
      para('9. Bellesi M, de Vivo L, Chini M, et al. Sleep Loss Promotes Astrocytic Phagocytosis and Microglial Activation in Mouse Cerebral Cortex. J Neurosci. 2017;37(21):5263-5273.'),
    ]),
  ],
}
