// Introduction - French
// Source: public/chapter-0/Chapter0_Introduction_ROP_pret_a_publier.docx

import type { Chapter } from './types'

export const introductionFr: Chapter = {
  slug: 'introduction',
  title: 'Introduction',
  sections: [
    {
      id: "fil-conducteur-clinique",
      title: "Le fil conducteur clinique du troisième volume",
      blocks: [
        { type: 'para', text: "Ce troisième volume de Réflexothérapie occipito-podale (ROP) prolonge naturellement les deux précédents. Après l’étude du système ostéo-musculo-articulaire dans le premier tome, puis celle du système neuro-méningé dans le deuxième, nous entrons ici dans le champ du viscéral abdomino-pelvien, du système nerveux autonome et des mécanismes d’adaptation au stress." },
        { type: 'para', text: "L’ambition reste la même : proposer une cartographie cohérente avec l’anatomie et la physiologie, pensée en trois dimensions sous la forme d’un bébé en position fœtale dans le pied, puis articulée avec les zones réflexes occipitales. Ensemble, les zones réflexes occipitales et podales constituent les zones réflexes ROP." },
        { type: 'para', text: "Ce troisième ouvrage poursuit toutefois un objectif supplémentaire : rendre explicite une méthode clinique cohérente, capable de relier les centres de régulation, les voies neuro-végétatives, les interfaces loco-régionales et les organes." },
        { type: 'para', text: "L’ouvrage ne doit donc pas être lu comme une simple succession de chapitres anatomiques. Son organisation suit également la progression du raisonnement clinique utilisé en ROP." },
      ],
    },
    {
      id: "en-bref-ce-que-ce-livre-vous-apporte",
      title: "En bref : ce que ce livre vous apporte",
      blocks: [
        { type: 'bullets', items: ["Une lecture simple des relations viscéro-somatiques : comment un viscère peut influencer le système locomoteur et, inversement, comment une contrainte somatique peut retentir sur la fonction viscérale.", "Des repères cliniques et une logique de palpation permettant de localiser les zones réflexes podales de la ROP malgré la rareté des repères osseux sur la face plantaire.", "Des cartographies ajustées sur des points anatomiques précis, notamment le diaphragme, puis mises en perspective avec l’anamnèse et les comptes rendus médicaux ou chirurgicaux.", "Une approche globale visant à interrompre ou à atténuer certaines boucles réflexes susceptibles d’associer composantes neurologiques, viscérales, somatiques et émotionnelles.", "Une méthode clinique progressive permettant de replacer la cible viscérale dans son environnement central, neuro-végétatif et loco-régional.", "Des repères pour observer, mesurer et réévaluer les effets d’une séance."] },
        { type: 'para', text: "La ROP cherche ainsi à soutenir les capacités propres de régulation et d’adaptation de l’organisme, sans réduire le patient à un organe isolé ni à une cartographie appliquée mécaniquement." },
      ],
    },
    {
      id: "une-methode-clinique-coherente",
      title: "Une méthode clinique cohérente",
      blocks: [
        { type: 'para', text: "Contrairement à un atlas anatomique, ce livre n’a pas été organisé organe par organe au hasard." },
        { type: 'para', text: "Les chapitres suivent volontairement une progression clinique. Chaque partie apporte un niveau supplémentaire de compréhension, depuis les mécanismes généraux de régulation jusqu’aux viscères eux-mêmes." },
        { type: 'para', text: "L’objectif n’est pas seulement d’apprendre une cartographie réflexe. Il est de comprendre dans quel ordre raisonner devant un patient." },
        { type: 'para', text: "La ROP considère qu’un trouble fonctionnel peut être associé à plusieurs dimensions simultanées : une régulation centrale, une modulation neuro-végétative, des contraintes loco-régionales et une expression viscérale ou fonctionnelle spécifique." },
        { type: 'para', text: "Le praticien cherche donc à replacer chaque symptôme dans cette organisation générale avant de cibler un organe particulier. Cette progression constitue le fil conducteur du livre." },
        { type: 'figure', src: "/chapter-0/figure-0-2.png", caption: "La séquence clinique ROP : une progression en quatre niveaux", alt: "Schéma de la séquence clinique ROP en quatre niveaux, de la régulation centrale à la cible viscérale ou fonctionnelle spécifique.", orientation: 'landscape' },
        { type: 'sub', text: "Niveau 1 — Régulation centrale" },
        { type: 'para', text: "Le premier niveau concerne le système nerveux central. Il rassemble les structures qui participent à l’intégration des informations sensorielles et viscérales, à l’organisation des réponses adaptatives, à la modulation de la douleur, aux réponses émotionnelles, aux fonctions neuro-endocrines, à la vigilance, au sommeil, à la récupération et à la coordination des réponses autonomes." },
        { type: 'bullets', items: ["Tronc cérébral", "Cervelet", "Diencéphale", "Système limbique", "Noyaux gris centraux", "Membranes intracrâniennes", "Environnement neuro-méningé et neurovasculaire"] },
        { type: 'para', text: "Dans la méthode clinique développée dans cet ouvrage, le système nerveux central constitue le premier niveau de régulation. Les localisations proposées appartiennent à la cartographie clinique de la ROP : elles ne représentent ni une projection anatomique directe sur le pied, ni la preuve d’une action spécifique sur une aire cérébrale déterminée." },
        { type: 'sub', text: "Niveau 2 — Régulation neuro-végétative" },
        { type: 'para', text: "Le deuxième niveau concerne le système nerveux autonome. Il assure la communication fonctionnelle entre les centres de régulation et les différents territoires corporels, et participe à l’adaptation permanente des fonctions cardiovasculaires, respiratoires, digestives, urinaires, génitales, métaboliques, sécrétoires et thermorégulatrices." },
        { type: 'bullets', items: ["Voies sympathiques", "Voies parasympathiques", "Nerf vague", "Parasympathique sacré", "Chaînes ganglionnaires", "Nerfs splanchniques", "Plexus prévertébraux et préviscéraux", "Plexus pelviens", "Système nerveux entérique"] },
        { type: 'para', text: "Le système nerveux autonome constitue le deuxième niveau du protocole clinique. L’objectif n’est pas d’opposer un sympathique « mauvais » à un parasympathique « bon », mais de soutenir la flexibilité autonome : mobiliser une réponse adaptée, puis retrouver la récupération lorsque la contrainte cesse." },
        { type: 'sub', text: "Niveau 3 — Interfaces loco-régionales" },
        { type: 'para', text: "Le troisième niveau concerne les cavités et interfaces loco-régionales. Entre les centres de régulation, les voies autonomes et les organes existent de nombreuses structures susceptibles d’influencer la mobilité, les pressions, les passages nerveux et vasculaires ou les rapports entre les viscères et les parois." },
        { type: 'bullets', items: ["Cavités abdominale et pelvienne", "Diaphragme", "Péritoine", "Fascias", "Mésos et ligaments viscéraux", "Muscles et charnières vertébrales", "Passages neurovasculaires", "Plexus régionaux"] },
        { type: 'para', text: "Les chapitres consacrés aux cavités abdominale et pelvienne, ainsi qu’au diaphragme, développent ce troisième niveau. L’objectif n’est pas de traiter systématiquement toutes les structures d’une région, mais de rechercher les interfaces pertinentes au regard de l’anamnèse, des tests et de la réponse observée." },
        { type: 'sub', text: "Niveau 4 — Cible viscérale spécifique" },
        { type: 'para', text: "Le quatrième niveau concerne l’organe ou la fonction qui constitue la cible clinique spécifique. Les chapitres d’organes développent leur anatomie, leur physiologie, leurs rapports, leur cartographie réflexe et leurs applications cliniques." },
        { type: 'bullets', items: ["Estomac et duodénum", "Foie et voies biliaires", "Pancréas et rate", "Intestin grêle, côlon et rectum", "Reins et vessie", "Organes génitaux", "Système érectile"] },
        { type: 'para', text: "Le quatrième niveau ne signifie pas que la ROP traite directement une maladie organique. Il désigne la cible fonctionnelle ou symptomatique autour de laquelle le traitement est individualisé : douleur, gêne, transit, miction, mobilité, fatigue, sommeil ou capacités fonctionnelles." },
        { type: 'figure', src: "/chapter-0/figure-0-1.png", caption: "Protocole clinique ROP : quatre niveaux unifiés", alt: "Schéma du protocole clinique ROP en quatre niveaux : régulation centrale, régulation neuro-végétative, interfaces loco-régionales et cible viscérale spécifique.", orientation: 'landscape' },
        { type: 'quote', text: "Comprendre la régulation centrale, suivre les voies neuro-végétatives, examiner les interfaces régionales, puis cibler l’expression viscérale ou fonctionnelle du trouble." },
      ],
    },
    {
      id: "une-progression-clinique-non-un-protocole-rigide",
      title: "Une progression clinique, non un protocole rigide",
      blocks: [
        { type: 'para', text: "Les quatre niveaux ne constituent pas quatre étapes obligatoires à appliquer de manière identique à tous les patients. Ils organisent le raisonnement clinique :" },
        { type: 'numbered', items: ["Régulation centrale.", "Régulation neuro-végétative.", "Interfaces loco-régionales.", "Cible viscérale spécifique."] },
        { type: 'para', text: "L’ordre réel du traitement dépend de l’histoire du patient, de ses symptômes, des antécédents médicaux, traumatiques ou chirurgicaux, des tests, de la tolérance au toucher et de la réponse observée." },
        { type: 'para', text: "Une fixation locale clairement identifiée peut être prioritaire. À l’inverse, un tableau diffus, une fatigue importante ou une forte réactivité neuro-végétative peuvent conduire à commencer par les niveaux de régulation générale." },
        { type: 'para', text: "Le modèle en quatre niveaux doit donc rester une grille de lecture et de hiérarchisation, et non une séquence automatique. Le mouvement clinique peut également être compris dans les deux sens : du central vers le viscéral et du viscéral vers les centres d’intégration." },
      ],
    },
    {
      id: "le-role-transversal-du-stress-et-de-la-regulation",
      title: "Le rôle transversal du stress et de la régulation",
      blocks: [
        { type: 'para', text: "Les chapitres consacrés au mécanisme du stress et à la théorie polyvagale ne constituent pas un cinquième niveau clinique. Ils expliquent comment les quatre niveaux interagissent dans le temps." },
        { type: 'para', text: "Le stress est une réponse d’adaptation. Il mobilise le système nerveux central, le système nerveux autonome, les systèmes hormonaux, les muscles, la respiration et les viscères. Cette mobilisation est utile lorsqu’elle est proportionnée, limitée et suivie d’une récupération." },
        { type: 'bullets', items: ["persiste ;", "se répète ;", "reste disproportionnée ;", "ne se clôt pas ;", "dépasse les capacités de récupération du patient."] },
        { type: 'para', text: "Le chapitre consacré au mécanisme du stress fournit ainsi le cadre permettant de comprendre l’adaptation, la charge allostatique, la mobilisation défensive, la récupération, la chronicisation et la réduction progressive de la marge adaptative." },
        { type: 'para', text: "Le chapitre consacré à la théorie polyvagale propose une lecture complémentaire des états autonomes et des réponses de mobilisation, de protection ou d’engagement relationnel. Ces chapitres décrivent donc la dynamique qui relie les centres de régulation, les voies autonomes, les tensions régionales et les manifestations viscérales." },
        { type: 'quote', text: "Dans cette perspective, la ROP ne cherche pas à empêcher l’organisme de réagir. Elle cherche à soutenir sa capacité à ne pas rester bloqué dans une réaction devenue inutile ou insuffisamment résolue." },
      ],
    },
    {
      id: "comment-lire-lorganisation-du-livre",
      title: "Comment lire l’organisation du livre",
      blocks: [
        { type: 'sub', text: "Partie I — Introduction" },
        { type: 'para', text: "Genèse de la méthode, principes généraux, mobilité viscérale, traitement par la ROP, anamnèse, tests, hiérarchisation clinique, sécurité et réévaluation." },
        { type: 'sub', text: "Partie II — Systèmes nerveux" },
        { type: 'para', text: "Le chapitre sur le système nerveux central développe le niveau 1. Le chapitre sur le système nerveux autonome développe le niveau 2." },
        { type: 'sub', text: "Partie III — Stress et régulation" },
        { type: 'para', text: "Les chapitres sur le stress et la théorie polyvagale expliquent les mécanismes dynamiques qui relient les quatre niveaux." },
        { type: 'sub', text: "Partie IV — Viscères abdominaux" },
        { type: 'para', text: "Les chapitres sur la cavité abdominale et le diaphragme développent principalement le niveau 3 ; les chapitres d’organes digestifs développent le niveau 4." },
        { type: 'sub', text: "Partie V — Uro-génital et pelvien" },
        { type: 'para', text: "Le chapitre consacré à la cavité pelvienne développe le niveau 3 ; les chapitres sur les reins, la vessie, les organes génitaux et le système érectile développent le niveau 4." },
      ],
    },
    {
      id: "pourquoi-le-visceral-est-incontournable",
      title: "Pourquoi le viscéral est incontournable",
      blocks: [
        { type: 'para', text: "Le système viscéral assure une grande partie de la logistique de l’organisme : nutrition, digestion, absorption, élimination, équilibre hydrominéral, fonctions endocrines, reproduction et maintien de l’équilibre interne." },
        { type: 'para', text: "Dans ce cadre, certaines douleurs ou limitations ostéo-musculo-articulaires peuvent être associées à des contraintes viscérales. L’inverse est également possible : une restriction pariétale, diaphragmatique ou musculo-fasciale peut influencer le confort ou la mobilité d’un territoire viscéral." },
        { type: 'para', text: "Travailler l’un en ignorant systématiquement l’autre peut donc conduire à une lecture incomplète du patient. Cette relation ne doit toutefois pas être interprétée comme une causalité automatique. L’anamnèse, l’examen clinique et, lorsque cela est nécessaire, l’évaluation médicale restent indispensables." },
        { type: 'para', text: "La ROP intervient dans le champ des troubles fonctionnels et de l’accompagnement. Elle ne remplace ni le diagnostic médical ni les traitements nécessaires en présence d’une maladie organique." },
      ],
    },
    {
      id: "notre-parti-pris-rigueur-anatomique-et-pragmatisme-clinique",
      title: "Notre parti pris : rigueur anatomique et pragmatisme clinique",
      blocks: [
        { type: 'para', text: "Comme dans toute approche manuelle, nous constatons parfois des résultats sans pouvoir en objectiver pleinement les mécanismes." },
        { type: 'para', text: "L’observation clinique ne possède pas, à elle seule, la rigueur d’un protocole expérimental. Elle conserve néanmoins une valeur lorsqu’elle est :" },
        { type: 'bullets', items: ["conduite avec méthode ;", "décrite avec précision ;", "confrontée à l’évolution réelle du patient ;", "mise en relation avec les données médicales disponibles ;", "réévaluée dans le temps."] },
        { type: 'para', text: "Ce livre privilégie donc quatre exigences :" },
        { type: 'numbered', items: ["la cohérence anatomique ;", "la reproductibilité des repères ;", "la confrontation au réel par l’anamnèse, l’imagerie et les données médicales ou chirurgicales ;", "la documentation structurée de la pratique et de l’évolution du patient."] },
        { type: 'note', label: "SuiviPatient — De l’observation clinique à une communauté de données", body: ["Pour prolonger cette exigence au-delà du livre, nous mettons gratuitement à disposition des praticiens certifiés ROP l’application SuiviPatient. Cet outil permet de documenter de manière structurée le motif principal de consultation, les éléments de l’anamnèse, les niveaux et zones travaillés, le protocole réellement suivi, les réactions observées pendant et après la séance, ainsi que l’évolution de la douleur, du sommeil, de la fatigue, du transit, de la mobilité ou des capacités fonctionnelles.", "L’objectif n’est pas de transformer chaque séance en protocole expérimental ni de tirer des conclusions causales à partir de simples observations. Il est de rendre la pratique plus traçable, plus comparable et plus facilement réévaluable. Grâce à SuiviPatient, chaque praticien enrichit sa propre expérience et contribue à une dynamique collective : mieux identifier les protocoles pertinents, les adaptations nécessaires, les réponses immédiates ou différées, les facteurs associés à la récupération et les limites de la méthode.", "Cette démarche respecte le consentement du patient, la confidentialité des informations et les règles applicables à la protection des données. Les lecteurs qui souhaitent se former, être certifiés ROP, rejoindre la communauté des praticiens ou utiliser gratuitement SuiviPatient dans leur pratique sont invités à nous contacter.", "Contact : [adresse e-mail, site ou QR code à insérer]"] },
        { type: 'sub', text: "Distinguer anatomie, cartographie et hypothèses cliniques" },
        { type: 'para', text: "Les zones réflexes décrites dans cet ouvrage appartiennent à la cartographie clinique de la méthode. Elles ne constituent pas une projection anatomique directe de l’organe sur le pied, la preuve d’un lien anatomique spécifique, ni la démonstration d’un mécanisme d’action particulier." },
        { type: 'para', text: "L’ouvrage s’efforce également de distinguer les connaissances anatomiques et physiologiques établies, les modèles scientifiques encore en discussion et la lecture clinique propre à la ROP. Cette distinction permet de conserver l’identité de la méthode sans présenter comme démontrées des relations qui restent hypothétiques." },
      ],
    },
    {
      id: "deux-reperes-anatomiques-fondamentaux",
      title: "Deux repères anatomiques fondamentaux",
      blocks: [
        { type: 'sub', text: "1. Le diaphragme" },
        { type: 'para', text: "Les deux coupoles diaphragmatiques ne se trouvent pas à la même hauteur. La coupole droite est généralement plus haute que la gauche, notamment en raison de la présence du foie. Ignorer cette asymétrie rendrait incohérente la cartographie du diaphragme et des viscères qui entretiennent avec lui des rapports directs ou indirects." },
        { type: 'sub', text: "2. Le péritoine" },
        { type: 'para', text: "Le péritoine constitue une interface majeure entre les viscères et les parois. Par ses replis, ses mésos, ses ligaments et ses rapports, il participe à la suspension des organes, à leurs plans de glissement, aux rapports vasculaires et nerveux et à l’organisation des espaces abdominaux et pelviens. Dans le raisonnement clinique proposé, il appartient pleinement au niveau 3 des interfaces loco-régionales." },
      ],
    },
    {
      id: "terminologie",
      title: "Terminologie",
      blocks: [
        { type: 'para', text: "Dans un souci de clarté et de cohérence anatomique, nous adopterons les termes suivants :" },
        { type: 'bullets', items: ["dorsalement, à la place de « postérieurement » lorsque l’orientation corporelle le justifie ;", "ventralement, à la place de « antérieurement » ;", "latéralement, à la place de « extérieurement » ;", "médialement, à la place de « intérieurement » ;", "céphaliquement, à la place de « vers le haut » ;", "caudalement, à la place de « vers le bas » ;", "frontalement, pour décrire une orientation dans le plan frontal ;", "sagittalement, pour décrire une orientation dans le plan sagittal."] },
      ],
    },
    {
      id: "plan-type-des-chapitres",
      title: "Plan-type des chapitres",
      blocks: [
        { type: 'sub', text: "Présentation" },
        { type: 'para', text: "Situe l’organe dans le raisonnement général du livre et précise son intérêt clinique." },
        { type: 'sub', text: "Situation" },
        { type: 'para', text: "Localise l’organe dans la cavité concernée et définit ses principaux repères." },
        { type: 'sub', text: "Anatomie" },
        { type: 'para', text: "Décrit sa forme, ses parties constitutives et ses caractéristiques essentielles." },
        { type: 'sub', text: "Rapports" },
        { type: 'para', text: "Présente les relations avec les organes voisins, les parois, les fascias, les muscles, les ligaments et les structures vasculo-nerveuses." },
        { type: 'sub', text: "Vascularisation" },
        { type: 'para', text: "Décrit les principaux axes artériels, veineux et, lorsque cela est pertinent, lymphatiques." },
        { type: 'sub', text: "Innervation" },
        { type: 'para', text: "Présente les voies sympathiques et parasympathiques, les plexus, les afférences viscérales et les niveaux médullaires associés." },
        { type: 'sub', text: "Physiologie" },
        { type: 'para', text: "Rappelle les fonctions principales de l’organe et leur régulation." },
        { type: 'sub', text: "Pathologies courantes" },
        { type: 'para', text: "Fournit des repères de compréhension et de prudence. La ROP ne se substitue pas au diagnostic médical." },
        { type: 'sub', text: "Zones réflexes podales" },
        { type: 'para', text: "Relie autant que possible les repères de régulation générale, les voies neuro-végétatives, les interfaces loco-régionales et la cible viscérale spécifique." },
        { type: 'sub', text: "Relations viscéro-somatiques" },
        { type: 'para', text: "Décrit les liens possibles entre l’organe, les segments rachidiens, les muscles, les articulations et les territoires douloureux associés." },
        { type: 'sub', text: "Relations viscéro-émotionnelles" },
        { type: 'para', text: "Propose une lecture prudente des relations possibles entre les états émotionnels, la perception corporelle, la régulation autonome et les symptômes." },
        { type: 'sub', text: "Conseils" },
        { type: 'para', text: "Complète la séance par des mesures simples et adaptées : repos relatif, hydratation, activité physique adaptée, alimentation, sommeil, suivi des symptômes et consultation médicale si nécessaire." },
      ],
    },
    {
      id: "observer-mesurer-et-reevaluer",
      title: "Observer, mesurer et réévaluer",
      blocks: [
        { type: 'para', text: "Une méthode clinique cohérente doit pouvoir être réévaluée." },
        { type: 'sub', text: "Avant la séance" },
        { type: 'bullets', items: ["symptôme principal ;", "intensité et ancienneté ;", "retentissement fonctionnel ;", "facteurs aggravants ou améliorants ;", "sommeil, transit, fatigue, mobilité, activité ou fonction viscérale."] },
        { type: 'sub', text: "Pendant la séance" },
        { type: 'bullets', items: ["tolérance au toucher ;", "modifications du tonus ;", "respiration ;", "réactions végétatives ;", "évolution des tests ;", "signes inhabituels."] },
        { type: 'sub', text: "Après la séance et dans les jours suivants" },
        { type: 'bullets', items: ["symptôme principal ;", "douleur ou gêne ;", "mobilité ;", "sommeil ;", "transit et diurèse ;", "fatigue ;", "capacités fonctionnelles ;", "durée et cinétique de la récupération."] },
        { type: 'para', text: "Une amélioration immédiate n’est pas toujours durable. À l’inverse, certaines évolutions apparaissent progressivement. Une aggravation intense, prolongée ou accompagnée de signes inhabituels impose une réévaluation et, lorsque le contexte le nécessite, une orientation médicale." },
      ],
    },
    {
      id: "a-retenir",
      title: "À retenir",
      blocks: [
        { type: 'para', text: "Ce troisième volume ne présente pas seulement une nouvelle série de cartographies viscérales. Il propose une lecture clinique organisée selon quatre niveaux :" },
        { type: 'numbered', items: ["le système nerveux central, premier niveau de régulation ;", "le système nerveux autonome, deuxième niveau de transmission et de modulation ;", "les cavités et interfaces loco-régionales, troisième niveau ;", "l’organe ou la fonction ciblés, quatrième niveau."] },
        { type: 'para', text: "Les chapitres consacrés au stress et à la régulation expliquent comment ces niveaux interagissent entre mobilisation, adaptation et récupération. Cette architecture ne constitue pas un protocole rigide : l’anamnèse, les tests et la réponse du patient déterminent la priorité." },
        { type: 'quote', text: "Comprendre la régulation centrale, suivre les voies neuro-végétatives, examiner les interfaces régionales, puis cibler l’expression viscérale ou fonctionnelle du trouble." },
        { type: 'para', text: "C’est cette continuité qui donne à l’ensemble du troisième ouvrage sa cohérence clinique et pédagogique." },
      ],
    },
  ],
}
