import type { ReactNode } from 'react'
import type { Lang } from '@/app/i18n/translations'

export type TeamPageCopy = {
  metadata: { title: string; description: string }
  home: string
  eyebrow: string
  titleBefore: string
  titleEmphasis: string
  intro: string
  membersLabel: string
  portraitAlt: (name: string) => string
  portraitPending: string
  members: Array<{ name: string; role: string; body: ReactNode[] }>
  cta: string
  exploreBook: string
  discoverMethod: string
}

export const teamPageCopy: Record<Lang, TeamPageCopy> = {
  fr: {
    metadata: { title: "L'équipe · R.O.P.", description: "Découvrez l'équipe qui porte la Réflexothérapie Occipito-Podale : clinique, formation, technologie, relation avec les lecteurs et marketing." },
    home: 'Retour à l’accueil', eyebrow: 'L’équipe R.O.P.', titleBefore: 'Trois expertises,', titleEmphasis: 'une même exigence.',
    intro: 'Faire vivre la R.O.P., c’est réunir la transmission d’une méthode construite sur plus de cinquante ans de pratique, une expérience numérique solide et un accompagnement attentif. Chacun intervient dans son domaine, au service d’un même projet : rendre la méthode claire, accessible et durable.',
    membersLabel: 'Membres de l’équipe', portraitAlt: (name) => `Portrait de ${name}`, portraitPending: 'Portrait à venir',
    members: [
      { name: 'Guy Boitout', role: 'Fondateur · Direction clinique · Formation', body: ['Guy est le créateur de la Réflexothérapie Occipito-Podale. Il en porte la vision clinique, la cohérence et la transmission. Il structure les contenus de la méthode, dirige les formations et accompagne leur évolution à partir de l’expérience accumulée auprès des patients et des praticiens. Il veille enfin à préserver la fidélité de la R.O.P. à ses fondements, à l’anatomie et aux principes cliniques qui ont guidé son développement.'] },
      { name: 'Nicolas Boitout', role: 'Direction technologique · Imagerie scientifique', body: ['Nicolas conçoit et pilote l’environnement numérique de la R.O.P. et coordonne la production de ses contenus visuels et scientifiques. Il est notamment responsable de la réalisation des figures anatomiques, élaborées à l’aide d’un processus assisté par l’IA associant génération, vérifications croisées, confrontation aux sources anatomiques et corrections successives afin d’en renforcer la précision et la fiabilité.', 'Il contribue également à la revue de la littérature neuro-anatomique et à l’analyse des données scientifiques disponibles, afin de mettre en perspective les observations et les concepts de la méthode avec les connaissances actuelles en anatomie, neurophysiologie et neuromodulation.', 'Il pilote enfin Patient-Care, l’application dédiée au suivi des patients et à la collecte structurée des données issues de la pratique. Cet outil permet de documenter les prises en charge, leur évolution et les observations des praticiens, avec l’objectif de constituer progressivement une base de données exploitable pour mieux décrire, analyser et évaluer les pratiques en R.O.P.'] },
      { name: 'Matei Boitout', role: 'Relation avec les lecteurs · Marketing', body: ['Matei est en charge de la relation avec les lecteurs et les praticiens. Il accompagne leurs premiers échanges avec l’équipe, répond à leurs questions et contribue à les orienter vers les contenus, ressources ou formations les plus adaptés à leurs besoins.', 'Il participe également au développement et à la mise en œuvre des actions marketing : communication autour des publications et des formations, campagnes de sensibilisation, suivi des contacts et animation de la relation avec la communauté.', <>À l’écoute des retours du terrain, Matei joue enfin un rôle de relais entre les utilisateurs et l’équipe. Il recueille les attentes, les questions et les suggestions afin d’améliorer en permanence l’expérience proposée et de veiller à ce que chaque interaction reste <strong>claire, humaine, réactive et utile</strong>.</>] },
    ],
    cta: 'Découvrir le travail porté par l’équipe.', exploreBook: 'Explorer l’ouvrage', discoverMethod: 'Découvrir la méthode',
  },
  en: {
    metadata: { title: 'The team · R.O.P.', description: 'Meet the team behind Occipito-Podal Reflexotherapy: clinical direction, training, technology, reader relations and marketing.' },
    home: 'Back to home', eyebrow: 'The R.O.P. team', titleBefore: 'Three areas of expertise,', titleEmphasis: 'one shared standard.',
    intro: 'Bringing R.O.P. to life means combining the transmission of a method built on more than fifty years of practice, strong digital expertise and attentive support. Each person contributes in their own field to the same project: making the method clear, accessible and sustainable.',
    membersLabel: 'Team members', portraitAlt: (name) => `Portrait of ${name}`, portraitPending: 'Portrait coming soon',
    members: [
      { name: 'Guy Boitout', role: 'Lead Founder · Clinical & Educational Lead', body: ['Guy developed Occipito-Podal Reflexotherapy (R.O.P.) over more than fifty years of clinical practice. He continues to guide the method’s clinical approach, structure its core principles and oversee its transmission. He leads the training programmes and ensures that their content remains grounded in anatomy, clinical observation and the experience accumulated through decades of work with patients and practitioners.'] },
      { name: 'Nicolas Boitout', role: 'Co-Founder, Digital, Research & Data Lead', body: ['Nicolas leads the digital, research and data environment supporting R.O.P. He develops the method’s digital tools and produces its anatomical and scientific figures through an AI-assisted process combining generation, cross-checking against anatomical reference sources and successive corrections. He also contributes to the review of the scientific literature, placing R.O.P. concepts and observations in the context of current neuroanatomical and physiological knowledge. Through Patient-Care, he helps structure practitioner follow-up and build a practice-based dataset for future analysis.'] },
      { name: 'Matei Boitout', role: 'Reader & Practitioner Relations · Marketing & Sales', body: ['Matei manages relationships with readers, practitioners and prospective participants. He is often the first point of contact with the team and supports communication around the books, training programmes and other R.O.P. activities. He contributes to marketing campaigns, sales development and follow-up, while gathering feedback from the field and bringing it back to the team to help improve the way R.O.P. content, services and training are presented and delivered.'] },
    ],
    cta: 'Discover the work led by the team.', exploreBook: 'Explore the book', discoverMethod: 'Discover the method',
  },
  de: {
    metadata: { title: 'Das Team · R.O.P.', description: 'Lernen Sie das Team hinter der okzipito-podalen Reflextherapie kennen: klinische Leitung, Ausbildung, Technologie, Leserbetreuung und Marketing.' },
    home: 'Zurück zur Startseite', eyebrow: 'Das R.O.P.-Team', titleBefore: 'Drei Kompetenzbereiche,', titleEmphasis: 'ein gemeinsamer Anspruch.',
    intro: 'R.O.P. lebendig zu halten bedeutet, die Weitergabe einer in mehr als fünfzig Jahren Praxis entwickelten Methode mit fundierter digitaler Kompetenz und aufmerksamer Begleitung zu verbinden. Jeder wirkt in seinem Fachgebiet an demselben Ziel mit: die Methode klar, zugänglich und nachhaltig zu gestalten.',
    membersLabel: 'Teammitglieder', portraitAlt: (name) => `Porträt von ${name}`, portraitPending: 'Porträt folgt',
    members: [
      { name: 'Guy Boitout', role: 'Gründer · Klinische & pädagogische Leitung', body: ['Guy entwickelte die Okzipito-Podale Reflextherapie (R.O.P.) im Laufe von mehr als fünfzig Jahren klinischer Praxis. Bis heute prägt er den klinischen Ansatz der Methode, strukturiert ihre grundlegenden Prinzipien und begleitet ihre Weitergabe. Er leitet die Ausbildungsprogramme und stellt sicher, dass deren Inhalte auf anatomischen Grundlagen, klinischer Beobachtung und den Erfahrungen aus jahrzehntelanger Arbeit mit Patienten und Praktikern beruhen.'] },
      { name: 'Nicolas Boitout', role: 'Mitgründer · Digitales, Forschung & Daten', body: ['Nicolas verantwortet das digitale, wissenschaftliche und datenbezogene Umfeld der R.O.P. Er entwickelt die digitalen Werkzeuge der Methode und erstellt ihre anatomischen und wissenschaftlichen Abbildungen mithilfe eines KI-gestützten Prozesses, der Generierung, den Abgleich mit anatomischen Referenzquellen und schrittweise Korrekturen miteinander verbindet. Darüber hinaus wirkt er an der Auswertung der wissenschaftlichen Literatur mit und ordnet die Konzepte und Beobachtungen der R.O.P. in den Kontext des aktuellen neuroanatomischen und physiologischen Wissens ein. Über Patient-Care trägt er dazu bei, die Nachverfolgung durch Praktiker zu strukturieren und einen praxisbasierten Datensatz für zukünftige Analysen aufzubauen.'] },
      { name: 'Matei Boitout', role: 'Leser- & Praktikerbeziehungen · Marketing & Vertrieb', body: ['Matei betreut die Beziehungen zu Lesern, Praktikern und Interessenten. Er ist häufig der erste Ansprechpartner des Teams und unterstützt die Kommunikation rund um die Bücher, Ausbildungsprogramme und weiteren Aktivitäten der R.O.P. Er wirkt an Marketingkampagnen, Vertriebsentwicklung und Follow-up-Aktivitäten mit und sammelt zugleich Rückmeldungen aus der Praxis. Diese bringt er in das Team ein, um die Darstellung und Vermittlung der Inhalte, Angebote und Ausbildungsprogramme der R.O.P. kontinuierlich zu verbessern.'] },
    ],
    cta: 'Entdecken Sie die Arbeit des Teams.', exploreBook: 'Das Buch entdecken', discoverMethod: 'Die Methode entdecken',
  },
  es: {
    metadata: { title: 'El equipo · R.O.P.', description: 'Conozca al equipo que impulsa la Reflexoterapia Occípito-Podal: dirección clínica, formación, tecnología, relación con los lectores y marketing.' },
    home: 'Volver al inicio', eyebrow: 'El equipo R.O.P.', titleBefore: 'Tres ámbitos de experiencia,', titleEmphasis: 'una misma exigencia.',
    intro: 'Dar vida a la R.O.P. significa unir la transmisión de un método construido a lo largo de más de cincuenta años de práctica, una sólida experiencia digital y un acompañamiento atento. Cada miembro interviene desde su especialidad al servicio de un mismo proyecto: hacer que el método sea claro, accesible y duradero.',
    membersLabel: 'Miembros del equipo', portraitAlt: (name) => `Retrato de ${name}`, portraitPending: 'Retrato próximamente',
    members: [
      { name: 'Guy Boitout', role: 'Fundador · Dirección clínica · Formación', body: ['Guy es el creador de la Reflexoterapia Occípito-Podal. Es responsable de su visión clínica, su coherencia y su transmisión. Estructura los contenidos del método, dirige las formaciones y acompaña su evolución a partir de la experiencia acumulada con pacientes y profesionales. Asimismo, vela por que la R.O.P. se mantenga fiel a sus fundamentos, a la anatomía y a los principios clínicos que han guiado su desarrollo.'] },
      { name: 'Nicolas Boitout', role: 'Dirección tecnológica · Imagen científica', body: ['Nicolas diseña y dirige el entorno digital de la R.O.P. y coordina la producción de sus contenidos visuales y científicos. Es responsable, en particular, de las figuras anatómicas, elaboradas mediante un proceso asistido por IA que combina generación, comprobaciones cruzadas, contraste con fuentes anatómicas y correcciones sucesivas para reforzar su precisión y fiabilidad.', 'También contribuye a la revisión de la literatura neuroanatómica y al análisis de los datos científicos disponibles, con el fin de situar las observaciones y los conceptos del método en relación con los conocimientos actuales de anatomía, neurofisiología y neuromodulación.', 'Por último, dirige Patient-Care, la aplicación dedicada al seguimiento de los pacientes y a la recopilación estructurada de datos procedentes de la práctica. Esta herramienta documenta la atención, su evolución y las observaciones de los profesionales, con el objetivo de constituir progresivamente una base de datos utilizable para describir, analizar y evaluar mejor las prácticas de R.O.P.'] },
      { name: 'Matei Boitout', role: 'Relación con los lectores · Marketing', body: ['Matei se encarga de la relación con los lectores y los profesionales. Acompaña sus primeros intercambios con el equipo, responde a sus preguntas y les ayuda a encontrar los contenidos, recursos o formaciones más adecuados a sus necesidades.', 'También participa en el desarrollo y la ejecución de las acciones de marketing: comunicación sobre publicaciones y formaciones, campañas de sensibilización, seguimiento de contactos y dinamización de la relación con la comunidad.', <>Atento a los comentarios procedentes de la práctica, Matei actúa además como enlace entre los usuarios y el equipo. Recoge expectativas, preguntas y sugerencias para mejorar continuamente la experiencia y procurar que cada interacción siga siendo <strong>clara, humana, ágil y útil</strong>.</>] },
    ],
    cta: 'Descubra el trabajo del equipo.', exploreBook: 'Explorar la obra', discoverMethod: 'Descubrir el método',
  },
  it: {
    metadata: { title: 'Il team · R.O.P.', description: 'Scoprite il team che porta avanti la Riflessoterapia Occipito-Podale: direzione clinica, formazione, tecnologia, relazioni con i lettori e marketing.' },
    home: 'Torna alla home', eyebrow: 'Il team R.O.P.', titleBefore: 'Tre competenze,', titleEmphasis: 'un’unica esigenza.',
    intro: 'Far vivere la R.O.P. significa unire la trasmissione di un metodo costruito in oltre cinquant’anni di pratica, una solida esperienza digitale e un accompagnamento attento. Ognuno interviene nel proprio ambito al servizio dello stesso progetto: rendere il metodo chiaro, accessibile e duraturo.',
    membersLabel: 'Membri del team', portraitAlt: (name) => `Ritratto di ${name}`, portraitPending: 'Ritratto in arrivo',
    members: [
      { name: 'Guy Boitout', role: 'Fondatore · Direzione clinica · Formazione', body: ['Guy è il creatore della Riflessoterapia Occipito-Podale. Ne custodisce la visione clinica, la coerenza e la trasmissione. Struttura i contenuti del metodo, dirige le formazioni e ne accompagna l’evoluzione sulla base dell’esperienza maturata con pazienti e professionisti. Veglia inoltre affinché la R.O.P. rimanga fedele ai propri fondamenti, all’anatomia e ai principi clinici che ne hanno guidato lo sviluppo.'] },
      { name: 'Nicolas Boitout', role: 'Direzione tecnologica · Imaging scientifico', body: ['Nicolas progetta e dirige l’ambiente digitale della R.O.P. e coordina la produzione dei contenuti visivi e scientifici. È responsabile in particolare delle figure anatomiche, realizzate attraverso un processo assistito dall’IA che combina generazione, verifiche incrociate, confronto con le fonti anatomiche e correzioni successive per aumentarne precisione e affidabilità.', 'Contribuisce inoltre alla revisione della letteratura neuroanatomica e all’analisi dei dati scientifici disponibili, per mettere in prospettiva le osservazioni e i concetti del metodo con le conoscenze attuali in anatomia, neurofisiologia e neuromodulazione.', 'Dirige infine Patient-Care, l’applicazione dedicata al monitoraggio dei pazienti e alla raccolta strutturata dei dati provenienti dalla pratica. Lo strumento documenta i trattamenti, la loro evoluzione e le osservazioni dei professionisti, con l’obiettivo di costruire progressivamente una banca dati utilizzabile per descrivere, analizzare e valutare meglio le pratiche R.O.P.'] },
      { name: 'Matei Boitout', role: 'Relazioni con i lettori · Marketing', body: ['Matei cura le relazioni con i lettori e i professionisti. Li accompagna nei primi contatti con il team, risponde alle loro domande e li aiuta a orientarsi verso i contenuti, le risorse o le formazioni più adatti alle loro esigenze.', 'Partecipa inoltre allo sviluppo e all’attuazione delle attività di marketing: comunicazione sulle pubblicazioni e sulle formazioni, campagne di sensibilizzazione, gestione dei contatti e animazione del rapporto con la comunità.', <>Ascoltando i riscontri provenienti dalla pratica, Matei svolge anche un ruolo di collegamento tra gli utenti e il team. Raccoglie aspettative, domande e suggerimenti per migliorare continuamente l’esperienza e garantire che ogni interazione rimanga <strong>chiara, umana, reattiva e utile</strong>.</>] },
    ],
    cta: 'Scoprite il lavoro del team.', exploreBook: 'Esplora il libro', discoverMethod: 'Scopri il metodo',
  },
  th: {
    metadata: { title: 'ทีมงาน · R.O.P.', description: 'ทำความรู้จักทีมงานผู้อยู่เบื้องหลังการสะท้อนบำบัดท้ายทอยและฝ่าเท้า ทั้งด้านคลินิก การฝึกอบรม เทคโนโลยี การดูแลผู้อ่าน และการตลาด' },
    home: 'กลับสู่หน้าหลัก', eyebrow: 'ทีมงาน R.O.P.', titleBefore: 'สามความเชี่ยวชาญ', titleEmphasis: 'หนึ่งมาตรฐานร่วมกัน',
    intro: 'การขับเคลื่อน R.O.P. คือการผสานการถ่ายทอดวิธีการที่พัฒนาจากประสบการณ์ปฏิบัติกว่าห้าสิบปี ความเชี่ยวชาญด้านดิจิทัลที่แข็งแกร่ง และการดูแลอย่างใส่ใจ แต่ละคนทำงานในสาขาของตนเพื่อเป้าหมายเดียวกัน คือทำให้วิธีการนี้ชัดเจน เข้าถึงได้ และยั่งยืน',
    membersLabel: 'สมาชิกทีม', portraitAlt: (name) => `ภาพของ ${name}`, portraitPending: 'จะเพิ่มภาพในภายหลัง',
    members: [
      { name: 'Guy Boitout', role: 'ผู้ก่อตั้ง · ผู้อำนวยการด้านคลินิก · การฝึกอบรม', body: ['Guy เป็นผู้สร้างวิธีการสะท้อนบำบัดท้ายทอยและฝ่าเท้า เขารับผิดชอบวิสัยทัศน์ทางคลินิก ความสอดคล้อง และการถ่ายทอดของวิธีการนี้ เขาวางโครงสร้างเนื้อหา เป็นผู้นำการฝึกอบรม และพัฒนาหลักสูตรจากประสบการณ์ที่สั่งสมร่วมกับผู้ป่วยและผู้ประกอบวิชาชีพ พร้อมดูแลให้ R.O.P. ยังคงซื่อตรงต่อรากฐาน กายวิภาค และหลักการทางคลินิกที่กำหนดทิศทางการพัฒนา'] },
      { name: 'Nicolas Boitout', role: 'ผู้อำนวยการด้านเทคโนโลยี · ภาพประกอบทางวิทยาศาสตร์', body: ['Nicolas ออกแบบและกำกับสภาพแวดล้อมดิจิทัลของ R.O.P. รวมทั้งประสานงานการผลิตเนื้อหาด้านภาพและวิทยาศาสตร์ โดยเฉพาะภาพกายวิภาคซึ่งสร้างผ่านกระบวนการที่มี AI ช่วย ตั้งแต่การสร้างภาพ การตรวจสอบไขว้ การเทียบกับแหล่งข้อมูลกายวิภาค ไปจนถึงการแก้ไขหลายรอบ เพื่อเพิ่มความแม่นยำและความน่าเชื่อถือ', 'เขายังร่วมทบทวนวรรณกรรมด้านประสาทกายวิภาคและวิเคราะห์ข้อมูลวิทยาศาสตร์ที่มีอยู่ เพื่อเชื่อมโยงข้อสังเกตและแนวคิดของวิธีการกับความรู้ปัจจุบันด้านกายวิภาค ประสาทสรีรวิทยา และการปรับการทำงานของระบบประสาท', 'นอกจากนี้ เขายังเป็นผู้ดูแล Patient-Care แอปพลิเคชันสำหรับติดตามผู้ป่วยและเก็บข้อมูลจากการปฏิบัติงานอย่างเป็นระบบ เครื่องมือนี้ช่วยบันทึกการดูแล การเปลี่ยนแปลง และข้อสังเกตของผู้ประกอบวิชาชีพ โดยมีเป้าหมายเพื่อค่อย ๆ สร้างฐานข้อมูลที่นำไปใช้ในการอธิบาย วิเคราะห์ และประเมินการปฏิบัติ R.O.P. ได้ดียิ่งขึ้น'] },
      { name: 'Matei Boitout', role: 'การดูแลผู้อ่าน · การตลาด', body: ['Matei รับผิดชอบความสัมพันธ์กับผู้อ่านและผู้ประกอบวิชาชีพ เขาดูแลการติดต่อครั้งแรกกับทีม ตอบคำถาม และช่วยแนะนำเนื้อหา ทรัพยากร หรือการฝึกอบรมที่เหมาะกับความต้องการของแต่ละคน', 'เขายังมีส่วนร่วมในการพัฒนาและดำเนินงานด้านการตลาด ทั้งการสื่อสารเกี่ยวกับสิ่งพิมพ์และการฝึกอบรม แคมเปญสร้างการรับรู้ การติดตามผู้ติดต่อ และการสร้างความสัมพันธ์กับชุมชน', <>ด้วยการรับฟังเสียงสะท้อนจากการปฏิบัติงาน Matei ยังทำหน้าที่เป็นตัวเชื่อมระหว่างผู้ใช้กับทีม เขารวบรวมความคาดหวัง คำถาม และข้อเสนอแนะ เพื่อปรับปรุงประสบการณ์อย่างต่อเนื่อง และทำให้ทุกการติดต่อยังคง <strong>ชัดเจน เป็นมิตร ตอบสนองรวดเร็ว และเป็นประโยชน์</strong></>] },
    ],
    cta: 'ค้นพบผลงานของทีม', exploreBook: 'สำรวจหนังสือ', discoverMethod: 'ทำความรู้จักวิธีการ',
  },
}
