// AUTO-GENERATED by scripts/sync-chapter-meta.ts — do not edit manually.
// Recomputed daily from the chapter content files via GitHub Actions.
export const chapterMetaSnapshot: Record<string, { readingMinutes: number; figureCount: number }> = {
  'introduction': { readingMinutes: 4, figureCount: 0 },
  'chapter-2': { readingMinutes: 16, figureCount: 0 },
  'chapter-5': { readingMinutes: 19, figureCount: 4 },
  'chapter-14': { readingMinutes: 19, figureCount: 13 },
}
