// AUTO-GENERATED by scripts/sync-chapter-meta.ts — do not edit manually.
// Recomputed daily from the chapter content files via GitHub Actions.
//
//   photoCount        photos embedded in the chapter text
//   slideCount        anatomy / physiology plates of the reading deck
//   cartographyCount  reflex-zone maps of the reading deck
//   visualCount       photoCount + slideCount + cartographyCount

export type ChapterMetaSnapshot = {
  readingMinutes: number
  photoCount: number
  slideCount: number
  cartographyCount: number
  visualCount: number
}

export const chapterMetaSnapshot: Record<string, ChapterMetaSnapshot> = {
  'introduction': { readingMinutes: 26, photoCount: 6, slideCount: 0, cartographyCount: 0, visualCount: 6 },
  'chapter-1': { readingMinutes: 14, photoCount: 0, slideCount: 18, cartographyCount: 1, visualCount: 19 },
  'chapter-2': { readingMinutes: 22, photoCount: 1, slideCount: 10, cartographyCount: 5, visualCount: 16 },
  'chapter-3': { readingMinutes: 27, photoCount: 7, slideCount: 15, cartographyCount: 10, visualCount: 32 },
  'chapter-4': { readingMinutes: 48, photoCount: 17, slideCount: 27, cartographyCount: 18, visualCount: 62 },
  'chapter-5': { readingMinutes: 20, photoCount: 9, slideCount: 26, cartographyCount: 0, visualCount: 35 },
  'chapter-6': { readingMinutes: 10, photoCount: 0, slideCount: 18, cartographyCount: 0, visualCount: 18 },
  'chapter-7': { readingMinutes: 22, photoCount: 5, slideCount: 14, cartographyCount: 5, visualCount: 24 },
  'chapter-8': { readingMinutes: 29, photoCount: 8, slideCount: 16, cartographyCount: 8, visualCount: 32 },
  'chapter-9': { readingMinutes: 21, photoCount: 2, slideCount: 19, cartographyCount: 4, visualCount: 25 },
  'chapter-10': { readingMinutes: 15, photoCount: 4, slideCount: 13, cartographyCount: 5, visualCount: 22 },
  'chapter-11': { readingMinutes: 34, photoCount: 7, slideCount: 14, cartographyCount: 4, visualCount: 25 },
  'chapter-12': { readingMinutes: 23, photoCount: 2, slideCount: 13, cartographyCount: 3, visualCount: 18 },
  'chapter-13': { readingMinutes: 17, photoCount: 2, slideCount: 18, cartographyCount: 3, visualCount: 23 },
  'chapter-14': { readingMinutes: 23, photoCount: 9, slideCount: 23, cartographyCount: 0, visualCount: 32 },
  'chapter-15': { readingMinutes: 36, photoCount: 5, slideCount: 28, cartographyCount: 5, visualCount: 38 },
  'chapter-16': { readingMinutes: 32, photoCount: 5, slideCount: 22, cartographyCount: 6, visualCount: 33 },
  'chapter-17': { readingMinutes: 29, photoCount: 6, slideCount: 18, cartographyCount: 7, visualCount: 31 },
  'chapter-18': { readingMinutes: 24, photoCount: 7, slideCount: 21, cartographyCount: 9, visualCount: 37 },
  'chapter-19': { readingMinutes: 36, photoCount: 13, slideCount: 34, cartographyCount: 13, visualCount: 60 },
  'chapter-20': { readingMinutes: 31, photoCount: 10, slideCount: 14, cartographyCount: 11, visualCount: 35 },
  'chapter-21': { readingMinutes: 12, photoCount: 5, slideCount: 10, cartographyCount: 7, visualCount: 22 },
}

export const bookVisualTotals = {
  chapterCount: 22,
  readingMinutes: 551,
  photoCount: 130,
  slideCount: 391,
  cartographyCount: 124,
  visualCount: 645,
}
