#!/usr/bin/env node
// Computes reading time and illustration count for every chapter in the
// registry (using the French canonical content) and writes the results to
// lib/chapterMetaSnapshot.ts.  Run daily via GitHub Actions; commit the
// output when it changes.

import { writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { chapterStats } from '../lib/chapterStats.ts'
import { introductionFr } from '../content/introduction.fr.ts'
import { chapter2Fr } from '../content/chapter2.fr.ts'
import { chapter5Fr } from '../content/chapter5.fr.ts'
import { chapter14Fr } from '../content/chapter14.fr.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))

const chapters = [
  { slug: 'introduction',  content: introductionFr },
  { slug: 'chapter-2',     content: chapter2Fr },
  { slug: 'chapter-5',     content: chapter5Fr },
  { slug: 'chapter-14',    content: chapter14Fr },
]

const entries = chapters.map(({ slug, content }) => {
  const { readingMinutes, figureCount } = chapterStats(content)
  console.log(`${slug}: ${readingMinutes} min, ${figureCount} figures`)
  return `  '${slug}': { readingMinutes: ${readingMinutes}, figureCount: ${figureCount} },`
})

const output = `// AUTO-GENERATED by scripts/sync-chapter-meta.ts — do not edit manually.
// Recomputed daily from the chapter content files via GitHub Actions.
export const chapterMetaSnapshot: Record<string, { readingMinutes: number; figureCount: number }> = {
${entries.join('\n')}
}
`

const outPath = resolve(__dirname, '../lib/chapterMetaSnapshot.ts')
writeFileSync(outPath, output, 'utf8')
console.log(`Written → ${outPath}`)
